In [1]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import re
import pyproj
import folium

In [2]:
mes = 'May'

In [3]:
# Ruta de la carpeta que contiene los archivos de desglosados zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/Blogger/Asistencia/2026/{mes}'

# Fechas de inicio y fin para el filtro
fecha_inicio = '12-05-2026'
fecha_fin = '31-05-2026'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:10]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%d-%m-%Y', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', delimiter=';',skiprows=2, low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            # Añadir una nueva columna 'Fecha' con la fecha extraída del nombre del archivo
            df['Fecha'] = fecha_archivo
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    asistencia = pd.concat(dataframes, ignore_index=True)

    # # Guardar el DataFrame consolidado en un nuevo archivo
    # asistencia.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/asistencia_nov24.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET4M-T2,ET4M-T2,04:00:00,NaN,03:56:00,08:00:00,12:00:00,...,12:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12-05-2026
1,JAIME HUMBERTO GARCIA GOMEZ,JAIME HUMBERTO,GARCIA GOMEZ,EG7,Gaco I,04:00:00,NaN,04:02:00,09:00:00,13:00:00,...,13:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12-05-2026
2,ANETH MAYERLI CHONTAL VILLARRAGA,ANETH MAYERLI,CHONTAL VILLARRAGA,EG1,Verbena I,04:00:00,NaN,03:56:00,09:15:00,13:15:00,...,16:21:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12-05-2026
3,ANGELICA PATRICIA FLOREZ SOLANO,ANGELICA PATRICIA,FLOREZ SOLANO,PLA1,Portal Dorado,04:30:00,NaN,04:29:00,08:00:00,12:30:00,...,12:34:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12-05-2026
4,LUIS ARCESIO NAVARRETE VARGAS,LUIS ARCESIO,NAVARRETE VARGAS,EG11,Villa Gladys - Gaco,05:00:00,NaN,04:52:00,08:30:00,13:30:00,...,13:25:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12-05-2026

In [4]:
## Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia

# Convertir la columna 'Fecha' a tipo datetime
asistencia['Fecha'] = pd.to_datetime(asistencia['Fecha'], format='%d-%m-%Y')

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
asistencia['Fecha'] = asistencia['Fecha'].dt.strftime('%d/%m/%Y')

asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET4M-T2,ET4M-T2,04:00:00,NaN,03:56:00,08:00:00,12:00:00,...,12:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026
1,JAIME HUMBERTO GARCIA GOMEZ,JAIME HUMBERTO,GARCIA GOMEZ,EG7,Gaco I,04:00:00,NaN,04:02:00,09:00:00,13:00:00,...,13:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026
2,ANETH MAYERLI CHONTAL VILLARRAGA,ANETH MAYERLI,CHONTAL VILLARRAGA,EG1,Verbena I,04:00:00,NaN,03:56:00,09:15:00,13:15:00,...,16:21:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026
3,ANGELICA PATRICIA FLOREZ SOLANO,ANGELICA PATRICIA,FLOREZ SOLANO,PLA1,Portal Dorado,04:30:00,NaN,04:29:00,08:00:00,12:30:00,...,12:34:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026
4,LUIS ARCESIO NAVARRETE VARGAS,LUIS ARCESIO,NAVARRETE VARGAS,EG11,Villa Gladys - Gaco,05:00:00,NaN,04:52:00,08:30:00,13:30:00,...,13:25:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026

In [5]:
cambio_nombres = {
    'NOMBRE': 'Nombre Completo',
    'NOMBRE.1': 'NOMBRES',
    'Aplica novedad':'APLICA NOVEDAD',
    'Informa':'INFORMA ?',
    'Tipo de novedad':'TIPO NOVEDAD',
    'Supervisor':'SUPERVISOR REPORTA',
    'Observaciones':'OBSERVACIONES'
    
}

# Aplicar los cambios de nombres al DataFrame
asistencia.rename(columns=cambio_nombres, inplace=True)

asistencia.head(3)

,Nombre Completo,NOMBRES,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,APLICA NOVEDAD,INFORMA ?,TIPO NOVEDAD,SUPERVISOR REPORTA,OBSERVACIONES,INTRANET,Fecha
0,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET4M-T2,ET4M-T2,04:00:00,NaN,03:56:00,08:00:00,12:00:00,...,12:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026
1,JAIME HUMBERTO GARCIA GOMEZ,JAIME HUMBERTO,GARCIA GOMEZ,EG7,Gaco I,04:00:00,NaN,04:02:00,09:00:00,13:00:00,...,13:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026
2,ANETH MAYERLI CHONTAL VILLARRAGA,ANETH MAYERLI,CHONTAL VILLARRAGA,EG1,Verbena I,04:00:00,NaN,03:56:00,09:15:00,13:15:00,...,16:21:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/05/2026

In [6]:
orden_columnas = [
    'Fecha', 'Nombre Completo', 'NOMBRES', 'APELLIDOS', 'TURNO Programado',
    'Sitio Programado', 'Hora Inicio Programado', 'Hora Inicio Referencia Ajustado',
    'Hora Inicio Real', 'Duración Programado', 'Hora Fin Programado', 
    'Hora Fin Referencia_Calculado', 'Hora Fin Referencia Ajustado', 'Hora Fin Real',
    'HTL', 'Sitio Real', 'APLICA NOVEDAD', 'INFORMA ?', 'TIPO NOVEDAD', 
    'SUPERVISOR REPORTA', 'OBSERVACIONES', 'INTRANET'
]

# Asegurarte de que las columnas existen en tu DataFrame
asistencia = asistencia[[col for col in orden_columnas if col in asistencia.columns]]

asistencia.head()

,Fecha,Nombre Completo,NOMBRES,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,...,Hora Fin Referencia Ajustado,Hora Fin Real,HTL,Sitio Real,APLICA NOVEDAD,INFORMA ?,TIPO NOVEDAD,SUPERVISOR REPORTA,OBSERVACIONES,INTRANET
0,12/05/2026,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET4M-T2,ET4M-T2,04:00:00,NaN,03:56:00,08:00:00,...,NaN,12:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12/05/2026,JAIME HUMBERTO GARCIA GOMEZ,JAIME HUMBERTO,GARCIA GOMEZ,EG7,Gaco I,04:00:00,NaN,04:02:00,09:00:00,...,NaN,13:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12/05/2026,ANETH MAYERLI CHONTAL VILLARRAGA,ANETH MAYERLI,CHONTAL VILLARRAGA,EG1,Verbena I,04:00:00,NaN,03:56:00,09:15:00,...,NaN,16:21:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12/05/2026,ANGELICA PATRICIA FLOREZ SOLANO,ANGELICA PATRICIA,FLOREZ SOLANO,PLA1,Portal Dorado,04:30:00,NaN,04:29:00,08:00:00,...,NaN,12:34:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12/05/2026,LUIS ARCESIO NAVARRETE VARGAS,LUIS ARCESIO,NAVARRETE VARGAS,EG11,Villa Gladys - Gaco,05:00:00,NaN,04:52:00,08:30:00,...,NaN,13:25:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#Exportar archivo

asistencia.to_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Asistencia_v1.csv", sep=';', index=False)