In [1]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import re
import pyproj
import folium

In [ ]:
#Datos de filtros
fecha_i = '20260601'
fecha_f = '20260612'

#Fonias
fecha_if = '01062026'
fecha_ff = '12062026'

mes = 'Junio'

Actividad de bus

In [3]:
# Ruta de la carpeta que contiene los archivos de actividad de bus zonal
ruta_carpeta = 'Z:/01 base_datos/03 actividad_bus_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_actividad_bus.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    ab_zonal = pd.concat(dataframes, ignore_index=True)

    # # Guardar el DataFrame consolidado en un nuevo archivo
    # desg_troncal.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_ago24.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
ab_zonal.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias
0,13/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,Inicio Viaje - Linea(11),4:00:00,4:00:00,4:00:02,4:00:02,NaN,NaN,0:00:00,NaN
1,13/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:01:10,4:01:10,4:01:23,4:01:47,0:01:21,NaN,0:00:08,NaN
2,13/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:02:03,4:02:03,4:02:40,4:03:05,0:00:53,NaN,0:00:08,NaN
3,13/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:02:53,4:02:53,4:03:45,4:04:21,0:00:40,NaN,0:00:20,NaN
4,13/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:03:53,4:03:53,4:05:10,4:05:17,0:00:49,NaN,0:00:00,NaN

In [4]:
# Ruta de la carpeta que contiene los archivos de actividad de bus alimentación
ruta_carpeta = 'Z:/01 base_datos/15 actividad_bus_alimentacion_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_actividad_bus.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    ab_troncal = pd.concat(dataframes, ignore_index=True)

    # # Guardar el DataFrame consolidado en un nuevo archivo
    # desg_troncal.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_ago24.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
ab_troncal.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias
0,13/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,10474,16-2 Engativa Centro,12551,16-2_V2,13,1,1,...,CAMILO ANDRES ESTRADA GAMBOA,Inicio Viaje - Linea(11),4:09:00,4:09:00,4:08:15,4:08:15,NaN,NaN,0:00:07,NaN
1,13/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,10474,16-2 Engativa Centro,12551,16-2_V2,13,1,1,...,CAMILO ANDRES ESTRADA GAMBOA,NaN,4:18:15,4:18:15,4:16:28,4:16:53,0:08:13,NaN,0:00:05,NaN
2,13/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,10474,16-2 Engativa Centro,12551,16-2_V2,13,1,1,...,CAMILO ANDRES ESTRADA GAMBOA,NaN,4:18:42,4:18:42,4:17:22,4:17:43,0:00:29,NaN,0:00:05,NaN
3,13/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,10474,16-2 Engativa Centro,12551,16-2_V2,13,1,1,...,CAMILO ANDRES ESTRADA GAMBOA,NaN,4:19:54,4:19:54,4:18:49,4:19:12,0:01:06,NaN,0:00:07,NaN
4,13/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,10474,16-2 Engativa Centro,12551,16-2_V2,13,1,1,...,CAMILO ANDRES ESTRADA GAMBOA,NaN,4:20:20,4:20:20,4:19:27,4:19:50,0:00:15,NaN,0:00:05,NaN

In [5]:
# Consolidar todos los DataFrames en uno solo

ab = pd.concat([ab_zonal, ab_troncal], ignore_index=True)

# Convertir la columna 'Fecha' a tipo datetime
ab['Fecha'] = pd.to_datetime(ab['Fecha'], format='%d/%m/%Y')

ab.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias
0,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,Inicio Viaje - Linea(11),4:00:00,4:00:00,4:00:02,4:00:02,NaN,NaN,0:00:00,NaN
1,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:01:10,4:01:10,4:01:23,4:01:47,0:01:21,NaN,0:00:08,NaN
2,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:02:03,4:02:03,4:02:40,4:03:05,0:00:53,NaN,0:00:08,NaN
3,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:02:53,4:02:53,4:03:45,4:04:21,0:00:40,NaN,0:00:20,NaN
4,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,FREDY DE JESUS NARANJO,NaN,4:03:53,4:03:53,4:05:10,4:05:17,0:00:49,NaN,0:00:00,NaN

In [6]:
# Filtrar el DataFrame para que solo contenga las filas donde 'Operador' sea '[105] E'
if 'Operador' in ab.columns:
    ab = ab[ab['Operador'] == '[105] E']
    
# Crear la columna 'Hora' 
ab['Hora'] = ab.apply(
    lambda row: row['Hora Llegada'] if pd.notna(row['Hora Llegada']) else (
        row['Hora Salida'] if pd.notna(row['Hora Salida']) else row['Hora Teórica']
    ),
    axis=1
)    

# Eliminar las columnas 'Tipo Fonía' y 'Grabación' si existen en el DataFrame
columns_to_drop = ["Hora Llegada", "Hora Salida", "HoraReferencia", "Source.Name", "Operador", "NumEventosBus", "OrdenViaje", "Nodo", "Descripcion", "TiempoRegulacion", "Alarma", "TiempoAperturaPuertas"]
ab = ab.drop(columns=columns_to_drop, errors='ignore')

ab.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Conductor,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,Hora
0,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,Inicio Viaje - Linea(11),4:00:00,4:00:00,NaN,NaN,0:00:00,NaN,4:00:02
1,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:01:10,4:01:10,0:01:21,NaN,0:00:08,NaN,4:01:23
2,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:02:03,4:02:03,0:00:53,NaN,0:00:08,NaN,4:02:40
3,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:02:53,4:02:53,0:00:40,NaN,0:00:20,NaN,4:03:45
4,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:03:53,4:03:53,0:00:49,NaN,0:00:00,NaN,4:05:10

In [7]:
def fix_time(date_str):
    # Strip any leading or trailing whitespace
    date_str = date_str.strip()
    
    # Ensure the string has the correct format
    if ':' not in date_str or len(date_str.split(':')) < 3:
        return date_str
    
    hour = date_str.split(':')[0]
    
    # Check if the hour part is numeric and convert it
    if hour.isdigit() and int(hour) >= 24:
        corrected_hour = int(hour) - 24
        corrected_time = f'{corrected_hour:02}' + date_str[2:]
        return corrected_time
    return date_str

ab['Hora'] = ab['Hora'].astype(str)

ab['Hora'] = ab['Hora'].apply(fix_time)

ab['Hora'] = pd.to_datetime(
    ab['Hora'],
    format='%H:%M:%S',
    errors='coerce'
).dt.time

ab.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Conductor,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,Hora
0,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,Inicio Viaje - Linea(11),4:00:00,4:00:00,NaN,NaN,0:00:00,NaN,04:00:02
1,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:01:10,4:01:10,0:01:21,NaN,0:00:08,NaN,04:01:23
2,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:02:03,4:02:03,0:00:53,NaN,0:00:08,NaN,04:02:40
3,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:02:53,4:02:53,0:00:40,NaN,0:00:20,NaN,04:03:45
4,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:03:53,4:03:53,0:00:49,NaN,0:00:00,NaN,04:05:10

In [8]:
# Filtrar el DataFrame para que solo contenga las filas donde 'ViajeLinea' es diferente de cero
if 'ViajeLinea' in ab.columns:
    ab = ab[ab['ViajeLinea'] != 0]

# Mostrar el DataFrame resultante
ab.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Conductor,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,Hora
0,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,Inicio Viaje - Linea(11),4:00:00,4:00:00,NaN,NaN,0:00:00,NaN,04:00:02
1,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:01:10,4:01:10,0:01:21,NaN,0:00:08,NaN,04:01:23
2,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:02:03,4:02:03,0:00:53,NaN,0:00:08,NaN,04:02:40
3,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:02:53,4:02:53,0:00:40,NaN,0:00:20,NaN,04:03:45
4,2026-05-13,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10350,SE14,12739,SE14_Vuelta_V2,1,1,1,...,505578.0,FREDY DE JESUS NARANJO,NaN,4:03:53,4:03:53,0:00:49,NaN,0:00:00,NaN,04:05:10

In [9]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699189 entries, 0 to 699188
Data columns (total 27 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Fecha                              699189 non-null  datetime64[ns]
 1   Concesión                          699189 non-null  object
 2   Concesionario de Operación         699189 non-null  object
 3   Id Línea                           699189 non-null  int64
 4   Línea                              699189 non-null  object
 5   Id Ruta                            699189 non-null  int64
 6   Ruta                               699189 non-null  object
 7   Tabla                              699189 non-null  int64
 8   Viaje Linea                        699189 non-null  int64
 9   Orden Viaje                        699189 non-null  int64
 10  Id Viaje                           699189 non-null  int64
 11  Tipo de Nodo                       699189 non-null  int64
 12  Id Nodo                            699189 non-null  int64
 13  Nombre Nodo                        699189 non-null  object
 14  Servicio Bus                       699189 non-null  object
 15  Código Bus                         621114 non-null  object
 16  Número FMS Bus                     699189 non-null  int64
 17  Conductor                          620944 non-null  float64
 18  Nombre de Conductor                699189 non-null  object
 19  Evento                             16806 non-null   object
 20  Hora Teórica                       699189 non-null  object
 21  Hora Referencia                    699189 non-null  object
 22  Tiempo entre paradas               583226 non-null  object
 23  Alarma Exceso de Tiempo en Parada  0 non-null       float64
 24  Tiempo Apertura de Puertas         596888 non-null  object
 25  Lista de acciones regulatorias     70519 non-null   object
 26  Hora                               699189 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(9), object(15)
memory usage: 144.0+ MB

In [10]:
ab['Hora'] = pd.to_datetime(
    ab['Hora'],
    format='%H:%M:%S',
    errors='coerce'
)

In [11]:
# Agrupar por 'ServicioBus', 'Coche', e 'IDViaje' y calcular la hora mínima y máxima
acb = ab.groupby(['Fecha','Código Bus',	'Número FMS Bus','Servicio Bus', 'Línea','Tabla', 'Viaje Linea','Id Viaje','Conductor'])['Hora'].agg(['min', 'max']).reset_index()

# Renombrar las columnas para claridad
acb.columns = ['Fecha','Código Bus','Numero FMS Bus','Servicio Bus', 'Línea','Tabla', 'Viaje Linea','Id Viaje','Conductor','HoraMinima','HoraMaxima']

acb['Conductor'] = acb['Conductor'].astype(int)

# Mostrar el DataFrame resultante
acb.head()

,Fecha,Código Bus,Numero FMS Bus,Servicio Bus,Línea,Tabla,Viaje Linea,Id Viaje,Conductor,HoraMinima,HoraMaxima
0,2026-05-13,E0200,7200,CE0A40013,16-2 Engativa Centro,6,1,2,507030,1900-01-01 04:12:51,1900-01-01 04:43:13
1,2026-05-13,E0200,7200,CE0A40013,16-2 Engativa Centro,6,2,3,507030,1900-01-01 04:46:51,1900-01-01 05:23:46
2,2026-05-13,E0200,7200,CE0A40013,16-2 Engativa Centro,6,3,4,507030,1900-01-01 05:24:06,1900-01-01 06:01:24
3,2026-05-13,E0200,7200,CE0A40013,16-2 Engativa Centro,6,4,5,507030,1900-01-01 06:04:59,1900-01-01 06:45:15
4,2026-05-13,E0200,7200,CE0A40013,16-2 Engativa Centro,6,5,6,507030,1900-01-01 06:53:14,1900-01-01 07:33:32

In [12]:
# Cambiar 'E0' por '70' al inicio del código
acb['Código Bus'] = (
    acb['Código Bus']
      .astype(str)
      .str.strip()                        # quitar espacios
      .str.replace(r'^E', '7', regex=True)  # E al inicio → 7
      .str.replace('Z', '', regex=False)    # quitar Z
      .str.replace('-', '', regex=False)    # quitar guiones
      .str.replace(r'\.0$', '', regex=True) # por si vienen como 123.0
)

# Convertir a entero (forzando errores a NaN por seguridad)
acb['Código Bus'] = pd.to_numeric(acb['Código Bus'], errors='coerce').astype('Int64')

acb.head()

,Fecha,Código Bus,Numero FMS Bus,Servicio Bus,Línea,Tabla,Viaje Linea,Id Viaje,Conductor,HoraMinima,HoraMaxima
0,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,1,2,507030,1900-01-01 04:12:51,1900-01-01 04:43:13
1,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,2,3,507030,1900-01-01 04:46:51,1900-01-01 05:23:46
2,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,3,4,507030,1900-01-01 05:24:06,1900-01-01 06:01:24
3,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,4,5,507030,1900-01-01 06:04:59,1900-01-01 06:45:15
4,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,5,6,507030,1900-01-01 06:53:14,1900-01-01 07:33:32

In [13]:
# Convertir la columna 'Fecha' a tipo datetime
acb['Fecha'] = pd.to_datetime(acb['Fecha'], format='%d/%m/%Y')

acb

,Fecha,Código Bus,Numero FMS Bus,Servicio Bus,Línea,Tabla,Viaje Linea,Id Viaje,Conductor,HoraMinima,HoraMaxima
0,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,1,2,507030,1900-01-01 04:12:51,1900-01-01 04:43:13
1,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,2,3,507030,1900-01-01 04:46:51,1900-01-01 05:23:46
2,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,3,4,507030,1900-01-01 05:24:06,1900-01-01 06:01:24
3,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,4,5,507030,1900-01-01 06:04:59,1900-01-01 06:45:15
4,2026-05-13,70200,7200,CE0A40013,16-2 Engativa Centro,6,5,6,507030,1900-01-01 06:53:14,1900-01-01 07:33:32
...,...,...,...,...,...,...,...,...,...,...,...
7646,2026-05-14,524010,524010,CE1270004,DA213,4,2,3,510572,1900-01-01 06:51:00,1900-01-01 09:55:00
7647,2026-05-14,524010,524010,CE127G009,DA213,14,1,1,509260,1900-01-01 18:51:51,1900-01-01 21:14:05
7648,2026-05-14,524010,524010,CE127G009,DA213,14,2,2,509260,1900-01-01 21:36:51,1900-01-01 23:17:10
7649,2026-05-14,524010,524010,CE17B0018,DH209,18,2,3,510391,1900-01-01 10:12:26,1900-01-01 13:52:00
7650,2026-05-14,524010,524010,CE17B0018,DH209,18,3,4,510142,1900-01-01 14:00:16,1900-01-01 18:08:32

Fonias

In [14]:
# # Convertir las columnas de tiempo a cadenas
# ab['Hora'] = ab['Hora'].astype(str)

# # Aplicar la función para corregir los tiempos
# ab['Hora'] = ab['Hora'].apply(fix_time)

# # Convertir las columnas de tiempo a datetime (sin fecha, solo tiempo)
# ab['Hora'] = pd.to_datetime(ab['Hora'], format='%H:%M:%S').dt.time

# ab.head()

In [15]:
# Ruta de la carpeta que contiene los archivos de actividad de bus zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/FMS 2025/Zonal/Fonias'

# Fechas de inicio y fin para el filtro
fecha_inicio = pd.to_datetime(f'{fecha_if}', format='%d%m%Y')
fecha_fin = pd.to_datetime(f'{fecha_ff}', format='%d%m%Y')

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_fonias.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato datetime para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo_dt <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo .csv
            df = pd.read_csv(ruta_archivo, encoding='latin')
            
            # Completar los valores faltantes en la columna 'Fecha'
            if 'Fecha' in df.columns:
                df['Fecha'] = df['Fecha'].ffill()
                
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    fn_zonal = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
fn_zonal.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,Z50-4360,...,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:30,0:00:58,Llamada terminada por el técnico de control
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,Z50-4454,...,Si,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:38,13/05/2026 3:38,NaN,NaN,NaN,Eliminado de la lista
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,Z50-7120,...,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,0:00:20,Llamada terminada por el técnico de control
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,Z50-7098,...,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 4:05,13/05/2026 4:05,13/05/2026 4:06,13/05/2026 4:06,0:00:32,Llamada terminada por el técnico de control
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,Z50-4303,...,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:08,0:00:27,Llamada terminada por el técnico de control

In [16]:
# Ruta de la carpeta que contiene los archivos de actividad de bus zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/FMS 2025/Alimentacion/Fonias Troncal'

# Fechas de inicio y fin para el filtro
fecha_inicio = pd.to_datetime(f'{fecha_if}', format='%d%m%Y')
fecha_fin = pd.to_datetime(f'{fecha_ff}', format='%d%m%Y')

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_fonias Troncal.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato datetime para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo_dt <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo .csv
            df = pd.read_csv(ruta_archivo, encoding='latin')
            
            # Completar los valores faltantes en la columna 'Fecha'
            if 'Fecha' in df.columns:
                df['Fecha'] = df['Fecha'].ffill()
                
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    fn_troncal = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
fn_troncal.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado
0,13/05/2026,ENGATIVA AL,GMOVIL ENGATIVA,Vehículo,10474,16-feb,16-2 Engativa Centro,12551.0,16-2_V2,E0228,...,Si,Llamada normal,LVARGAS_105,LAURA VARGAS MARCELA GUTIERREZ,13/05/2026 8:59,13/05/2026 8:59,13/05/2026 9:01,13/05/2026 9:02,0:00:12,Fallo apertura de llamada
1,13/05/2026,ENGATIVA AL,GMOVIL ENGATIVA,Vehículo,10504,1-ene,1-1 Alamos,10990.0,1-1_V1,E0227,...,Si,Llamada normal,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,13/05/2026 12:02,13/05/2026 12:02,13/05/2026 12:05,13/05/2026 12:06,0:00:49,Llamada terminada por el técnico de control
2,13/05/2026,ENGATIVA AL,GMOVIL ENGATIVA,Vehículo,10504,1-ene,1-1 Alamos,10990.0,1-1_V1,E0227,...,No,Llamada normal,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,13/05/2026 12:10,13/05/2026 12:10,13/05/2026 12:10,13/05/2026 12:11,0:00:50,Llamada terminada por el técnico de control
3,13/05/2026,ENGATIVA AL,GMOVIL ENGATIVA,Vehículo,10504,1-ene,1-1 Alamos,10990.0,1-1_V1,E0227,...,No,Llamada normal,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,13/05/2026 12:12,13/05/2026 12:12,13/05/2026 12:12,13/05/2026 12:13,0:00:55,Llamada terminada por el técnico de control
4,13/05/2026,ENGATIVA AL,GMOVIL ENGATIVA,Vehículo,10474,16-feb,16-2 Engativa Centro,12551.0,16-2_V2,E0200,...,Si,Llamada normal,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,13/05/2026 14:13,13/05/2026 14:13,13/05/2026 14:13,13/05/2026 14:14,0:00:47,Llamada terminada por el técnico de control

In [17]:
# Consolidar todos los DataFrames en uno solo

fonias = pd.concat([fn_zonal, fn_troncal], ignore_index=True)

# # Convertir la columna 'Fecha' a tipo datetime
# fonias['Fecha'] = pd.to_datetime(fonias['Fecha'], format='%d/%m/%Y')

fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,Z50-4360,...,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:30,0:00:58,Llamada terminada por el técnico de control
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,Z50-4454,...,Si,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:38,13/05/2026 3:38,NaN,NaN,NaN,Eliminado de la lista
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,Z50-7120,...,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,0:00:20,Llamada terminada por el técnico de control
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,Z50-7098,...,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 4:05,13/05/2026 4:05,13/05/2026 4:06,13/05/2026 4:06,0:00:32,Llamada terminada por el técnico de control
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,Z50-4303,...,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:08,0:00:27,Llamada terminada por el técnico de control

In [18]:
# Eliminar las filas donde la columna 'Petición de Móvil' sea NaN
if 'Petición Móvil' in fonias.columns:
    fonias = fonias.dropna(subset=['Petición Móvil'])
    
# Eliminar las columnas 'Tipo Fonía' y 'Grabación' si existen en el DataFrame
columns_to_drop = ['Tipo Fonía', 'Grabación','Id. Fonía','Id. Fonía Puesto','Puesto']
fonias = fonias.drop(columns=columns_to_drop, errors='ignore')

# Mostrar el DataFrame resultante
fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,Z50-4360,...,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:30,0:00:58,Llamada terminada por el técnico de control
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,Z50-4454,...,Si,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:38,13/05/2026 3:38,NaN,NaN,NaN,Eliminado de la lista
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,Z50-7120,...,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,0:00:20,Llamada terminada por el técnico de control
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,Z50-7098,...,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 4:05,13/05/2026 4:05,13/05/2026 4:06,13/05/2026 4:06,0:00:32,Llamada terminada por el técnico de control
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,Z50-4303,...,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:08,0:00:27,Llamada terminada por el técnico de control

In [19]:
# Convertir las columnas de fecha y hora 
columns_to_modify = ['Hora Petición', 'Hora Apertura', 'Hora Cierre']

for column in columns_to_modify:
    if column in fonias.columns:
        # Extraer solo la parte de la hora
        fonias[column] = fonias[column].dt.strftime('%H:%M:%S')

# Mostrar el DataFrame resultante
fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,Z50-4360,...,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:30,0:00:58,Llamada terminada por el técnico de control
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,Z50-4454,...,Si,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:38,13/05/2026 3:38,NaN,NaN,NaN,Eliminado de la lista
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,Z50-7120,...,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,0:00:20,Llamada terminada por el técnico de control
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,Z50-7098,...,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 4:05,13/05/2026 4:05,13/05/2026 4:06,13/05/2026 4:06,0:00:32,Llamada terminada por el técnico de control
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,Z50-4303,...,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:08,0:00:27,Llamada terminada por el técnico de control

In [20]:
# Filtrar filas donde 'Código' no sea NaN y no esté vacío
fonias = fonias[fonias['Código Bus'].notna() & (fonias['Código Bus'].str.strip() != '')]

# Cambiar 'E0' por '70' al inicio del código
fonias['Código Bus'] = (
    fonias['Código Bus']
      .astype(str)
      .str.strip()                        # quitar espacios
      .str.replace(r'^E', '7', regex=True)  # E al inicio → 7
      .str.replace('Z', '', regex=False)    # quitar Z
      .str.replace('-', '', regex=False)    # quitar guiones
      .str.replace(r'\.0$', '', regex=True) # por si vienen como 123.0
)

# Convertir a entero (forzando errores a NaN por seguridad)
fonias['Código Bus'] = pd.to_numeric(fonias['Código Bus'], errors='coerce').astype('Int64')

fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:29,13/05/2026 3:30,0:00:58,Llamada terminada por el técnico de control
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,504454,...,Si,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,13/05/2026 3:38,13/05/2026 3:38,NaN,NaN,NaN,Eliminado de la lista
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,13/05/2026 3:50,0:00:20,Llamada terminada por el técnico de control
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,13/05/2026 4:05,13/05/2026 4:05,13/05/2026 4:06,13/05/2026 4:06,0:00:32,Llamada terminada por el técnico de control
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:07,13/05/2026 4:08,0:00:27,Llamada terminada por el técnico de control

In [21]:
# Asegúrate de que las columnas 'Hora Apertura' y 'Hora Petición' están en formato de tiempo
fonias['Tiempo Apertura'] = pd.to_datetime(fonias['Tiempo Apertura'], errors='coerce').dt.time
fonias['Tiempo Petición Real'] = pd.to_datetime(fonias['Tiempo Petición Real'], errors='coerce').dt.time

# Función para calcular el tiempo de atención y formatearlo como 'HH:MM:SS'
def calcular_tiempo_atencion(row):
    if pd.isna(row['Tiempo Apertura']) or row['Estado'] == 'Eliminado de la lista':
        return ''
    
    hora_apertura = pd.to_datetime(row['Tiempo Apertura'], format='%H:%M:%S').time()
    hora_peticion = pd.to_datetime(row['Tiempo Petición Real'], format='%H:%M:%S').time()
    
    # Convertir las horas a datetime para la resta
    t1 = pd.to_datetime(hora_apertura.strftime('%H:%M:%S'), format='%H:%M:%S')
    t2 = pd.to_datetime(hora_peticion.strftime('%H:%M:%S'), format='%H:%M:%S')

    if hora_apertura == hora_peticion:
        return '00:00:00'
    elif hora_peticion < hora_apertura:
        diferencia = t1 - t2
    elif hora_peticion < pd.to_datetime('23:59:00', format='%H:%M:%S').time() and hora_apertura > pd.to_datetime('00:00:00', format='%H:%M:%S').time():
        t1 = pd.to_datetime('23:59:00', format='%H:%M:%S')
        t2 = pd.to_datetime(hora_peticion.strftime('%H:%M:%S'), format='%H:%M:%S')
        t3 = pd.to_datetime(hora_apertura.strftime('%H:%M:%S'), format='%H:%M:%S')
        diferencia = (t1 - t2) + (t3 - pd.to_datetime('00:00:00', format='%H:%M:%S'))
    else:
        return ''

    # Formatear la diferencia como 'HH:MM:SS'
    return str(diferencia).split()[-1]

# Aplicar la función para crear la nueva columna
fonias['TMR'] = fonias.apply(calcular_tiempo_atencion, axis=1)

# Mostrar el DataFrame resultante
fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_13372\3285904674.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  fonias['Tiempo Apertura'] = pd.to_datetime(fonias['Tiempo Apertura'], errors='coerce').dt.time
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_13372\3285904674.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  fonias['Tiempo Petición Real'] = pd.to_datetime(fonias['Tiempo Petición Real'], errors='coerce').dt.time

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado,TMR
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,03:29:00,13/05/2026 3:29,03:29:00,13/05/2026 3:30,0:00:58,Llamada terminada por el técnico de control,00:00:00
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,504454,...,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,03:38:00,13/05/2026 3:38,NaT,NaN,NaN,Eliminado de la lista,
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,03:50:00,13/05/2026 3:50,03:50:00,13/05/2026 3:50,0:00:20,Llamada terminada por el técnico de control,00:00:00
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,04:05:00,13/05/2026 4:05,04:06:00,13/05/2026 4:06,0:00:32,Llamada terminada por el técnico de control,00:01:00
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,04:07:00,13/05/2026 4:07,04:07:00,13/05/2026 4:08,0:00:27,Llamada terminada por el técnico de control,00:00:00

In [22]:
# Hora Cierre está en formato datetime

fonias['Tiempo Cierre'] = pd.to_datetime(fonias['Tiempo Cierre'], errors='coerce').dt.time

fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_13372\564445473.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  fonias['Tiempo Cierre'] = pd.to_datetime(fonias['Tiempo Cierre'], errors='coerce').dt.time

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado,TMR
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,03:29:00,13/05/2026 3:29,03:29:00,03:30:00,0:00:58,Llamada terminada por el técnico de control,00:00:00
1,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10292,577,577,NaN,NaN,504454,...,Prioritaria,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,03:38:00,13/05/2026 3:38,NaT,NaT,NaN,Eliminado de la lista,
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,03:50:00,13/05/2026 3:50,03:50:00,03:50:00,0:00:20,Llamada terminada por el técnico de control,00:00:00
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,04:05:00,13/05/2026 4:05,04:06:00,04:06:00,0:00:32,Llamada terminada por el técnico de control,00:01:00
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,04:07:00,13/05/2026 4:07,04:07:00,04:08:00,0:00:27,Llamada terminada por el técnico de control,00:00:00

In [23]:
# Filtra las filas donde 'Tiempo Petición Real' NO esté vacío
fonias = fonias[fonias['Estado'] != 'Eliminado de la lista']
fonias = fonias[fonias['Tiempo Petición Real'].notna()]
fonias = fonias[fonias['Duración'].notna()]

fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Prioridad,Usuario,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado,TMR
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,03:29:00,13/05/2026 3:29,03:29:00,03:30:00,0:00:58,Llamada terminada por el técnico de control,00:00:00
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,03:50:00,13/05/2026 3:50,03:50:00,03:50:00,0:00:20,Llamada terminada por el técnico de control,00:00:00
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,04:05:00,13/05/2026 4:05,04:06:00,04:06:00,0:00:32,Llamada terminada por el técnico de control,00:01:00
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,04:07:00,13/05/2026 4:07,04:07:00,04:08:00,0:00:27,Llamada terminada por el técnico de control,00:00:00
5,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504311,...,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,04:08:00,13/05/2026 4:08,04:08:00,04:09:00,0:00:39,Llamada terminada por el técnico de control,00:00:00

In [24]:
# Función para convertir un tiempo en formato datetime a segundos desde el inicio del día
def time_to_seconds(time):
    if pd.isna(time):
        return None
    return time.hour * 3600 + time.minute * 60 + time.second

# Aplicar la función a las columnas correspondientes
fonias['Hora Petición Segundos'] = fonias['Tiempo Petición Real'].apply(time_to_seconds)
acb['HoraMinima Segundos'] = acb['HoraMinima'].apply(time_to_seconds)
acb['HoraMaxima Segundos'] = acb['HoraMaxima'].apply(time_to_seconds)

In [25]:
def calcular_max_linea(fecha, codigo_bus, hora_peticion_segundos):
    # Filtro para el DataFrame combinado
    filtro = (
        (acb['Fecha'] == fecha) &
        (acb['Código Bus'] == codigo_bus) &
        (acb['HoraMinima Segundos'] <= hora_peticion_segundos) &
        (hora_peticion_segundos < acb['HoraMaxima Segundos'])
    )
    
    # Filtrar el DataFrame acb según el filtro
    resultado = acb.loc[filtro, 'Viaje Linea']
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not resultado.empty:
        # Obtener el valor máximo de 'ViajeLinea'
        return resultado.max()
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes en fonias
fonias['Viaje'] = fonias.apply(
    lambda row: calcular_max_linea(
        row['Fecha'],
        row['Código Bus'],
        row['Hora Petición Segundos']
    ),
    axis=1
)

fonias['Viaje'].fillna(0, inplace=True)

# Convertir la columna 'Viaje' a enteros
fonias['Viaje'] = fonias['Viaje'].astype(int)

fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_13372\316449512.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['Viaje'].fillna(0, inplace=True)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Nombre de Usuario,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado,TMR,Hora Petición Segundos,Viaje
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,WILLIAM VALDERRAMA IGNACIO GONZALEZ,03:29:00,13/05/2026 3:29,03:29:00,03:30:00,0:00:58,Llamada terminada por el técnico de control,00:00:00,12540,0
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,SANDRA VALERIANO CAROLINA SARMIENTO,03:50:00,13/05/2026 3:50,03:50:00,03:50:00,0:00:20,Llamada terminada por el técnico de control,00:00:00,13800,0
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,SANDRA VALERIANO CAROLINA SARMIENTO,04:05:00,13/05/2026 4:05,04:06:00,04:06:00,0:00:32,Llamada terminada por el técnico de control,00:01:00,14700,1
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,MARTHA IBETH MARTIN MARTIN,04:07:00,13/05/2026 4:07,04:07:00,04:08:00,0:00:27,Llamada terminada por el técnico de control,00:00:00,14820,1
5,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504311,...,MARTHA IBETH MARTIN MARTIN,04:08:00,13/05/2026 4:08,04:08:00,04:09:00,0:00:39,Llamada terminada por el técnico de control,00:00:00,14880,1

In [26]:
def calcular_max_linea(fecha, codigo_bus, hora_peticion_segundos):
    # Filtro para el DataFrame combinado
    filtro = (
        (acb['Fecha'] == fecha) &
        (acb['Código Bus'] == codigo_bus) &
        (acb['HoraMinima Segundos'] <= hora_peticion_segundos) &
        (hora_peticion_segundos < acb['HoraMaxima Segundos'])
    )
    
    # Filtrar el DataFrame acb según el filtro
    resultado = acb.loc[filtro, 'Servicio Bus']
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not resultado.empty:
        # Obtener el valor máximo de 'ViajeLinea'
        return resultado.max()
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes en fonias
fonias['ServicioBus'] = fonias.apply(
    lambda row: calcular_max_linea(
        row['Fecha'],
        row['Código Bus'],
        row['Hora Petición Segundos']
    ),
    axis=1
)

fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Tiempo Petición Real,Tiempo Registro Sistema,Tiempo Apertura,Tiempo Cierre,Duración,Estado,TMR,Hora Petición Segundos,Viaje,ServicioBus
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,03:29:00,13/05/2026 3:29,03:29:00,03:30:00,0:00:58,Llamada terminada por el técnico de control,00:00:00,12540,0,None
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,03:50:00,13/05/2026 3:50,03:50:00,03:50:00,0:00:20,Llamada terminada por el técnico de control,00:00:00,13800,0,None
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,04:05:00,13/05/2026 4:05,04:06:00,04:06:00,0:00:32,Llamada terminada por el técnico de control,00:01:00,14700,1,CN31B0001
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,04:07:00,13/05/2026 4:07,04:07:00,04:08:00,0:00:27,Llamada terminada por el técnico de control,00:00:00,14820,1,CE1210001
5,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504311,...,04:08:00,13/05/2026 4:08,04:08:00,04:09:00,0:00:39,Llamada terminada por el técnico de control,00:00:00,14880,1,CE1210002

In [27]:
fonias['TMR1'] = fonias['TMR']
fonias['Duración1'] = fonias['Duración']

In [28]:
# Convertir las columnas a tipo timedelta
fonias['TMR1'] = pd.to_timedelta(fonias['TMR1'], errors='coerce')
fonias['Duración1'] = pd.to_timedelta(fonias['Duración1'], errors='coerce')

# Función para convertir un tiempo en formato timedelta a segundos, si no es NaN
def time_to_seconds(td):
    if pd.isna(td):
        return None
    return td.total_seconds()

# Aplicar la función a las columnas correspondientes solo si contienen datos válidos
fonias['TMR Segundos'] = fonias['TMR1'].apply(lambda x: time_to_seconds(x) if pd.notna(x) else None)
fonias['Duración Segundos'] = fonias['Duración1'].apply(lambda x: time_to_seconds(x) if pd.notna(x) else None)

fonias['TMR Segundos'].fillna(0, inplace=True)
fonias['Duración Segundos'].fillna(0, inplace=True)

# Convertir la columna 'Viaje' a enteros
fonias['TMR Segundos'] = fonias['TMR Segundos'].astype(int)
fonias['Duración Segundos'] = fonias['Duración Segundos'].astype(int)

fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_13372\3967663187.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['TMR Segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_13372\3967663187.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['Duración Segundos'].fillna(0, inplace=True)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Duración,Estado,TMR,Hora Petición Segundos,Viaje,ServicioBus,TMR1,Duración1,TMR Segundos,Duración Segundos
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,0:00:58,Llamada terminada por el técnico de control,00:00:00,12540,0,None,0 days 00:00:00,0 days 00:00:58,0,58
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,0:00:20,Llamada terminada por el técnico de control,00:00:00,13800,0,None,0 days 00:00:00,0 days 00:00:20,0,20
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,0:00:32,Llamada terminada por el técnico de control,00:01:00,14700,1,CN31B0001,0 days 00:01:00,0 days 00:00:32,60,32
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,0:00:27,Llamada terminada por el técnico de control,00:00:00,14820,1,CE1210001,0 days 00:00:00,0 days 00:00:27,0,27
5,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504311,...,0:00:39,Llamada terminada por el técnico de control,00:00:00,14880,1,CE1210002,0 days 00:00:00,0 days 00:00:39,0,39

In [29]:
# Crear condiciones
condiciones = [
    (fonias['Estado'] == 'Llamada terminada por el técnico de control') & (fonias['Duración Segundos'] >= 10) & (fonias['Petición Vehículo'] == 'Si'),
    (fonias['Estado'] == 'Llamada terminada por el técnico de control') & (fonias['TMR Segundos'] <= 60) & (fonias['Petición Vehículo'] == 'Si'),
    (fonias['Estado'] == 'Llamada terminada por el técnico de control') & (fonias['TMR Segundos'] > 90) & (fonias['Petición Vehículo'] == 'Si')
]

# Valores correspondientes para cada condición
valores = [
    0.5,  # Valor por defecto si ninguna de las condiciones anteriores se cumple
    1,
    0
]

# Aplicar condiciones y asignar valores
fonias['Cumplimiento'] = np.select(condiciones, valores, default=np.nan)

# Imprimir el DataFrame para ver el resultado
fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Estado,TMR,Hora Petición Segundos,Viaje,ServicioBus,TMR1,Duración1,TMR Segundos,Duración Segundos,Cumplimiento
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,Llamada terminada por el técnico de control,00:00:00,12540,0,None,0 days 00:00:00,0 days 00:00:58,0,58,NaN
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,Llamada terminada por el técnico de control,00:00:00,13800,0,None,0 days 00:00:00,0 days 00:00:20,0,20,NaN
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,Llamada terminada por el técnico de control,00:01:00,14700,1,CN31B0001,0 days 00:01:00,0 days 00:00:32,60,32,0.5
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,Llamada terminada por el técnico de control,00:00:00,14820,1,CE1210001,0 days 00:00:00,0 days 00:00:27,0,27,0.5
5,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504311,...,Llamada terminada por el técnico de control,00:00:00,14880,1,CE1210002,0 days 00:00:00,0 days 00:00:39,0,39,0.5

In [30]:
# Asegurarse de que 'Código' sea tipo string
fonias['Código Bus'] = fonias['Código Bus'].astype(str)

# Crear condiciones
condiciones = (
    (fonias['Estado'] == 'Llamada terminada por el técnico de control') &
    (fonias['Duración Segundos'] >= 10) &
    (fonias['Petición Vehículo'] == 'Si') &
    (
        (fonias['Código Bus'].str.startswith('50')) |
        (fonias['Código Bus'].str.startswith('52'))
    ) &
    fonias['Línea'].isna()
)

# Asignar valores según las condiciones
fonias['No Asignado'] = np.where(condiciones, 1, np.where(~condiciones, 0, np.nan))

fonias['No Asignado'] = fonias['No Asignado'].astype(int)

# Imprimir el DataFrame para ver el resultado
fonias.head()

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,TMR,Hora Petición Segundos,Viaje,ServicioBus,TMR1,Duración1,TMR Segundos,Duración Segundos,Cumplimiento,No Asignado
0,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,504360,...,00:00:00,12540,0,None,0 days 00:00:00,0 days 00:00:58,0,58,NaN,0
2,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,NaN,NaN,507120,...,00:00:00,13800,0,None,0 days 00:00:00,0 days 00:00:20,0,20,NaN,0
3,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10339,C25,C25,12756.0,C25_V3,507098,...,00:01:00,14700,1,CN31B0001,0 days 00:01:00,0 days 00:00:32,60,32,0.5,0
4,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504303,...,00:00:00,14820,1,CE1210001,0 days 00:00:00,0 days 00:00:27,0,27,0.5,0
5,13/05/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,504311,...,00:00:00,14880,1,CE1210002,0 days 00:00:00,0 days 00:00:39,0,39,0.5,0

In [31]:
# Especificar las columnas que quieres mantener
columnas_deseadas = [
    'Fecha', 'Código Bus', 'Id Línea','Petición Vehículo', 'Prioridad', 'Usuario',
    'Nombre de Usuario', 'Estado','Línea', 'Viaje', 'ServicioBus', 'Cumplimiento',
    'No Asignado', 'Tiempo Petición Real', 'Tiempo Apertura', 'Tiempo Cierre', 'TMR', 'Duración'
]

# Filtrar el DataFrame para mantener solo las columnas deseadas
fonias = fonias[columnas_deseadas]

# Imprimir el DataFrame filtrado para verificar
fonias.head()

,Fecha,Código Bus,Id Línea,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Estado,Línea,Viaje,ServicioBus,Cumplimiento,No Asignado,Tiempo Petición Real,Tiempo Apertura,Tiempo Cierre,TMR,Duración
0,13/05/2026,504360,10184,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,Llamada terminada por el técnico de control,740,0,None,NaN,0,03:29:00,03:29:00,03:30:00,00:00:00,0:00:58
2,13/05/2026,507120,10194,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,539,0,None,NaN,0,03:50:00,03:50:00,03:50:00,00:00:00,0:00:20
3,13/05/2026,507098,10339,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,C25,1,CN31B0001,0.5,0,04:05:00,04:06:00,04:06:00,00:01:00,0:00:32
4,13/05/2026,504303,10690,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210001,0.5,0,04:07:00,04:07:00,04:08:00,00:00:00,0:00:27
5,13/05/2026,504311,10690,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210002,0.5,0,04:08:00,04:08:00,04:09:00,00:00:00,0:00:39

In [32]:
fonias['Emergencia'] = 0

fonias.head()

,Fecha,Código Bus,Id Línea,Petición Vehículo,Prioridad,Usuario,Nombre de Usuario,Estado,Línea,Viaje,ServicioBus,Cumplimiento,No Asignado,Tiempo Petición Real,Tiempo Apertura,Tiempo Cierre,TMR,Duración,Emergencia
0,13/05/2026,504360,10184,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,Llamada terminada por el técnico de control,740,0,None,NaN,0,03:29:00,03:29:00,03:30:00,00:00:00,0:00:58,0
2,13/05/2026,507120,10194,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,539,0,None,NaN,0,03:50:00,03:50:00,03:50:00,00:00:00,0:00:20,0
3,13/05/2026,507098,10339,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,C25,1,CN31B0001,0.5,0,04:05:00,04:06:00,04:06:00,00:01:00,0:00:32,0
4,13/05/2026,504303,10690,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210001,0.5,0,04:07:00,04:07:00,04:08:00,00:00:00,0:00:27,0
5,13/05/2026,504311,10690,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210002,0.5,0,04:08:00,04:08:00,04:09:00,00:00:00,0:00:39,0

In [33]:
# Diccionario de equivalencias FMS -> SAE
columnas_rename = {
    'Fecha': 'Fecha',
    'Código Bus': 'Código',
    'Petición Vehículo': 'Petición Móvil',
    'Prioridad': 'Urgente',
    'Emergencia': 'Emergencia',
    'Usuario': 'Usuario',
    'Nombre de Usuario': 'Nombre Usuario',
    'Estado': 'Estado',
    'Línea': 'Ruta',
    'Viaje': 'Viaje',
    'ServicioBus': 'ServBus',
    'Cumplimiento': 'Cumplimiento',
    'No Asignado': 'No Asignado',
    'Tiempo Petición Real': 'Hora Petición',
    'Tiempo Apertura': 'Hora Apertura',
    'Tiempo Cierre': 'Hora Cierre',
    'TMR': 'TMR',
    'Duración': 'Duración',
    'Id Fonia': 'Id Línea'
}

# Aplicar cambio de nombres
fonias.rename(columns=columnas_rename, inplace=True)

# Verificar
fonias.head()

,Fecha,Código,Id Línea,Petición Móvil,Urgente,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Emergencia
0,13/05/2026,504360,10184,No,Llamada normal,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,Llamada terminada por el técnico de control,740,0,None,NaN,0,03:29:00,03:29:00,03:30:00,00:00:00,0:00:58,0
2,13/05/2026,507120,10194,No,Llamada normal,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,539,0,None,NaN,0,03:50:00,03:50:00,03:50:00,00:00:00,0:00:20,0
3,13/05/2026,507098,10339,Si,Prioritaria,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,C25,1,CN31B0001,0.5,0,04:05:00,04:06:00,04:06:00,00:01:00,0:00:32,0
4,13/05/2026,504303,10690,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210001,0.5,0,04:07:00,04:07:00,04:08:00,00:00:00,0:00:27,0
5,13/05/2026,504311,10690,Si,Llamada normal,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210002,0.5,0,04:08:00,04:08:00,04:09:00,00:00:00,0:00:39,0

In [34]:
# Orden deseado de columnas (SAE)
orden_columnas = [
    'Fecha',
    'Código',
    'Id Línea',
    'Petición Móvil',
    'Urgente',
    'Emergencia',
    'Usuario',
    'Nombre Usuario',
    'Estado',
    'Ruta',
    'Viaje',
    'ServBus',
    'Cumplimiento',
    'No Asignado',
    'Hora Petición',
    'Hora Apertura',
    'Hora Cierre',
    'TMR',
    'Duración'
]

# Reordenar columnas
fonias = fonias[orden_columnas]

# Verificar
fonias.head()

,Fecha,Código,Id Línea,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración
0,13/05/2026,504360,10184,No,Llamada normal,0,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,Llamada terminada por el técnico de control,740,0,None,NaN,0,03:29:00,03:29:00,03:30:00,00:00:00,0:00:58
2,13/05/2026,507120,10194,No,Llamada normal,0,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,539,0,None,NaN,0,03:50:00,03:50:00,03:50:00,00:00:00,0:00:20
3,13/05/2026,507098,10339,Si,Prioritaria,0,SVALERIANO_105,SANDRA VALERIANO CAROLINA SARMIENTO,Llamada terminada por el técnico de control,C25,1,CN31B0001,0.5,0,04:05:00,04:06:00,04:06:00,00:01:00,0:00:32
4,13/05/2026,504303,10690,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210001,0.5,0,04:07:00,04:07:00,04:08:00,00:00:00,0:00:27
5,13/05/2026,504311,10690,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el técnico de control,DL219,1,CE1210002,0.5,0,04:08:00,04:08:00,04:09:00,00:00:00,0:00:39

In [35]:
# fonias.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Fonias/fonias_FMS_{mes}_1.csv', index=False)

In [ ]:
fonias.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Fonias/fonias_FMS_{mes}.csv', index=False)