In [59]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob
from nltk.sentiment import SentimentIntensityAnalyzer
import speech_recognition as sr
from pydub import AudioSegment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
from wordcloud import WordCloud
from collections import Counter
import re

In [60]:
# Crear DataFrame
df = pd.DataFrame({
    'Tipo Novedad': [
        'I5013',
        'I5023',
        'I5023',
        'I5023',
        'I5013',
        'I5023',
        'I5013',
        'I5023',
        'I5013'
    ],
    
    'Fecha Novedad': [
        '05/01/2026 5:56',
        '07/01/2026 12:29',
        '08/01/2026 9:30',
        '08/01/2026 10:18',
        '30/01/2026 12:22',
        '02/03/2026 4:48',
        '04/03/2026 6:19',
        '18/03/2026 3:15',
        '19/03/2026 11:37'
    ],
    
    'Placa': [
        'WDD790',
        'WEW889',
        'WDG054',
        'WHP500',
        'WDG077',
        'WGG311',
        'TUP282',
        'WPM822',
        'KYP769'
    ],
    
    'Móvil': [
        'Z50-4187',
        'Z50-4285',
        'Z50-4415',
        'Z50-4166',
        'Z50-4421',
        'Z50-2124',
        'Z52-4003',
        'Z50-4372',
        'Z50-4498'
    ]
})

# Convertir fecha
df['Fecha Novedad'] = pd.to_datetime(
    df['Fecha Novedad'],
    dayfirst=True
)

df.head()

  Tipo Novedad       Fecha Novedad   Placa     Móvil
0        I5013 2026-01-05 05:56:00  WDD790  Z50-4187
1        I5023 2026-01-07 12:29:00  WEW889  Z50-4285
2        I5023 2026-01-08 09:30:00  WDG054  Z50-4415
3        I5023 2026-01-08 10:18:00  WHP500  Z50-4166
4        I5013 2026-01-30 12:22:00  WDG077  Z50-4421

In [61]:
# Crear DataFrame
df2 = pd.DataFrame({
    'Tipo Novedad': [
        'I5022',
        'I5022',
        'I5022',
        'I5022'
    ],
    
    'Fecha Novedad': [
        '02/01/2026 3:32',
        '09/01/2026 3:25',
        '14/01/2026 4:36',
        '04/03/2026 4:39'
    ],
    
    'Placa': [
        'WDG520',
        'WDG501',
        'WCM432',
        'WDE327'
    ],
    
    'Móvil': [
        'Z50-4227',
        'Z50-4204',
        'Z50-4137',
        'Z50-4202'
    ]
})

# Convertir fecha
df2['Fecha Novedad'] = pd.to_datetime(
    df2['Fecha Novedad'],
    dayfirst=True
)

df2

  Tipo Novedad       Fecha Novedad   Placa     Móvil
0        I5022 2026-01-02 03:32:00  WDG520  Z50-4227
1        I5022 2026-01-09 03:25:00  WDG501  Z50-4204
2        I5022 2026-01-14 04:36:00  WCM432  Z50-4137
3        I5022 2026-03-04 04:39:00  WDE327  Z50-4202

In [62]:
# Consolidar los dos DataFrames
df_consolidado = pd.concat(
    [df, df2],
    ignore_index=True
)

# Ordenar por fecha
df_consolidado = df_consolidado.sort_values(
    'Fecha Novedad'
).reset_index(drop=True)

df_consolidado

   Tipo Novedad       Fecha Novedad   Placa     Móvil
0         I5022 2026-01-02 03:32:00  WDG520  Z50-4227
1         I5013 2026-01-05 05:56:00  WDD790  Z50-4187
2         I5023 2026-01-07 12:29:00  WEW889  Z50-4285
3         I5023 2026-01-08 09:30:00  WDG054  Z50-4415
4         I5023 2026-01-08 10:18:00  WHP500  Z50-4166
5         I5022 2026-01-09 03:25:00  WDG501  Z50-4204
6         I5022 2026-01-14 04:36:00  WCM432  Z50-4137
7         I5013 2026-01-30 12:22:00  WDG077  Z50-4421
8         I5023 2026-03-02 04:48:00  WGG311  Z50-2124
9         I5022 2026-03-04 04:39:00  WDE327  Z50-4202
10        I5013 2026-03-04 06:19:00  TUP282  Z52-4003
11        I5023 2026-03-18 03:15:00  WPM822  Z50-4372
12        I5013 2026-03-19 11:37:00  KYP769  Z50-4498

In [63]:
buses = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/buses_inmovilizados.xlsx')

buses.head(2)

,Concesionario de Operación,Placa,Fecha de Inmovilización,Causa de Inmovilización,Descripción de la novedad,Creador,Fecha de Revisión,Revisor,Descripción de Revisión,Fecha de Habilitación,Habilitador
0,GMOVIL ENGATIVA,JTQ522,01/12/2025 04:33:19,PATIO,SUSPENSIÓN§Móvil 504446 hoja muelle posición 3...,FLOTA BERENICE ARIAS DIAZ,01/12/2025 04:33:21,FLINM Liliana Andrea Rey,Móvil 504446/ O.T. 662601/ se realiza cambio ...,01/12/2025 16:51:15,FLINM Liliana Andrea Rey
1,GMOVIL ENGATIVA,WGG314,01/12/2025 04:33:58,PATIO,PUERTAS§Móvil 502118 puerta de servicio 2 fue...,FLOTA BERENICE ARIAS DIAZ,01/12/2025 04:33:59,FLOTA BERENICE ARIAS DIAZ,Móvil 502118/ O.T. 662339/ cambio de electrov...,01/12/2025 05:46:39,FLOTA BERENICE ARIAS DIAZ

In [64]:
# ======================================================
# FECHAS CORRECTAS
# ======================================================

buses_aux = buses.copy()

buses_aux['Fecha_bus'] = pd.to_datetime(
    buses_aux['Fecha de Inmovilización'],
    dayfirst=True,
    errors='coerce'
)

# Dejar SOLO texto dd/mm/yyyy
buses_aux['Fecha_bus'] = buses_aux['Fecha_bus'].dt.strftime('%d/%m/%Y')


df_aux = df_consolidado.copy()

df_aux['Fecha_nov'] = pd.to_datetime(
    df_aux['Fecha Novedad'],
    dayfirst=True,
    errors='coerce'
)

df_aux['Fecha_nov'] = df_aux['Fecha_nov'].dt.strftime('%d/%m/%Y')


# ======================================================
# CREAR COLUMNAS DE FECHAS
# ======================================================

buses_aux['Marca'] = 'X'

tabla_fechas = (
    buses_aux
    .pivot_table(
        index='Placa',
        columns='Fecha_bus',
        values='Marca',
        aggfunc='first'
    )
    .reset_index()
)

# ======================================================
# CRUZAR
# ======================================================

resultado = df_aux.merge(
    tabla_fechas,
    on='Placa',
    how='left'
)

resultado.head()

,Tipo Novedad,Fecha Novedad,Placa,Móvil,Fecha_nov,01/01/2026,01/02/2026,01/03/2026,01/04/2026,01/05/2026,...,29/03/2026,29/04/2026,29/12/2025,30/01/2026,30/03/2026,30/04/2026,30/12/2025,31/01/2026,31/03/2026,31/12/2025
0,I5022,2026-01-02 03:32:00,WDG520,Z50-4227,02/01/2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I5013,2026-01-05 05:56:00,WDD790,Z50-4187,05/01/2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I5023,2026-01-07 12:29:00,WEW889,Z50-4285,07/01/2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I5023,2026-01-08 09:30:00,WDG054,Z50-4415,08/01/2026,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,X,NaN
4,I5023,2026-01-08 10:18:00,WHP500,Z50-4166,08/01/2026,NaN,NaN,NaN,NaN,NaN,...,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
resultado.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Automatización/resultado.csv', index=False, sep=';')