In [1]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import re
import pyproj
import folium

In [2]:
#Filtros de fechas

dia_ivd = '20260401'
dia_fvd = '20260430'

dia_ias = '01-04-2026'
dia_fas = '30-04-2026'

dia_if = '2026-04-01'
dia_ff = '2026-04-30'

mes = 'Novedades_abr26'

mes_i = 'abr26'

total_dias_julio = 30

mes_c = 'Abril'

Importar archivos de viajes desglosados zonal y troncal, informes de regularidad de plataforma EIC

In [3]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/01 viajes_desglosados_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosado.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_zonal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_zonal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_zonal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,0,36341,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00
1,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,0,36466,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99
2,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,0,36311,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00
3,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,0,36478,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99
4,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,0,36331,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00

In [4]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/16 viajes_desglosados_alimentacion_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosadotroncal.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_troncal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_troncal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_troncal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/04/2026,ENGATIVA AL,NaN,(105) GMOVIL ENGATIVA,20260401-AD0474012-1-12551,AD0474012,1,1,1,10474,...,0,12875,No,NaN,NaN,NaN,"1, 1",NaN,NaN,1.0
1,1/04/2026,ENGATIVA AL,NaN,(105) GMOVIL ENGATIVA,20260401-AD0474012-2-12551,AD0474012,2,2,2,10474,...,0,12875,No,NaN,NaN,NaN,"1, 2",NaN,NaN,1.0
2,1/04/2026,ENGATIVA AL,NaN,(105) GMOVIL ENGATIVA,20260401-AD0474012-3-12551,AD0474012,3,3,3,10474,...,0,12875,No,NaN,NaN,NaN,"1, 2",NaN,NaN,1.0
3,1/04/2026,ENGATIVA AL,NaN,(105) GMOVIL ENGATIVA,20260401-AD0474012-4-12551,AD0474012,4,4,4,10474,...,0,12875,No,NaN,NaN,NaN,"1, 3",NaN,NaN,1.0
4,1/04/2026,ENGATIVA AL,NaN,(105) GMOVIL ENGATIVA,20260401-AD0474012-5-12551,AD0474012,5,5,5,10474,...,0,12875,No,NaN,NaN,NaN,"1, 3",NaN,NaN,1.0

In [5]:
# Consolidar todos los DataFrames en uno solo

desglosados_fms = pd.concat([desg_zonal_fms, desg_troncal_fms], ignore_index=True)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,0,36341,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00
1,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,0,36466,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99
2,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,0,36311,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00
3,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,0,36478,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99
4,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,0,36331,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00

In [6]:
desglosados_fms['Id Línea '] = (
    desglosados_fms['Id Línea ']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,0,36341,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00
1,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,0,36466,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99
2,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,0,36311,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00
3,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,0,36478,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99
4,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,0,36331,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00

In [7]:
desglosados_fms['KmEjecutado'] = (
    desglosados_fms['KmEjecutado']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,0,36341,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00
1,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,0,36466,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99
2,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,0,36311,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00
3,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,0,36478,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99
4,1/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,0,36331,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00

In [8]:
# Ruta de la carpeta que contiene los archivos de desglosados zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/Blogger/Asistencia/2026/{mes_c}'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ias}'
fecha_fin = f'{dia_fas}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:10]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%d-%m-%Y', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', delimiter=';',skiprows=2, low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            # Añadir una nueva columna 'Fecha' con la fecha extraída del nombre del archivo
            df['Fecha'] = fecha_archivo
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    asistencia = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    asistencia.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/asistencia_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET4M-T2,ET4M-T2,04:00:00,NaN,03:56:00,08:00:00,12:00:00,...,12:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2026
1,LUIS ARCESIO NAVARRETE VARGAS,LUIS ARCESIO,NAVARRETE VARGAS,EG1,Verbena I,04:00:00,NaN,03:59:00,09:00:00,13:00:00,...,12:59:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2026
2,LORENA BENILDA PAJARO AREVALO,LORENA BENILDA,PAJARO AREVALO,PLA1,Portal Dorado,04:30:00,NaN,04:26:00,08:00:00,12:30:00,...,12:34:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2026
3,GABY CONSTANZA MARTINEZ ORTIZ,GABY CONSTANZA,MARTINEZ ORTIZ,EG7,Gaco I,04:00:00,NaN,03:55:00,09:00:00,13:00:00,...,12:57:00,00:02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2026
4,OSCAR EDUARDO DUARTE BAQUERO,OSCAR EDUARDO,DUARTE BAQUERO,EG11,Villa Gladys - Gaco,04:00:00,NaN,03:58:00,09:00:00,13:00:00,...,13:01:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-04-2026

In [9]:
## Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia

# Convertir la columna 'Fecha' a tipo datetime
asistencia['Fecha'] = pd.to_datetime(asistencia['Fecha'], format='%d-%m-%Y')

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
asistencia['Fecha'] = asistencia['Fecha'].dt.strftime('%d/%m/%Y')

asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET4M-T2,ET4M-T2,04:00:00,NaN,03:56:00,08:00:00,12:00:00,...,12:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/04/2026
1,LUIS ARCESIO NAVARRETE VARGAS,LUIS ARCESIO,NAVARRETE VARGAS,EG1,Verbena I,04:00:00,NaN,03:59:00,09:00:00,13:00:00,...,12:59:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/04/2026
2,LORENA BENILDA PAJARO AREVALO,LORENA BENILDA,PAJARO AREVALO,PLA1,Portal Dorado,04:30:00,NaN,04:26:00,08:00:00,12:30:00,...,12:34:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/04/2026
3,GABY CONSTANZA MARTINEZ ORTIZ,GABY CONSTANZA,MARTINEZ ORTIZ,EG7,Gaco I,04:00:00,NaN,03:55:00,09:00:00,13:00:00,...,12:57:00,00:02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/04/2026
4,OSCAR EDUARDO DUARTE BAQUERO,OSCAR EDUARDO,DUARTE BAQUERO,EG11,Villa Gladys - Gaco,04:00:00,NaN,03:58:00,09:00:00,13:00:00,...,13:01:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/04/2026

In [10]:
#Archivo de novedades disciplinarias

novedades = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/{mes}.csv",encoding='latin', delimiter=';')

In [11]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
novedades['FECHA INICIAL'] = pd.to_datetime(novedades['FECHA INICIAL'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
novedades['FECHA INICIAL'] = novedades['FECHA INICIAL'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1057523,15/04/2026,15/04/2026,1,Ausentismo,PERMISO,Patio Dorado,NaN,1024489560,YERLI IRENE HERNANDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-09 08:42:09 PERMISO - PROCEDIMIENTO OD...,Por Aprobar,NaN
1,1058351,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501161.0,79453992,ALEXANDER GARAVITO HERNANDEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1058352,15/04/2026,15/04/2026,1,Cambio de Turno Operativo,NaN,Patio Dorado,501374.0,91538451,JESUS FLOREZ ALARCON,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
3,1058353,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501522.0,79904374,JOHN HENRY LEON QUIROGA,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
4,1058354,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,502645.0,79842026,MANUEL PISCO RODRIGUEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [12]:
#Archivos de regularidad de plataforma EIC

cerrado = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_cerrrado_{mes_i}.csv", delimiter=';')

etapa_1 = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_Etapa1_{mes_i}.csv", delimiter=';')

In [13]:
#Informes de turnos, tipo día, personal

turno_via = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_via_fms.csv", sep=';')

turno_sup = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_supervisor_fms.csv", sep=';')

tipo_dia = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Tipo día.csv", encoding='latin',delimiter=';')

personal = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Personal_id.csv",encoding='latin',delimiter=';')

turno_ccz = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_control_fms.csv", sep=';')

In [14]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [15]:
#Importar data de fonias

fonias = pd.read_excel ("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2023/fonias_fms.xlsx")

# Convertir la columna 'Fecha' a tipo datetime
fonias['Fecha'] = pd.to_datetime(fonias['Fecha'])

# Filtrar los valores mayores o iguales a la fecha indicada
fonias = fonias[(fonias['Fecha'] >= f'{dia_if}') & (fonias['Fecha'] <= f'{dia_ff}')]

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
fonias['Fecha'] = fonias['Fecha'].dt.strftime('%d/%m/%Y')

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,0,NaN,NaN,0,03:16:00,03:18:00,03:18:00,00:02:00,00:00:00
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,0,NaN,0.5,0,03:20:00,03:22:00,03:23:00,00:02:00,00:00:15
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,0,NaN,0.5,0,03:28:00,03:29:00,03:30:00,00:01:00,00:00:57
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,0,NaN,NaN,0,03:55:00,03:55:00,03:56:00,00:00:00,00:00:16
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,0,NaN,NaN,0,03:58:00,03:58:00,03:58:00,00:00:00,00:00:47

In [16]:
#Crear dataframe para llevar el nombre a fonias

# Crear un diccionario con los datos
data = {
    'RegC': [
        'Luis Fernando Gonzalez', 'William Munar Gonzalez', 'Adriana Patricia Tellez',
        'Jose Antonio Castro Garcia', 'Rosa Tellez', 'Edith Patarroyo',
        'Laura Marcela Vargas Gutierrez', 'Francy Linnie Timaran Cuesta', 
        'Yerly Irene Hernandez Ariza', 'Anderson Mizar Mendoza', 'Jorge Medina Espinoza',
        'Esteban Camilo Medina', 'Sandra Carolina Valeriano', 'Julian Andres Sanchez Restrepo',
        'Karen Lorena Barrera', 'Bryan Guzman', 'Jinneth Alexandra Guzman',
        'Maicol Alexander Pita Blanco', 'Martha Ibeth Martin', 'John Jairo Espinosa Santa',
        'Elicia Mongui Duarte', 'Sonia Constanza Correa Rodriguez', 'Jenny Alexandra Bernal',
        'Norberto Niño Rodriguez', 'Wilson Torres Fajardo', 'William Ignacio Valderrama',
        'Camilo Andres Lopez Penagos', 'Raúl Fabián Romero Micán', 'Deisi Yanira Rojas Torres',
        'Paula Katherine Cantor Salamanca','Angela Mireya Riaño Pasito'
    ],
    'RegControl': [
        'LUIS FERNANDO GONZALEZ REYES', 'WILLIAN HUMBERTO MUNAR GONZALEZ', 
        'ADRIANA PATRICIA TELLEZ VARELA', 'JOSE ANTONIO CASTRO GARCIA', 
        'ROSA MARIELA TELLEZ NAVARRO', 'DORIS EDITH PATARROYO GORDO',
        'LAURA MARCELA VARGAS GUTIERREZ', 'FRANCY LINNE TIMARAN CUESTA', 
        'YERLI IRENE HERNÁNDEZ ARIZA', 'ANDERSON MIZAR MENDOZA', 
        'JORGE MEDINA ESPINOSA', 'ESTEBAN CAMILO MEDINA', 
        'SANDRA CAROLINA VALERIANO SARMIENTO', 'JULIAN ANDRES SANCHEZ RESTREPO', 
        'KAREN LORENA BARRERA SERRANO', 'BRYAN ANDRES GUZMAN ROJANO', 
        'JINETH ALEXANDRA GUZMAN HERNANDEZ', 'MAICOL ALEXANDER PITA BLANCO', 
        'MARTHA IBETH MARTIN MARTIN', 'JOHN JAIRO ESPINOSA SANTA', 
        'ELICIA MONGUI DUARTE', 'SONIA CONSTANZA CORREA RODRIGUEZ', 
        'JENNY ALEXANDRA BERNAL BERNAL', 'NORBERTO NIÑO RODRIGUEZ', 
        'WILSON ABEL TORRES FAJARDO', 'WILLIAM IGNACIO VALDERRAMA GONZALEZ', 
        'CAMILO ANDRES LOPEZ PENAGOS', 'RAUL FABIAN ROMERO MICAN', 
        'DEISY YANIRA ROJAS TORRES', 'PAULA KATHERINE CANTOR SALAMANCA',
        'ANGELA MIREYA RIAÑO PASITO'
    ]
}

# Convertir el diccionario a un DataFrame
base = pd.DataFrame(data)

# Mostrar el DataFrame
base

                                RegC                           RegControl
0             Luis Fernando Gonzalez         LUIS FERNANDO GONZALEZ REYES
1             William Munar Gonzalez      WILLIAN HUMBERTO MUNAR GONZALEZ
2            Adriana Patricia Tellez       ADRIANA PATRICIA TELLEZ VARELA
3         Jose Antonio Castro Garcia           JOSE ANTONIO CASTRO GARCIA
4                        Rosa Tellez          ROSA MARIELA TELLEZ NAVARRO
5                    Edith Patarroyo          DORIS EDITH PATARROYO GORDO
6     Laura Marcela Vargas Gutierrez       LAURA MARCELA VARGAS GUTIERREZ
7       Francy Linnie Timaran Cuesta          FRANCY LINNE TIMARAN CUESTA
8        Yerly Irene Hernandez Ariza          YERLI IRENE HERNÁNDEZ ARIZA
9             Anderson Mizar Mendoza               ANDERSON MIZAR MENDOZA
10             Jorge Medina Espinoza                JORGE MEDINA ESPINOSA
11             Esteban Camilo Medina                ESTEBAN CAMILO MEDINA
12         Sandra Carolina Valeriano  SANDRA CAROLINA VALERIANO SARMIENTO
13    Julian Andres Sanchez Restrepo       JULIAN ANDRES SANCHEZ RESTREPO
14              Karen Lorena Barrera         KAREN LORENA BARRERA SERRANO
15                      Bryan Guzman           BRYAN ANDRES GUZMAN ROJANO
16          Jinneth Alexandra Guzman    JINETH ALEXANDRA GUZMAN HERNANDEZ
17      Maicol Alexander Pita Blanco         MAICOL ALEXANDER PITA BLANCO
18               Martha Ibeth Martin           MARTHA IBETH MARTIN MARTIN
19         John Jairo Espinosa Santa            JOHN JAIRO ESPINOSA SANTA
20              Elicia Mongui Duarte                 ELICIA MONGUI DUARTE
21  Sonia Constanza Correa Rodriguez     SONIA CONSTANZA CORREA RODRIGUEZ
22            Jenny Alexandra Bernal        JENNY ALEXANDRA BERNAL BERNAL
23           Norberto Niño Rodriguez              NORBERTO NIÑO RODRIGUEZ
24             Wilson Torres Fajardo           WILSON ABEL TORRES FAJARDO
25        William Ignacio Valderrama  WILLIAM IGNACIO VALDERRAMA GONZALEZ
26       Camilo Andres Lopez Penagos          CAMILO ANDRES LOPEZ PENAGOS
27          Raúl Fabián Romero Micán             RAUL FABIAN ROMERO MICAN
28         Deisi Yanira Rojas Torres            DEISY YANIRA ROJAS TORRES
29  Paula Katherine Cantor Salamanca     PAULA KATHERINE CANTOR SALAMANCA
30        Angela Mireya Riaño Pasito           ANGELA MIREYA RIAÑO PASITO

Indicador de regularidad de personal de control

In [17]:
#consolidar iri con los datos de cerrado y etapa_1

iri = pd.concat([cerrado,etapa_1], ignore_index=True)

#Eliminar columnas 

col_eliminar = ['IdIRI', 'Estado', 'F. Inicio DP', 'F. Cierre DP','Operador Programado','Id Operador','Operador','Evidencia']

iri = iri.drop(columns=col_eliminar)

iri['Cantidad'] = 1

iri

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\1407071630.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  iri = pd.concat([cerrado,etapa_1], ignore_index=True)

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,1/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,2.25,-1.40,40.000.000,1,0,1,1
1,1/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,4.33,-1.00,40.000.000,1,0,1,1
2,1/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,3.50,-1.77,37.500.000,1,0,1,1
3,1/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.07,-1.75,50.000.000,1,0,1,1
4,1/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,3.98,-0.87,50.000.000,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.07,-1.82,60.000.000,1,0,1,1
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,3.97,-1.25,60.000.000,1,0,1,1
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,7.27,-0.37,60.000.000,1,0,1,1
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,6.87,-0.78,60.000.000,1,0,1,1
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,8.85,-0.48,100.000.000,1,0,1,1

In [18]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
iri['Fecha Viaje'] = pd.to_datetime(iri['Fecha Viaje'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
iri['Fecha Viaje'] = iri['Fecha Viaje'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,2.25,-1.40,40.000.000,1,0,1,1
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,4.33,-1.00,40.000.000,1,0,1,1
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,3.50,-1.77,37.500.000,1,0,1,1
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.07,-1.75,50.000.000,1,0,1,1
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,Con hora de Inicio LG SMART OPERATOR,0,0,3.98,-0.87,50.000.000,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.07,-1.82,60.000.000,1,0,1,1
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,3.97,-1.25,60.000.000,1,0,1,1
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,7.27,-0.37,60.000.000,1,0,1,1
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,6.87,-0.78,60.000.000,1,0,1,1
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,Con hora de Inicio LG SMART OPERATOR,0,0,8.85,-0.48,100.000.000,1,0,1,1

In [19]:
#Convertir datos de columna Hora Teórica

# Expresión regular ajustada para extraer la hora
patron_hora = r'(\d{1,2}:\d{2}:\d{2}\s?[ap]\.?m\.?)'

# Aplicar la extracción de hora a la columna 'Hora Teórica'
iri['Hora'] = iri['Hora Teórica'].str.extract(patron_hora)

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,0,0,2.25,-1.40,40.000.000,1,0,1,1,NaN
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,0,0,4.33,-1.00,40.000.000,1,0,1,1,NaN
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,0,0,3.50,-1.77,37.500.000,1,0,1,1,NaN
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,0,0,5.07,-1.75,50.000.000,1,0,1,1,NaN
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,0,0,3.98,-0.87,50.000.000,1,0,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,0,0,5.07,-1.82,60.000.000,1,0,1,1,NaN
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,0,0,3.97,-1.25,60.000.000,1,0,1,1,NaN
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,0,0,7.27,-0.37,60.000.000,1,0,1,1,NaN
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,0,0,6.87,-0.78,60.000.000,1,0,1,1,NaN
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,0,0,8.85,-0.48,100.000.000,1,0,1,1,NaN

In [20]:
# Dividir la columna 'Hora Teórica' en 'Fecha' y 'Hora'
iri[['Fecha1', 'Hora']] = iri['Hora Teórica'].str.split(' ', n=1, expand=True)

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,0,2.25,-1.40,40.000.000,1,0,1,1,NaN,NaN
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,0,4.33,-1.00,40.000.000,1,0,1,1,NaN,NaN
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,0,3.50,-1.77,37.500.000,1,0,1,1,NaN,NaN
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,0,5.07,-1.75,50.000.000,1,0,1,1,NaN,NaN
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,0,3.98,-0.87,50.000.000,1,0,1,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,0,5.07,-1.82,60.000.000,1,0,1,1,16:34,30/04/2026
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,0,3.97,-1.25,60.000.000,1,0,1,1,17:14,30/04/2026
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,0,7.27,-0.37,60.000.000,1,0,1,1,17:55,30/04/2026
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,0,6.87,-0.78,60.000.000,1,0,1,1,18:38,30/04/2026
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,0,8.85,-0.48,100.000.000,1,0,1,1,20:04,30/04/2026

In [21]:
# Dividir la columna  en partes usando ':', y seleccionar la primera parte (horas)
iri['franja'] = iri['Hora'].str.split(':').str[0]

# Convertir la columna 'franja' a tipo entero
iri['franja'] = pd.to_numeric(iri['franja'], errors='coerce').astype('Int64')

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,2.25,-1.40,40.000.000,1,0,1,1,NaN,NaN,<NA>
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,4.33,-1.00,40.000.000,1,0,1,1,NaN,NaN,<NA>
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,3.50,-1.77,37.500.000,1,0,1,1,NaN,NaN,<NA>
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,5.07,-1.75,50.000.000,1,0,1,1,NaN,NaN,<NA>
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,3.98,-0.87,50.000.000,1,0,1,1,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,5.07,-1.82,60.000.000,1,0,1,1,16:34,30/04/2026,16
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,3.97,-1.25,60.000.000,1,0,1,1,17:14,30/04/2026,17
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,7.27,-0.37,60.000.000,1,0,1,1,17:55,30/04/2026,17
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,6.87,-0.78,60.000.000,1,0,1,1,18:38,30/04/2026,18
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,8.85,-0.48,100.000.000,1,0,1,1,20:04,30/04/2026,20

In [22]:
#Llevar ruta comercial a iri

def calcular_posicion(Linea):
    
    filtro = (
        (turno_via['Linea'] == Linea)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        ruta = turno_via.loc[filtro, 'Ruta'].iloc[0]
        return ruta  if not pd.isna(ruta) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Ruta_Comercial'] = iri.apply(
    lambda row: calcular_posicion(
        row['Linea SAE']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,-1.40,40.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,-1.00,40.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,-1.77,37.500.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,-1.75,50.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,-0.87,50.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,-1.82,60.000.000,1,0,1,1,16:34,30/04/2026,16,1-9 Villas del Dorado
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,-1.25,60.000.000,1,0,1,1,17:14,30/04/2026,17,1-9 Villas del Dorado
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,-0.37,60.000.000,1,0,1,1,17:55,30/04/2026,17,1-9 Villas del Dorado
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,-0.78,60.000.000,1,0,1,1,18:38,30/04/2026,18,1-9 Villas del Dorado
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,-0.48,100.000.000,1,0,1,1,20:04,30/04/2026,20,1-9 Villas del Dorado

In [23]:
#Llevar tipo día a iri

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Tipo dia'] = iri.apply(
    lambda row: calcular_posicion(
        row['Fecha Viaje']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,40.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,40.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,37.500.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,50.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,50.000.000,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,60.000.000,1,0,1,1,16:34,30/04/2026,16,1-9 Villas del Dorado,Hábil
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,60.000.000,1,0,1,1,17:14,30/04/2026,17,1-9 Villas del Dorado,Hábil
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,60.000.000,1,0,1,1,17:55,30/04/2026,17,1-9 Villas del Dorado,Hábil
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,60.000.000,1,0,1,1,18:38,30/04/2026,18,1-9 Villas del Dorado,Hábil
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,100.000.000,1,0,1,1,20:04,30/04/2026,20,1-9 Villas del Dorado,Hábil

In [24]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
iri['Tipo_dia'] = iri['Tipo dia'].apply(obtener_letra_inicial)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,1,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,1,0,1,1,16:34,30/04/2026,16,1-9 Villas del Dorado,Hábil,H
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,1,0,1,1,17:14,30/04/2026,17,1-9 Villas del Dorado,Hábil,H
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,1,0,1,1,17:55,30/04/2026,17,1-9 Villas del Dorado,Hábil,H
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,1,0,1,1,18:38,30/04/2026,18,1-9 Villas del Dorado,Hábil,H
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,1,0,1,1,20:04,30/04/2026,20,1-9 Villas del Dorado,Hábil,H

In [25]:
#Traer el turno de reg_via

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,0,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,0,1,1,16:34,30/04/2026,16,1-9 Villas del Dorado,Hábil,H,PLAD
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,0,1,1,17:14,30/04/2026,17,1-9 Villas del Dorado,Hábil,H,PLAD
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,0,1,1,17:55,30/04/2026,17,1-9 Villas del Dorado,Hábil,H,PLAD
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,0,1,1,18:38,30/04/2026,18,1-9 Villas del Dorado,Hábil,H,PLAD
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,0,1,1,20:04,30/04/2026,20,1-9 Villas del Dorado,Hábil,H,PLAD

In [26]:
#Traer el turno de control

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,1,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,1,1,16:34,30/04/2026,16,1-9 Villas del Dorado,Hábil,H,PLAD,None
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,1,1,17:14,30/04/2026,17,1-9 Villas del Dorado,Hábil,H,PLAD,None
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,1,1,17:55,30/04/2026,17,1-9 Villas del Dorado,Hábil,H,PLAD,None
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,1,1,18:38,30/04/2026,18,1-9 Villas del Dorado,Hábil,H,PLAD,None
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,1,1,20:04,30/04/2026,20,1-9 Villas del Dorado,Hábil,H,PLAD,None

In [27]:
#Traer el turno de supervisor

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_Sup'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,1,NaN,NaN,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,1,16:34,30/04/2026,16,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,1,17:14,30/04/2026,17,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,1,17:55,30/04/2026,17,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,1,18:38,30/04/2026,18,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,1,20:04,30/04/2026,20,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM

In [28]:
#Traer el regulador según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['reg_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_via']
    ),
    axis=1
)

iri['reg_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_ccz']
    ),
    axis=1
)

iri['Supervisor'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_Sup']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None,None,None,None
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None,None,None,None
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None,None,None,None
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None,None,None,None
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,<NA>,16-2 Engativa Centro,Hábil,H,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,16,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,17,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,17,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,18,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,20,1-9 Villas del Dorado,Hábil,H,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS

In [29]:
#Llevar identificación al regulador

def calcular_posicion(Nombre_completo):
    
    filtro = (
        (personal['Nombre Completo'] == Nombre_completo)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not personal.loc[filtro].empty:
        # Obtener el primer valor
        personas = personal.loc[filtro, 'Identificación'].iloc[0]
        return  personas  if not pd.isna( personas ) else None  
    
    return 0  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Id_via'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_via']
    ),
    axis=1
)

iri['Id_ccz'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_ccz']
    ),
    axis=1
)

iri['Id_sup'] = iri.apply(
    lambda row: calcular_posicion(
        row['Supervisor']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,H,None,None,None,None,None,None,0,0,0
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,H,None,None,None,None,None,None,0,0,0
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,H,None,None,None,None,None,None,0,0,0
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,H,None,None,None,None,None,None,0,0,0
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,H,None,None,None,None,None,None,0,0,0

In [30]:
# Convertir 'Nodo' a tipo entero
iri['Viaje Regular'] = iri['Viaje Regular'].astype(int)

iri['Viaje Totales'] = iri['Viaje Regular']

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup,Viaje Totales
0,01/04/2026,ALIMENTACION,AD0474012,1,1,12,105,10474,12551,514,...,None,None,None,None,None,None,0,0,0,1
1,01/04/2026,ALIMENTACION,AD0474012,2,2,12,105,10474,12551,514,...,None,None,None,None,None,None,0,0,0,1
2,01/04/2026,ALIMENTACION,AD0474012,3,3,12,105,10474,12551,514,...,None,None,None,None,None,None,0,0,0,1
3,01/04/2026,ALIMENTACION,AD0474012,4,4,12,105,10474,12551,514,...,None,None,None,None,None,None,0,0,0,1
4,01/04/2026,ALIMENTACION,AD0474012,5,5,12,105,10474,12551,514,...,None,None,None,None,None,None,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109772,30/04/2026,ALIMENTACION,CO11B0012,20,19,6,105,10527,12440,230,...,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS,52521464,0,1023870284,1
109773,30/04/2026,ALIMENTACION,CO11B0012,21,20,6,105,10527,12440,230,...,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS,52521464,0,1023870284,1
109774,30/04/2026,ALIMENTACION,CO11B0012,22,21,6,105,10527,12440,230,...,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS,52521464,0,1023870284,1
109775,30/04/2026,ALIMENTACION,CO11B0012,23,22,6,105,10527,12440,230,...,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS,52521464,0,1023870284,1
109776,30/04/2026,ALIMENTACION,CO11B0012,25,24,6,105,10527,12440,230,...,PLAD,None,SUP AM,YNGRI YAMILY CASTILLO CRUZ,None,CAMILO ANDRES LOPEZ PENAGOS,52521464,0,1023870284,1

In [31]:
#Realizar tres copias para los datos del personal

iri_1 = iri.copy()
iri_2 = iri.copy()
iri_3 = iri.copy()

In [32]:
#Kilometros por regulador de control

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_1 = iri_1.groupby(['Fecha Viaje', 'reg_ccz']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

iri_1

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34
...,...,...,...,...
131,29/04/2026,ROSA MARIELA TELLEZ NAVARRO,98,131
132,30/04/2026,ESTEBAN CAMILO MEDINA,271,320
133,30/04/2026,JOHN JAIRO ESPINOSA SANTA,144,168
134,30/04/2026,NORBERTO NIÑO RODRIGUEZ,124,158
135,30/04/2026,ROSA MARIELA TELLEZ NAVARRO,113,134

In [33]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_2 = iri_2.groupby(['Fecha Viaje', 'reg_via']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

iri_2

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/04/2026,ADRIANA YANETH RAMIREZ GALVAN,38,48
1,01/04/2026,ALEXANDRA MARTINEZ TAPIA,35,36
2,01/04/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,115,136
3,01/04/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,184,236
4,01/04/2026,ANETH MAYERLI CHONTAL VILLARRAGA,97,117
...,...,...,...,...
674,30/04/2026,MAYERLI AVILA GOMEZ,39,58
675,30/04/2026,NINI JOHANNA MARTINEZ,17,20
676,30/04/2026,OSCAR EDUARDO DUARTE BAQUERO,53,79
677,30/04/2026,PABLO EMILIO GUERRERO LLANOS,32,45
678,30/04/2026,YNGRI YAMILY CASTILLO CRUZ,318,398

In [34]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_3 = iri_3.groupby(['Fecha Viaje', 'Supervisor']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_3.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

iri_3

   Fecha Viaje                         reg_ccz  Viaje Regular  Viaje Totales
0   01/04/2026        DIEGO ARTURO URIBE ROJAS           2356           2757
1   01/04/2026  LISETH GERALDINE GARCIA GARZÓN            888           1037
2   02/04/2026  LISETH GERALDINE GARCIA GARZÓN           2201           2416
3   03/04/2026  LISETH GERALDINE GARCIA GARZÓN           2231           2440
4   04/04/2026        DIEGO ARTURO URIBE ROJAS           2410           2639
5   05/04/2026        DIEGO ARTURO URIBE ROJAS           2200           2430
6   06/04/2026        DIEGO ARTURO URIBE ROJAS            818           1025
7   06/04/2026  LISETH GERALDINE GARCIA GARZÓN           2346           2772
8   07/04/2026        DIEGO ARTURO URIBE ROJAS            771            994
9   07/04/2026  LISETH GERALDINE GARCIA GARZÓN           2206           2729
10  08/04/2026        DIEGO ARTURO URIBE ROJAS            758            986
11  08/04/2026  LISETH GERALDINE GARCIA GARZÓN           2164           2715
12  09/04/2026        DIEGO ARTURO URIBE ROJAS            798           1023
13  09/04/2026  LISETH GERALDINE GARCIA GARZÓN           2243           2721
14  10/04/2026        DIEGO ARTURO URIBE ROJAS           2164           2704
15  10/04/2026  LISETH GERALDINE GARCIA GARZÓN            654            932
16  11/04/2026  LISETH GERALDINE GARCIA GARZÓN           2192           2588
17  12/04/2026  LISETH GERALDINE GARCIA GARZÓN           2059           2345
18  13/04/2026        DIEGO ARTURO URIBE ROJAS           2265           2736
19  13/04/2026  LISETH GERALDINE GARCIA GARZÓN            698            960
20  14/04/2026        DIEGO ARTURO URIBE ROJAS           2116           2637
21  14/04/2026  LISETH GERALDINE GARCIA GARZÓN            739            992
22  15/04/2026        DIEGO ARTURO URIBE ROJAS           1809           2426
23  15/04/2026  LISETH GERALDINE GARCIA GARZÓN            748            983
24  16/04/2026        DIEGO ARTURO URIBE ROJAS           2071           2618
25  16/04/2026  LISETH GERALDINE GARCIA GARZÓN            724            979
26  17/04/2026        DIEGO ARTURO URIBE ROJAS           1721           2449
27  18/04/2026        DIEGO ARTURO URIBE ROJAS           2027           2500
28  19/04/2026  LISETH GERALDINE GARCIA GARZÓN           2038           2338
29  20/04/2026     CAMILO ANDRES LOPEZ PENAGOS           2214           2699
30  20/04/2026        DIEGO ARTURO URIBE ROJAS            765           1003
31  21/04/2026     CAMILO ANDRES LOPEZ PENAGOS           2106           2618
32  21/04/2026        DIEGO ARTURO URIBE ROJAS            786            997
33  22/04/2026     CAMILO ANDRES LOPEZ PENAGOS           2192           2690
34  22/04/2026        DIEGO ARTURO URIBE ROJAS            777           1020
35  23/04/2026     CAMILO ANDRES LOPEZ PENAGOS           2144           2722
36  23/04/2026        DIEGO ARTURO URIBE ROJAS            836           1029
37  24/04/2026     CAMILO ANDRES LOPEZ PENAGOS           1967           2612
38  24/04/2026        DIEGO ARTURO URIBE ROJAS            608            909
39  25/04/2026        DIEGO ARTURO URIBE ROJAS           1974           2468
40  26/04/2026     CAMILO ANDRES LOPEZ PENAGOS           1923           2241
41  27/04/2026     CAMILO ANDRES LOPEZ PENAGOS            778           1002
42  27/04/2026        DIEGO ARTURO URIBE ROJAS           2150           2709
43  28/04/2026     CAMILO ANDRES LOPEZ PENAGOS            709            976
44  28/04/2026        DIEGO ARTURO URIBE ROJAS           2033           2631
45  29/04/2026     CAMILO ANDRES LOPEZ PENAGOS            653            923
46  29/04/2026        DIEGO ARTURO URIBE ROJAS           1893           2500
47  30/04/2026     CAMILO ANDRES LOPEZ PENAGOS           2110           2641
48  30/04/2026        DIEGO ARTURO URIBE ROJAS            605            893

In [35]:
#Consolidar los dos dataframe para validar fonias

regularidad = pd.concat([iri_1,iri_2, iri_3], ignore_index=True)

# Realizar la división y convertir a porcentaje
regularidad['IRI (%)'] = (regularidad['Viaje Regular'] / regularidad['Viaje Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
regularidad['Regularidad (%)'] = regularidad['IRI (%)'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
regularidad.rename(columns={'Fecha Viaje': 'Fecha'}, inplace=True)

regularidad

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88
...,...,...,...,...,...,...
859,28/04/2026,DIEGO ARTURO URIBE ROJAS,2033,2631,77.271000,77
860,29/04/2026,CAMILO ANDRES LOPEZ PENAGOS,653,923,70.747562,71
861,29/04/2026,DIEGO ARTURO URIBE ROJAS,1893,2500,75.720000,76
862,30/04/2026,CAMILO ANDRES LOPEZ PENAGOS,2110,2641,79.893980,80
863,30/04/2026,DIEGO ARTURO URIBE ROJAS,605,893,67.749160,68

Kilometros personal de control (SAE _ FMS)

In [36]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [37]:
#FMS

# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia
desglosados_fms['Fecha'] = pd.to_datetime(desglosados_fms['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
desglosados_fms['Fecha'] = desglosados_fms['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,0,36341,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,0,36466,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,0,36311,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,0,36478,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,0,36331,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00

In [38]:
#Llevar tipo día a desglosados FMS

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Tipo dia'] = desglosados_fms.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,36341,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00,Hábil
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,36466,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99,Hábil
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,36311,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00,Hábil
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,36478,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99,Hábil
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,36331,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00,Hábil

In [39]:
# Función para obtener la letra inicial de cada palabra FMS
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
desglosados_fms['Tipo_dia'] = desglosados_fms['Tipo dia'].apply(obtener_letra_inicial)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00,Hábil,H
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99,Hábil,H
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00,Hábil,H
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99,Hábil,H
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00,Hábil,H

In [40]:
#Tipo de dato a entero FMS

desglosados_fms['Id Línea '] = desglosados_fms['Id Línea '].astype(int)
desglosados_fms['Ruta '] = desglosados_fms['Ruta '].astype(int)
desglosados_fms['KmEjecutado'] = desglosados_fms['KmEjecutado'].astype(int)
desglosados_fms['KmProgAd'] = desglosados_fms['KmProgAd'].astype(int)
desglosados_fms['KmElimado'] = desglosados_fms['KmElimado'].astype(int)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00,Hábil,H
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99,Hábil,H
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00,Hábil,H
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99,Hábil,H
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00,Hábil,H

In [41]:
# Filtrar todo lo que no sea vacío ni NaN
desglosados_fms = desglosados_fms[
    desglosados_fms['Hora Ini Teorica '].notna() & 
    (desglosados_fms['Hora Ini Teorica '].astype(str).str.strip() != "")
]

desglosados_fms

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,Si,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00,Hábil,H
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,No,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99,Hábil,H
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,No,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00,Hábil,H
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,No,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99,Hábil,H
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,No,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00,Hábil,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111822,30/04/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260430-CO11B0012-20-12440,CO11B0012,20,21,20,10527,...,No,NaN,NaN,NaN,"1, 7",CDZ4,100.00,1.00,Hábil,H
111823,30/04/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260430-CO11B0012-21-12440,CO11B0012,21,22,21,10527,...,No,NaN,NaN,NaN,"1, 7",CDZ4,100.00,1.00,Hábil,H
111824,30/04/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260430-CO11B0012-22-12440,CO11B0012,22,23,22,10527,...,No,NaN,NaN,NaN,"1, 8",CDZ4,100.00,1.00,Hábil,H
111825,30/04/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260430-CO11B0012-23-12440,CO11B0012,23,24,23,10527,...,No,NaN,NaN,NaN,"1, 8",CDZ4,99.30,0.99,Hábil,H
111826,30/04/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260430-CO11B0012-24-12440,CO11B0012,24,25,24,10527,...,No,NaN,NaN,NaN,"1, 8",CDZ4,100.00,1.00,Hábil,H

In [42]:
# Extraer la hora y convertirla a entero FMS
desglosados_fms['Hora'] = desglosados_fms['Hora Ini Teorica '].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
desglosados_fms['Hora'] = desglosados_fms['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,NaN,NaN,NaN,"1, 1",CDZ4,100.00,1.00,Hábil,H,4
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,NaN,NaN,NaN,"1, 3",CDZ4,98.80,0.99,Hábil,H,5
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,NaN,NaN,NaN,"1, 4",CDZ4,99.92,1.00,Hábil,H,8
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,NaN,NaN,NaN,"1, 5",CDZ4,98.83,0.99,Hábil,H,11
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,NaN,NaN,NaN,"1, 5",CDZ4,99.97,1.00,Hábil,H,13

In [43]:
#Traer el turno de control FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,NaN,NaN,"1, 1",CDZ4,100.00,1.00,Hábil,H,4,ET6N
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,NaN,NaN,"1, 3",CDZ4,98.80,0.99,Hábil,H,5,ET6N
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,NaN,NaN,"1, 4",CDZ4,99.92,1.00,Hábil,H,8,ET8M
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,NaN,NaN,"1, 5",CDZ4,98.83,0.99,Hábil,H,11,ET8M
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,NaN,NaN,"1, 5",CDZ4,99.97,1.00,Hábil,H,13,ET8M

In [44]:
#Traer el turno de vía FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,NaN,"1, 1",CDZ4,100.00,1.00,Hábil,H,4,ET6N,None
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,NaN,"1, 3",CDZ4,98.80,0.99,Hábil,H,5,ET6N,EG9
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,NaN,"1, 4",CDZ4,99.92,1.00,Hábil,H,8,ET8M,EG9
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,NaN,"1, 5",CDZ4,98.83,0.99,Hábil,H,11,ET8M,EG9
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,NaN,"1, 5",CDZ4,99.97,1.00,Hábil,H,13,ET8M,EG9

In [45]:
#Traer el turno de supervisor FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_sup'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,"1, 1",CDZ4,100.00,1.00,Hábil,H,4,ET6N,None,SUP AM
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,"1, 3",CDZ4,98.80,0.99,Hábil,H,5,ET6N,EG9,SUP AM
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,"1, 4",CDZ4,99.92,1.00,Hábil,H,8,ET8M,EG9,SUP AM
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,"1, 5",CDZ4,98.83,0.99,Hábil,H,11,ET8M,EG9,SUP AM
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,"1, 5",CDZ4,99.97,1.00,Hábil,H,13,ET8M,EG9,SUP AM

In [46]:
#Traer el regulador de control según el turno FMS

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_ccz']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_via']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['supervisor'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,1.00,Hábil,H,4,ET6N,None,SUP AM,RAUL FABIAN ROMERO MICAN,None,DIEGO ARTURO URIBE ROJAS
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,0.99,Hábil,H,5,ET6N,EG9,SUP AM,RAUL FABIAN ROMERO MICAN,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,1.00,Hábil,H,8,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,0.99,Hábil,H,11,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,1.00,Hábil,H,13,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS

In [47]:
# Crear una nueva columna con la suma de las columnas kiloemtros planificados y adicionales FMS
desglosados_fms['Kilómetros Totales'] = desglosados_fms['KmProgAd']

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,Kilómetros Totales
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,Hábil,H,4,ET6N,None,SUP AM,RAUL FABIAN ROMERO MICAN,None,DIEGO ARTURO URIBE ROJAS,36341
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,Hábil,H,5,ET6N,EG9,SUP AM,RAUL FABIAN ROMERO MICAN,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36909
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,Hábil,H,8,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36341
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,Hábil,H,11,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36909
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,Hábil,H,13,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36341

In [48]:
# Realizar la división y convertir a porcentaje FMS
desglosados_fms['Kilómetros (%)'] = (desglosados_fms['KmEjecutado'] / desglosados_fms['Kilómetros Totales']) * 100

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,Kilómetros Totales,Kilómetros (%)
0,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-1-12739,BC29D0002,1,2,1,10350,...,H,4,ET6N,None,SUP AM,RAUL FABIAN ROMERO MICAN,None,DIEGO ARTURO URIBE ROJAS,36341,100.000000
1,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-2-12738,BC29D0002,2,3,2,10350,...,H,5,ET6N,EG9,SUP AM,RAUL FABIAN ROMERO MICAN,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36909,98.799751
2,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-3-12739,BC29D0002,3,4,3,10350,...,H,8,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36341,99.917449
3,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-4-12738,BC29D0002,4,5,4,10350,...,H,11,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36909,98.832263
4,01/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260401-BC29D0002-5-12739,BC29D0002,5,6,5,10350,...,H,13,ET8M,EG9,SUP AM,None,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,36341,99.972483

In [49]:
#Copias de los dataframes FMS

desglosados_fms1 = desglosados_fms.copy()
desglosados_fms2 = desglosados_fms.copy()
desglosados_fms3 = desglosados_fms.copy()

In [50]:
#Kilometros por regulador de control FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms1 = desglosados_fms1.groupby(['Fecha', 'reg_ccz']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

desglosados_fms1.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/04/2026,DORIS EDITH PATARROYO GORDO,6834896,6630030
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,5431621,5210289
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,3553225,3488279
3,01/04/2026,RAUL FABIAN ROMERO MICAN,8402578,7979146
4,02/04/2026,DORIS EDITH PATARROYO GORDO,1216946,1203317

In [51]:
#Kilometros por regulador de via FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms2 = desglosados_fms2.groupby(['Fecha', 'reg_via']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

desglosados_fms2.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/04/2026,ADRIANA YANETH RAMIREZ GALVAN,2451072,2425651
1,01/04/2026,ALEXANDRA MARTINEZ TAPIA,1463832,1418069
2,01/04/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,3729739,3613434
3,01/04/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,7912481,7508613
4,01/04/2026,ANETH MAYERLI CHONTAL VILLARRAGA,4580760,4525698

In [52]:
#Kilometros por supervisor FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms3 = desglosados_fms3.groupby(['Fecha', 'supervisor']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms3.rename(columns={'supervisor': 'reg_ccz'}, inplace=True)

desglosados_fms3.head()

        Fecha                         reg_ccz  Kilómetros Totales  KmEjecutado
0  01/04/2026        DIEGO ARTURO URIBE ROJAS            70419602     67698827
1  01/04/2026  LISETH GERALDINE GARCIA GARZÓN            34385757     32306190
2  02/04/2026  LISETH GERALDINE GARCIA GARZÓN            63623119     60949543
3  03/04/2026  LISETH GERALDINE GARCIA GARZÓN            63558009     61920081
4  04/04/2026        DIEGO ARTURO URIBE ROJAS            67229838     65120975

In [53]:
#Consolidar los dos dataframe para validar KM FMS

kilometros_fms = pd.concat([desglosados_fms1,desglosados_fms2, desglosados_fms3], ignore_index=True)

# Realizar la división y convertir a porcentaje
kilometros_fms['Kilómetros (%)'] = (kilometros_fms['KmEjecutado'] / kilometros_fms['Kilómetros Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
kilometros_fms['Kilómetros (%)'] = kilometros_fms['Kilómetros (%)'].round(0).astype(int)

kilometros_fms.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/04/2026,DORIS EDITH PATARROYO GORDO,6834896,6630030,97
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,5431621,5210289,96
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,3553225,3488279,98
3,01/04/2026,RAUL FABIAN ROMERO MICAN,8402578,7979146,95
4,02/04/2026,DORIS EDITH PATARROYO GORDO,1216946,1203317,99

In [54]:
# Consolidar todos los DataFrames en uno solo

kilometros = pd.concat([kilometros_fms], ignore_index=True)

kilometros

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/04/2026,DORIS EDITH PATARROYO GORDO,6834896,6630030,97
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,5431621,5210289,96
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,3553225,3488279,98
3,01/04/2026,RAUL FABIAN ROMERO MICAN,8402578,7979146,95
4,02/04/2026,DORIS EDITH PATARROYO GORDO,1216946,1203317,99
...,...,...,...,...,...
859,28/04/2026,DIEGO ARTURO URIBE ROJAS,76626735,62886227,82
860,29/04/2026,CAMILO ANDRES LOPEZ PENAGOS,36790654,28329985,77
861,29/04/2026,DIEGO ARTURO URIBE ROJAS,76626735,58127562,76
862,30/04/2026,CAMILO ANDRES LOPEZ PENAGOS,76626735,62548700,82
863,30/04/2026,DIEGO ARTURO URIBE ROJAS,36790654,26525371,72

Indicadores de fonias de personal de control

In [55]:
#Traer el supervisor según el turno

def calcular_turno(nombre):
    
    filtro = (
        (base['RegC'] == nombre)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base.loc[filtro, 'RegControl'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['reg_ccz'] = fonias.apply(
    lambda row: calcular_turno(
        row['Nombre Usuario']
    ),
    axis=1
)

fonias

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,0,NaN,NaN,0,03:16:00,03:18:00,03:18:00,00:02:00,00:00:00,None
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,0,NaN,0.5,0,03:20:00,03:22:00,03:23:00,00:02:00,00:00:15,None
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,0,NaN,0.5,0,03:28:00,03:29:00,03:30:00,00:01:00,00:00:57,None
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,0,NaN,NaN,0,03:55:00,03:55:00,03:56:00,00:00:00,00:00:16,None
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,0,NaN,NaN,0,03:58:00,03:58:00,03:58:00,00:00:00,00:00:47,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78656,27/04/2026,70205,10474.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-2 Engativa Centro,19,CE0A40001,0.5,0,20:17:00,20:18:00,20:18:00,00:01:00,00:00:17,None
78657,27/04/2026,70220,10527.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,1-9 Villas del Dorado,0,NaN,0.5,0,20:45:00,20:45:00,20:46:00,00:00:00,00:01:17,None
78658,27/04/2026,70220,10527.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,1-9 Villas del Dorado,0,NaN,0.5,0,20:55:00,20:56:00,20:57:00,00:01:00,00:01:12,None
78659,27/04/2026,70222,10478.0,No,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-3 Av. Eldorado Alamos,21,CE0A40036,NaN,0,21:31:00,21:31:00,21:31:00,00:00:00,00:00:30,None
78660,27/04/2026,70211,10495.0,No,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-14 Aeropuerto,23,CE0A40023,NaN,0,22:20:00,22:20:00,22:20:00,00:00:00,00:00:03,None

In [56]:
# Reemplazar valores vacíos y '(en blanco)' con '00:00:00' en las columnas 'TRM' y 'Duración'
fonias['TMR'] = fonias['TMR'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['Duración'] = fonias['Duración'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['No Asignado'] = fonias['No Asignado'].replace({'': 0, '(en blanco)': 0})

fonias

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,0,NaN,NaN,0,03:16:00,03:18:00,03:18:00,00:02:00,00:00:00,None
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,0,NaN,0.5,0,03:20:00,03:22:00,03:23:00,00:02:00,00:00:15,None
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,0,NaN,0.5,0,03:28:00,03:29:00,03:30:00,00:01:00,00:00:57,None
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,0,NaN,NaN,0,03:55:00,03:55:00,03:56:00,00:00:00,00:00:16,None
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,0,NaN,NaN,0,03:58:00,03:58:00,03:58:00,00:00:00,00:00:47,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78656,27/04/2026,70205,10474.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-2 Engativa Centro,19,CE0A40001,0.5,0,20:17:00,20:18:00,20:18:00,00:01:00,00:00:17,None
78657,27/04/2026,70220,10527.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,1-9 Villas del Dorado,0,NaN,0.5,0,20:45:00,20:45:00,20:46:00,00:00:00,00:01:17,None
78658,27/04/2026,70220,10527.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,1-9 Villas del Dorado,0,NaN,0.5,0,20:55:00,20:56:00,20:57:00,00:01:00,00:01:12,None
78659,27/04/2026,70222,10478.0,No,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-3 Av. Eldorado Alamos,21,CE0A40036,NaN,0,21:31:00,21:31:00,21:31:00,00:00:00,00:00:30,None
78660,27/04/2026,70211,10495.0,No,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-14 Aeropuerto,23,CE0A40023,NaN,0,22:20:00,22:20:00,22:20:00,00:00:00,00:00:03,None

In [57]:
# Asegúrate de que todas las entradas sean cadenas de texto
fonias['TMR'] = fonias['TMR'].astype(str)
fonias['Duración'] = fonias['Duración'].astype(str)

# Convertir las columnas 'TRM' y 'Duración' a formato timedelta
fonias['TMR'] = pd.to_timedelta(fonias['TMR'], errors='coerce')
fonias['Duración'] = pd.to_timedelta(fonias['Duración'], errors='coerce')

# Convertir los tiempos a segundos
fonias['TMR_segundos'] = fonias['TMR'].dt.total_seconds()
fonias['Duración_segundos'] = fonias['Duración'].dt.total_seconds()

# Reemplazar los valores NaN con 0
fonias['TMR_segundos'].fillna(0, inplace=True)
fonias['Duración_segundos'].fillna(0, inplace=True)

# Pasar a enteros
fonias['TMR_segundos'] = fonias['TMR_segundos'].astype(int)
fonias['Duración_segundos'] = fonias['Duración_segundos'].astype(int)

# Mostrar el DataFrame resultante
fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\479846426.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\479846426.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['Duración_segundos'].fillna(0, inplace=True)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,NaN,0,03:16:00,03:18:00,0 days 03:18:00,0 days 00:02:00,00:00:00,None,11880,120
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,0.5,0,03:20:00,03:22:00,0 days 03:23:00,0 days 00:02:00,00:00:15,None,12180,120
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,0.5,0,03:28:00,03:29:00,0 days 03:30:00,0 days 00:01:00,00:00:57,None,12600,60
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,NaN,0,03:55:00,03:55:00,0 days 03:56:00,0 days 00:00:00,00:00:16,None,14160,0
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,NaN,0,03:58:00,03:58:00,0 days 03:58:00,0 days 00:00:00,00:00:47,None,14280,0

In [58]:
#Llevar tipo día a fonias

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Tipo dia'] = fonias.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,0,03:16:00,03:18:00,0 days 03:18:00,0 days 00:02:00,00:00:00,None,11880,120,Hábil
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,0,03:20:00,03:22:00,0 days 03:23:00,0 days 00:02:00,00:00:15,None,12180,120,Hábil
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,0,03:28:00,03:29:00,0 days 03:30:00,0 days 00:01:00,00:00:57,None,12600,60,Hábil
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0,03:55:00,03:55:00,0 days 03:56:00,0 days 00:00:00,00:00:16,None,14160,0,Hábil
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0,03:58:00,03:58:00,0 days 03:58:00,0 days 00:00:00,00:00:47,None,14280,0,Hábil

In [59]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
fonias['Tipo_dia'] = fonias['Tipo dia'].apply(obtener_letra_inicial)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,03:16:00,03:18:00,0 days 03:18:00,0 days 00:02:00,00:00:00,None,11880,120,Hábil,H
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,03:20:00,03:22:00,0 days 03:23:00,0 days 00:02:00,00:00:15,None,12180,120,Hábil,H
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,03:28:00,03:29:00,0 days 03:30:00,0 days 00:01:00,00:00:57,None,12600,60,Hábil,H
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,03:55:00,03:55:00,0 days 03:56:00,0 days 00:00:00,00:00:16,None,14160,0,Hábil,H
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,03:58:00,03:58:00,0 days 03:58:00,0 days 00:00:00,00:00:47,None,14280,0,Hábil,H

In [60]:
# Extraer la hora y convertirla a entero

# las entradas sean cadenas de texto
fonias['Hora Petición'] = fonias['Hora Petición'].astype(str)

# Extraer la hora y convertirla a entero
fonias['Hora'] = fonias['Hora Petición'].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
fonias['Hora'] = fonias['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,03:18:00,0 days 03:18:00,0 days 00:02:00,00:00:00,None,11880,120,Hábil,H,0
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,03:22:00,0 days 03:23:00,0 days 00:02:00,00:00:15,None,12180,120,Hábil,H,0
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,03:29:00,0 days 03:30:00,0 days 00:01:00,00:00:57,None,12600,60,Hábil,H,0
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,03:55:00,0 days 03:56:00,0 days 00:00:00,00:00:16,None,14160,0,Hábil,H,0
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,03:58:00,0 days 03:58:00,0 days 00:00:00,00:00:47,None,14280,0,Hábil,H,0

In [61]:
#Traer el turno de supervisor

def calcular_turno(Franja,Tipo_Dia):
    
    filtro = (
        
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Turno_sup'] = fonias.apply(
    lambda row: calcular_turno(
        
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,0 days 03:18:00,0 days 00:02:00,00:00:00,None,11880,120,Hábil,H,0,None
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,0 days 03:23:00,0 days 00:02:00,00:00:15,None,12180,120,Hábil,H,0,None
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,0 days 03:30:00,0 days 00:01:00,00:00:57,None,12600,60,Hábil,H,0,None
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 03:56:00,0 days 00:00:00,00:00:16,None,14160,0,Hábil,H,0,None
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 03:58:00,0 days 00:00:00,00:00:47,None,14280,0,Hábil,H,0,None

In [62]:
#Traer el supervisor según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Supervisor'] = fonias.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,0 days 00:02:00,00:00:00,None,11880,120,Hábil,H,0,None,None
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,0 days 00:02:00,00:00:15,None,12180,120,Hábil,H,0,None,None
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,0 days 00:01:00,00:00:57,None,12600,60,Hábil,H,0,None,None
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 00:00:00,00:00:16,None,14160,0,Hábil,H,0,None,None
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 00:00:00,00:00:47,None,14280,0,Hábil,H,0,None,None

In [63]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_ser = fonias.copy()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)

fonias_ser['Duración_segundos'].fillna(0, inplace=True)

fonias_ser

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\48388375.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\48388375.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,0 days 00:02:00,00:00:00,None,11880,120,Hábil,H,0,None,None
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,0 days 00:02:00,00:00:15,None,12180,120,Hábil,H,0,None,None
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,0 days 00:01:00,00:00:57,None,12600,60,Hábil,H,0,None,None
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 00:00:00,00:00:16,None,14160,0,Hábil,H,0,None,None
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 00:00:00,00:00:47,None,14280,0,Hábil,H,0,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78656,27/04/2026,70205,10474.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-2 Engativa Centro,...,0 days 00:01:00,00:00:17,None,73080,60,Hábil,H,0,None,None
78657,27/04/2026,70220,10527.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,1-9 Villas del Dorado,...,0 days 00:00:00,00:01:17,None,74760,0,Hábil,H,0,None,None
78658,27/04/2026,70220,10527.0,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,1-9 Villas del Dorado,...,0 days 00:01:00,00:01:12,None,75420,60,Hábil,H,0,None,None
78659,27/04/2026,70222,10478.0,No,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-3 Av. Eldorado Alamos,...,0 days 00:00:00,00:00:30,None,77460,0,Hábil,H,0,None,None
78660,27/04/2026,70211,10495.0,No,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,16-14 Aeropuerto,...,0 days 00:00:00,00:00:03,None,80400,0,Hábil,H,0,None,None

In [64]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_ser = fonias_ser.groupby(['Fecha', 'reg_ccz']).agg({
    'TMR_segundos':  mean_without_zeros,
    'Duración_segundos':  mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)
fonias_ser['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_ser['TMR_segundos'] = fonias_ser['TMR_segundos'].round(0).astype(int)
fonias_ser['Duración_segundos'] = fonias_ser['Duración_segundos'].round(0).astype(int)

fonias_ser.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\3888450677.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\3888450677.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

Empty DataFrame
Columns: [Fecha, reg_ccz, TMR_segundos, Duración_segundos, No Asignado]
Index: []

In [65]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_1 = fonias.copy()

fonias_1.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
56235,01/04/2026,504516,10184.0,Si,Emergencia,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Solicitud cerrada por nueva de igual o mayor j...,740,...,0 days 00:02:00,00:00:00,None,11880,120,Hábil,H,0,None,None
56236,01/04/2026,504463,10310.0,Si,Prioritaria,0,DPATARROYO_105,DORIS PATARROYO EDITH GORDO,Llamada terminada por el tÃ©cnico de control,C101,...,0 days 00:02:00,00:00:15,None,12180,120,Hábil,H,0,None,None
56237,01/04/2026,504148,10690.0,Si,Llamada normal,0,JDURAN_105,JIMMY ALEXANDER CARABALLO DIAZ,Llamada terminada por el tÃ©cnico de control,DL219,...,0 days 00:01:00,00:00:57,None,12600,60,Hábil,H,0,None,None
56238,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 00:00:00,00:00:16,None,14160,0,Hábil,H,0,None,None
56239,01/04/2026,504000,10266.0,No,Llamada normal,0,RROMERO_105,Raul Fabian Romero Mican,Llamada terminada por el tÃ©cnico de control,DD204,...,0 days 00:00:00,00:00:47,None,14280,0,Hábil,H,0,None,None

In [66]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_1 = fonias_1.groupby(['Fecha', 'Supervisor']).agg({
    'TMR_segundos': mean_without_zeros,
    'Duración_segundos': mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_1['TMR_segundos'].fillna(0, inplace=True)
fonias_1['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_1['TMR_segundos'] = fonias_1['TMR_segundos'].round(0).astype(int)
fonias_1['Duración_segundos'] = fonias_1['Duración_segundos'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
fonias_1.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

fonias_1.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\3334358817.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\3334358817.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['Duración_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,03/04/2026,LISETH GERALDINE GARCIA GARZÓN,64920,60,0.5
1,13/04/2026,DIEGO ARTURO URIBE ROJAS,71460,0,0.5
2,20/04/2026,CAMILO ANDRES LOPEZ PENAGOS,66120,0,0.5
3,22/04/2026,CAMILO ANDRES LOPEZ PENAGOS,49380,60,0.5

In [67]:
#Consolidar los dos dataframe para validar fonias

fonias_fin = pd.concat([fonias_ser, fonias_1], ignore_index=True)

fonias_fin

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,03/04/2026,LISETH GERALDINE GARCIA GARZÓN,64920,60,0.5
1,13/04/2026,DIEGO ARTURO URIBE ROJAS,71460,0,0.5
2,20/04/2026,CAMILO ANDRES LOPEZ PENAGOS,66120,0,0.5
3,22/04/2026,CAMILO ANDRES LOPEZ PENAGOS,49380,60,0.5

Información de novedades

In [68]:
# Rellena los valores NaN en la columna
novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

# Convertir 'Nodo' a tipo entero
novedades['CODIGO OPERADOR'] = novedades['CODIGO OPERADOR'].astype(int)

novedades.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\2588241090.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1057523,15/04/2026,15/04/2026,1,Ausentismo,PERMISO,Patio Dorado,0,1024489560,YERLI IRENE HERNANDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-09 08:42:09 PERMISO - PROCEDIMIENTO OD...,Por Aprobar,NaN
1,1058351,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501161,79453992,ALEXANDER GARAVITO HERNANDEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1058352,15/04/2026,15/04/2026,1,Cambio de Turno Operativo,NaN,Patio Dorado,501374,91538451,JESUS FLOREZ ALARCON,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
3,1058353,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501522,79904374,JOHN HENRY LEON QUIROGA,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
4,1058354,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,502645,79842026,MANUEL PISCO RODRIGUEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [69]:
# Filtrar el DataFrame para obtener solo las filas donde 'CODIGO OPERADOR' sea diferente de 0
novedades = novedades[novedades['CODIGO OPERADOR'] == 0]

# Filtrar el DataFrame para eliminar las filas donde 'estado' es igual a 'Eliminada'
novedades = novedades[novedades['ESTADO'] != 'Eliminada']

novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1057523,15/04/2026,15/04/2026,1,Ausentismo,PERMISO,Patio Dorado,0,1024489560,YERLI IRENE HERNANDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-09 08:42:09 PERMISO - PROCEDIMIENTO OD...,Por Aprobar,NaN
22,1058975,14/04/2026,14/04/2026,1,Retroalimentación,NaN,Patio Dorado,0,1069714687,ROBINSON ESTIBEN LOPEZ CARDENAS,RECOMOTO,LEIDY JAZMIN SALINAS VARGAS,0,NaN,NaN,2026-04-14 09:30:00 EL REMOTO ROBINSON ESTIBEN...,Por Aprobar,NaN
52,1059007,13/04/2026,13/04/2026,1,Retroalimentación,NaN,Patio Dorado,0,53154005,ANGELA MIREYA RIAÑO PASITO,REGULADOR EN CENTRO DE CONTROL,DIEGO ARTURO URIBE ROJAS,0,NaN,NaN,2026-04-14 11:36:44 Se realiza retroalimentaci...,Aprobada,DIEGO ARTURO URIBE ROJAS
53,1059017,13/04/2026,15/04/2026,3,Ausentismo,NO JUSTIFICADO,Patio Dorado,0,52980742,DORIS EDITH PATARROYO GORDO,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,-150,NaN,NaN,"2026-04-14 12:11:34 Se reporta tp34., /.../",Por Aprobar,NaN
54,1059033,13/04/2026,13/04/2026,1,Ausentismo,PERMISO,Patio Dorado,0,52737325,DIANA MARCELA AGUILERA MADRIGAL,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-14 13:54:08 PERMISO - Asiste al funera...,Por Aprobar,NaN

In [70]:
#resumen por fecha y regulador según las novedades

# Crear columnas para cada tipo de novedad
novedades['Ausentismo'] = (novedades['TIPO NOVEDAD'] == 'Ausentismo').astype(int)
novedades['Retardo'] = (novedades['TIPO NOVEDAD'] == 'Retardo').astype(int)
novedades['Novedades'] = ~novedades['TIPO NOVEDAD'].isin(['Ausentismo', 'Retardo'])

# Agrupar por 'FECHA INICIAL' y 'REGULADOR', y contar las ocurrencias de cada tipo de novedad
novedades_fin = novedades.groupby(['FECHA INICIAL', 'EMPLEADO']).agg({
    'Ausentismo': 'sum',
    'Retardo': 'sum',
    'Novedades': 'sum'
}).reset_index()

# Renombrar la columna 'Supervisor' a 'reg_ccz'
novedades_fin.rename(columns={'FECHA INICIAL': 'Fecha'}, inplace=True)
novedades_fin.rename(columns={'EMPLEADO': 'reg_ccz'}, inplace=True)

# Mostrar el DataFrame resultante
novedades_fin.head()

        Fecha                         reg_ccz  Ausentismo  Retardo  Novedades
0  01/04/2026  ANDRES GABRIEL SANABRIA ACHURY           1        1          0
1  01/04/2026   EDICSON YAIR VELANDIA PEÑUELA           1        0          0
2  01/04/2026  MARTHA DOLORES DURAN GUTIERREZ           1        0          0
3  01/04/2026     YERLI IRENE HERNANDEZ ARIZA           0        0          1
4  01/04/2026          YORLEY VALLEJO AGUILAR           1        0          0

Consolidar la data para validar la información

In [71]:
#copiar data de regularidad

indicadores = regularidad.copy()

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88

In [72]:
#llevar KMS a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (kilometros['Fecha'] == Fecha)&
        (kilometros['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not kilometros.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = kilometros.loc[filtro, 'Kilómetros (%)'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Kilómetros (%)'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%)
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71,97
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86,96
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90,98
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84,95
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88,99

In [73]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'TMR_segundos'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['TMR_segundos'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['TMR_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
indicadores['TMR_segundos'] = indicadores['TMR_segundos'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\679954610.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['TMR_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71,97,0
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86,96,0
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90,98,0
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84,95,0
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88,99,0

In [74]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'No Asignado'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['No Asignado'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['No Asignado'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['No Asignado'] = indicadores['No Asignado'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\3884926540.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['No Asignado'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71,97,0,0
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86,96,0,0
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90,98,0,0
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84,95,0,0
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88,99,0,0

In [75]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Ausentismo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Ausentismo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Ausentismo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Ausentismo'] = indicadores['Ausentismo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\2427483280.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Ausentismo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71,97,0,0,0
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86,96,0,0,0
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90,98,0,0,0
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84,95,0,0,0
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88,99,0,0,0

In [76]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Novedades'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Novedades'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Novedades'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Novedades'] = indicadores['Novedades'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\590017984.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Novedades'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71,97,0,0,0,0
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86,96,0,0,0,0
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90,98,0,0,0,0
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84,95,0,0,0,0
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88,99,0,0,0,0

In [77]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Retardo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Retardo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Retardo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Retardo'] = indicadores['Retardo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_20508\3046602996.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Retardo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/04/2026,DORIS EDITH PATARROYO GORDO,115,161,71.428571,71,97,0,0,0,0,0
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,101,117,86.324786,86,96,0,0,0,0,0
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,147,163,90.184049,90,98,0,0,0,0,0
3,01/04/2026,RAUL FABIAN ROMERO MICAN,253,302,83.774834,84,95,0,0,0,0,0
4,02/04/2026,DORIS EDITH PATARROYO GORDO,30,34,88.235294,88,99,0,0,0,0,0

In [78]:
#Eliminar columnas que no se necesitan para el proceso

col_eliminar = ['Viaje Regular', 'Viaje Totales','IRI (%)']

indicadores= indicadores.drop(columns=col_eliminar)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/04/2026,DORIS EDITH PATARROYO GORDO,71,97,0,0,0,0,0
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,86,96,0,0,0,0,0
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,90,98,0,0,0,0,0
3,01/04/2026,RAUL FABIAN ROMERO MICAN,84,95,0,0,0,0,0
4,02/04/2026,DORIS EDITH PATARROYO GORDO,88,99,0,0,0,0,0

In [79]:
# Agrupar por 'reg_ccz' y contar los días únicos laborados
dias_laborados = indicadores.groupby('reg_ccz')['Fecha'].nunique()

# Crear una nueva columna en el DataFrame de indicadores con los días laborados
indicadores['Días Laborados'] = indicadores['reg_ccz'].map(dias_laborados)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,01/04/2026,DORIS EDITH PATARROYO GORDO,71,97,0,0,0,0,0,3
1,01/04/2026,JIMMY ALEXANDER CARABALLO DIAZ,86,96,0,0,0,0,0,3
2,01/04/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,90,98,0,0,0,0,0,3
3,01/04/2026,RAUL FABIAN ROMERO MICAN,84,95,0,0,0,0,0,3
4,02/04/2026,DORIS EDITH PATARROYO GORDO,88,99,0,0,0,0,0,3

In [80]:
# Agrupar por 'reg_ccz' y aplicar las funciones de agregación necesarias
indicadores_f = indicadores.groupby('reg_ccz').agg({
    'Regularidad (%)': 'mean',
    'Kilómetros (%)': 'mean',
    'TMR_segundos': 'mean',
    'No Asignado': 'sum',
    'Ausentismo': 'sum',
    'Novedades': 'sum',
    'Retardo': 'sum',
    'Días Laborados':'max'
}).reset_index()

# Redondear las columnas a 2 decimales
indicadores_f['Regularidad (%)'] = indicadores_f['Regularidad (%)'].round(0).astype(int)
indicadores_f['Kilómetros (%)'] = indicadores_f['Kilómetros (%)'].round(0).astype(int)
indicadores_f['TMR_segundos'] = indicadores_f['TMR_segundos'].round(0).astype(int)

# Mostrar el DataFrame resultante
indicadores_f.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15

In [81]:
#copia de la data de indicadores 

calificacion = indicadores_f.copy()

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15

In [82]:
# Definir la función para convertir la lógica de Excel a Python
def convertir_regularidad(valor):
    if valor >= 84:
        return 100
    elif 80 <= valor < 84:
        return 75
    elif 74 <= valor < 80:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Regularidad (%)'
calificacion['IRI'] = calificacion['Regularidad (%)'].apply(convertir_regularidad)

# Mostrar el DataFrame resultante con la nueva columna
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0

In [83]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_kilometros(valor):
    if valor >= 95:
        return 100
    elif 90 <= valor < 95:
        return 75
    elif 80 <= valor < 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['KM'] = calificacion['Kilómetros (%)'].apply(convertir_kilometros)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50

In [84]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_tmr(valor):
    if valor <= 60:
        return 100
    elif 60 < valor <= 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['Fonias'] = calificacion['TMR_segundos'].apply(convertir_tmr)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75,100
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50,100
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50,100
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50,100
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50,100

In [85]:
# Duplicar la columna 'No Asignado'
calificacion['No Asignado %'] = calificacion['No Asignado']

# Nombres a excluir
excluir_nombres = ['DIEGO ARTURO URIBE ROJAS', 'CAMILO ANDRES LOPEZ PENAGOS', 'LISETH GERALDINE GARCIA GARZÓN']

# Filtrar el DataFrame para excluir estos nombres
calificacion_filtrado = calificacion[~calificacion['reg_ccz'].isin(excluir_nombres)]

# Encontrar el valor máximo en la columna 'No Asignado Modificado' del DataFrame filtrado
max_no_asignado = calificacion_filtrado['No Asignado %'].max()

# Asignar 5 al valor máximo y 0 al resto
calificacion['No Asignado %'] = calificacion['No Asignado %'].apply(lambda x: 5 if x == max_no_asignado else 0)

# Mostrar el DataFrame resultante
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75,100,5
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50,100,5
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50,100,5
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50,100,5
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50,100,5

In [86]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_retardo(valor):
    if valor <= 0:
        return 100
    elif 1 >= valor <= 3:
        return 40
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Retardos'] = calificacion['Retardo'].apply(convertir_retardo)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75,100,5,40
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50,100,5,100
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50,100,5,100
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50,100,5,40
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50,100,5,100

In [87]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_novedades(valor):
    if valor <= 0:
        return 100
    elif valor == 1:
        return 75
    elif valor == 2:
        return 50
    elif valor == 3:
        return 25
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Novedades'] = calificacion['Novedades'].apply(convertir_novedades)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75,100,5,40,100
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50,100,5,100,100
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50,100,5,100,100
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50,100,5,40,100
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50,100,5,100,100

In [88]:
#Sumar las novedades retardos y novedades

calificacion['Novedad'] = ((calificacion['% Novedades'] + calificacion['% Retardos']) / 2).astype(int)

# Calcular el promedio de las columnas mencionadas
calificacion['Total Calificación'] = calificacion[['IRI', 'KM', 'Fonias','Novedad']].mean(axis=1)

# Convertir el resultado a enteros si es necesario
calificacion['Total Calificación'] = calificacion['Total Calificación'].astype(int)

calificacion['Total'] = calificacion['Total Calificación'] + calificacion['No Asignado %']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75,100,5,40,100,70,86,91
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50,100,5,100,100,100,62,67
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50,100,5,100,100,100,75,80
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50,100,5,40,100,70,67,72
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50,100,5,100,100,100,62,67

In [89]:
#Crear base auxiliar para llevar el cargo

base_personal = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/base_personal.csv', encoding='latin', delimiter=';')

base_personal.head()

                                Nombre                           Cargo
0     PAULA KATHERINE CANTOR SALAMANCA  REGULADOR EN CENTRO DE CONTROL
1         LUIS FERNANDO GONZALEZ REYES  REGULADOR EN CENTRO DE CONTROL
2         MAICOL ALEXANDER PITA BLANCO  REGULADOR EN CENTRO DE CONTROL
3  SANDRA CAROLINA VALERIANO SARMIENTO  REGULADOR EN CENTRO DE CONTROL
4                 ELICIA MONGUI DUARTE  REGULADOR EN CENTRO DE CONTROL

In [90]:
#Llevar el cargo a la base de calificacion

def calcular_turno(reg):
    
    filtro = (
        (base_personal['Nombre'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base_personal.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base_personal.loc[filtro, 'Cargo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
calificacion['Cargo'] = calificacion.apply(
    lambda row: calcular_turno(
        row['reg_ccz']
    ),
    axis=1
)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total,Cargo
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,75,100,5,40,100,70,86,91,REGULADOR EN CENTRO DE CONTROL
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,50,100,5,100,100,100,62,67,REGULADOR DE VÍA
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,50,100,5,100,100,100,75,80,REGULADOR DE VÍA
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,50,100,5,40,100,70,67,72,REGULADOR DE VÍA
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,50,100,5,100,100,100,62,67,REGULADOR DE VÍA

In [91]:
#Validación del 100% a que corresponde

# Calcular el 35% de las columnas 'IRI' y 'KM'
calificacion['IRI_35%'] = calificacion['IRI'] * 0.35
calificacion['KM_35%'] = calificacion['KM'] * 0.35
calificacion['fonias_20%'] = calificacion['Fonias'] * 0.20
calificacion['No Asignado_5%'] = calificacion['No Asignado %'] * 0.05
calificacion['Novedad_10%'] = calificacion['Novedad'] * 0.10


# Redondear las columnas a 2 decimales
calificacion['IRI_35%'] = calificacion['IRI_35%'].round(0).astype(int)
calificacion['KM_35%'] = calificacion['KM_35%'].round(0).astype(int)
calificacion['fonias_20%'] = calificacion['fonias_20%'].round(0).astype(int)
calificacion['No Asignado_5%'] =calificacion['No Asignado_5%'].round(2).astype(int)
calificacion['Novedad_10%'] =calificacion['Novedad_10%'].round(0).astype(int)

calificacion['Total_100%'] = calificacion['IRI_35%'] + calificacion['KM_35%'] + calificacion['fonias_20%'] + calificacion['No Asignado_5%'] + calificacion['Novedad_10%']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,...,Novedad,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,...,70,86,91,REGULADOR EN CENTRO DE CONTROL,35,26,20,0,7,88
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,...,100,62,67,REGULADOR DE VÍA,0,18,20,0,10,48
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,...,100,75,80,REGULADOR DE VÍA,18,18,20,0,10,66
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,...,70,67,72,REGULADOR DE VÍA,18,18,20,0,7,63
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,...,100,62,67,REGULADOR DE VÍA,0,18,20,0,10,48

In [92]:
# Total de días en el mes

# Calcular el 70% de los días laborados
umbral = 0.70 * total_dias_julio

# Revisar si los días laborados cumplen con la condición
calificacion['Cumple Condición'] = calificacion['Días Laborados'].apply(lambda x: 1 if x >= umbral else 0)

# Mostrar el DataFrame actualizado
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,...,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%,Cumple Condición
0,ADRIANA PATRICIA TELLEZ VARELA,89,92,0,0,0,0,1,7,100,...,86,91,REGULADOR EN CENTRO DE CONTROL,35,26,20,0,7,88,0
1,ADRIANA YANETH RAMIREZ GALVAN,70,81,0,0,0,0,0,20,0,...,62,67,REGULADOR DE VÍA,0,18,20,0,10,48,0
2,ALEXANDRA MARTINEZ TAPIA,76,83,0,0,0,0,0,26,50,...,75,80,REGULADOR DE VÍA,18,18,20,0,10,66,1
3,AMANDA LUCIA RODRIGUEZ ARAUJO,74,85,0,0,0,0,1,11,50,...,67,72,REGULADOR DE VÍA,18,18,20,0,7,63,0
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,83,0,0,0,0,0,15,0,...,62,67,REGULADOR DE VÍA,0,18,20,0,10,48,0

In [93]:
#Exportar archivo
calificacion.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/calificacion_{mes_i}.csv', index=False)

In [94]:
#Exportar archivo
indicadores.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/indicadores_{mes_i}.csv', index=False)

In [95]:
#Exportar archivo

kilometros.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/kilometros_{mes_i}.csv', index=False)

In [96]:
novedades_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/novedades_fin_{mes_i}.csv', index=False)

In [97]:
#Exportar archivo

fonias_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/fonias_{mes_i}.csv', index=False)

In [98]:
#Exportar archivo

iri.to_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python//regularidad_{mes_i}.csv", index=False)