In [1]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import re
import pyproj
import folium

In [2]:
#Filtros de fechas

dia_ivd = '20260201'
dia_fvd = '20260228'

dia_ias = '01-02-2026'
dia_fas = '28-02-2026'

dia_if = '2026-02-01'
dia_ff = '2026-02-28'

mes = 'Novedades_feb26'

mes_i = 'feb26'

total_dias_julio = 28

mes_c = 'Febrero'

Importar archivos de viajes desglosados zonal y troncal, informes de regularidad de plataforma EIC

In [3]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/01 viajes_desglosados_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosado.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_zonal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_zonal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_zonal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,0,41896,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98
1,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
2,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,0,0,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00
3,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
4,1/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,0,42019,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98

In [4]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/16 viajes_desglosados_alimentacion_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosadotroncal.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_troncal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_troncal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_troncal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0A60001-1-12553,CE0A60001,1,2,1,10502,...,0,14465,Si,NaN,NaN,NaN,"3, 1",CDZ4,100.0,1.0
1,1/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0A60001-2-12553,CE0A60001,2,3,2,10502,...,0,14465,No,NaN,NaN,NaN,"3, 1",CDZ4,100.0,1.0
2,1/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0A60001-3-12553,CE0A60001,3,4,3,10502,...,0,14465,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0A60001-4-12553,CE0A60001,4,5,4,10502,...,0,14465,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0A60001-5-12553,CE0A60001,5,6,5,10502,...,0,14465,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [5]:
# Consolidar todos los DataFrames en uno solo

desglosados_fms = pd.concat([desg_zonal_fms, desg_troncal_fms], ignore_index=True)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,0,41896,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98
1,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
2,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,0,0,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00
3,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
4,1/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,0,42019,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98

In [6]:
desglosados_fms['Id Línea '] = (
    desglosados_fms['Id Línea ']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,0,41896,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98
1,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
2,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,0,0,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00
3,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
4,1/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,0,42019,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98

In [7]:
desglosados_fms['KmEjecutado'] = (
    desglosados_fms['KmEjecutado']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,0,41896,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98
1,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
2,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,0,0,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00
3,1/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
4,1/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,0,42019,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98

In [8]:
# Ruta de la carpeta que contiene los archivos de desglosados zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/Blogger/Asistencia/2026/{mes_c}'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ias}'
fecha_fin = f'{dia_fas}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:10]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%d-%m-%Y', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', delimiter=';',skiprows=2, low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            # Añadir una nueva columna 'Fecha' con la fecha extraída del nombre del archivo
            df['Fecha'] = fecha_archivo
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    asistencia = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    asistencia.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/asistencia_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,ADRIANA YANETH RAMIREZ GALVAN,ADRIANA YANETH,RAMIREZ GALVAN,PLA1,Portal Dorado,05:00:00,NaN,04:58:00,09:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2026
1,JENNY LIZETH SALINAS SUAREZ,JENNY LIZETH,SALINAS SUAREZ,PLA3,Portal 80,05:00:00,NaN,04:56:00,09:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2026
2,DIEGO ARTURO URIBE ROJAS,DIEGO ARTURO,URIBE ROJAS,SUP CCZ,Disponible CCZ,06:00:00,NaN,06:00:00,16:00:00,22:00:00,...,22:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2026
3,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET2M,ET2M,06:00:00,NaN,05:57:00,08:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2026
4,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,ET3M,ET3M,06:00:00,NaN,05:33:00,08:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-02-2026

In [9]:
## Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia

# Convertir la columna 'Fecha' a tipo datetime
asistencia['Fecha'] = pd.to_datetime(asistencia['Fecha'], format='%d-%m-%Y')

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
asistencia['Fecha'] = asistencia['Fecha'].dt.strftime('%d/%m/%Y')

asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,ADRIANA YANETH RAMIREZ GALVAN,ADRIANA YANETH,RAMIREZ GALVAN,PLA1,Portal Dorado,05:00:00,NaN,04:58:00,09:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/02/2026
1,JENNY LIZETH SALINAS SUAREZ,JENNY LIZETH,SALINAS SUAREZ,PLA3,Portal 80,05:00:00,NaN,04:56:00,09:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/02/2026
2,DIEGO ARTURO URIBE ROJAS,DIEGO ARTURO,URIBE ROJAS,SUP CCZ,Disponible CCZ,06:00:00,NaN,06:00:00,16:00:00,22:00:00,...,22:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/02/2026
3,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,ET2M,ET2M,06:00:00,NaN,05:57:00,08:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/02/2026
4,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,ET3M,ET3M,06:00:00,NaN,05:33:00,08:00:00,14:00:00,...,14:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/02/2026

In [10]:
#Archivo de novedades disciplinarias

novedades = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/{mes}.csv",encoding='latin', delimiter=';')

In [11]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
novedades['FECHA INICIAL'] = pd.to_datetime(novedades['FECHA INICIAL'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
novedades['FECHA INICIAL'] = novedades['FECHA INICIAL'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1044260,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500159.0,19290239,LUIS HERNANDO CORTES DIAZ,OPERADOR PADRON HIBRIDO DUAL,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
1,1045566,28/02/2026,28/02/2026,1,Cambio de Turno Operativo,NaN,Patio Dorado,500029.0,19337415,ISRAEL MARTINEZ GONZALEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1045567,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500113.0,80800170,LUIS EDUARDO GRISALES GONZALEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
3,1045568,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500118.0,80512739,LEONARDO MONTOYA ARIAS,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
4,1045569,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501149.0,80926723,OSCAR EMIRO BARRERA BERNAL,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [12]:
#Archivos de regularidad de plataforma EIC

cerrado = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_cerrrado_{mes_i}.csv", delimiter=';')

etapa_1 = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_Etapa1_{mes_i}.csv", delimiter=';')

In [13]:
#Informes de turnos, tipo día, personal

turno_via = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_via_fms.csv", sep=';')

turno_sup = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_supervisor_fms.csv", sep=';')

tipo_dia = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Tipo día.csv", encoding='latin',delimiter=';')

personal = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Personal_id.csv",encoding='latin',delimiter=';')

turno_ccz = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_control_fms.csv", sep=';')

In [14]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [15]:
#Importar data de fonias

fonias = pd.read_excel ("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2023/fonias_fms.xlsx")

# Convertir la columna 'Fecha' a tipo datetime
fonias['Fecha'] = pd.to_datetime(fonias['Fecha'])

# Filtrar los valores mayores o iguales a la fecha indicada
fonias = fonias[(fonias['Fecha'] >= f'{dia_if}') & (fonias['Fecha'] <= f'{dia_ff}')]

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
fonias['Fecha'] = fonias['Fecha'].dt.strftime('%d/%m/%Y')

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:05:00,05:05:00,05:06:00,00:00:00,00:00:37,NaN
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:12:00,05:13:00,05:13:00,00:01:00,00:00:47,NaN
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,NaN,0.5,0.0,05:30:00,05:32:00,05:32:00,00:02:00,00:00:21,NaN
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,NaN,0.5,0.0,05:47:00,05:47:00,05:48:00,00:00:00,00:01:00,NaN
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:59:00,05:59:00,06:00:00,00:00:00,00:00:26,NaN

In [16]:
#Crear dataframe para llevar el nombre a fonias

# Crear un diccionario con los datos
data = {
    'RegC': [
        'Luis Fernando Gonzalez', 'William Munar Gonzalez', 'Adriana Patricia Tellez',
        'Jose Antonio Castro Garcia', 'Rosa Tellez', 'Edith Patarroyo',
        'Laura Marcela Vargas Gutierrez', 'Francy Linnie Timaran Cuesta', 
        'Yerly Irene Hernandez Ariza', 'Anderson Mizar Mendoza', 'Jorge Medina Espinoza',
        'Esteban Camilo Medina', 'Sandra Carolina Valeriano', 'Julian Andres Sanchez Restrepo',
        'Karen Lorena Barrera', 'Bryan Guzman', 'Jinneth Alexandra Guzman',
        'Maicol Alexander Pita Blanco', 'Martha Ibeth Martin', 'John Jairo Espinosa Santa',
        'Elicia Mongui Duarte', 'Sonia Constanza Correa Rodriguez', 'Jenny Alexandra Bernal',
        'Norberto Niño Rodriguez', 'Wilson Torres Fajardo', 'William Ignacio Valderrama',
        'Camilo Andres Lopez Penagos', 'Raúl Fabián Romero Micán', 'Deisi Yanira Rojas Torres',
        'Paula Katherine Cantor Salamanca','Angela Mireya Riaño Pasito'
    ],
    'RegControl': [
        'LUIS FERNANDO GONZALEZ REYES', 'WILLIAN HUMBERTO MUNAR GONZALEZ', 
        'ADRIANA PATRICIA TELLEZ VARELA', 'JOSE ANTONIO CASTRO GARCIA', 
        'ROSA MARIELA TELLEZ NAVARRO', 'DORIS EDITH PATARROYO GORDO',
        'LAURA MARCELA VARGAS GUTIERREZ', 'FRANCY LINNE TIMARAN CUESTA', 
        'YERLI IRENE HERNÁNDEZ ARIZA', 'ANDERSON MIZAR MENDOZA', 
        'JORGE MEDINA ESPINOSA', 'ESTEBAN CAMILO MEDINA', 
        'SANDRA CAROLINA VALERIANO SARMIENTO', 'JULIAN ANDRES SANCHEZ RESTREPO', 
        'KAREN LORENA BARRERA SERRANO', 'BRYAN ANDRES GUZMAN ROJANO', 
        'JINETH ALEXANDRA GUZMAN HERNANDEZ', 'MAICOL ALEXANDER PITA BLANCO', 
        'MARTHA IBETH MARTIN MARTIN', 'JOHN JAIRO ESPINOSA SANTA', 
        'ELICIA MONGUI DUARTE', 'SONIA CONSTANZA CORREA RODRIGUEZ', 
        'JENNY ALEXANDRA BERNAL BERNAL', 'NORBERTO NIÑO RODRIGUEZ', 
        'WILSON ABEL TORRES FAJARDO', 'WILLIAM IGNACIO VALDERRAMA GONZALEZ', 
        'CAMILO ANDRES LOPEZ PENAGOS', 'RAUL FABIAN ROMERO MICAN', 
        'DEISY YANIRA ROJAS TORRES', 'PAULA KATHERINE CANTOR SALAMANCA',
        'ANGELA MIREYA RIAÑO PASITO'
    ]
}

# Convertir el diccionario a un DataFrame
base = pd.DataFrame(data)

# Mostrar el DataFrame
base

                                RegC                           RegControl
0             Luis Fernando Gonzalez         LUIS FERNANDO GONZALEZ REYES
1             William Munar Gonzalez      WILLIAN HUMBERTO MUNAR GONZALEZ
2            Adriana Patricia Tellez       ADRIANA PATRICIA TELLEZ VARELA
3         Jose Antonio Castro Garcia           JOSE ANTONIO CASTRO GARCIA
4                        Rosa Tellez          ROSA MARIELA TELLEZ NAVARRO
5                    Edith Patarroyo          DORIS EDITH PATARROYO GORDO
6     Laura Marcela Vargas Gutierrez       LAURA MARCELA VARGAS GUTIERREZ
7       Francy Linnie Timaran Cuesta          FRANCY LINNE TIMARAN CUESTA
8        Yerly Irene Hernandez Ariza          YERLI IRENE HERNÁNDEZ ARIZA
9             Anderson Mizar Mendoza               ANDERSON MIZAR MENDOZA
10             Jorge Medina Espinoza                JORGE MEDINA ESPINOSA
11             Esteban Camilo Medina                ESTEBAN CAMILO MEDINA
12         Sandra Carolina Valeriano  SANDRA CAROLINA VALERIANO SARMIENTO
13    Julian Andres Sanchez Restrepo       JULIAN ANDRES SANCHEZ RESTREPO
14              Karen Lorena Barrera         KAREN LORENA BARRERA SERRANO
15                      Bryan Guzman           BRYAN ANDRES GUZMAN ROJANO
16          Jinneth Alexandra Guzman    JINETH ALEXANDRA GUZMAN HERNANDEZ
17      Maicol Alexander Pita Blanco         MAICOL ALEXANDER PITA BLANCO
18               Martha Ibeth Martin           MARTHA IBETH MARTIN MARTIN
19         John Jairo Espinosa Santa            JOHN JAIRO ESPINOSA SANTA
20              Elicia Mongui Duarte                 ELICIA MONGUI DUARTE
21  Sonia Constanza Correa Rodriguez     SONIA CONSTANZA CORREA RODRIGUEZ
22            Jenny Alexandra Bernal        JENNY ALEXANDRA BERNAL BERNAL
23           Norberto Niño Rodriguez              NORBERTO NIÑO RODRIGUEZ
24             Wilson Torres Fajardo           WILSON ABEL TORRES FAJARDO
25        William Ignacio Valderrama  WILLIAM IGNACIO VALDERRAMA GONZALEZ
26       Camilo Andres Lopez Penagos          CAMILO ANDRES LOPEZ PENAGOS
27          Raúl Fabián Romero Micán             RAUL FABIAN ROMERO MICAN
28         Deisi Yanira Rojas Torres            DEISY YANIRA ROJAS TORRES
29  Paula Katherine Cantor Salamanca     PAULA KATHERINE CANTOR SALAMANCA
30        Angela Mireya Riaño Pasito           ANGELA MIREYA RIAÑO PASITO

Indicador de regularidad de personal de control

In [17]:
#consolidar iri con los datos de cerrado y etapa_1

iri = pd.concat([cerrado,etapa_1], ignore_index=True)

#Eliminar columnas 

col_eliminar = ['IdIRI', 'Estado', 'F. Inicio DP', 'F. Cierre DP','Operador Programado','Id Operador','Operador','Evidencia']

iri = iri.drop(columns=col_eliminar)

iri['Cantidad'] = 1

iri

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\1407071630.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  iri = pd.concat([cerrado,etapa_1], ignore_index=True)

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,1/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,Con hora de Inicio LG SMART OPERATOR,1,0,52.15,6.03,600.000.000,1,0,1,1
1,1/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,Con hora de Inicio LG SMART OPERATOR,1,0,0.00,11.10,300.000.000,1,0,1,1
2,1/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,Con hora de Inicio LG SMART OPERATOR,0,0,32.48,0.65,300.000.000,1,0,1,1
3,1/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,Con hora de Inicio LG SMART OPERATOR,0,0,29.50,1.77,300.000.000,1,0,1,1
4,1/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,Con hora de Inicio LG SMART OPERATOR,0,0,36.13,6.80,300.000.000,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,Con hora de Inicio LG SMART OPERATOR,0,0,11.67,11.78,120.000.000,1,0,1,1
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,Con hora de Inicio LG SMART OPERATOR,0,0,7.88,1.37,200.000.000,0,0,1,1
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,Con hora de Inicio LG SMART OPERATOR,0,0,4.03,2.50,200.000.000,0,0,1,1
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.48,0.92,200.000.000,0,0,1,1
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,Con hora de Inicio LG SMART OPERATOR,0,0,16.45,5.30,600.000.000,1,0,1,1

In [18]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
iri['Fecha Viaje'] = pd.to_datetime(iri['Fecha Viaje'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
iri['Fecha Viaje'] = iri['Fecha Viaje'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,Con hora de Inicio LG SMART OPERATOR,1,0,52.15,6.03,600.000.000,1,0,1,1
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,Con hora de Inicio LG SMART OPERATOR,1,0,0.00,11.10,300.000.000,1,0,1,1
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,Con hora de Inicio LG SMART OPERATOR,0,0,32.48,0.65,300.000.000,1,0,1,1
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,Con hora de Inicio LG SMART OPERATOR,0,0,29.50,1.77,300.000.000,1,0,1,1
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,Con hora de Inicio LG SMART OPERATOR,0,0,36.13,6.80,300.000.000,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,Con hora de Inicio LG SMART OPERATOR,0,0,11.67,11.78,120.000.000,1,0,1,1
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,Con hora de Inicio LG SMART OPERATOR,0,0,7.88,1.37,200.000.000,0,0,1,1
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,Con hora de Inicio LG SMART OPERATOR,0,0,4.03,2.50,200.000.000,0,0,1,1
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.48,0.92,200.000.000,0,0,1,1
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,Con hora de Inicio LG SMART OPERATOR,0,0,16.45,5.30,600.000.000,1,0,1,1

In [19]:
#Convertir datos de columna Hora Teórica

# Expresión regular ajustada para extraer la hora
patron_hora = r'(\d{1,2}:\d{2}:\d{2}\s?[ap]\.?m\.?)'

# Aplicar la extracción de hora a la columna 'Hora Teórica'
iri['Hora'] = iri['Hora Teórica'].str.extract(patron_hora)

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,1,0,52.15,6.03,600.000.000,1,0,1,1,NaN
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,1,0,0.00,11.10,300.000.000,1,0,1,1,NaN
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,0,0,32.48,0.65,300.000.000,1,0,1,1,NaN
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,0,0,29.50,1.77,300.000.000,1,0,1,1,NaN
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,0,0,36.13,6.80,300.000.000,1,0,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,0,0,11.67,11.78,120.000.000,1,0,1,1,NaN
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,0,0,7.88,1.37,200.000.000,0,0,1,1,NaN
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,0,0,4.03,2.50,200.000.000,0,0,1,1,NaN
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,0,0,5.48,0.92,200.000.000,0,0,1,1,NaN
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,0,0,16.45,5.30,600.000.000,1,0,1,1,NaN

In [20]:
# Dividir la columna 'Hora Teórica' en 'Fecha' y 'Hora'
iri[['Fecha1', 'Hora']] = iri['Hora Teórica'].str.split(' ', n=1, expand=True)

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,0,52.15,6.03,600.000.000,1,0,1,1,NaN,NaN
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,0,0.00,11.10,300.000.000,1,0,1,1,5:00,1/02/2026
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,0,32.48,0.65,300.000.000,1,0,1,1,7:14,1/02/2026
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,0,29.50,1.77,300.000.000,1,0,1,1,9:23,1/02/2026
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,0,36.13,6.80,300.000.000,1,0,1,1,17:28,1/02/2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,0,11.67,11.78,120.000.000,1,0,1,1,NaN,NaN
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,0,7.88,1.37,200.000.000,0,0,1,1,NaN,NaN
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,0,4.03,2.50,200.000.000,0,0,1,1,NaN,NaN
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,0,5.48,0.92,200.000.000,0,0,1,1,NaN,NaN
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,0,16.45,5.30,600.000.000,1,0,1,1,NaN,NaN

In [21]:
# Dividir la columna  en partes usando ':', y seleccionar la primera parte (horas)
iri['franja'] = iri['Hora'].str.split(':').str[0]

# Convertir la columna 'franja' a tipo entero
iri['franja'] = pd.to_numeric(iri['franja'], errors='coerce').astype('Int64')

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,52.15,6.03,600.000.000,1,0,1,1,NaN,NaN,<NA>
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,0.00,11.10,300.000.000,1,0,1,1,5:00,1/02/2026,5
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,32.48,0.65,300.000.000,1,0,1,1,7:14,1/02/2026,7
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,29.50,1.77,300.000.000,1,0,1,1,9:23,1/02/2026,9
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,36.13,6.80,300.000.000,1,0,1,1,17:28,1/02/2026,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,11.67,11.78,120.000.000,1,0,1,1,NaN,NaN,<NA>
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,7.88,1.37,200.000.000,0,0,1,1,NaN,NaN,<NA>
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,4.03,2.50,200.000.000,0,0,1,1,NaN,NaN,<NA>
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,5.48,0.92,200.000.000,0,0,1,1,NaN,NaN,<NA>
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,16.45,5.30,600.000.000,1,0,1,1,NaN,NaN,<NA>

In [22]:
#Llevar ruta comercial a iri

def calcular_posicion(Linea):
    
    filtro = (
        (turno_via['Linea'] == Linea)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        ruta = turno_via.loc[filtro, 'Ruta'].iloc[0]
        return ruta  if not pd.isna(ruta) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Ruta_Comercial'] = iri.apply(
    lambda row: calcular_posicion(
        row['Linea SAE']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,6.03,600.000.000,1,0,1,1,NaN,NaN,<NA>,539
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,11.10,300.000.000,1,0,1,1,5:00,1/02/2026,5,539
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,0.65,300.000.000,1,0,1,1,7:14,1/02/2026,7,539
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,1.77,300.000.000,1,0,1,1,9:23,1/02/2026,9,539
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,6.80,300.000.000,1,0,1,1,17:28,1/02/2026,17,539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,11.78,120.000.000,1,0,1,1,NaN,NaN,<NA>,576
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,1.37,200.000.000,0,0,1,1,NaN,NaN,<NA>,576
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,2.50,200.000.000,0,0,1,1,NaN,NaN,<NA>,576
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,0.92,200.000.000,0,0,1,1,NaN,NaN,<NA>,576
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,5.30,600.000.000,1,0,1,1,NaN,NaN,<NA>,576

In [23]:
#Llevar tipo día a iri

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Tipo dia'] = iri.apply(
    lambda row: calcular_posicion(
        row['Fecha Viaje']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,600.000.000,1,0,1,1,NaN,NaN,<NA>,539,Festivo
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,300.000.000,1,0,1,1,5:00,1/02/2026,5,539,Festivo
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,300.000.000,1,0,1,1,7:14,1/02/2026,7,539,Festivo
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,300.000.000,1,0,1,1,9:23,1/02/2026,9,539,Festivo
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,300.000.000,1,0,1,1,17:28,1/02/2026,17,539,Festivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,120.000.000,1,0,1,1,NaN,NaN,<NA>,576,Sábado
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,200.000.000,0,0,1,1,NaN,NaN,<NA>,576,Sábado
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,200.000.000,0,0,1,1,NaN,NaN,<NA>,576,Sábado
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,200.000.000,0,0,1,1,NaN,NaN,<NA>,576,Sábado
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,600.000.000,1,0,1,1,NaN,NaN,<NA>,576,Sábado

In [24]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
iri['Tipo_dia'] = iri['Tipo dia'].apply(obtener_letra_inicial)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,1,0,1,1,NaN,NaN,<NA>,539,Festivo,F
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,1,0,1,1,5:00,1/02/2026,5,539,Festivo,F
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,1,0,1,1,7:14,1/02/2026,7,539,Festivo,F
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,1,0,1,1,9:23,1/02/2026,9,539,Festivo,F
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,1,0,1,1,17:28,1/02/2026,17,539,Festivo,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,1,0,1,1,NaN,NaN,<NA>,576,Sábado,S
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,0,0,1,1,NaN,NaN,<NA>,576,Sábado,S
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,0,0,1,1,NaN,NaN,<NA>,576,Sábado,S
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,0,0,1,1,NaN,NaN,<NA>,576,Sábado,S
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,1,0,1,1,NaN,NaN,<NA>,576,Sábado,S

In [25]:
#Traer el turno de reg_via

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,0,1,1,NaN,NaN,<NA>,539,Festivo,F,None
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,0,1,1,5:00,1/02/2026,5,539,Festivo,F,None
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,0,1,1,7:14,1/02/2026,7,539,Festivo,F,EG9
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,0,1,1,9:23,1/02/2026,9,539,Festivo,F,EG9
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,0,1,1,17:28,1/02/2026,17,539,Festivo,F,EG10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,0,1,1,NaN,NaN,<NA>,576,Sábado,S,None
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,0,1,1,NaN,NaN,<NA>,576,Sábado,S,None
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,0,1,1,NaN,NaN,<NA>,576,Sábado,S,None
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,0,1,1,NaN,NaN,<NA>,576,Sábado,S,None
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,0,1,1,NaN,NaN,<NA>,576,Sábado,S,None

In [26]:
#Traer el turno de control

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,1,1,NaN,NaN,<NA>,539,Festivo,F,None,None
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,1,1,5:00,1/02/2026,5,539,Festivo,F,None,ET3N
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,1,1,7:14,1/02/2026,7,539,Festivo,F,EG9,ET5M
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,1,1,9:23,1/02/2026,9,539,Festivo,F,EG9,ET5M
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,1,1,17:28,1/02/2026,17,539,Festivo,F,EG10,ET5T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,1,1,NaN,NaN,<NA>,576,Sábado,S,None,None
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,1,1,NaN,NaN,<NA>,576,Sábado,S,None,None
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,1,1,NaN,NaN,<NA>,576,Sábado,S,None,None
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,1,1,NaN,NaN,<NA>,576,Sábado,S,None,None
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,1,1,NaN,NaN,<NA>,576,Sábado,S,None,None

In [27]:
#Traer el turno de supervisor

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_Sup'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,1,NaN,NaN,<NA>,539,Festivo,F,None,None,None
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,1,5:00,1/02/2026,5,539,Festivo,F,None,ET3N,SUP CCZ
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,1,7:14,1/02/2026,7,539,Festivo,F,EG9,ET5M,SUP CCZ
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,1,9:23,1/02/2026,9,539,Festivo,F,EG9,ET5M,SUP CCZ
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,1,17:28,1/02/2026,17,539,Festivo,F,EG10,ET5T,SUP CCZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,1,NaN,NaN,<NA>,576,Sábado,S,None,None,None
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,1,NaN,NaN,<NA>,576,Sábado,S,None,None,None
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,1,NaN,NaN,<NA>,576,Sábado,S,None,None,None
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,1,NaN,NaN,<NA>,576,Sábado,S,None,None,None
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,1,NaN,NaN,<NA>,576,Sábado,S,None,None,None

In [28]:
#Traer el regulador según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['reg_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_via']
    ),
    axis=1
)

iri['reg_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_ccz']
    ),
    axis=1
)

iri['Supervisor'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_Sup']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,<NA>,539,Festivo,F,None,None,None,None,None,None
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,5,539,Festivo,F,None,ET3N,SUP CCZ,None,ROSA MARIELA TELLEZ NAVARRO,DIEGO ARTURO URIBE ROJAS
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,7,539,Festivo,F,EG9,ET5M,SUP CCZ,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,KAREN LORENA BARRERA SERRANO,DIEGO ARTURO URIBE ROJAS
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,9,539,Festivo,F,EG9,ET5M,SUP CCZ,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,KAREN LORENA BARRERA SERRANO,DIEGO ARTURO URIBE ROJAS
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,17,539,Festivo,F,EG10,ET5T,SUP CCZ,DIANA MARCELA AGUILERA MADRIGAL,WILSON ABEL TORRES FAJARDO,DIEGO ARTURO URIBE ROJAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,<NA>,576,Sábado,S,None,None,None,None,None,None
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,<NA>,576,Sábado,S,None,None,None,None,None,None
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,<NA>,576,Sábado,S,None,None,None,None,None,None
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,<NA>,576,Sábado,S,None,None,None,None,None,None
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,<NA>,576,Sábado,S,None,None,None,None,None,None

In [29]:
#Llevar identificación al regulador

def calcular_posicion(Nombre_completo):
    
    filtro = (
        (personal['Nombre Completo'] == Nombre_completo)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not personal.loc[filtro].empty:
        # Obtener el primer valor
        personas = personal.loc[filtro, 'Identificación'].iloc[0]
        return  personas  if not pd.isna( personas ) else None  
    
    return 0  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Id_via'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_via']
    ),
    axis=1
)

iri['Id_ccz'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_ccz']
    ),
    axis=1
)

iri['Id_sup'] = iri.apply(
    lambda row: calcular_posicion(
        row['Supervisor']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,F,None,None,None,None,None,None,0,0,0
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,F,None,ET3N,SUP CCZ,None,ROSA MARIELA TELLEZ NAVARRO,DIEGO ARTURO URIBE ROJAS,0,52735918,1016052079
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,F,EG9,ET5M,SUP CCZ,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,KAREN LORENA BARRERA SERRANO,DIEGO ARTURO URIBE ROJAS,46678181,1031150803,1016052079
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,F,EG9,ET5M,SUP CCZ,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,KAREN LORENA BARRERA SERRANO,DIEGO ARTURO URIBE ROJAS,46678181,1031150803,1016052079
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,F,EG10,ET5T,SUP CCZ,DIANA MARCELA AGUILERA MADRIGAL,WILSON ABEL TORRES FAJARDO,DIEGO ARTURO URIBE ROJAS,52737325,79565949,1016052079

In [30]:
# Convertir 'Nodo' a tipo entero
iri['Viaje Regular'] = iri['Viaje Regular'].astype(int)

iri['Viaje Totales'] = iri['Viaje Regular']

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup,Viaje Totales
0,01/02/2026,URBANO,AD0194019,1,1,19,105,10194,10425,504182,...,None,None,None,None,None,None,0,0,0,1
1,01/02/2026,URBANO,CE0590001,2,1,1,105,10194,10425,524009,...,None,ET3N,SUP CCZ,None,ROSA MARIELA TELLEZ NAVARRO,DIEGO ARTURO URIBE ROJAS,0,52735918,1016052079,1
2,01/02/2026,URBANO,CE0590001,3,2,1,105,10194,10426,504174,...,EG9,ET5M,SUP CCZ,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,KAREN LORENA BARRERA SERRANO,DIEGO ARTURO URIBE ROJAS,46678181,1031150803,1016052079,1
3,01/02/2026,URBANO,CE0590001,4,3,1,105,10194,10425,504174,...,EG9,ET5M,SUP CCZ,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,KAREN LORENA BARRERA SERRANO,DIEGO ARTURO URIBE ROJAS,46678181,1031150803,1016052079,1
4,01/02/2026,URBANO,CE0590001,7,6,1,105,10194,10426,504181,...,EG10,ET5T,SUP CCZ,DIANA MARCELA AGUILERA MADRIGAL,WILSON ABEL TORRES FAJARDO,DIEGO ARTURO URIBE ROJAS,52737325,79565949,1016052079,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103952,28/02/2026,URBANO,KE1EAG025,2,2,36,105,10325,12719,502109,...,None,None,None,None,None,None,0,0,0,1
103953,28/02/2026,URBANO,KE1EAG026,1,1,35,112,10325,12719,254756,...,None,None,None,None,None,None,0,0,0,0
103954,28/02/2026,URBANO,KE1EAG026,2,2,35,112,10325,12713,254756,...,None,None,None,None,None,None,0,0,0,0
103955,28/02/2026,URBANO,KE1EAG029,1,1,42,105,10325,12713,502112,...,None,None,None,None,None,None,0,0,0,0
103956,28/02/2026,URBANO,KE1EAG029,2,2,42,105,10325,12719,502112,...,None,None,None,None,None,None,0,0,0,1

In [31]:
#Realizar tres copias para los datos del personal

iri_1 = iri.copy()
iri_2 = iri.copy()
iri_3 = iri.copy()

In [32]:
#Kilometros por regulador de control

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_1 = iri_1.groupby(['Fecha Viaje', 'reg_ccz']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

iri_1

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176
...,...,...,...,...
221,28/02/2026,MAICOL ALEXANDER PITA BLANCO,191,224
222,28/02/2026,MARTHA IBETH MARTIN MARTIN,10,12
223,28/02/2026,PAULA KATHERINE CANTOR SALAMANCA,8,10
224,28/02/2026,WILLIAM IGNACIO VALDERRAMA GONZALEZ,338,371
225,28/02/2026,WILLIAN HUMBERTO MUNAR GONZALEZ,7,7

In [33]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_2 = iri_2.groupby(['Fecha Viaje', 'reg_via']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

iri_2

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/02/2026,ADRIANA YANETH RAMIREZ GALVAN,355,389
1,01/02/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,70,99
2,01/02/2026,BETSY MILENA DE DIOS HUERFANO,54,78
3,01/02/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,16,24
4,01/02/2026,DIANA MARCELA AGUILERA MADRIGAL,31,62
...,...,...,...,...
721,28/02/2026,LUIS ARCESIO NAVARRETE VARGAS,45,63
722,28/02/2026,NINI JOHANNA MARTINEZ,95,165
723,28/02/2026,OSCAR EDUARDO DUARTE BAQUERO,19,37
724,28/02/2026,PABLO EMILIO GUERRERO LLANOS,64,77
725,28/02/2026,YNGRI YAMILY CASTILLO CRUZ,258,308

In [34]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_3 = iri_3.groupby(['Fecha Viaje', 'Supervisor']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_3.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

iri_3

   Fecha Viaje                         reg_ccz  Viaje Regular  Viaje Totales
0   01/02/2026        DIEGO ARTURO URIBE ROJAS           1722           2162
1   02/02/2026     CAMILO ANDRES LOPEZ PENAGOS            612            847
2   02/02/2026        DIEGO ARTURO URIBE ROJAS           1689           2429
3   03/02/2026     CAMILO ANDRES LOPEZ PENAGOS            585            865
4   03/02/2026        DIEGO ARTURO URIBE ROJAS           1684           2425
5   04/02/2026     CAMILO ANDRES LOPEZ PENAGOS            610            872
6   04/02/2026        DIEGO ARTURO URIBE ROJAS           1860           2554
7   05/02/2026     CAMILO ANDRES LOPEZ PENAGOS           2339           2827
8   05/02/2026        DIEGO ARTURO URIBE ROJAS            985           1162
9   06/02/2026     CAMILO ANDRES LOPEZ PENAGOS            515            758
10  06/02/2026        DIEGO ARTURO URIBE ROJAS           1747           2433
11  07/02/2026        DIEGO ARTURO URIBE ROJAS           1822           2368
12  08/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1943           2315
13  09/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1985           2659
14  09/02/2026        DIEGO ARTURO URIBE ROJAS            735            993
15  10/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1880           2528
16  10/02/2026        DIEGO ARTURO URIBE ROJAS            706            950
17  11/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1910           2595
18  11/02/2026        DIEGO ARTURO URIBE ROJAS            645            912
19  12/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1951           2581
20  12/02/2026        DIEGO ARTURO URIBE ROJAS            639            938
21  13/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1827           2508
22  13/02/2026        DIEGO ARTURO URIBE ROJAS            620            883
23  14/02/2026        DIEGO ARTURO URIBE ROJAS           2083           2571
24  15/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1897           2294
25  16/02/2026     CAMILO ANDRES LOPEZ PENAGOS            699            942
26  16/02/2026        DIEGO ARTURO URIBE ROJAS           2009           2632
27  17/02/2026     CAMILO ANDRES LOPEZ PENAGOS            722            944
28  17/02/2026        DIEGO ARTURO URIBE ROJAS           1885           2581
29  18/02/2026     CAMILO ANDRES LOPEZ PENAGOS            784           1021
30  18/02/2026        DIEGO ARTURO URIBE ROJAS           1936           2630
31  19/02/2026     CAMILO ANDRES LOPEZ PENAGOS           2137           2720
32  19/02/2026        DIEGO ARTURO URIBE ROJAS            830           1035
33  20/02/2026     CAMILO ANDRES LOPEZ PENAGOS            688            927
34  20/02/2026        DIEGO ARTURO URIBE ROJAS           2038           2641
35  21/02/2026        DIEGO ARTURO URIBE ROJAS           2219           2589
36  22/02/2026     CAMILO ANDRES LOPEZ PENAGOS           2026           2360
37  26/02/2026     CAMILO ANDRES LOPEZ PENAGOS           2004           2559
38  26/02/2026  LISETH GERALDINE GARCIA GARZÓN            652            966
39  27/02/2026     CAMILO ANDRES LOPEZ PENAGOS           1993           2597
40  27/02/2026  LISETH GERALDINE GARCIA GARZÓN            523            830
41  28/02/2026  LISETH GERALDINE GARCIA GARZÓN           1738           2310

In [35]:
#Consolidar los dos dataframe para validar fonias

regularidad = pd.concat([iri_1,iri_2, iri_3], ignore_index=True)

# Realizar la división y convertir a porcentaje
regularidad['IRI (%)'] = (regularidad['Viaje Regular'] / regularidad['Viaje Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
regularidad['Regularidad (%)'] = regularidad['IRI (%)'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
regularidad.rename(columns={'Fecha Viaje': 'Fecha'}, inplace=True)

regularidad

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83
...,...,...,...,...,...,...
989,26/02/2026,CAMILO ANDRES LOPEZ PENAGOS,2004,2559,78.311841,78
990,26/02/2026,LISETH GERALDINE GARCIA GARZÓN,652,966,67.494824,67
991,27/02/2026,CAMILO ANDRES LOPEZ PENAGOS,1993,2597,76.742395,77
992,27/02/2026,LISETH GERALDINE GARCIA GARZÓN,523,830,63.012048,63
993,28/02/2026,LISETH GERALDINE GARCIA GARZÓN,1738,2310,75.238095,75

Kilometros personal de control (SAE _ FMS)

In [36]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [37]:
#FMS

# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia
desglosados_fms['Fecha'] = pd.to_datetime(desglosados_fms['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
desglosados_fms['Fecha'] = desglosados_fms['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,0,41896,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98
1,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
2,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,0,0,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00
3,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,0,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,0,42019,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98

In [38]:
#Llevar tipo día a desglosados FMS

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Tipo dia'] = desglosados_fms.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia
0,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,41896,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98,Festivo
1,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00,Festivo
2,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,0,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00,Festivo
3,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,0,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00,Festivo
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,42019,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98,Festivo

In [39]:
# Función para obtener la letra inicial de cada palabra FMS
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
desglosados_fms['Tipo_dia'] = desglosados_fms['Tipo dia'].apply(obtener_letra_inicial)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98,Festivo,F
1,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00,Festivo,F
2,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00,Festivo,F
3,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00,Festivo,F
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98,Festivo,F

In [40]:
#Tipo de dato a entero FMS

desglosados_fms['Id Línea '] = desglosados_fms['Id Línea '].astype(int)
desglosados_fms['Ruta '] = desglosados_fms['Ruta '].astype(int)
desglosados_fms['KmEjecutado'] = desglosados_fms['KmEjecutado'].astype(int)
desglosados_fms['KmProgAd'] = desglosados_fms['KmProgAd'].astype(int)
desglosados_fms['KmElimado'] = desglosados_fms['KmElimado'].astype(int)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0194019-1-10425,AD0194019,1,1,1,10194,...,No,NaN,NaN,NaN,"3, 10",NaN,98.10,0.98,Festivo,F
1,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-1-12333,AD0261012,1,1,1,10261,...,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00,Festivo,F
2,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261012-2-12333,AD0261012,2,2,2,10261,...,No,NaN,NaN,NaN,"3, 5",NaN,0.00,0.00,Festivo,F
3,01/02/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260201-AD0261013-1-12333,AD0261013,1,1,1,10261,...,No,NaN,NaN,NaN,"3, 4",NaN,0.00,0.00,Festivo,F
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98,Festivo,F

In [41]:
# Filtrar todo lo que no sea vacío ni NaN
desglosados_fms = desglosados_fms[
    desglosados_fms['Hora Ini Teorica '].notna() & 
    (desglosados_fms['Hora Ini Teorica '].astype(str).str.strip() != "")
]

desglosados_fms

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98,Festivo,F
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,No,NaN,NaN,NaN,"3, 3",CDZ4,96.45,0.99,Festivo,F
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,No,NaN,NaN,NaN,"3, 4",CDZ4,97.98,0.98,Festivo,F
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,No,NaN,NaN,NaN,"3, 6",CDZ5,NaN,0.00,Festivo,F
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,No,NaN,NaN,NaN,"3, 7",CDZ5,NaN,0.00,Festivo,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109894,28/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260228-CO11C0009-23-10990,CO11C0009,23,24,23,10504,...,No,NaN,NaN,NaN,"2, 9",CDZ4,100.00,1.00,Sábado,S
109895,28/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260228-CO11C0009-24-10990,CO11C0009,24,25,24,10504,...,No,NaN,NaN,NaN,"2, 9",CDZ4,100.00,1.00,Sábado,S
109896,28/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260228-CO11C0009-25-10990,CO11C0009,25,26,25,10504,...,No,NaN,NaN,NaN,"2, 9",CDZ4,100.00,1.00,Sábado,S
109897,28/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260228-CO11C0009-26-10990,CO11C0009,26,27,26,10504,...,No,NaN,NaN,NaN,"2, 9",CDZ4,100.00,1.00,Sábado,S
109898,28/02/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260228-CO11C0009-27-10990,CO11C0009,27,28,27,10504,...,No,NaN,NaN,NaN,"2, 9",CDZ4,100.00,1.00,Sábado,S

In [42]:
# Extraer la hora y convertirla a entero FMS
desglosados_fms['Hora'] = desglosados_fms['Hora Ini Teorica '].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
desglosados_fms['Hora'] = desglosados_fms['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,NaN,NaN,NaN,"3, 2",CDZ4,98.39,0.98,Festivo,F,5
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,NaN,NaN,NaN,"3, 3",CDZ4,96.45,0.99,Festivo,F,7
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,NaN,NaN,NaN,"3, 4",CDZ4,97.98,0.98,Festivo,F,9
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,NaN,NaN,NaN,"3, 6",CDZ5,NaN,0.00,Festivo,F,11
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,NaN,NaN,NaN,"3, 7",CDZ5,NaN,0.00,Festivo,F,14

In [43]:
#Traer el turno de control FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,NaN,NaN,"3, 2",CDZ4,98.39,0.98,Festivo,F,5,ET3N
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,NaN,NaN,"3, 3",CDZ4,96.45,0.99,Festivo,F,7,ET5M
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,NaN,NaN,"3, 4",CDZ4,97.98,0.98,Festivo,F,9,ET5M
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,NaN,NaN,"3, 6",CDZ5,NaN,0.00,Festivo,F,11,ET5M
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,NaN,NaN,"3, 7",CDZ5,NaN,0.00,Festivo,F,14,ET5M

In [44]:
#Traer el turno de vía FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,NaN,"3, 2",CDZ4,98.39,0.98,Festivo,F,5,ET3N,None
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,NaN,"3, 3",CDZ4,96.45,0.99,Festivo,F,7,ET5M,EG9
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,NaN,"3, 4",CDZ4,97.98,0.98,Festivo,F,9,ET5M,EG9
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,NaN,"3, 6",CDZ5,NaN,0.00,Festivo,F,11,ET5M,EG9
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,NaN,"3, 7",CDZ5,NaN,0.00,Festivo,F,14,ET5M,EG9

In [45]:
#Traer el turno de supervisor FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_sup'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,"3, 2",CDZ4,98.39,0.98,Festivo,F,5,ET3N,None,SUP CCZ
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,"3, 3",CDZ4,96.45,0.99,Festivo,F,7,ET5M,EG9,SUP CCZ
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,"3, 4",CDZ4,97.98,0.98,Festivo,F,9,ET5M,EG9,SUP CCZ
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,"3, 6",CDZ5,NaN,0.00,Festivo,F,11,ET5M,EG9,SUP CCZ
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,"3, 7",CDZ5,NaN,0.00,Festivo,F,14,ET5M,EG9,SUP CCZ

In [46]:
#Traer el regulador de control según el turno FMS

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_ccz']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_via']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['supervisor'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,0.98,Festivo,F,5,ET3N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,DIEGO ARTURO URIBE ROJAS
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,0.99,Festivo,F,7,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,0.98,Festivo,F,9,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,0.00,Festivo,F,11,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,0.00,Festivo,F,14,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS

In [47]:
# Crear una nueva columna con la suma de las columnas kiloemtros planificados y adicionales FMS
desglosados_fms['Kilómetros Totales'] = desglosados_fms['KmProgAd']

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,Kilómetros Totales
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,Festivo,F,5,ET3N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,DIEGO ARTURO URIBE ROJAS,42706
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,Festivo,F,7,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,43656
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,Festivo,F,9,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,42706
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,Festivo,F,11,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,43656
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,Festivo,F,14,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,42706

In [48]:
# Realizar la división y convertir a porcentaje FMS
desglosados_fms['Kilómetros (%)'] = (desglosados_fms['KmEjecutado'] / desglosados_fms['Kilómetros Totales']) * 100

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,Kilómetros Totales,Kilómetros (%)
4,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-1-10425,CE0590001,1,2,1,10194,...,F,5,ET3N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,DIEGO ARTURO URIBE ROJAS,42706,98.391327
5,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-2-10426,CE0590001,2,3,2,10194,...,F,7,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,43656,99.351750
6,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-3-10425,CE0590001,3,4,3,10194,...,F,9,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,42706,97.981548
7,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-4-10426,CE0590001,4,5,4,10194,...,F,11,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,43656,0.000000
8,01/02/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260201-CE0590001-5-10425,CE0590001,5,6,5,10194,...,F,14,ET5M,EG9,SUP CCZ,KAREN LORENA BARRERA SERRANO,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,DIEGO ARTURO URIBE ROJAS,42706,0.000000

In [49]:
#Copias de los dataframes FMS

desglosados_fms1 = desglosados_fms.copy()
desglosados_fms2 = desglosados_fms.copy()
desglosados_fms3 = desglosados_fms.copy()

In [50]:
#Kilometros por regulador de control FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms1 = desglosados_fms1.groupby(['Fecha', 'reg_ccz']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

desglosados_fms1.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/02/2026,CATHERINE YISELL PRADA MORENO,6873212,5079458
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,6047144,4143172
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,1342435,1244258
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,2974427,2795894
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,9838835,8038619

In [51]:
#Kilometros por regulador de via FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms2 = desglosados_fms2.groupby(['Fecha', 'reg_via']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

desglosados_fms2.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/02/2026,ADRIANA YANETH RAMIREZ GALVAN,3080419,2978347
1,01/02/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,4127698,2882338
2,01/02/2026,BETSY MILENA DE DIOS HUERFANO,3756027,2562699
3,01/02/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,1471915,929039
4,01/02/2026,DIANA MARCELA AGUILERA MADRIGAL,2693020,1736739

In [52]:
#Kilometros por supervisor FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms3 = desglosados_fms3.groupby(['Fecha', 'supervisor']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms3.rename(columns={'supervisor': 'reg_ccz'}, inplace=True)

desglosados_fms3.head()

        Fecha                      reg_ccz  Kilómetros Totales  KmEjecutado
0  01/02/2026     DIEGO ARTURO URIBE ROJAS            65877231     51558521
1  02/02/2026  CAMILO ANDRES LOPEZ PENAGOS            36824849     25076346
2  02/02/2026     DIEGO ARTURO URIBE ROJAS            76947746     55511378
3  03/02/2026  CAMILO ANDRES LOPEZ PENAGOS            36824849     25386602
4  03/02/2026     DIEGO ARTURO URIBE ROJAS            76947746     54849705

In [53]:
#Consolidar los dos dataframe para validar KM FMS

kilometros_fms = pd.concat([desglosados_fms1,desglosados_fms2, desglosados_fms3], ignore_index=True)

# Realizar la división y convertir a porcentaje
kilometros_fms['Kilómetros (%)'] = (kilometros_fms['KmEjecutado'] / kilometros_fms['Kilómetros Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
kilometros_fms['Kilómetros (%)'] = kilometros_fms['Kilómetros (%)'].round(0).astype(int)

kilometros_fms.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/02/2026,CATHERINE YISELL PRADA MORENO,6873212,5079458,74
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,6047144,4143172,69
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,1342435,1244258,93
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,2974427,2795894,94
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,9838835,8038619,82

In [54]:
# Consolidar todos los DataFrames en uno solo

kilometros = pd.concat([kilometros_fms], ignore_index=True)

kilometros

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/02/2026,CATHERINE YISELL PRADA MORENO,6873212,5079458,74
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,6047144,4143172,69
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,1342435,1244258,93
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,2974427,2795894,94
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,9838835,8038619,82
...,...,...,...,...,...
989,26/02/2026,CAMILO ANDRES LOPEZ PENAGOS,76740501,59914478,78
990,26/02/2026,LISETH GERALDINE GARCIA GARZÓN,36711088,29388379,80
991,27/02/2026,CAMILO ANDRES LOPEZ PENAGOS,76740501,60955825,79
992,27/02/2026,LISETH GERALDINE GARCIA GARZÓN,36711088,24299813,66
993,28/02/2026,LISETH GERALDINE GARCIA GARZÓN,72956812,53260373,73

Indicadores de fonias de personal de control

In [55]:
#Traer el supervisor según el turno

def calcular_turno(nombre):
    
    filtro = (
        (base['RegC'] == nombre)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base.loc[filtro, 'RegControl'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['reg_ccz'] = fonias.apply(
    lambda row: calcular_turno(
        row['Nombre Usuario']
    ),
    axis=1
)

fonias

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:05:00,05:05:00,05:06:00,00:00:00,00:00:37,NaN,None
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:12:00,05:13:00,05:13:00,00:01:00,00:00:47,NaN,None
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,NaN,0.5,0.0,05:30:00,05:32:00,05:32:00,00:02:00,00:00:21,NaN,None
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,NaN,0.5,0.0,05:47:00,05:47:00,05:48:00,00:00:00,00:01:00,NaN,None
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:59:00,05:59:00,06:00:00,00:00:00,00:00:26,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36988,28/02/2026,70227,Si,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,NaN,0.5,0.0,18:31:00,18:32:00,18:33:00,00:01:00,00:00:40,NaN,None
36989,28/02/2026,70227,No,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,NaN,NaN,0.0,18:57:00,18:57:00,18:58:00,00:00:00,00:00:23,NaN,None
36990,28/02/2026,70227,No,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,NaN,NaN,0.0,18:58:00,18:58:00,18:58:00,00:00:00,00:00:18,NaN,None
36991,28/02/2026,70256,Si,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-1 Tierra Grata,20,CE0A50009,0.5,0.0,19:50:00,19:50:00,19:51:00,00:00:00,00:00:18,NaN,None
36992,28/02/2026,70248,Si,Llamada normal,0,EMEDINA_105,ESTEBAN MEDINA CAMILO,Llamada terminada por el tÃ©cnico de control,16-6 La Faena,20,CE0A50017,0.0,0.0,22:01:00,22:05:00,22:05:00,00:04:00,00:00:07,NaN,None

In [56]:
# Reemplazar valores vacíos y '(en blanco)' con '00:00:00' en las columnas 'TRM' y 'Duración'
fonias['TMR'] = fonias['TMR'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['Duración'] = fonias['Duración'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['No Asignado'] = fonias['No Asignado'].replace({'': 0, '(en blanco)': 0})

fonias

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:05:00,05:05:00,05:06:00,00:00:00,00:00:37,NaN,None
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:12:00,05:13:00,05:13:00,00:01:00,00:00:47,NaN,None
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,NaN,0.5,0.0,05:30:00,05:32:00,05:32:00,00:02:00,00:00:21,NaN,None
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,NaN,0.5,0.0,05:47:00,05:47:00,05:48:00,00:00:00,00:01:00,NaN,None
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,NaN,0.5,0.0,05:59:00,05:59:00,06:00:00,00:00:00,00:00:26,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36988,28/02/2026,70227,Si,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,NaN,0.5,0.0,18:31:00,18:32:00,18:33:00,00:01:00,00:00:40,NaN,None
36989,28/02/2026,70227,No,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,NaN,NaN,0.0,18:57:00,18:57:00,18:58:00,00:00:00,00:00:23,NaN,None
36990,28/02/2026,70227,No,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,NaN,NaN,0.0,18:58:00,18:58:00,18:58:00,00:00:00,00:00:18,NaN,None
36991,28/02/2026,70256,Si,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-1 Tierra Grata,20,CE0A50009,0.5,0.0,19:50:00,19:50:00,19:51:00,00:00:00,00:00:18,NaN,None
36992,28/02/2026,70248,Si,Llamada normal,0,EMEDINA_105,ESTEBAN MEDINA CAMILO,Llamada terminada por el tÃ©cnico de control,16-6 La Faena,20,CE0A50017,0.0,0.0,22:01:00,22:05:00,22:05:00,00:04:00,00:00:07,NaN,None

In [57]:
# Asegúrate de que todas las entradas sean cadenas de texto
fonias['TMR'] = fonias['TMR'].astype(str)
fonias['Duración'] = fonias['Duración'].astype(str)

# Convertir las columnas 'TRM' y 'Duración' a formato timedelta
fonias['TMR'] = pd.to_timedelta(fonias['TMR'], errors='coerce')
fonias['Duración'] = pd.to_timedelta(fonias['Duración'], errors='coerce')

# Convertir los tiempos a segundos
fonias['TMR_segundos'] = fonias['TMR'].dt.total_seconds()
fonias['Duración_segundos'] = fonias['Duración'].dt.total_seconds()

# Reemplazar los valores NaN con 0
fonias['TMR_segundos'].fillna(0, inplace=True)
fonias['Duración_segundos'].fillna(0, inplace=True)

# Pasar a enteros
fonias['TMR_segundos'] = fonias['TMR_segundos'].astype(int)
fonias['Duración_segundos'] = fonias['Duración_segundos'].astype(int)

# Mostrar el DataFrame resultante
fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\479846426.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\479846426.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['Duración_segundos'].fillna(0, inplace=True)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0.0,05:05:00,05:05:00,05:06:00,0 days 00:00:00,0 days 00:00:37,NaN,None,0,37
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0.0,05:12:00,05:13:00,05:13:00,0 days 00:01:00,0 days 00:00:47,NaN,None,60,47
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,0.0,05:30:00,05:32:00,05:32:00,0 days 00:02:00,0 days 00:00:21,NaN,None,120,21
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,0.0,05:47:00,05:47:00,05:48:00,0 days 00:00:00,0 days 00:01:00,NaN,None,0,60
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,0.0,05:59:00,05:59:00,06:00:00,0 days 00:00:00,0 days 00:00:26,NaN,None,0,26

In [58]:
#Llevar tipo día a fonias

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Tipo dia'] = fonias.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,05:05:00,05:05:00,05:06:00,0 days 00:00:00,0 days 00:00:37,NaN,None,0,37,Festivo
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,05:12:00,05:13:00,05:13:00,0 days 00:01:00,0 days 00:00:47,NaN,None,60,47,Festivo
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,05:30:00,05:32:00,05:32:00,0 days 00:02:00,0 days 00:00:21,NaN,None,120,21,Festivo
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,05:47:00,05:47:00,05:48:00,0 days 00:00:00,0 days 00:01:00,NaN,None,0,60,Festivo
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,05:59:00,05:59:00,06:00:00,0 days 00:00:00,0 days 00:00:26,NaN,None,0,26,Festivo

In [59]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
fonias['Tipo_dia'] = fonias['Tipo dia'].apply(obtener_letra_inicial)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,05:05:00,05:06:00,0 days 00:00:00,0 days 00:00:37,NaN,None,0,37,Festivo,F
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,05:13:00,05:13:00,0 days 00:01:00,0 days 00:00:47,NaN,None,60,47,Festivo,F
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,05:32:00,05:32:00,0 days 00:02:00,0 days 00:00:21,NaN,None,120,21,Festivo,F
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,05:47:00,05:48:00,0 days 00:00:00,0 days 00:01:00,NaN,None,0,60,Festivo,F
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,05:59:00,06:00:00,0 days 00:00:00,0 days 00:00:26,NaN,None,0,26,Festivo,F

In [60]:
# Extraer la hora y convertirla a entero

# las entradas sean cadenas de texto
fonias['Hora Petición'] = fonias['Hora Petición'].astype(str)

# Extraer la hora y convertirla a entero
fonias['Hora'] = fonias['Hora Petición'].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
fonias['Hora'] = fonias['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,05:06:00,0 days 00:00:00,0 days 00:00:37,NaN,None,0,37,Festivo,F,5
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,05:13:00,0 days 00:01:00,0 days 00:00:47,NaN,None,60,47,Festivo,F,5
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,05:32:00,0 days 00:02:00,0 days 00:00:21,NaN,None,120,21,Festivo,F,5
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,05:48:00,0 days 00:00:00,0 days 00:01:00,NaN,None,0,60,Festivo,F,5
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,06:00:00,0 days 00:00:00,0 days 00:00:26,NaN,None,0,26,Festivo,F,5

In [61]:
#Traer el turno de supervisor

def calcular_turno(Franja,Tipo_Dia):
    
    filtro = (
        
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Turno_sup'] = fonias.apply(
    lambda row: calcular_turno(
        
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:00,0 days 00:00:37,NaN,None,0,37,Festivo,F,5,SUP CCZ
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:01:00,0 days 00:00:47,NaN,None,60,47,Festivo,F,5,SUP CCZ
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,0 days 00:02:00,0 days 00:00:21,NaN,None,120,21,Festivo,F,5,SUP CCZ
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,0 days 00:00:00,0 days 00:01:00,NaN,None,0,60,Festivo,F,5,SUP CCZ
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:00,0 days 00:00:26,NaN,None,0,26,Festivo,F,5,SUP CCZ

In [62]:
#Traer el supervisor según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Supervisor'] = fonias.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:37,NaN,None,0,37,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:47,NaN,None,60,47,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,0 days 00:00:21,NaN,None,120,21,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,0 days 00:01:00,NaN,None,0,60,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:26,NaN,None,0,26,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS

In [63]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_ser = fonias.copy()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)

fonias_ser['Duración_segundos'].fillna(0, inplace=True)

fonias_ser

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\48388375.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\48388375.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:37,NaN,None,0,37,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:47,NaN,None,60,47,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,0 days 00:00:21,NaN,None,120,21,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,0 days 00:01:00,NaN,None,0,60,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:26,NaN,None,0,26,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36988,28/02/2026,70227,Si,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,...,0 days 00:00:40,NaN,None,60,40,Sábado,S,18,SUP CCZ,LISETH GERALDINE GARCIA GARZÓN
36989,28/02/2026,70227,No,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,...,0 days 00:00:23,NaN,None,0,23,Sábado,S,18,SUP CCZ,LISETH GERALDINE GARCIA GARZÓN
36990,28/02/2026,70227,No,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-4 El Muelle,0,...,0 days 00:00:18,NaN,None,0,18,Sábado,S,18,SUP CCZ,LISETH GERALDINE GARCIA GARZÓN
36991,28/02/2026,70256,Si,Llamada normal,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,16-1 Tierra Grata,20,...,0 days 00:00:18,NaN,None,0,18,Sábado,S,19,SUP CCZ,LISETH GERALDINE GARCIA GARZÓN
36992,28/02/2026,70248,Si,Llamada normal,0,EMEDINA_105,ESTEBAN MEDINA CAMILO,Llamada terminada por el tÃ©cnico de control,16-6 La Faena,20,...,0 days 00:00:07,NaN,None,240,7,Sábado,S,22,SUP CCZ,LISETH GERALDINE GARCIA GARZÓN

In [64]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_ser = fonias_ser.groupby(['Fecha', 'reg_ccz']).agg({
    'TMR_segundos':  mean_without_zeros,
    'Duración_segundos':  mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)
fonias_ser['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_ser['TMR_segundos'] = fonias_ser['TMR_segundos'].round(0).astype(int)
fonias_ser['Duración_segundos'] = fonias_ser['Duración_segundos'].round(0).astype(int)

fonias_ser.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\3888450677.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\3888450677.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,01/02/2026,PAULA KATHERINE CANTOR SALAMANCA,240,20,0.0
1,02/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,36,0.0
2,03/02/2026,PAULA KATHERINE CANTOR SALAMANCA,73,44,0.0
3,04/02/2026,PAULA KATHERINE CANTOR SALAMANCA,70,43,0.0
4,05/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,32,0.0

In [65]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_1 = fonias.copy()

fonias_1.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
263,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:37,NaN,None,0,37,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
264,01/02/2026,504221,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:47,NaN,None,60,47,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
265,01/02/2026,502133,Si,Prioritaria,0,MPITA_105,MAICOL PITA ALEXANDER BLANCO,Llamada terminada por el tÃ©cnico de control,SE10,0,...,0 days 00:00:21,NaN,None,120,21,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
266,01/02/2026,504176,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,466,0,...,0 days 00:01:00,NaN,None,0,60,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS
267,01/02/2026,504221,Si,Llamada normal,0,SCORREA_105,SONIA CORREA CONSTANZA RODRIGUEZ,Llamada terminada por el tÃ©cnico de control,402,0,...,0 days 00:00:26,NaN,None,0,26,Festivo,F,5,SUP CCZ,DIEGO ARTURO URIBE ROJAS

In [66]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_1 = fonias_1.groupby(['Fecha', 'Supervisor']).agg({
    'TMR_segundos': mean_without_zeros,
    'Duración_segundos': mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_1['TMR_segundos'].fillna(0, inplace=True)
fonias_1['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_1['TMR_segundos'] = fonias_1['TMR_segundos'].round(0).astype(int)
fonias_1['Duración_segundos'] = fonias_1['Duración_segundos'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
fonias_1.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

fonias_1.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\3334358817.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\3334358817.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['Duración_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,01/02/2026,DIEGO ARTURO URIBE ROJAS,77,46,0.0
1,02/02/2026,DIEGO ARTURO URIBE ROJAS,150,41,0.0
2,03/02/2026,DIEGO ARTURO URIBE ROJAS,103,44,0.0
3,04/02/2026,DIEGO ARTURO URIBE ROJAS,102,46,0.0
4,05/02/2026,CAMILO ANDRES LOPEZ PENAGOS,289,39,0.0

In [67]:
#Consolidar los dos dataframe para validar fonias

fonias_fin = pd.concat([fonias_ser, fonias_1], ignore_index=True)

fonias_fin

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,01/02/2026,PAULA KATHERINE CANTOR SALAMANCA,240,20,0.0
1,02/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,36,0.0
2,03/02/2026,PAULA KATHERINE CANTOR SALAMANCA,73,44,0.0
3,04/02/2026,PAULA KATHERINE CANTOR SALAMANCA,70,43,0.0
4,05/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,32,0.0
5,09/02/2026,PAULA KATHERINE CANTOR SALAMANCA,68,30,0.0
6,10/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,33,0.0
7,11/02/2026,PAULA KATHERINE CANTOR SALAMANCA,63,36,0.0
8,12/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,37,0.0
9,13/02/2026,PAULA KATHERINE CANTOR SALAMANCA,65,39,0.0
10,14/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,30,0.0
11,20/02/2026,PAULA KATHERINE CANTOR SALAMANCA,64,42,0.0
12,21/02/2026,PAULA KATHERINE CANTOR SALAMANCA,66,39,0.0
13,23/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,43,0.0
14,24/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,41,0.0
15,25/02/2026,PAULA KATHERINE CANTOR SALAMANCA,75,40,0.0
16,26/02/2026,PAULA KATHERINE CANTOR SALAMANCA,60,38,0.0
17,27/02/2026,PAULA KATHERINE CANTOR SALAMANCA,62,36,0.0
18,28/02/2026,PAULA KATHERINE CANTOR SALAMANCA,83,77,0.0
19,01/02/2026,DIEGO ARTURO URIBE ROJAS,77,46,0.0
20,02/02/2026,DIEGO ARTURO URIBE ROJAS,150,41,0.0
21,03/02/2026,DIEGO ARTURO URIBE ROJAS,103,44,0.0
22,04/02/2026,DIEGO ARTURO URIBE ROJAS,102,46,0.0
23,05/02/2026,CAMILO ANDRES LOPEZ PENAGOS,289,39,0.0
24,06/02/2026,CAMILO ANDRES LOPEZ PENAGOS,118,38,0.0
25,06/02/2026,DIEGO ARTURO URIBE ROJAS,89,42,0.0
26,07/02/2026,DIEGO ARTURO URIBE ROJAS,93,42,0.0
27,08/02/2026,CAMILO ANDRES LOPEZ PENAGOS,108,56,6.0
28,09/02/2026,CAMILO ANDRES LOPEZ PENAGOS,100,38,0.0
29,10/02/2026,CAMILO ANDRES LOPEZ PENAGOS,78,41,0.0
30,11/02/2026,CAMILO ANDRES LOPEZ PENAGOS,97,37,2.0
31,12/02/2026,CAMILO ANDRES LOPEZ PENAGOS,126,40,0.0
32,13/02/2026,CAMILO ANDRES LOPEZ PENAGOS,100,42,1.0
33,13/02/2026,DIEGO ARTURO URIBE ROJAS,95,40,0.0
34,14/02/2026,DIEGO ARTURO URIBE ROJAS,86,45,1.0
35,15/02/2026,CAMILO ANDRES LOPEZ PENAGOS,92,56,0.0
36,16/02/2026,DIEGO ARTURO URIBE ROJAS,130,34,0.0
37,17/02/2026,DIEGO ARTURO URIBE ROJAS,164,44,0.0
38,18/02/2026,DIEGO ARTURO URIBE ROJAS,77,40,0.0
39,19/02/2026,CAMILO ANDRES LOPEZ PENAGOS,78,43,0.0
40,20/02/2026,CAMILO ANDRES LOPEZ PENAGOS,66,61,0.0
41,20/02/2026,DIEGO ARTURO URIBE ROJAS,91,43,0.0
42,21/02/2026,DIEGO ARTURO URIBE ROJAS,116,44,0.0
43,22/02/2026,CAMILO ANDRES LOPEZ PENAGOS,87,56,0.0
44,26/02/2026,CAMILO ANDRES LOPEZ PENAGOS,85,37,0.0
45,27/02/2026,CAMILO ANDRES LOPEZ PENAGOS,97,41,0.0
46,27/02/2026,LISETH GERALDINE GARCIA GARZÓN,82,26,0.0
47,28/02/2026,LISETH GERALDINE GARCIA GARZÓN,83,42,0.0

Información de novedades

In [68]:
# Rellena los valores NaN en la columna
novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

# Convertir 'Nodo' a tipo entero
novedades['CODIGO OPERADOR'] = novedades['CODIGO OPERADOR'].astype(int)

novedades.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\2588241090.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1044260,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500159,19290239,LUIS HERNANDO CORTES DIAZ,OPERADOR PADRON HIBRIDO DUAL,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
1,1045566,28/02/2026,28/02/2026,1,Cambio de Turno Operativo,NaN,Patio Dorado,500029,19337415,ISRAEL MARTINEZ GONZALEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1045567,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500113,80800170,LUIS EDUARDO GRISALES GONZALEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
3,1045568,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500118,80512739,LEONARDO MONTOYA ARIAS,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
4,1045569,28/02/2026,28/02/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501149,80926723,OSCAR EMIRO BARRERA BERNAL,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-02-28 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [69]:
# Filtrar el DataFrame para obtener solo las filas donde 'CODIGO OPERADOR' sea diferente de 0
novedades = novedades[novedades['CODIGO OPERADOR'] == 0]

# Filtrar el DataFrame para eliminar las filas donde 'estado' es igual a 'Eliminada'
novedades = novedades[novedades['ESTADO'] != 'Eliminada']

novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
25,1046633,28/02/2026,28/02/2026,1,Retardo,NaN,Patio Dorado,0,1014228633,LEIDY ESTEFANIA BARRERO CHAVEZ,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,-30,NaN,NaN,2026-03-02 12:16:43 Se presenta a las 05:04 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL
26,1046636,28/02/2026,28/02/2026,1,Retardo,NaN,Patio Dorado,0,52521464,YNGRI YAMILY CASTILLO CRUZ,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,-30,NaN,NaN,2026-03-02 12:21:09 Se presenta a las 12:48 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL
27,1046637,28/02/2026,28/02/2026,1,Retardo,NaN,Patio Dorado,0,1030613263,JOHANA ANDREA GORDILLO CUBILLOS,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,-30,NaN,NaN,2026-03-02 12:21:47 Se presenta a las 13:24 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL
28,1046641,28/02/2026,28/02/2026,1,Retardo,NaN,Patio Dorado,0,1002185518,LUIS ARCESIO NAVARRETE VARGAS,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,-30,NaN,NaN,2026-03-02 12:39:38 Se presenta a las 13:06 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL
29,1046642,28/02/2026,28/02/2026,1,Retardo,NaN,Patio Dorado,0,53154005,ANGELA MIREYA RIAÑO PASITO,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,-30,NaN,NaN,2026-03-02 12:40:05 Se presenta a las 14:06 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL

In [70]:
#resumen por fecha y regulador según las novedades

# Crear columnas para cada tipo de novedad
novedades['Ausentismo'] = (novedades['TIPO NOVEDAD'] == 'Ausentismo').astype(int)
novedades['Retardo'] = (novedades['TIPO NOVEDAD'] == 'Retardo').astype(int)
novedades['Novedades'] = ~novedades['TIPO NOVEDAD'].isin(['Ausentismo', 'Retardo'])

# Agrupar por 'FECHA INICIAL' y 'REGULADOR', y contar las ocurrencias de cada tipo de novedad
novedades_fin = novedades.groupby(['FECHA INICIAL', 'EMPLEADO']).agg({
    'Ausentismo': 'sum',
    'Retardo': 'sum',
    'Novedades': 'sum'
}).reset_index()

# Renombrar la columna 'Supervisor' a 'reg_ccz'
novedades_fin.rename(columns={'FECHA INICIAL': 'Fecha'}, inplace=True)
novedades_fin.rename(columns={'EMPLEADO': 'reg_ccz'}, inplace=True)

# Mostrar el DataFrame resultante
novedades_fin.head()

,Fecha,reg_ccz,Ausentismo,Retardo,Novedades
0,01/02/2026,NANCY LORENA AVENDAÑO MORENO,1,0,0
1,02/02/2026,ANETH MAYERLI CHONTAL VILLARRAGA,0,1,0
2,02/02/2026,ANGELA MIREYA RIAÑO PASITO,0,1,0
3,02/02/2026,CARLOS FERNANDO MOLINA BONILLA,0,1,0
4,02/02/2026,HENRY OCTAVIO BENAVIDES RAMIREZ,0,1,0

Consolidar la data para validar la información

In [71]:
#copiar data de regularidad

indicadores = regularidad.copy()

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83

In [72]:
#llevar KMS a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (kilometros['Fecha'] == Fecha)&
        (kilometros['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not kilometros.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = kilometros.loc[filtro, 'Kilómetros (%)'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Kilómetros (%)'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%)
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59,74
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68,69
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92,93
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83,94
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83,82

In [73]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'TMR_segundos'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['TMR_segundos'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['TMR_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
indicadores['TMR_segundos'] = indicadores['TMR_segundos'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\679954610.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['TMR_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59,74,0
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68,69,0
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92,93,0
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83,94,0
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83,82,0

In [74]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'No Asignado'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['No Asignado'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['No Asignado'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['No Asignado'] = indicadores['No Asignado'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\3884926540.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['No Asignado'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59,74,0,0
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68,69,0,0
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92,93,0,0
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83,94,0,0
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83,82,0,0

In [75]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Ausentismo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Ausentismo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Ausentismo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Ausentismo'] = indicadores['Ausentismo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\2427483280.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Ausentismo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59,74,0,0,0
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68,69,0,0,0
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92,93,0,0,0
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83,94,0,0,0
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83,82,0,0,0

In [76]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Novedades'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Novedades'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Novedades'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Novedades'] = indicadores['Novedades'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\590017984.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Novedades'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59,74,0,0,0,0
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68,69,0,0,0,0
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92,93,0,0,0,0
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83,94,0,0,0,0
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83,82,0,0,0,0

In [77]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Retardo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Retardo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Retardo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Retardo'] = indicadores['Retardo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18040\3046602996.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Retardo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/02/2026,CATHERINE YISELL PRADA MORENO,96,164,58.536585,59,74,0,0,0,0,0
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,65,96,67.708333,68,69,0,0,0,0,0
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,116,126,92.063492,92,93,0,0,0,0,0
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,75,90,83.333333,83,94,0,0,0,0,0
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,146,176,82.954545,83,82,0,0,0,0,0

In [78]:
#Eliminar columnas que no se necesitan para el proceso

col_eliminar = ['Viaje Regular', 'Viaje Totales','IRI (%)']

indicadores= indicadores.drop(columns=col_eliminar)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/02/2026,CATHERINE YISELL PRADA MORENO,59,74,0,0,0,0,0
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,68,69,0,0,0,0,0
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,92,93,0,0,0,0,0
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,83,94,0,0,0,0,0
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,83,82,0,0,0,0,0

In [79]:
# Agrupar por 'reg_ccz' y contar los días únicos laborados
dias_laborados = indicadores.groupby('reg_ccz')['Fecha'].nunique()

# Crear una nueva columna en el DataFrame de indicadores con los días laborados
indicadores['Días Laborados'] = indicadores['reg_ccz'].map(dias_laborados)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,01/02/2026,CATHERINE YISELL PRADA MORENO,59,74,0,0,0,0,0,2
1,01/02/2026,EDGAR ALEJANDRO RIOS CARDOZO,68,69,0,0,0,0,0,2
2,01/02/2026,FRANCY LINNE TIMARAN CUESTA,92,93,0,0,0,0,0,6
3,01/02/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,83,94,0,0,0,0,0,6
4,01/02/2026,JOHN JAIRO ESPINOSA SANTA,83,82,0,0,0,0,0,15

In [80]:
# Agrupar por 'reg_ccz' y aplicar las funciones de agregación necesarias
indicadores_f = indicadores.groupby('reg_ccz').agg({
    'Regularidad (%)': 'mean',
    'Kilómetros (%)': 'mean',
    'TMR_segundos': 'mean',
    'No Asignado': 'sum',
    'Ausentismo': 'sum',
    'Novedades': 'sum',
    'Retardo': 'sum',
    'Días Laborados':'max'
}).reset_index()

# Redondear las columnas a 2 decimales
indicadores_f['Regularidad (%)'] = indicadores_f['Regularidad (%)'].round(0).astype(int)
indicadores_f['Kilómetros (%)'] = indicadores_f['Kilómetros (%)'].round(0).astype(int)
indicadores_f['TMR_segundos'] = indicadores_f['TMR_segundos'].round(0).astype(int)

# Mostrar el DataFrame resultante
indicadores_f.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17

In [81]:
#copia de la data de indicadores 

calificacion = indicadores_f.copy()

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17

In [82]:
# Definir la función para convertir la lógica de Excel a Python
def convertir_regularidad(valor):
    if valor >= 84:
        return 100
    elif 80 <= valor < 84:
        return 75
    elif 74 <= valor < 80:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Regularidad (%)'
calificacion['IRI'] = calificacion['Regularidad (%)'].apply(convertir_regularidad)

# Mostrar el DataFrame resultante con la nueva columna
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0

In [83]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_kilometros(valor):
    if valor >= 95:
        return 100
    elif 90 <= valor < 95:
        return 75
    elif 80 <= valor < 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['KM'] = calificacion['Kilómetros (%)'].apply(convertir_kilometros)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50

In [84]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_tmr(valor):
    if valor <= 60:
        return 100
    elif 60 < valor <= 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['Fonias'] = calificacion['TMR_segundos'].apply(convertir_tmr)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50,100
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0,100
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0,100
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0,100
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50,100

In [85]:
# Duplicar la columna 'No Asignado'
calificacion['No Asignado %'] = calificacion['No Asignado']

# Nombres a excluir
excluir_nombres = ['DIEGO ARTURO URIBE ROJAS', 'CAMILO ANDRES LOPEZ PENAGOS', 'LISETH GERALDINE GARCIA GARZÓN']

# Filtrar el DataFrame para excluir estos nombres
calificacion_filtrado = calificacion[~calificacion['reg_ccz'].isin(excluir_nombres)]

# Encontrar el valor máximo en la columna 'No Asignado Modificado' del DataFrame filtrado
max_no_asignado = calificacion_filtrado['No Asignado %'].max()

# Asignar 5 al valor máximo y 0 al resto
calificacion['No Asignado %'] = calificacion['No Asignado %'].apply(lambda x: 5 if x == max_no_asignado else 0)

# Mostrar el DataFrame resultante
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50,100,5
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0,100,5
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0,100,5
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0,100,5
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50,100,5

In [86]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_retardo(valor):
    if valor <= 0:
        return 100
    elif 1 >= valor <= 3:
        return 40
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Retardos'] = calificacion['Retardo'].apply(convertir_retardo)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50,100,5,100
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0,100,5,0
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0,100,5,100
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0,100,5,100
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50,100,5,100

In [87]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_novedades(valor):
    if valor <= 0:
        return 100
    elif valor == 1:
        return 75
    elif valor == 2:
        return 50
    elif valor == 3:
        return 25
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Novedades'] = calificacion['Novedades'].apply(convertir_novedades)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50,100,5,100,100
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0,100,5,0,100
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0,100,5,100,100
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0,100,5,100,100
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50,100,5,100,100

In [88]:
#Sumar las novedades retardos y novedades

calificacion['Novedad'] = ((calificacion['% Novedades'] + calificacion['% Retardos']) / 2).astype(int)

# Calcular el promedio de las columnas mencionadas
calificacion['Total Calificación'] = calificacion[['IRI', 'KM', 'Fonias','Novedad']].mean(axis=1)

# Convertir el resultado a enteros si es necesario
calificacion['Total Calificación'] = calificacion['Total Calificación'].astype(int)

calificacion['Total'] = calificacion['Total Calificación'] + calificacion['No Asignado %']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50,100,5,100,100,100,75,80
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0,100,5,0,100,50,37,42
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0,100,5,100,100,100,68,73
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0,100,5,100,100,100,50,55
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50,100,5,100,100,100,62,67

In [89]:
#Crear base auxiliar para llevar el cargo

base_personal = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/base_personal.csv', encoding='latin', delimiter=';')

base_personal.head()

                                Nombre                           Cargo
0     PAULA KATHERINE CANTOR SALAMANCA  REGULADOR EN CENTRO DE CONTROL
1         LUIS FERNANDO GONZALEZ REYES  REGULADOR EN CENTRO DE CONTROL
2         MAICOL ALEXANDER PITA BLANCO  REGULADOR EN CENTRO DE CONTROL
3  SANDRA CAROLINA VALERIANO SARMIENTO  REGULADOR EN CENTRO DE CONTROL
4                 ELICIA MONGUI DUARTE  REGULADOR EN CENTRO DE CONTROL

In [90]:
#Llevar el cargo a la base de calificacion

def calcular_turno(reg):
    
    filtro = (
        (base_personal['Nombre'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base_personal.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base_personal.loc[filtro, 'Cargo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
calificacion['Cargo'] = calificacion.apply(
    lambda row: calcular_turno(
        row['reg_ccz']
    ),
    axis=1
)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total,Cargo
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,50,100,5,100,100,100,75,80,REGULADOR EN CENTRO DE CONTROL
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,0,100,5,0,100,50,37,42,REGULADOR DE VÍA
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,0,100,5,100,100,100,68,73,REGULADOR DE VÍA
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,0,100,5,100,100,100,50,55,REGULADOR DE VÍA
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,50,100,5,100,100,100,62,67,REGULADOR DE VÍA

In [91]:
#Validación del 100% a que corresponde

# Calcular el 35% de las columnas 'IRI' y 'KM'
calificacion['IRI_35%'] = calificacion['IRI'] * 0.35
calificacion['KM_35%'] = calificacion['KM'] * 0.35
calificacion['fonias_20%'] = calificacion['Fonias'] * 0.20
calificacion['No Asignado_5%'] = calificacion['No Asignado %'] * 0.05
calificacion['Novedad_10%'] = calificacion['Novedad'] * 0.10


# Redondear las columnas a 2 decimales
calificacion['IRI_35%'] = calificacion['IRI_35%'].round(0).astype(int)
calificacion['KM_35%'] = calificacion['KM_35%'].round(0).astype(int)
calificacion['fonias_20%'] = calificacion['fonias_20%'].round(0).astype(int)
calificacion['No Asignado_5%'] =calificacion['No Asignado_5%'].round(2).astype(int)
calificacion['Novedad_10%'] =calificacion['Novedad_10%'].round(0).astype(int)

calificacion['Total_100%'] = calificacion['IRI_35%'] + calificacion['KM_35%'] + calificacion['fonias_20%'] + calificacion['No Asignado_5%'] + calificacion['Novedad_10%']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,...,Novedad,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,...,100,75,80,REGULADOR EN CENTRO DE CONTROL,18,18,20,0,10,66
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,...,50,37,42,REGULADOR DE VÍA,0,0,20,0,5,25
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,...,100,68,73,REGULADOR DE VÍA,26,0,20,0,10,56
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,...,100,50,55,REGULADOR DE VÍA,0,0,20,0,10,30
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,...,100,62,67,REGULADOR DE VÍA,0,18,20,0,10,48

In [92]:
# Total de días en el mes

# Calcular el 70% de los días laborados
umbral = 0.70 * total_dias_julio

# Revisar si los días laborados cumplen con la condición
calificacion['Cumple Condición'] = calificacion['Días Laborados'].apply(lambda x: 1 if x >= umbral else 0)

# Mostrar el DataFrame actualizado
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,...,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%,Cumple Condición
0,ADRIANA PATRICIA TELLEZ VARELA,78,89,0,0,0,0,0,13,50,...,75,80,REGULADOR EN CENTRO DE CONTROL,18,18,20,0,10,66,0
1,ADRIANA YANETH RAMIREZ GALVAN,69,78,0,0,0,0,2,23,0,...,37,42,REGULADOR DE VÍA,0,0,20,0,5,25,1
2,AMANDA LUCIA RODRIGUEZ ARAUJO,82,77,0,0,0,0,0,3,75,...,68,73,REGULADOR DE VÍA,26,0,20,0,10,56,0
3,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,69,75,0,0,0,0,0,24,0,...,50,55,REGULADOR DE VÍA,0,0,20,0,10,30,1
4,ANETH MAYERLI CHONTAL VILLARRAGA,72,82,0,0,0,0,0,17,0,...,62,67,REGULADOR DE VÍA,0,18,20,0,10,48,0

In [93]:
#Exportar archivo
calificacion.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/calificacion_{mes_i}.csv', index=False)

In [94]:
#Exportar archivo
indicadores.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/indicadores_{mes_i}.csv', index=False)

In [95]:
#Exportar archivo

kilometros.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/kilometros_{mes_i}.csv', index=False)

In [96]:
novedades_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/novedades_fin_{mes_i}.csv', index=False)

In [97]:
#Exportar archivo

fonias_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/fonias_{mes_i}.csv', index=False)

In [98]:
#Exportar archivo

iri.to_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python//regularidad_{mes_i}.csv", index=False)