In [9]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import re
import pyproj
import folium

In [10]:
#Filtros de fechas

dia_ivd = '20260501'
dia_fvd = '20260531'

dia_ias = '01-05-2026'
dia_fas = '31-05-2026'

dia_if = '2026-05-01'
dia_ff = '2026-05-31'

mes = 'Novedades_may26'

mes_i = 'may26'

total_dias_julio = 31

mes_c = 'May'

Importar archivos de viajes desglosados zonal y troncal, informes de regularidad de plataforma EIC

In [11]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/01 viajes_desglosados_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosado.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_zonal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_zonal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_zonal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,0,37292,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0
1,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,0,36477,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0
2,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [12]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/16 viajes_desglosados_alimentacion_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosadotroncal.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_troncal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_troncal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_troncal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0A60001-1-12553,CE0A60001,1,2,1,10502,...,0,14465,Si,NaN,NaN,NaN,"3, 1",CDZ4,100.0,1.0
1,1/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0A60001-2-12553,CE0A60001,2,3,2,10502,...,0,14465,No,NaN,NaN,NaN,"3, 1",CDZ4,100.0,1.0
2,1/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0A60001-3-12553,CE0A60001,3,4,3,10502,...,0,14465,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0A60001-4-12553,CE0A60001,4,5,4,10502,...,0,14465,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0A60001-5-12553,CE0A60001,5,6,5,10502,...,0,14465,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [13]:
# Consolidar todos los DataFrames en uno solo

desglosados_fms = pd.concat([desg_zonal_fms, desg_troncal_fms], ignore_index=True)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,0,37292,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0
1,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,0,36477,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0
2,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [14]:
desglosados_fms['Id Línea '] = (
    desglosados_fms['Id Línea ']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,0,37292,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0
1,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,0,36477,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0
2,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [15]:
desglosados_fms['KmEjecutado'] = (
    desglosados_fms['KmEjecutado']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,0,37292,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0
1,1/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,0,36477,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0
2,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [16]:
# Ruta de la carpeta que contiene los archivos de desglosados zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/Blogger/Asistencia/2026/{mes_c}'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ias}'
fecha_fin = f'{dia_fas}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:10]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%d-%m-%Y', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', delimiter=';',skiprows=2, low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            # Añadir una nueva columna 'Fecha' con la fecha extraída del nombre del archivo
            df['Fecha'] = fecha_archivo
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    asistencia = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    asistencia.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/asistencia_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,INES NATHALY DUQUE ALBAN,INES NATHALY,DUQUE ALBAN,PLA1,Portal Dorado,05:00:00,NaN,04:56:00,09:00:00,14:00:00,...,14:24:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-05-2026
1,GLORIA ESPERANZA MESA REYES,GLORIA ESPERANZA,MESA REYES,PLA3,Portal 80,06:00:00,NaN,05:55:00,09:00:00,14:00:00,...,14:29:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-05-2026
2,CAMILO ANDRES LOPEZ PENAGOS,CAMILO ANDRES,LOPEZ PENAGOS,SUP CCZ,Disponible CCZ,06:00:00,06:00:00,06:00:00,16:00:00,22:00:00,...,22:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-05-2026
3,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,ET4M,ET4M,06:00:00,NaN,05:50:00,08:00:00,14:00:00,...,14:30:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-05-2026
4,JENNY ALEXANDRA BERNAL BERNAL,JENNY ALEXANDRA,BERNAL BERNAL,ET8M-V,ET8M-V,06:00:00,NaN,05:50:00,08:00:00,14:00:00,...,14:31:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-05-2026

In [17]:
## Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia

# Convertir la columna 'Fecha' a tipo datetime
asistencia['Fecha'] = pd.to_datetime(asistencia['Fecha'], format='%d-%m-%Y')

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
asistencia['Fecha'] = asistencia['Fecha'].dt.strftime('%d/%m/%Y')

asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,INES NATHALY DUQUE ALBAN,INES NATHALY,DUQUE ALBAN,PLA1,Portal Dorado,05:00:00,NaN,04:56:00,09:00:00,14:00:00,...,14:24:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/05/2026
1,GLORIA ESPERANZA MESA REYES,GLORIA ESPERANZA,MESA REYES,PLA3,Portal 80,06:00:00,NaN,05:55:00,09:00:00,14:00:00,...,14:29:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/05/2026
2,CAMILO ANDRES LOPEZ PENAGOS,CAMILO ANDRES,LOPEZ PENAGOS,SUP CCZ,Disponible CCZ,06:00:00,06:00:00,06:00:00,16:00:00,22:00:00,...,22:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/05/2026
3,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,ET4M,ET4M,06:00:00,NaN,05:50:00,08:00:00,14:00:00,...,14:30:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/05/2026
4,JENNY ALEXANDRA BERNAL BERNAL,JENNY ALEXANDRA,BERNAL BERNAL,ET8M-V,ET8M-V,06:00:00,NaN,05:50:00,08:00:00,14:00:00,...,14:31:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/05/2026

In [18]:
#Archivo de novedades disciplinarias

novedades = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/{mes}.csv",encoding='latin', delimiter=';')

In [19]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
novedades['FECHA INICIAL'] = pd.to_datetime(novedades['FECHA INICIAL'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
novedades['FECHA INICIAL'] = novedades['FECHA INICIAL'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1057523,15/04/2026,15/04/2026,1,Ausentismo,PERMISO,Patio Dorado,NaN,1024489560,YERLI IRENE HERNANDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-09 08:42:09 PERMISO - PROCEDIMIENTO OD...,Por Aprobar,NaN
1,1058351,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501161.0,79453992,ALEXANDER GARAVITO HERNANDEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1058352,15/04/2026,15/04/2026,1,Cambio de Turno Operativo,NaN,Patio Dorado,501374.0,91538451,JESUS FLOREZ ALARCON,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
3,1058353,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501522.0,79904374,JOHN HENRY LEON QUIROGA,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
4,1058354,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,502645.0,79842026,MANUEL PISCO RODRIGUEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [20]:
#Archivos de regularidad de plataforma EIC

cerrado = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_cerrrado_{mes_i}.csv", delimiter=';')

etapa_1 = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_Etapa1_{mes_i}.csv", delimiter=';')

In [21]:
#Informes de turnos, tipo día, personal

turno_via = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_via_fms.csv", sep=';')

turno_sup = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_supervisor_fms.csv", sep=';')

tipo_dia = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Tipo día.csv", encoding='latin',delimiter=';')

personal = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Personal_id.csv",encoding='latin',delimiter=';')

turno_ccz = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_control_fms.csv", sep=';')

In [22]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [23]:
#Importar data de fonias

fonias = pd.read_excel ("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2023/fonias_fms.xlsx")

# Convertir la columna 'Fecha' a tipo datetime
fonias['Fecha'] = pd.to_datetime(fonias['Fecha'])

# Filtrar los valores mayores o iguales a la fecha indicada
fonias = fonias[(fonias['Fecha'] >= f'{dia_if}') & (fonias['Fecha'] <= f'{dia_ff}')]

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
fonias['Fecha'] = fonias['Fecha'].dt.strftime('%d/%m/%Y')

fonias.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18]
Index: []

In [24]:
#Crear dataframe para llevar el nombre a fonias

# Crear un diccionario con los datos
data = {
    'RegC': [
        'Luis Fernando Gonzalez', 'William Munar Gonzalez', 'Adriana Patricia Tellez',
        'Jose Antonio Castro Garcia', 'Rosa Tellez', 'Edith Patarroyo',
        'Laura Marcela Vargas Gutierrez', 'Francy Linnie Timaran Cuesta', 
        'Yerly Irene Hernandez Ariza', 'Anderson Mizar Mendoza', 'Jorge Medina Espinoza',
        'Esteban Camilo Medina', 'Sandra Carolina Valeriano', 'Julian Andres Sanchez Restrepo',
        'Karen Lorena Barrera', 'Bryan Guzman', 'Jinneth Alexandra Guzman',
        'Maicol Alexander Pita Blanco', 'Martha Ibeth Martin', 'John Jairo Espinosa Santa',
        'Elicia Mongui Duarte', 'Sonia Constanza Correa Rodriguez', 'Jenny Alexandra Bernal',
        'Norberto Niño Rodriguez', 'Wilson Torres Fajardo', 'William Ignacio Valderrama',
        'Camilo Andres Lopez Penagos', 'Raúl Fabián Romero Micán', 'Deisi Yanira Rojas Torres',
        'Paula Katherine Cantor Salamanca','Angela Mireya Riaño Pasito'
    ],
    'RegControl': [
        'LUIS FERNANDO GONZALEZ REYES', 'WILLIAN HUMBERTO MUNAR GONZALEZ', 
        'ADRIANA PATRICIA TELLEZ VARELA', 'JOSE ANTONIO CASTRO GARCIA', 
        'ROSA MARIELA TELLEZ NAVARRO', 'DORIS EDITH PATARROYO GORDO',
        'LAURA MARCELA VARGAS GUTIERREZ', 'FRANCY LINNE TIMARAN CUESTA', 
        'YERLI IRENE HERNÁNDEZ ARIZA', 'ANDERSON MIZAR MENDOZA', 
        'JORGE MEDINA ESPINOSA', 'ESTEBAN CAMILO MEDINA', 
        'SANDRA CAROLINA VALERIANO SARMIENTO', 'JULIAN ANDRES SANCHEZ RESTREPO', 
        'KAREN LORENA BARRERA SERRANO', 'BRYAN ANDRES GUZMAN ROJANO', 
        'JINETH ALEXANDRA GUZMAN HERNANDEZ', 'MAICOL ALEXANDER PITA BLANCO', 
        'MARTHA IBETH MARTIN MARTIN', 'JOHN JAIRO ESPINOSA SANTA', 
        'ELICIA MONGUI DUARTE', 'SONIA CONSTANZA CORREA RODRIGUEZ', 
        'JENNY ALEXANDRA BERNAL BERNAL', 'NORBERTO NIÑO RODRIGUEZ', 
        'WILSON ABEL TORRES FAJARDO', 'WILLIAM IGNACIO VALDERRAMA GONZALEZ', 
        'CAMILO ANDRES LOPEZ PENAGOS', 'RAUL FABIAN ROMERO MICAN', 
        'DEISY YANIRA ROJAS TORRES', 'PAULA KATHERINE CANTOR SALAMANCA',
        'ANGELA MIREYA RIAÑO PASITO'
    ]
}

# Convertir el diccionario a un DataFrame
base = pd.DataFrame(data)

# Mostrar el DataFrame
base

                                RegC                           RegControl
0             Luis Fernando Gonzalez         LUIS FERNANDO GONZALEZ REYES
1             William Munar Gonzalez      WILLIAN HUMBERTO MUNAR GONZALEZ
2            Adriana Patricia Tellez       ADRIANA PATRICIA TELLEZ VARELA
3         Jose Antonio Castro Garcia           JOSE ANTONIO CASTRO GARCIA
4                        Rosa Tellez          ROSA MARIELA TELLEZ NAVARRO
5                    Edith Patarroyo          DORIS EDITH PATARROYO GORDO
6     Laura Marcela Vargas Gutierrez       LAURA MARCELA VARGAS GUTIERREZ
7       Francy Linnie Timaran Cuesta          FRANCY LINNE TIMARAN CUESTA
8        Yerly Irene Hernandez Ariza          YERLI IRENE HERNÁNDEZ ARIZA
9             Anderson Mizar Mendoza               ANDERSON MIZAR MENDOZA
10             Jorge Medina Espinoza                JORGE MEDINA ESPINOSA
11             Esteban Camilo Medina                ESTEBAN CAMILO MEDINA
12         Sandra Carolina Valeriano  SANDRA CAROLINA VALERIANO SARMIENTO
13    Julian Andres Sanchez Restrepo       JULIAN ANDRES SANCHEZ RESTREPO
14              Karen Lorena Barrera         KAREN LORENA BARRERA SERRANO
15                      Bryan Guzman           BRYAN ANDRES GUZMAN ROJANO
16          Jinneth Alexandra Guzman    JINETH ALEXANDRA GUZMAN HERNANDEZ
17      Maicol Alexander Pita Blanco         MAICOL ALEXANDER PITA BLANCO
18               Martha Ibeth Martin           MARTHA IBETH MARTIN MARTIN
19         John Jairo Espinosa Santa            JOHN JAIRO ESPINOSA SANTA
20              Elicia Mongui Duarte                 ELICIA MONGUI DUARTE
21  Sonia Constanza Correa Rodriguez     SONIA CONSTANZA CORREA RODRIGUEZ
22            Jenny Alexandra Bernal        JENNY ALEXANDRA BERNAL BERNAL
23           Norberto Niño Rodriguez              NORBERTO NIÑO RODRIGUEZ
24             Wilson Torres Fajardo           WILSON ABEL TORRES FAJARDO
25        William Ignacio Valderrama  WILLIAM IGNACIO VALDERRAMA GONZALEZ
26       Camilo Andres Lopez Penagos          CAMILO ANDRES LOPEZ PENAGOS
27          Raúl Fabián Romero Micán             RAUL FABIAN ROMERO MICAN
28         Deisi Yanira Rojas Torres            DEISY YANIRA ROJAS TORRES
29  Paula Katherine Cantor Salamanca     PAULA KATHERINE CANTOR SALAMANCA
30        Angela Mireya Riaño Pasito           ANGELA MIREYA RIAÑO PASITO

Indicador de regularidad de personal de control

In [25]:
#consolidar iri con los datos de cerrado y etapa_1

iri = pd.concat([cerrado,etapa_1], ignore_index=True)

#Eliminar columnas 

col_eliminar = ['IdIRI', 'Estado', 'F. Inicio DP', 'F. Cierre DP','Operador Programado','Id Operador','Operador','Evidencia']

iri = iri.drop(columns=col_eliminar)

iri['Cantidad'] = 1

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,1/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,1,0,0.00,-0.07,104.000.000,1,0,1,1
1,1/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,12.88,-0.05,104.000.000,1,0,1,1
2,1/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,13.90,-0.13,104.000.000,1,0,1,1
3,1/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,14.12,0.05,150.000.000,1,0,1,1
4,1/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,13.05,-0.50,150.000.000,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,5/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,Con hora de Inicio LG SMART OPERATOR,0,0,22.07,3.15,300.000.000,0,0,1,1
32614,8/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,Con hora de Inicio LG SMART OPERATOR,0,0,31.85,12.20,200.000.000,0,0,1,1
32615,6/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,Con hora de Inicio LG SMART OPERATOR,0,0,7.75,0.57,85.714.286,1,0,1,1
32616,8/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.65,-0.57,60.000.000,1,0,1,1
32617,9/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,Con hora de Inicio LG SMART OPERATOR,0,0,28.95,0.68,150.000.000,0,0,1,1

In [26]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
iri['Fecha Viaje'] = pd.to_datetime(iri['Fecha Viaje'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
iri['Fecha Viaje'] = iri['Fecha Viaje'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,1,0,0.00,-0.07,104.000.000,1,0,1,1
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,12.88,-0.05,104.000.000,1,0,1,1
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,13.90,-0.13,104.000.000,1,0,1,1
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,14.12,0.05,150.000.000,1,0,1,1
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,Con hora de Inicio LG SMART OPERATOR,0,0,13.05,-0.50,150.000.000,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,Con hora de Inicio LG SMART OPERATOR,0,0,22.07,3.15,300.000.000,0,0,1,1
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,Con hora de Inicio LG SMART OPERATOR,0,0,31.85,12.20,200.000.000,0,0,1,1
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,Con hora de Inicio LG SMART OPERATOR,0,0,7.75,0.57,85.714.286,1,0,1,1
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,Con hora de Inicio LG SMART OPERATOR,0,0,5.65,-0.57,60.000.000,1,0,1,1
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,Con hora de Inicio LG SMART OPERATOR,0,0,28.95,0.68,150.000.000,0,0,1,1

In [27]:
#Convertir datos de columna Hora Teórica

# Expresión regular ajustada para extraer la hora
patron_hora = r'(\d{1,2}:\d{2}:\d{2}\s?[ap]\.?m\.?)'

# Aplicar la extracción de hora a la columna 'Hora Teórica'
iri['Hora'] = iri['Hora Teórica'].str.extract(patron_hora)

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,1,0,0.00,-0.07,104.000.000,1,0,1,1,NaN
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,0,0,12.88,-0.05,104.000.000,1,0,1,1,NaN
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,0,0,13.90,-0.13,104.000.000,1,0,1,1,NaN
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,0,0,14.12,0.05,150.000.000,1,0,1,1,NaN
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,0,0,13.05,-0.50,150.000.000,1,0,1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,0,0,22.07,3.15,300.000.000,0,0,1,1,NaN
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,0,0,31.85,12.20,200.000.000,0,0,1,1,NaN
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,0,0,7.75,0.57,85.714.286,1,0,1,1,NaN
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,0,0,5.65,-0.57,60.000.000,1,0,1,1,NaN
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,0,0,28.95,0.68,150.000.000,0,0,1,1,NaN

In [28]:
# Dividir la columna 'Hora Teórica' en 'Fecha' y 'Hora'
iri[['Fecha1', 'Hora']] = iri['Hora Teórica'].str.split(' ', n=1, expand=True)

# Mostrar el DataFrame resultante
iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,0,0.00,-0.07,104.000.000,1,0,1,1,4:08,1/05/2026
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,0,12.88,-0.05,104.000.000,1,0,1,1,4:34,1/05/2026
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,0,13.90,-0.13,104.000.000,1,0,1,1,5:00,1/05/2026
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,0,14.12,0.05,150.000.000,1,0,1,1,5:26,1/05/2026
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,0,13.05,-0.50,150.000.000,1,0,1,1,5:52,1/05/2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,0,22.07,3.15,300.000.000,0,0,1,1,NaN,NaN
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,0,31.85,12.20,200.000.000,0,0,1,1,NaN,NaN
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,0,7.75,0.57,85.714.286,1,0,1,1,10:38,6/05/2026
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,0,5.65,-0.57,60.000.000,1,0,1,1,3:43,8/05/2026
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,0,28.95,0.68,150.000.000,0,0,1,1,NaN,NaN

In [29]:
# Dividir la columna  en partes usando ':', y seleccionar la primera parte (horas)
iri['franja'] = iri['Hora'].str.split(':').str[0]

# Convertir la columna 'franja' a tipo entero
iri['franja'] = pd.to_numeric(iri['franja'], errors='coerce').astype('Int64')

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,0.00,-0.07,104.000.000,1,0,1,1,4:08,1/05/2026,4
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,12.88,-0.05,104.000.000,1,0,1,1,4:34,1/05/2026,4
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,13.90,-0.13,104.000.000,1,0,1,1,5:00,1/05/2026,5
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,14.12,0.05,150.000.000,1,0,1,1,5:26,1/05/2026,5
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,13.05,-0.50,150.000.000,1,0,1,1,5:52,1/05/2026,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,22.07,3.15,300.000.000,0,0,1,1,NaN,NaN,<NA>
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,31.85,12.20,200.000.000,0,0,1,1,NaN,NaN,<NA>
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,7.75,0.57,85.714.286,1,0,1,1,10:38,6/05/2026,10
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,5.65,-0.57,60.000.000,1,0,1,1,3:43,8/05/2026,3
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,28.95,0.68,150.000.000,0,0,1,1,NaN,NaN,<NA>

In [30]:
#Llevar ruta comercial a iri

def calcular_posicion(Linea):
    
    filtro = (
        (turno_via['Linea'] == Linea)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        ruta = turno_via.loc[filtro, 'Ruta'].iloc[0]
        return ruta  if not pd.isna(ruta) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Ruta_Comercial'] = iri.apply(
    lambda row: calcular_posicion(
        row['Linea SAE']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,-0.07,104.000.000,1,0,1,1,4:08,1/05/2026,4,1-1 Alamos
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,-0.05,104.000.000,1,0,1,1,4:34,1/05/2026,4,1-1 Alamos
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,-0.13,104.000.000,1,0,1,1,5:00,1/05/2026,5,1-1 Alamos
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,0.05,150.000.000,1,0,1,1,5:26,1/05/2026,5,1-1 Alamos
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,-0.50,150.000.000,1,0,1,1,5:52,1/05/2026,5,1-1 Alamos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,3.15,300.000.000,0,0,1,1,NaN,NaN,<NA>,DH209
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,12.20,200.000.000,0,0,1,1,NaN,NaN,<NA>,DH209
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,0.57,85.714.286,1,0,1,1,10:38,6/05/2026,10,614
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,-0.57,60.000.000,1,0,1,1,3:43,8/05/2026,3,740
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,0.68,150.000.000,0,0,1,1,NaN,NaN,<NA>,SE14

In [31]:
#Llevar tipo día a iri

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Tipo dia'] = iri.apply(
    lambda row: calcular_posicion(
        row['Fecha Viaje']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,104.000.000,1,0,1,1,4:08,1/05/2026,4,1-1 Alamos,Festivo
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,104.000.000,1,0,1,1,4:34,1/05/2026,4,1-1 Alamos,Festivo
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,104.000.000,1,0,1,1,5:00,1/05/2026,5,1-1 Alamos,Festivo
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,150.000.000,1,0,1,1,5:26,1/05/2026,5,1-1 Alamos,Festivo
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,150.000.000,1,0,1,1,5:52,1/05/2026,5,1-1 Alamos,Festivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,300.000.000,0,0,1,1,NaN,NaN,<NA>,DH209,Hábil
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,200.000.000,0,0,1,1,NaN,NaN,<NA>,DH209,Hábil
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,85.714.286,1,0,1,1,10:38,6/05/2026,10,614,Hábil
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,60.000.000,1,0,1,1,3:43,8/05/2026,3,740,Hábil
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,150.000.000,0,0,1,1,NaN,NaN,<NA>,SE14,Sábado

In [32]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
iri['Tipo_dia'] = iri['Tipo dia'].apply(obtener_letra_inicial)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,1,0,1,1,4:08,1/05/2026,4,1-1 Alamos,Festivo,F
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,1,0,1,1,4:34,1/05/2026,4,1-1 Alamos,Festivo,F
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,1,0,1,1,5:00,1/05/2026,5,1-1 Alamos,Festivo,F
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,1,0,1,1,5:26,1/05/2026,5,1-1 Alamos,Festivo,F
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,1,0,1,1,5:52,1/05/2026,5,1-1 Alamos,Festivo,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,0,0,1,1,NaN,NaN,<NA>,DH209,Hábil,H
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,0,0,1,1,NaN,NaN,<NA>,DH209,Hábil,H
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,1,0,1,1,10:38,6/05/2026,10,614,Hábil,H
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,1,0,1,1,3:43,8/05/2026,3,740,Hábil,H
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,0,0,1,1,NaN,NaN,<NA>,SE14,Sábado,S

In [33]:
#Traer el turno de reg_via

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,0,1,1,4:08,1/05/2026,4,1-1 Alamos,Festivo,F,None
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,0,1,1,4:34,1/05/2026,4,1-1 Alamos,Festivo,F,None
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,0,1,1,5:00,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,0,1,1,5:26,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,0,1,1,5:52,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,0,1,1,NaN,NaN,<NA>,DH209,Hábil,H,None
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,0,1,1,NaN,NaN,<NA>,DH209,Hábil,H,None
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,0,1,1,10:38,6/05/2026,10,614,Hábil,H,FT5
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,0,1,1,3:43,8/05/2026,3,740,Hábil,H,None
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,0,1,1,NaN,NaN,<NA>,SE14,Sábado,S,None

In [34]:
#Traer el turno de control

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,1,1,4:08,1/05/2026,4,1-1 Alamos,Festivo,F,None,ENLACE N
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,1,1,4:34,1/05/2026,4,1-1 Alamos,Festivo,F,None,ENLACE N
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,1,1,5:00,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,1,1,5:26,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,1,1,5:52,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,1,1,NaN,NaN,<NA>,DH209,Hábil,H,None,None
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,1,1,NaN,NaN,<NA>,DH209,Hábil,H,None,None
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,1,1,10:38,6/05/2026,10,614,Hábil,H,FT5,ET5M
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,1,1,3:43,8/05/2026,3,740,Hábil,H,None,ET3N
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,1,1,NaN,NaN,<NA>,SE14,Sábado,S,None,None

In [35]:
#Traer el turno de supervisor

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_Sup'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,1,4:08,1/05/2026,4,1-1 Alamos,Festivo,F,None,ENLACE N,SUP CCZ
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,1,4:34,1/05/2026,4,1-1 Alamos,Festivo,F,None,ENLACE N,SUP CCZ
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,1,5:00,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N,SUP CCZ
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,1,5:26,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N,SUP CCZ
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,1,5:52,1/05/2026,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N,SUP CCZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,1,NaN,NaN,<NA>,DH209,Hábil,H,None,None,None
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,1,NaN,NaN,<NA>,DH209,Hábil,H,None,None,None
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,1,10:38,6/05/2026,10,614,Hábil,H,FT5,ET5M,SUP AM
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,1,3:43,8/05/2026,3,740,Hábil,H,None,ET3N,SUP AM
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,1,NaN,NaN,<NA>,SE14,Sábado,S,None,None,None

In [36]:
#Traer el regulador según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['reg_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_via']
    ),
    axis=1
)

iri['reg_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_ccz']
    ),
    axis=1
)

iri['Supervisor'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_Sup']
    ),
    axis=1
)

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,4,1-1 Alamos,Festivo,F,None,ENLACE N,SUP CCZ,None,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,4,1-1 Alamos,Festivo,F,None,ENLACE N,SUP CCZ,None,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,5,1-1 Alamos,Festivo,F,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,<NA>,DH209,Hábil,H,None,None,None,None,None,None
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,<NA>,DH209,Hábil,H,None,None,None,None,None,None
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,10,614,Hábil,H,FT5,ET5M,SUP AM,BETSY MILENA DE DIOS HUERFANO,None,CAMILO ANDRES LOPEZ PENAGOS
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,3,740,Hábil,H,None,ET3N,SUP AM,None,DORIS EDITH PATARROYO GORDO,CAMILO ANDRES LOPEZ PENAGOS
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,<NA>,SE14,Sábado,S,None,None,None,None,None,None

In [37]:
#Llevar identificación al regulador

def calcular_posicion(Nombre_completo):
    
    filtro = (
        (personal['Nombre Completo'] == Nombre_completo)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not personal.loc[filtro].empty:
        # Obtener el primer valor
        personas = personal.loc[filtro, 'Identificación'].iloc[0]
        return  personas  if not pd.isna( personas ) else None  
    
    return 0  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Id_via'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_via']
    ),
    axis=1
)

iri['Id_ccz'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_ccz']
    ),
    axis=1
)

iri['Id_sup'] = iri.apply(
    lambda row: calcular_posicion(
        row['Supervisor']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,F,None,ENLACE N,SUP CCZ,None,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,0,79899304,1023870284
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,F,None,ENLACE N,SUP CCZ,None,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,0,79899304,1023870284
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,F,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,1030567617,79899304,1023870284
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,F,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,1030567617,79899304,1023870284
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,F,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,1030567617,79899304,1023870284

In [38]:
# Convertir 'Nodo' a tipo entero
iri['Viaje Regular'] = iri['Viaje Regular'].astype(int)

iri['Viaje Totales'] = iri['Viaje Regular']

iri

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup,Viaje Totales
0,01/05/2026,ALIMENTACION,CO11D0001,2,1,2,104,10504,10990,622,...,None,ENLACE N,SUP CCZ,None,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,0,79899304,1023870284,1
1,01/05/2026,ALIMENTACION,CO11D0001,3,2,2,104,10504,10990,622,...,None,ENLACE N,SUP CCZ,None,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,0,79899304,1023870284,1
2,01/05/2026,ALIMENTACION,CO11D0001,4,3,2,104,10504,10990,622,...,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,1030567617,79899304,1023870284,1
3,01/05/2026,ALIMENTACION,CO11D0001,5,4,2,104,10504,10990,622,...,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,1030567617,79899304,1023870284,1
4,01/05/2026,ALIMENTACION,CO11D0001,6,5,2,104,10504,10990,622,...,PLA1,ENLACE N,SUP CCZ,INES NATHALY DUQUE ALBAN,JOHN JAIRO ESPINOSA SANTA,CAMILO ANDRES LOPEZ PENAGOS,1030567617,79899304,1023870284,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32613,05/05/2026,URBANO,CE17BG021,1,1,29,105,10282,12852,504160,...,None,None,None,None,None,None,0,0,0,0
32614,08/05/2026,URBANO,CE17BG024,1,1,32,105,10282,12852,504283,...,None,None,None,None,None,None,0,0,0,0
32615,06/05/2026,URBANO,CE12D0036,4,3,36,105,10264,12328,504183,...,FT5,ET5M,SUP AM,BETSY MILENA DE DIOS HUERFANO,None,CAMILO ANDRES LOPEZ PENAGOS,0,0,1023870284,1
32616,08/05/2026,URBANO,CE1600008,2,1,8,105,10184,12774,504372,...,None,ET3N,SUP AM,None,DORIS EDITH PATARROYO GORDO,CAMILO ANDRES LOPEZ PENAGOS,0,52980742,1023870284,1
32617,09/05/2026,URBANO,CE16CG020,1,1,37,105,10350,12739,507042,...,None,None,None,None,None,None,0,0,0,0

In [39]:
#Realizar tres copias para los datos del personal

iri_1 = iri.copy()
iri_2 = iri.copy()
iri_3 = iri.copy()

In [40]:
#Kilometros por regulador de control

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_1 = iri_1.groupby(['Fecha Viaje', 'reg_ccz']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

iri_1

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48
5,01/05/2026,SONIA CONSTANZA CORREA RODRIGUEZ,197,200
6,02/05/2026,DORIS EDITH PATARROYO GORDO,10,13
7,02/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,50,51
8,02/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,10,11
9,02/05/2026,LAURA MARCELA VARGAS GUTIERREZ,220,236
10,02/05/2026,LUIS FERNANDO GONZALEZ REYES,361,372
11,02/05/2026,RAUL FABIAN ROMERO MICAN,6,6
12,03/05/2026,ANGELA MIREYA RIAÑO PASITO,255,267
13,03/05/2026,DORIS EDITH PATARROYO GORDO,32,34
14,03/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,118,130
15,03/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,46,47
16,03/05/2026,LAURA MARCELA VARGAS GUTIERREZ,190,200
17,03/05/2026,RAUL FABIAN ROMERO MICAN,83,94
18,04/05/2026,DORIS EDITH PATARROYO GORDO,125,167
19,04/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,147,158
20,04/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,105,134
21,04/05/2026,RAUL FABIAN ROMERO MICAN,213,281
22,05/05/2026,DORIS EDITH PATARROYO GORDO,127,164
23,05/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,138,160
24,05/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,94,128
25,05/05/2026,RAUL FABIAN ROMERO MICAN,220,279
26,06/05/2026,DORIS EDITH PATARROYO GORDO,117,165
27,06/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,137,157
28,06/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,99,126
29,06/05/2026,RAUL FABIAN ROMERO MICAN,224,282
30,07/05/2026,DORIS EDITH PATARROYO GORDO,137,166
31,07/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,144,162
32,07/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,111,133
33,07/05/2026,RAUL FABIAN ROMERO MICAN,234,278
34,08/05/2026,DORIS EDITH PATARROYO GORDO,133,166
35,08/05/2026,JIMMY ALEXANDER CARABALLO DIAZ,131,153
36,08/05/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,102,128
37,08/05/2026,RAUL FABIAN ROMERO MICAN,215,277
38,09/05/2026,ANGELA MIREYA RIAÑO PASITO,7,10
39,09/05/2026,LAURA MARCELA VARGAS GUTIERREZ,226,229
40,09/05/2026,MARTHA IBETH MARTIN MARTIN,8,9
41,09/05/2026,SANDRA CAROLINA VALERIANO SARMIENTO,5,5
42,09/05/2026,SONIA CONSTANZA CORREA RODRIGUEZ,324,344
43,09/05/2026,WILLIAM IGNACIO VALDERRAMA GONZALEZ,47,50
44,10/05/2026,ANGELA MIREYA RIAÑO PASITO,27,30
45,10/05/2026,JOHN JAIRO ESPINOSA SANTA,239,251
46,10/05/2026,MARTHA IBETH MARTIN MARTIN,46,47
47,10/05/2026,PAULA KATHERINE CANTOR SALAMANCA,172,183
48,10/05/2026,SANDRA CAROLINA VALERIANO SARMIENTO,62,77
49,10/05/2026,WILLIAM IGNACIO VALDERRAMA GONZALEZ,115,122

In [41]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_2 = iri_2.groupby(['Fecha Viaje', 'reg_via']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

iri_2

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/05/2026,ALEXANDRA MARTINEZ TAPIA,86,101
1,01/05/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,36,40
2,01/05/2026,ANETH MAYERLI CHONTAL VILLARRAGA,77,104
3,01/05/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,267,271
4,01/05/2026,DIANA CAROLINA ROJAS DIAZ,64,80
...,...,...,...,...
209,10/05/2026,LUIS ALBERTO MOLANO BALLESTEROS,24,27
210,10/05/2026,LUIS ARCESIO NAVARRETE VARGAS,93,115
211,10/05/2026,MARYORY BASABE CASTILLO,34,40
212,10/05/2026,MAYERLI AVILA GOMEZ,7,9
213,10/05/2026,OSCAR EDUARDO DUARTE BAQUERO,45,58

In [42]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_3 = iri_3.groupby(['Fecha Viaje', 'Supervisor']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_3.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

iri_3

   Fecha Viaje                      reg_ccz  Viaje Regular  Viaje Totales
0   01/05/2026  CAMILO ANDRES LOPEZ PENAGOS           2030           2312
1   02/05/2026     DIEGO ARTURO URIBE ROJAS           2331           2696
2   03/05/2026     DIEGO ARTURO URIBE ROJAS           2099           2381
3   04/05/2026  CAMILO ANDRES LOPEZ PENAGOS           2006           2464
4   04/05/2026     DIEGO ARTURO URIBE ROJAS            697            908
5   05/05/2026  CAMILO ANDRES LOPEZ PENAGOS           1941           2392
6   05/05/2026     DIEGO ARTURO URIBE ROJAS            693            908
7   06/05/2026  CAMILO ANDRES LOPEZ PENAGOS           1776           2295
8   06/05/2026     DIEGO ARTURO URIBE ROJAS            750            941
9   07/05/2026  CAMILO ANDRES LOPEZ PENAGOS           2002           2394
10  07/05/2026     DIEGO ARTURO URIBE ROJAS            702            913
11  08/05/2026  CAMILO ANDRES LOPEZ PENAGOS           1931           2394
12  08/05/2026     DIEGO ARTURO URIBE ROJAS            607            840
13  09/05/2026     DIEGO ARTURO URIBE ROJAS           1725           2148
14  10/05/2026  CAMILO ANDRES LOPEZ PENAGOS           1737           2028

In [43]:
#Consolidar los dos dataframe para validar fonias

regularidad = pd.concat([iri_1,iri_2, iri_3], ignore_index=True)

# Realizar la división y convertir a porcentaje
regularidad['IRI (%)'] = (regularidad['Viaje Regular'] / regularidad['Viaje Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
regularidad['Regularidad (%)'] = regularidad['IRI (%)'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
regularidad.rename(columns={'Fecha Viaje': 'Fecha'}, inplace=True)

regularidad

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94
...,...,...,...,...,...,...
274,07/05/2026,DIEGO ARTURO URIBE ROJAS,702,913,76.889376,77
275,08/05/2026,CAMILO ANDRES LOPEZ PENAGOS,1931,2394,80.659983,81
276,08/05/2026,DIEGO ARTURO URIBE ROJAS,607,840,72.261905,72
277,09/05/2026,DIEGO ARTURO URIBE ROJAS,1725,2148,80.307263,80
278,10/05/2026,CAMILO ANDRES LOPEZ PENAGOS,1737,2028,85.650888,86

Kilometros personal de control (SAE _ FMS)

In [44]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [45]:
#FMS

# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia
desglosados_fms['Fecha'] = pd.to_datetime(desglosados_fms['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
desglosados_fms['Fecha'] = desglosados_fms['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,0,37292,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0
1,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,0,36477,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [46]:
#Llevar tipo día a desglosados FMS

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Tipo dia'] = desglosados_fms.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia
0,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,37292,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0,Festivo
1,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,36477,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0,Festivo
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo

In [47]:
# Función para obtener la letra inicial de cada palabra FMS
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
desglosados_fms['Tipo_dia'] = desglosados_fms['Tipo dia'].apply(obtener_letra_inicial)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0,Festivo,F
1,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0,Festivo,F
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F

In [48]:
#Tipo de dato a entero FMS

desglosados_fms['Id Línea '] = desglosados_fms['Id Línea '].astype(int)
desglosados_fms['Ruta '] = desglosados_fms['Ruta '].astype(int)
desglosados_fms['KmEjecutado'] = desglosados_fms['KmEjecutado'].astype(int)
desglosados_fms['KmProgAd'] = desglosados_fms['KmProgAd'].astype(int)
desglosados_fms['KmElimado'] = desglosados_fms['KmElimado'].astype(int)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0292021-1-12789,AD0292021,1,1,1,10292,...,No,NaN,NaN,NaN,"3, 10",NaN,100.0,1.0,Festivo,F
1,01/05/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260501-AD0311008-1-12730,AD0311008,1,1,1,10311,...,No,NaN,NaN,NaN,"3, 6",NaN,100.0,1.0,Festivo,F
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F

In [49]:
# Filtrar todo lo que no sea vacío ni NaN
desglosados_fms = desglosados_fms[
    desglosados_fms['Hora Ini Teorica '].notna() & 
    (desglosados_fms['Hora Ini Teorica '].astype(str).str.strip() != "")
]

desglosados_fms

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,No,NaN,NaN,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39714,11/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260511-CO11B0012-20-12440,CO11B0012,20,21,20,10527,...,No,NaN,NaN,NaN,"1, 7",CDZ4,100.0,1.0,Hábil,H
39715,11/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260511-CO11B0012-21-12440,CO11B0012,21,22,21,10527,...,No,NaN,NaN,NaN,"1, 7",CDZ4,100.0,1.0,Hábil,H
39716,11/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260511-CO11B0012-22-12440,CO11B0012,22,23,22,10527,...,No,NaN,NaN,NaN,"1, 8",CDZ4,100.0,1.0,Hábil,H
39717,11/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260511-CO11B0012-23-12440,CO11B0012,23,24,23,10527,...,No,NaN,NaN,NaN,"1, 8",CDZ4,100.0,1.0,Hábil,H
39718,11/05/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260511-CO11B0012-24-12440,CO11B0012,24,25,24,10527,...,No,NaN,NaN,NaN,"1, 8",CDZ4,100.0,1.0,Hábil,H

In [50]:
# Extraer la hora y convertirla a entero FMS
desglosados_fms['Hora'] = desglosados_fms['Hora Ini Teorica '].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
desglosados_fms['Hora'] = desglosados_fms['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,6
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,7
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,NaN,NaN,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F,7

In [51]:
#Traer el turno de control FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,ET1N
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,ET1N
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,6,ET3M
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,7,ET3M
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,NaN,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F,7,ET3M

In [52]:
#Traer el turno de vía FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,ET1N,None
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,ET1N,None
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,6,ET3M,EG23
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,7,ET3M,EG23
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F,7,ET3M,EG23

In [53]:
#Traer el turno de supervisor FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_sup'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,ET1N,None,SUP CCZ
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,ET1N,None,SUP CCZ
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,"3, 3",CDZ4,100.0,1.0,Festivo,F,6,ET3M,EG23,SUP CCZ
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,"3, 3",CDZ4,100.0,1.0,Festivo,F,7,ET3M,EG23,SUP CCZ
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,"3, 4",CDZ4,100.0,1.0,Festivo,F,7,ET3M,EG23,SUP CCZ

In [54]:
#Traer el regulador de control según el turno FMS

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_ccz']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_via']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['supervisor'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,1.0,Festivo,F,5,ET1N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,CAMILO ANDRES LOPEZ PENAGOS
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,1.0,Festivo,F,5,ET1N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,CAMILO ANDRES LOPEZ PENAGOS
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,1.0,Festivo,F,6,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,1.0,Festivo,F,7,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,1.0,Festivo,F,7,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS

In [55]:
# Crear una nueva columna con la suma de las columnas kiloemtros planificados y adicionales FMS
desglosados_fms['Kilómetros Totales'] = desglosados_fms['KmProgAd']

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo dia,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,Kilómetros Totales
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Festivo,F,5,ET1N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,CAMILO ANDRES LOPEZ PENAGOS,10904
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,Festivo,F,5,ET1N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,CAMILO ANDRES LOPEZ PENAGOS,10904
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,Festivo,F,6,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,10904
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,Festivo,F,7,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,10904
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,Festivo,F,7,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,10904

In [56]:
# Realizar la división y convertir a porcentaje FMS
desglosados_fms['Kilómetros (%)'] = (desglosados_fms['KmEjecutado'] / desglosados_fms['Kilómetros Totales']) * 100

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo_dia,Hora,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,Kilómetros Totales,Kilómetros (%)
2,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-1-10533,CE0650001,1,2,1,10266,...,F,5,ET1N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,CAMILO ANDRES LOPEZ PENAGOS,10904,100.0
3,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-2-10533,CE0650001,2,3,2,10266,...,F,5,ET1N,None,SUP CCZ,ROSA MARIELA TELLEZ NAVARRO,None,CAMILO ANDRES LOPEZ PENAGOS,10904,100.0
4,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-3-10533,CE0650001,3,4,3,10266,...,F,6,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,10904,100.0
5,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-4-10533,CE0650001,4,5,4,10266,...,F,7,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,10904,100.0
6,01/05/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260501-CE0650001-5-10533,CE0650001,5,6,5,10266,...,F,7,ET3M,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,10904,100.0

In [57]:
#Copias de los dataframes FMS

desglosados_fms1 = desglosados_fms.copy()
desglosados_fms2 = desglosados_fms.copy()
desglosados_fms3 = desglosados_fms.copy()

In [58]:
#Kilometros por regulador de control FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms1 = desglosados_fms1.groupby(['Fecha', 'reg_ccz']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

desglosados_fms1.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/05/2026,ESTEBAN CAMILO MEDINA,2941615,2845795
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,1342435,1324012
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,1216946,1155656
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,2772366,2707586
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,2038394,1964480

In [59]:
#Kilometros por regulador de via FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms2 = desglosados_fms2.groupby(['Fecha', 'reg_via']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

desglosados_fms2.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/05/2026,ALEXANDRA MARTINEZ TAPIA,5328456,4567967
1,01/05/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,1144554,1066552
2,01/05/2026,ANETH MAYERLI CHONTAL VILLARRAGA,4088852,3129463
3,01/05/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,2158343,2127534
4,01/05/2026,DIANA CAROLINA ROJAS DIAZ,2804703,2361917

In [60]:
#Kilometros por supervisor FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms3 = desglosados_fms3.groupby(['Fecha', 'supervisor']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms3.rename(columns={'supervisor': 'reg_ccz'}, inplace=True)

desglosados_fms3.head()

        Fecha                      reg_ccz  Kilómetros Totales  KmEjecutado
0  01/05/2026  CAMILO ANDRES LOPEZ PENAGOS            65852471     56997088
1  02/05/2026     DIEGO ARTURO URIBE ROJAS            73039855     66757920
2  03/05/2026     DIEGO ARTURO URIBE ROJAS            65852471     60383284
3  04/05/2026  CAMILO ANDRES LOPEZ PENAGOS            76626735     65956683
4  04/05/2026     DIEGO ARTURO URIBE ROJAS            36790654     30259427

In [61]:
#Consolidar los dos dataframe para validar KM FMS

kilometros_fms = pd.concat([desglosados_fms1,desglosados_fms2, desglosados_fms3], ignore_index=True)

# Realizar la división y convertir a porcentaje
kilometros_fms['Kilómetros (%)'] = (kilometros_fms['KmEjecutado'] / kilometros_fms['Kilómetros Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
kilometros_fms['Kilómetros (%)'] = kilometros_fms['Kilómetros (%)'].round(0).astype(int)

kilometros_fms.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/05/2026,ESTEBAN CAMILO MEDINA,2941615,2845795,97
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,1342435,1324012,99
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,1216946,1155656,95
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,2772366,2707586,98
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,2038394,1964480,96

In [62]:
# Consolidar todos los DataFrames en uno solo

kilometros = pd.concat([kilometros_fms], ignore_index=True)

kilometros

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/05/2026,ESTEBAN CAMILO MEDINA,2941615,2845795,97
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,1342435,1324012,99
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,1216946,1155656,95
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,2772366,2707586,98
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,2038394,1964480,96
...,...,...,...,...,...
304,08/05/2026,DIEGO ARTURO URIBE ROJAS,36790654,27807127,76
305,09/05/2026,DIEGO ARTURO URIBE ROJAS,73039855,54085951,74
306,10/05/2026,CAMILO ANDRES LOPEZ PENAGOS,65852471,54922271,83
307,11/05/2026,CAMILO ANDRES LOPEZ PENAGOS,35140092,32079590,91
308,11/05/2026,LISETH GERALDINE GARCIA GARZÓN,74013475,64327867,87

Indicadores de fonias de personal de control

In [63]:
#Traer el supervisor según el turno

def calcular_turno(nombre):
    
    filtro = (
        (base['RegC'] == nombre)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base.loc[filtro, 'RegControl'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['reg_ccz'] = fonias.apply(
    lambda row: calcular_turno(
        row['Nombre Usuario']
    ),
    axis=1
)

fonias

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz]
Index: []

In [64]:
# Reemplazar valores vacíos y '(en blanco)' con '00:00:00' en las columnas 'TRM' y 'Duración'
fonias['TMR'] = fonias['TMR'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['Duración'] = fonias['Duración'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['No Asignado'] = fonias['No Asignado'].replace({'': 0, '(en blanco)': 0})

fonias

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz]
Index: []

In [65]:
# Asegúrate de que todas las entradas sean cadenas de texto
fonias['TMR'] = fonias['TMR'].astype(str)
fonias['Duración'] = fonias['Duración'].astype(str)

# Convertir las columnas 'TRM' y 'Duración' a formato timedelta
fonias['TMR'] = pd.to_timedelta(fonias['TMR'], errors='coerce')
fonias['Duración'] = pd.to_timedelta(fonias['Duración'], errors='coerce')

# Convertir los tiempos a segundos
fonias['TMR_segundos'] = fonias['TMR'].dt.total_seconds()
fonias['Duración_segundos'] = fonias['Duración'].dt.total_seconds()

# Reemplazar los valores NaN con 0
fonias['TMR_segundos'].fillna(0, inplace=True)
fonias['Duración_segundos'].fillna(0, inplace=True)

# Pasar a enteros
fonias['TMR_segundos'] = fonias['TMR_segundos'].astype(int)
fonias['Duración_segundos'] = fonias['Duración_segundos'].astype(int)

# Mostrar el DataFrame resultante
fonias.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\479846426.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\479846426.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['Duración_segundos'].fillna(0, inplace=True)

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos]
Index: []

[0 rows x 22 columns]

In [66]:
#Llevar tipo día a fonias

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Tipo dia'] = fonias.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

fonias.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia]
Index: []

[0 rows x 23 columns]

In [67]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
fonias['Tipo_dia'] = fonias['Tipo dia'].apply(obtener_letra_inicial)

fonias.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia, Tipo_dia]
Index: []

[0 rows x 24 columns]

In [68]:
# Extraer la hora y convertirla a entero

# las entradas sean cadenas de texto
fonias['Hora Petición'] = fonias['Hora Petición'].astype(str)

# Extraer la hora y convertirla a entero
fonias['Hora'] = fonias['Hora Petición'].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
fonias['Hora'] = fonias['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
fonias.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia, Tipo_dia, Hora]
Index: []

[0 rows x 25 columns]

In [69]:
#Traer el turno de supervisor

def calcular_turno(Franja,Tipo_Dia):
    
    filtro = (
        
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Turno_sup'] = fonias.apply(
    lambda row: calcular_turno(
        
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

fonias.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia, Tipo_dia, Hora, Turno_sup]
Index: []

[0 rows x 26 columns]

In [70]:
#Traer el supervisor según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Supervisor'] = fonias.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

fonias.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia, Tipo_dia, Hora, Turno_sup, Supervisor]
Index: []

[0 rows x 27 columns]

In [71]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_ser = fonias.copy()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)

fonias_ser['Duración_segundos'].fillna(0, inplace=True)

fonias_ser

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\48388375.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\48388375.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia, Tipo_dia, Hora, Turno_sup, Supervisor]
Index: []

[0 rows x 27 columns]

In [72]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_ser = fonias_ser.groupby(['Fecha', 'reg_ccz']).agg({
    'TMR_segundos':  mean_without_zeros,
    'Duración_segundos':  mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)
fonias_ser['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_ser['TMR_segundos'] = fonias_ser['TMR_segundos'].round(0).astype(int)
fonias_ser['Duración_segundos'] = fonias_ser['Duración_segundos'].round(0).astype(int)

fonias_ser.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3888450677.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3888450677.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

Empty DataFrame
Columns: [Fecha, reg_ccz, TMR_segundos, Duración_segundos, No Asignado]
Index: []

In [73]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_1 = fonias.copy()

fonias_1.head()

Empty DataFrame
Columns: [Fecha, Código, Petición Móvil, Urgente, Emergencia, Usuario, Nombre Usuario, Estado, Ruta, Viaje, ServBus, Cumplimiento, No Asignado, Hora Petición, Hora Apertura, Hora Cierre, TMR, Duración, Unnamed: 18, reg_ccz, TMR_segundos, Duración_segundos, Tipo dia, Tipo_dia, Hora, Turno_sup, Supervisor]
Index: []

[0 rows x 27 columns]

In [74]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_1 = fonias_1.groupby(['Fecha', 'Supervisor']).agg({
    'TMR_segundos': mean_without_zeros,
    'Duración_segundos': mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_1['TMR_segundos'].fillna(0, inplace=True)
fonias_1['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_1['TMR_segundos'] = fonias_1['TMR_segundos'].round(0).astype(int)
fonias_1['Duración_segundos'] = fonias_1['Duración_segundos'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
fonias_1.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

fonias_1.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3334358817.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3334358817.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['Duración_segundos'].fillna(0, inplace=True)

Empty DataFrame
Columns: [Fecha, reg_ccz, TMR_segundos, Duración_segundos, No Asignado]
Index: []

In [75]:
#Consolidar los dos dataframe para validar fonias

fonias_fin = pd.concat([fonias_ser, fonias_1], ignore_index=True)

fonias_fin

Empty DataFrame
Columns: [Fecha, reg_ccz, TMR_segundos, Duración_segundos, No Asignado]
Index: []

Información de novedades

In [76]:
# Rellena los valores NaN en la columna
novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

# Convertir 'Nodo' a tipo entero
novedades['CODIGO OPERADOR'] = novedades['CODIGO OPERADOR'].astype(int)

novedades.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\2588241090.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1057523,15/04/2026,15/04/2026,1,Ausentismo,PERMISO,Patio Dorado,0,1024489560,YERLI IRENE HERNANDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-09 08:42:09 PERMISO - PROCEDIMIENTO OD...,Por Aprobar,NaN
1,1058351,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501161,79453992,ALEXANDER GARAVITO HERNANDEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1058352,15/04/2026,15/04/2026,1,Cambio de Turno Operativo,NaN,Patio Dorado,501374,91538451,JESUS FLOREZ ALARCON,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
3,1058353,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501522,79904374,JOHN HENRY LEON QUIROGA,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
4,1058354,15/04/2026,15/04/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,502645,79842026,MANUEL PISCO RODRIGUEZ,OPERADOR DE BIARTICULADO,NaN,0,NaN,NaN,2026-04-15 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [77]:
# Filtrar el DataFrame para obtener solo las filas donde 'CODIGO OPERADOR' sea diferente de 0
novedades = novedades[novedades['CODIGO OPERADOR'] == 0]

# Filtrar el DataFrame para eliminar las filas donde 'estado' es igual a 'Eliminada'
novedades = novedades[novedades['ESTADO'] != 'Eliminada']

novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1057523,15/04/2026,15/04/2026,1,Ausentismo,PERMISO,Patio Dorado,0,1024489560,YERLI IRENE HERNANDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-09 08:42:09 PERMISO - PROCEDIMIENTO OD...,Por Aprobar,NaN
22,1058975,14/04/2026,14/04/2026,1,Retroalimentación,NaN,Patio Dorado,0,1069714687,ROBINSON ESTIBEN LOPEZ CARDENAS,RECOMOTO,LEIDY JAZMIN SALINAS VARGAS,0,NaN,NaN,2026-04-14 09:30:00 EL REMOTO ROBINSON ESTIBEN...,Por Aprobar,NaN
52,1059007,13/04/2026,13/04/2026,1,Retroalimentación,NaN,Patio Dorado,0,53154005,ANGELA MIREYA RIAÑO PASITO,REGULADOR EN CENTRO DE CONTROL,DIEGO ARTURO URIBE ROJAS,0,NaN,NaN,2026-04-14 11:36:44 Se realiza retroalimentaci...,Aprobada,DIEGO ARTURO URIBE ROJAS
53,1059017,13/04/2026,15/04/2026,3,Ausentismo,NO JUSTIFICADO,Patio Dorado,0,52980742,DORIS EDITH PATARROYO GORDO,REGULADOR EN CENTRO DE CONTROL,DIANA CAROLINA MELO PRIETO,-150,NaN,NaN,"2026-04-14 12:11:34 Se reporta tp34., /.../",Por Aprobar,NaN
54,1059033,13/04/2026,13/04/2026,1,Ausentismo,PERMISO,Patio Dorado,0,52737325,DIANA MARCELA AGUILERA MADRIGAL,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,0,NaN,NaN,2026-04-14 13:54:08 PERMISO - Asiste al funera...,Por Aprobar,NaN

In [78]:
#resumen por fecha y regulador según las novedades

# Crear columnas para cada tipo de novedad
novedades['Ausentismo'] = (novedades['TIPO NOVEDAD'] == 'Ausentismo').astype(int)
novedades['Retardo'] = (novedades['TIPO NOVEDAD'] == 'Retardo').astype(int)
novedades['Novedades'] = ~novedades['TIPO NOVEDAD'].isin(['Ausentismo', 'Retardo'])

# Agrupar por 'FECHA INICIAL' y 'REGULADOR', y contar las ocurrencias de cada tipo de novedad
novedades_fin = novedades.groupby(['FECHA INICIAL', 'EMPLEADO']).agg({
    'Ausentismo': 'sum',
    'Retardo': 'sum',
    'Novedades': 'sum'
}).reset_index()

# Renombrar la columna 'Supervisor' a 'reg_ccz'
novedades_fin.rename(columns={'FECHA INICIAL': 'Fecha'}, inplace=True)
novedades_fin.rename(columns={'EMPLEADO': 'reg_ccz'}, inplace=True)

# Mostrar el DataFrame resultante
novedades_fin.head()

        Fecha                         reg_ccz  Ausentismo  Retardo  Novedades
0  01/04/2026  ANDRES GABRIEL SANABRIA ACHURY           1        1          0
1  01/04/2026   EDICSON YAIR VELANDIA PEÑUELA           1        0          0
2  01/04/2026  MARTHA DOLORES DURAN GUTIERREZ           1        0          0
3  01/04/2026     YERLI IRENE HERNANDEZ ARIZA           0        0          1
4  01/04/2026          YORLEY VALLEJO AGUILAR           1        0          0

Consolidar la data para validar la información

In [79]:
#copiar data de regularidad

indicadores = regularidad.copy()

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94

In [80]:
#llevar KMS a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (kilometros['Fecha'] == Fecha)&
        (kilometros['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not kilometros.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = kilometros.loc[filtro, 'Kilómetros (%)'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Kilómetros (%)'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%)
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89,97
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100,99
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94,95
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98,98
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94,96

In [81]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'TMR_segundos'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['TMR_segundos'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['TMR_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
indicadores['TMR_segundos'] = indicadores['TMR_segundos'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\679954610.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\679954610.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  indicadores['TMR_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89,97,0
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100,99,0
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94,95,0
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98,98,0
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94,96,0

In [82]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'No Asignado'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['No Asignado'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['No Asignado'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['No Asignado'] = indicadores['No Asignado'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3884926540.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['No Asignado'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3884926540.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  indicadores['No Asignado'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89,97,0,0
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100,99,0,0
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94,95,0,0
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98,98,0,0
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94,96,0,0

In [83]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Ausentismo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Ausentismo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Ausentismo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Ausentismo'] = indicadores['Ausentismo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\2427483280.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Ausentismo'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\2427483280.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  indicadores['Ausentismo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89,97,0,0,0
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100,99,0,0,0
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94,95,0,0,0
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98,98,0,0,0
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94,96,0,0,0

In [84]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Novedades'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Novedades'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Novedades'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Novedades'] = indicadores['Novedades'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\590017984.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Novedades'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\590017984.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  indicadores['Novedades'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89,97,0,0,0,0
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100,99,0,0,0,0
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94,95,0,0,0,0
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98,98,0,0,0,0
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94,96,0,0,0,0

In [85]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Retardo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Retardo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Retardo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Retardo'] = indicadores['Retardo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3046602996.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Retardo'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_18992\3046602996.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  indicadores['Retardo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/05/2026,ESTEBAN CAMILO MEDINA,83,93,89.247312,89,97,0,0,0,0,0
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,128,128,100.000000,100,99,0,0,0,0,0
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,32,34,94.117647,94,95,0,0,0,0,0
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,256,262,97.709924,98,98,0,0,0,0,0
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,45,48,93.750000,94,96,0,0,0,0,0

In [86]:
#Eliminar columnas que no se necesitan para el proceso

col_eliminar = ['Viaje Regular', 'Viaje Totales','IRI (%)']

indicadores= indicadores.drop(columns=col_eliminar)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/05/2026,ESTEBAN CAMILO MEDINA,89,97,0,0,0,0,0
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,100,99,0,0,0,0,0
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,94,95,0,0,0,0,0
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,98,98,0,0,0,0,0
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,94,96,0,0,0,0,0

In [87]:
# Agrupar por 'reg_ccz' y contar los días únicos laborados
dias_laborados = indicadores.groupby('reg_ccz')['Fecha'].nunique()

# Crear una nueva columna en el DataFrame de indicadores con los días laborados
indicadores['Días Laborados'] = indicadores['reg_ccz'].map(dias_laborados)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,01/05/2026,ESTEBAN CAMILO MEDINA,89,97,0,0,0,0,0,1
1,01/05/2026,JOHN JAIRO ESPINOSA SANTA,100,99,0,0,0,0,0,2
2,01/05/2026,NORBERTO NIÑO RODRIGUEZ,94,95,0,0,0,0,0,1
3,01/05/2026,PAULA KATHERINE CANTOR SALAMANCA,98,98,0,0,0,0,0,2
4,01/05/2026,ROSA MARIELA TELLEZ NAVARRO,94,96,0,0,0,0,0,1

In [88]:
# Agrupar por 'reg_ccz' y aplicar las funciones de agregación necesarias
indicadores_f = indicadores.groupby('reg_ccz').agg({
    'Regularidad (%)': 'mean',
    'Kilómetros (%)': 'mean',
    'TMR_segundos': 'mean',
    'No Asignado': 'sum',
    'Ausentismo': 'sum',
    'Novedades': 'sum',
    'Retardo': 'sum',
    'Días Laborados':'max'
}).reset_index()

# Redondear las columnas a 2 decimales
indicadores_f['Regularidad (%)'] = indicadores_f['Regularidad (%)'].round(0).astype(int)
indicadores_f['Kilómetros (%)'] = indicadores_f['Kilómetros (%)'].round(0).astype(int)
indicadores_f['TMR_segundos'] = indicadores_f['TMR_segundos'].round(0).astype(int)

# Mostrar el DataFrame resultante
indicadores_f.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3

In [89]:
#copia de la data de indicadores 

calificacion = indicadores_f.copy()

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3

In [90]:
# Definir la función para convertir la lógica de Excel a Python
def convertir_regularidad(valor):
    if valor >= 84:
        return 100
    elif 80 <= valor < 84:
        return 75
    elif 74 <= valor < 80:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Regularidad (%)'
calificacion['IRI'] = calificacion['Regularidad (%)'].apply(convertir_regularidad)

# Mostrar el DataFrame resultante con la nueva columna
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100

In [91]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_kilometros(valor):
    if valor >= 95:
        return 100
    elif 90 <= valor < 95:
        return 75
    elif 80 <= valor < 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['KM'] = calificacion['Kilómetros (%)'].apply(convertir_kilometros)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75

In [92]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_tmr(valor):
    if valor <= 60:
        return 100
    elif 60 < valor <= 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['Fonias'] = calificacion['TMR_segundos'].apply(convertir_tmr)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0,100
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50,100
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50,100
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0,100
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75,100

In [93]:
# Duplicar la columna 'No Asignado'
calificacion['No Asignado %'] = calificacion['No Asignado']

# Nombres a excluir
excluir_nombres = ['DIEGO ARTURO URIBE ROJAS', 'CAMILO ANDRES LOPEZ PENAGOS', 'LISETH GERALDINE GARCIA GARZÓN']

# Filtrar el DataFrame para excluir estos nombres
calificacion_filtrado = calificacion[~calificacion['reg_ccz'].isin(excluir_nombres)]

# Encontrar el valor máximo en la columna 'No Asignado Modificado' del DataFrame filtrado
max_no_asignado = calificacion_filtrado['No Asignado %'].max()

# Asignar 5 al valor máximo y 0 al resto
calificacion['No Asignado %'] = calificacion['No Asignado %'].apply(lambda x: 5 if x == max_no_asignado else 0)

# Mostrar el DataFrame resultante
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0,100,5
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50,100,5
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50,100,5
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0,100,5
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75,100,5

In [94]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_retardo(valor):
    if valor <= 0:
        return 100
    elif 1 >= valor <= 3:
        return 40
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Retardos'] = calificacion['Retardo'].apply(convertir_retardo)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0,100,5,100
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50,100,5,100
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50,100,5,100
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0,100,5,100
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75,100,5,100

In [95]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_novedades(valor):
    if valor <= 0:
        return 100
    elif valor == 1:
        return 75
    elif valor == 2:
        return 50
    elif valor == 3:
        return 25
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Novedades'] = calificacion['Novedades'].apply(convertir_novedades)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0,100,5,100,100
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50,100,5,100,100
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50,100,5,100,100
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0,100,5,100,100
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75,100,5,100,100

In [96]:
#Sumar las novedades retardos y novedades

calificacion['Novedad'] = ((calificacion['% Novedades'] + calificacion['% Retardos']) / 2).astype(int)

# Calcular el promedio de las columnas mencionadas
calificacion['Total Calificación'] = calificacion[['IRI', 'KM', 'Fonias','Novedad']].mean(axis=1)

# Convertir el resultado a enteros si es necesario
calificacion['Total Calificación'] = calificacion['Total Calificación'].astype(int)

calificacion['Total'] = calificacion['Total Calificación'] + calificacion['No Asignado %']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0,100,5,100,100,100,62,67
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50,100,5,100,100,100,75,80
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50,100,5,100,100,100,87,92
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0,100,5,100,100,100,50,55
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75,100,5,100,100,100,93,98

In [97]:
#Crear base auxiliar para llevar el cargo

base_personal = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/base_personal.csv', encoding='latin', delimiter=';')

base_personal.head()

                                Nombre                           Cargo
0     PAULA KATHERINE CANTOR SALAMANCA  REGULADOR EN CENTRO DE CONTROL
1         LUIS FERNANDO GONZALEZ REYES  REGULADOR EN CENTRO DE CONTROL
2         MAICOL ALEXANDER PITA BLANCO  REGULADOR EN CENTRO DE CONTROL
3  SANDRA CAROLINA VALERIANO SARMIENTO  REGULADOR EN CENTRO DE CONTROL
4                 ELICIA MONGUI DUARTE  REGULADOR EN CENTRO DE CONTROL

In [98]:
#Llevar el cargo a la base de calificacion

def calcular_turno(reg):
    
    filtro = (
        (base_personal['Nombre'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base_personal.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base_personal.loc[filtro, 'Cargo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
calificacion['Cargo'] = calificacion.apply(
    lambda row: calcular_turno(
        row['reg_ccz']
    ),
    axis=1
)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total,Cargo
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,0,100,5,100,100,100,62,67,REGULADOR DE VÍA
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,50,100,5,100,100,100,75,80,REGULADOR DE VÍA
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,50,100,5,100,100,100,87,92,REGULADOR DE VÍA
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,0,100,5,100,100,100,50,55,REGULADOR DE VÍA
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,75,100,5,100,100,100,93,98,REGULADOR EN CENTRO DE CONTROL

In [99]:
#Validación del 100% a que corresponde

# Calcular el 35% de las columnas 'IRI' y 'KM'
calificacion['IRI_35%'] = calificacion['IRI'] * 0.35
calificacion['KM_35%'] = calificacion['KM'] * 0.35
calificacion['fonias_20%'] = calificacion['Fonias'] * 0.20
calificacion['No Asignado_5%'] = calificacion['No Asignado %'] * 0.05
calificacion['Novedad_10%'] = calificacion['Novedad'] * 0.10


# Redondear las columnas a 2 decimales
calificacion['IRI_35%'] = calificacion['IRI_35%'].round(0).astype(int)
calificacion['KM_35%'] = calificacion['KM_35%'].round(0).astype(int)
calificacion['fonias_20%'] = calificacion['fonias_20%'].round(0).astype(int)
calificacion['No Asignado_5%'] =calificacion['No Asignado_5%'].round(2).astype(int)
calificacion['Novedad_10%'] =calificacion['Novedad_10%'].round(0).astype(int)

calificacion['Total_100%'] = calificacion['IRI_35%'] + calificacion['KM_35%'] + calificacion['fonias_20%'] + calificacion['No Asignado_5%'] + calificacion['Novedad_10%']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,...,Novedad,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,...,100,62,67,REGULADOR DE VÍA,18,0,20,0,10,48
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,...,100,75,80,REGULADOR DE VÍA,18,18,20,0,10,66
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,...,100,87,92,REGULADOR DE VÍA,35,18,20,0,10,83
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,...,100,50,55,REGULADOR DE VÍA,0,0,20,0,10,30
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,...,100,93,98,REGULADOR EN CENTRO DE CONTROL,35,26,20,0,10,91

In [100]:
# Total de días en el mes

# Calcular el 70% de los días laborados
umbral = 0.70 * total_dias_julio

# Revisar si los días laborados cumplen con la condición
calificacion['Cumple Condición'] = calificacion['Días Laborados'].apply(lambda x: 1 if x >= umbral else 0)

# Mostrar el DataFrame actualizado
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,...,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%,Cumple Condición
0,ADRIANA YANETH RAMIREZ GALVAN,74,77,0,0,0,0,0,7,50,...,62,67,REGULADOR DE VÍA,18,0,20,0,10,48,0
1,ALEXANDRA MARTINEZ TAPIA,79,85,0,0,0,0,0,8,50,...,75,80,REGULADOR DE VÍA,18,18,20,0,10,66,0
2,AMANDA LUCIA RODRIGUEZ ARAUJO,85,84,0,0,0,0,0,3,100,...,87,92,REGULADOR DE VÍA,35,18,20,0,10,83,0
3,ANETH MAYERLI CHONTAL VILLARRAGA,72,77,0,0,0,0,0,3,0,...,50,55,REGULADOR DE VÍA,0,0,20,0,10,30,0
4,ANGELA MIREYA RIAÑO PASITO,85,90,0,0,0,0,0,3,100,...,93,98,REGULADOR EN CENTRO DE CONTROL,35,26,20,0,10,91,0

In [101]:
#Exportar archivo
calificacion.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/calificacion_{mes_i}.csv', index=False)

In [102]:
#Exportar archivo
indicadores.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/indicadores_{mes_i}.csv', index=False)

In [103]:
#Exportar archivo

kilometros.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/kilometros_{mes_i}.csv', index=False)

In [104]:
novedades_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/novedades_fin_{mes_i}.csv', index=False)

In [105]:
#Exportar archivo

fonias_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/fonias_{mes_i}.csv', index=False)

In [106]:
#Exportar archivo

iri.to_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python//regularidad_{mes_i}.csv", index=False)