In [217]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import re
import pyproj
import folium

In [218]:
#Filtros de fechas

dia_ivd = '20260301'
dia_fvd = '20260331'

dia_ias = '01-03-2026'
dia_fas = '31-03-2026'

dia_if = '2026-03-01'
dia_ff = '2026-03-31'

mes = 'Novedades_mar26'

mes_i = 'mar26'

total_dias_julio = 31

mes_c = 'Marzo'

mes_ico = 'marzo'

month = 'Marzo'

ISV

In [219]:
isv = pd.read_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/{month}_isv.csv', encoding='latin')

isv.head()

,Fecha,reg_ccz,accidentes_nivel_1,accidentes_nivel_2,accidentes_nivel_3
0,2026-03-02,CAMILO ANDRES LOPEZ PENAGOS,4,0,0
1,2026-03-02,DIANA CAROLINA MELO PRIETO,2,0,0
2,2026-03-02,EDWIN ECHEVERRI GOMEZ,1,0,0
3,2026-03-02,HENRY OCTAVIO BENAVIDES RAMIREZ,1,0,0
4,2026-03-02,JENNY ALEXANDRA BERNAL BERNAL,1,0,0

In [220]:
isv['Fecha'] = pd.to_datetime(
    isv['Fecha'],
    errors='coerce'
).dt.strftime('%d/%m/%Y')

isv.head()

,Fecha,reg_ccz,accidentes_nivel_1,accidentes_nivel_2,accidentes_nivel_3
0,02/03/2026,CAMILO ANDRES LOPEZ PENAGOS,4,0,0
1,02/03/2026,DIANA CAROLINA MELO PRIETO,2,0,0
2,02/03/2026,EDWIN ECHEVERRI GOMEZ,1,0,0
3,02/03/2026,HENRY OCTAVIO BENAVIDES RAMIREZ,1,0,0
4,02/03/2026,JENNY ALEXANDRA BERNAL BERNAL,1,0,0

ICO

In [221]:
ico_proc = pd.read_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/ICO/{mes_ico}_ICO_consolidado.csv', encoding='latin', sep=';')

ico_proc.head()

,Fecha,reg_ccz,cantidad_novedades,total_puntos
0,2026-03-01,AMANDA LUCIA RODRIGUEZ ARAUJO,1,15
1,2026-03-01,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,1,10
2,2026-03-01,CAMILO ANDRES LOPEZ PENAGOS,7,90
3,2026-03-01,EDWIN ECHEVERRI GOMEZ,7,90
4,2026-03-01,FRANCY LINNE TIMARAN CUESTA,1,15

In [222]:
ico_proc['Fecha'] = pd.to_datetime(
    ico_proc['Fecha'],
    errors='coerce'
).dt.strftime('%d/%m/%Y')

ico_proc.head()

,Fecha,reg_ccz,cantidad_novedades,total_puntos
0,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,1,15
1,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,1,10
2,01/03/2026,CAMILO ANDRES LOPEZ PENAGOS,7,90
3,01/03/2026,EDWIN ECHEVERRI GOMEZ,7,90
4,01/03/2026,FRANCY LINNE TIMARAN CUESTA,1,15

IRP

In [223]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores_general'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_irp_procesado_regccz.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', sep=';', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    irp_regccz = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
irp_regccz.head()

,Fecha,reg_ccz,Id LÃ­nea,LÃ­nea,Id Ruta,CV_promedio,tablas,buses,conductores,retraso_promedio,puntaje_cv,categoria_cv
0,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10184,740,12774,78,32,26,29,7,15,Regular
1,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10244,SE10,12741,52,9,16,15,11,50,Aceptable
2,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10244,SE10,12742,52,3,3,3,3,50,Aceptable
3,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10273,142,12749,77,9,18,16,13,15,Regular
4,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10292,577,12789,74,14,16,16,8,50,Aceptable

In [224]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores_general'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_irp_procesado_sup.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', sep=';', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    irp_sup = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
irp_sup.head()

,Fecha,Supervisor,Id LÃ­nea,LÃ­nea,Id Ruta,CV_promedio,tablas,buses,conductores,retraso_promedio,puntaje_cv,categoria_cv
0,2026-03-01,CAMILO ANDRES LOPEZ PENAGOS,10184,740,12774,78,32,33,52,9,15,Regular
1,2026-03-01,CAMILO ANDRES LOPEZ PENAGOS,10194,539,12785,30,14,23,30,12,75,Bueno
2,2026-03-01,CAMILO ANDRES LOPEZ PENAGOS,10194,539,12786,30,14,24,29,11,75,Bueno
3,2026-03-01,CAMILO ANDRES LOPEZ PENAGOS,10196,E25,12783,60,10,12,17,10,50,Aceptable
4,2026-03-01,CAMILO ANDRES LOPEZ PENAGOS,10196,E25,12784,60,10,12,16,11,50,Aceptable

In [225]:
# Consolidar todos los DataFrames en uno solo

irp_ccz = pd.concat([irp_regccz, irp_sup], ignore_index=True)

irp_ccz.head()

,Fecha,reg_ccz,Id LÃ­nea,LÃ­nea,Id Ruta,CV_promedio,tablas,buses,conductores,retraso_promedio,puntaje_cv,categoria_cv,Supervisor
0,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10184,740,12774,78,32,26,29,7,15,Regular,NaN
1,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10244,SE10,12741,52,9,16,15,11,50,Aceptable,NaN
2,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10244,SE10,12742,52,3,3,3,3,50,Aceptable,NaN
3,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10273,142,12749,77,9,18,16,13,15,Regular,NaN
4,2026-03-01,EDGAR ALEJANDRO RIOS CARDOZO,10292,577,12789,74,14,16,16,8,50,Aceptable,NaN

In [226]:
irp_ccz = (
    irp_ccz
    .groupby(['Fecha', 'reg_ccz'], as_index=False)['CV_promedio']
    .mean()
)

# Convertir el promedio a entero
irp_ccz['CV_promedio'] = (
    irp_ccz['CV_promedio']
    .round()
    .astype(int)
)

irp_ccz.head()

        Fecha                            reg_ccz  CV_promedio
0  2026-03-01       EDGAR ALEJANDRO RIOS CARDOZO           68
1  2026-03-01              ESTEBAN CAMILO MEDINA           45
2  2026-03-01        FRANCY LINNE TIMARAN CUESTA           68
3  2026-03-01  JINETH ALEXANDRA GUZMAN HERNANDEZ           73
4  2026-03-01     JULIAN ANDRES SANCHEZ RESTREPO           54

Importar archivos de viajes desglosados zonal y troncal

In [227]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/01 viajes_desglosados_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosado.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_zonal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_zonal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_zonal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,0,11790,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0
1,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
2,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0
4,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [228]:
# Ruta de la carpeta que contiene los archivos de desglosados troncal
ruta_carpeta = 'Z:/01 base_datos/16 viajes_desglosados_alimentacion_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ivd}'
fecha_fin = f'{dia_fvd}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_viajedesglosadotroncal.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    desg_troncal_fms = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    desg_troncal_fms.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
desg_troncal_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/03/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0A60001-1-12553,CE0A60001,1,2,1,10502,...,0,14465,Si,NaN,NaN,NaN,"3, 1",CDZ4,100.0,1.0
1,1/03/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0A60001-2-12553,CE0A60001,2,3,2,10502,...,0,14465,No,NaN,NaN,NaN,"3, 1",CDZ4,100.0,1.0
2,1/03/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0A60001-3-12553,CE0A60001,3,4,3,10502,...,0,14465,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/03/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0A60001-4-12553,CE0A60001,4,5,4,10502,...,0,14465,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
4,1/03/2026,ENGATIVA AL,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0A60001-5-12553,CE0A60001,5,6,5,10502,...,0,14465,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [229]:
# Consolidar todos los DataFrames en uno solo

desglosados_fms = pd.concat([desg_zonal_fms, desg_troncal_fms], ignore_index=True)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,0,11790,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0
1,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
2,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0
4,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [230]:
desglosados_fms['Id Línea '] = (
    desglosados_fms['Id Línea ']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,0,11790,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0
1,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
2,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0
4,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [231]:
desglosados_fms['KmEjecutado'] = (
    desglosados_fms['KmEjecutado']
    .replace("", 0)
    .fillna(0)
    .astype(int)
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,1/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,0,11790,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0
1,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
2,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0
4,1/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [232]:
# Ruta de la carpeta que contiene los archivos de desglosados zonal
ruta_carpeta = f'Z:/01 base_datos/41 Informe Diario CCZ/Blogger/Asistencia/2026/{mes_c}'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{dia_ias}'
fecha_fin = f'{dia_fas}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:10]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%d-%m-%Y', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', delimiter=';',skiprows=2, low_memory=False)
             # Eliminar filas que estén completamente vacías
            df = df.dropna(how='all')
            # Añadir una nueva columna 'Fecha' con la fecha extraída del nombre del archivo
            df['Fecha'] = fecha_archivo
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    asistencia = pd.concat(dataframes, ignore_index=True)

    # Guardar el DataFrame consolidado en un nuevo archivo
    asistencia.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/asistencia_{mes_i}.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,ADRIANA YANETH RAMIREZ GALVAN,ADRIANA YANETH,RAMIREZ GALVAN,PLA1,Portal Dorado,05:00:00,NaN,05:01:00,09:00:00,14:00:00,...,13:54:00,00:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-03-2026
1,LEIDY TATIANA SANCHEZ VELANDIA,LEIDY TATIANA,SANCHEZ VELANDIA,PLA3,Portal 80,05:00:00,NaN,05:00:00,09:00:00,14:00:00,...,13:59:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-03-2026
2,CAMILO ANDRES LOPEZ PENAGOS,CAMILO ANDRES,LOPEZ PENAGOS,SUP CCZ,Disponible CCZ,06:00:00,06:00:00,06:00:00,16:00:00,22:00:00,...,22:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-03-2026
3,GLORIA ESPERANZA MESA REYES,GLORIA ESPERANZA,MESA REYES,EG5,Verbena III,06:00:00,NaN,05:57:00,08:00:00,14:00:00,...,13:54:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-03-2026
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,AMANDA PATRICIA,RODRIGUEZ HERNANDEZ,EG9,Gaco II,06:00:00,NaN,05:56:00,08:00:00,14:00:00,...,13:56:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01-03-2026

In [233]:
## Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia

# Convertir la columna 'Fecha' a tipo datetime
asistencia['Fecha'] = pd.to_datetime(asistencia['Fecha'], format='%d-%m-%Y')

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
asistencia['Fecha'] = asistencia['Fecha'].dt.strftime('%d/%m/%Y')

asistencia.head()

,NOMBRE,NOMBRE.1,APELLIDOS,TURNO Programado,Sitio Programado,Hora Inicio Programado,Hora Inicio Referencia Ajustado,Hora Inicio Real,Duración Programado,Hora Fin Programado,...,Hora Fin Real,HTL,Sitio Real,Aplica novedad,Informa,Tipo de novedad,Supervisor,Observaciones,INTRANET,Fecha
0,ADRIANA YANETH RAMIREZ GALVAN,ADRIANA YANETH,RAMIREZ GALVAN,PLA1,Portal Dorado,05:00:00,NaN,05:01:00,09:00:00,14:00:00,...,13:54:00,00:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2026
1,LEIDY TATIANA SANCHEZ VELANDIA,LEIDY TATIANA,SANCHEZ VELANDIA,PLA3,Portal 80,05:00:00,NaN,05:00:00,09:00:00,14:00:00,...,13:59:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2026
2,CAMILO ANDRES LOPEZ PENAGOS,CAMILO ANDRES,LOPEZ PENAGOS,SUP CCZ,Disponible CCZ,06:00:00,06:00:00,06:00:00,16:00:00,22:00:00,...,22:00:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2026
3,GLORIA ESPERANZA MESA REYES,GLORIA ESPERANZA,MESA REYES,EG5,Verbena III,06:00:00,NaN,05:57:00,08:00:00,14:00:00,...,13:54:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2026
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,AMANDA PATRICIA,RODRIGUEZ HERNANDEZ,EG9,Gaco II,06:00:00,NaN,05:56:00,08:00:00,14:00:00,...,13:56:00,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2026

In [234]:
#Archivo de novedades disciplinarias

novedades = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/{mes}.csv",encoding='latin', delimiter=';')

In [235]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
novedades['FECHA INICIAL'] = pd.to_datetime(novedades['FECHA INICIAL'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
novedades['FECHA INICIAL'] = novedades['FECHA INICIAL'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1054730,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500029.0,19337415,ISRAEL MARTINEZ GONZALEZ,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
1,1054731,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501161.0,79453992,ALEXANDER GARAVITO HERNANDEZ,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1054732,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501374.0,91538451,JESUS FLOREZ ALARCON,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
3,1054733,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,502645.0,79842026,MANUEL PISCO RODRIGUEZ,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
4,1054734,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,503030.0,71776641,ALBER MEJIA CARMONA,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [236]:
#Archivos de regularidad de plataforma EIC

cerrado = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_cerrrado_{mes_i}.csv", delimiter=';')

etapa_1 = pd.read_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/IRI_Etapa1_{mes_i}.csv", delimiter=';')

In [237]:
#Informes de turnos, tipo día, personal

turno_via = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_via_fms.csv", sep=';')

turno_sup = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_supervisor_fms.csv", sep=';')

tipo_dia = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Tipo día.csv", encoding='latin',delimiter=';')

personal = pd.read_csv("Z:/01 base_datos/41 Informe Diario CCZ/2023/IRI TM/Personal_id.csv",encoding='latin',delimiter=';')

turno_ccz = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_control_fms_2026.csv", sep=';')

turno_moto_aux = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_motoregulador_fms.csv", sep=';')

turno_aux = pd.read_csv("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/turnos_aux_fms.csv", sep=';')

In [238]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [239]:
#Importar data de fonias

fonias = pd.read_excel ("C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2023/fonias_fms.xlsx")

# Convertir la columna 'Fecha' a tipo datetime
fonias['Fecha'] = pd.to_datetime(fonias['Fecha'])

# Filtrar los valores mayores o iguales a la fecha indicada
fonias = fonias[(fonias['Fecha'] >= f'{dia_if}') & (fonias['Fecha'] <= f'{dia_ff}')]

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
fonias['Fecha'] = fonias['Fecha'].dt.strftime('%d/%m/%Y')

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,NaN,0.5,1.0,04:05:00,04:06:00,04:07:00,00:01:00,00:01:22,NaN
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,NaN,NaN,0.0,04:07:00,04:07:00,04:08:00,00:00:00,00:00:03,NaN
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,NaN,NaN,0.0,05:04:00,05:04:00,05:04:00,00:00:00,00:00:18,NaN
36996,01/03/2026,507118,Si,Emergencia,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,SE14,0,NaN,0.5,0.0,05:04:00,05:04:00,05:05:00,00:00:00,00:00:35,NaN
36997,01/03/2026,502095,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,C101,0,NaN,0.5,0.0,05:07:00,05:09:00,05:09:00,00:02:00,00:00:15,NaN

In [240]:
#Crear dataframe para llevar el nombre a fonias

# Crear un diccionario con los datos
data = {
    'RegC': [
        'Luis Fernando Gonzalez', 'William Munar Gonzalez', 'Adriana Patricia Tellez',
        'Jose Antonio Castro Garcia', 'Rosa Tellez', 'Edith Patarroyo',
        'Laura Marcela Vargas Gutierrez', 'Francy Linnie Timaran Cuesta', 
        'Yerly Irene Hernandez Ariza', 'Anderson Mizar Mendoza', 'Jorge Medina Espinoza',
        'Esteban Camilo Medina', 'Sandra Carolina Valeriano', 'Julian Andres Sanchez Restrepo',
        'Karen Lorena Barrera', 'Bryan Guzman', 'Jinneth Alexandra Guzman',
        'Maicol Alexander Pita Blanco', 'Martha Ibeth Martin', 'John Jairo Espinosa Santa',
        'Elicia Mongui Duarte', 'Sonia Constanza Correa Rodriguez', 'Jenny Alexandra Bernal',
        'Norberto Niño Rodriguez', 'Wilson Torres Fajardo', 'William Ignacio Valderrama',
        'Camilo Andres Lopez Penagos', 'Raúl Fabián Romero Micán', 'Deisi Yanira Rojas Torres',
        'Paula Katherine Cantor Salamanca','Angela Mireya Riaño Pasito'
    ],
    'RegControl': [
        'LUIS FERNANDO GONZALEZ REYES', 'WILLIAN HUMBERTO MUNAR GONZALEZ', 
        'ADRIANA PATRICIA TELLEZ VARELA', 'JOSE ANTONIO CASTRO GARCIA', 
        'ROSA MARIELA TELLEZ NAVARRO', 'DORIS EDITH PATARROYO GORDO',
        'LAURA MARCELA VARGAS GUTIERREZ', 'FRANCY LINNE TIMARAN CUESTA', 
        'YERLI IRENE HERNÁNDEZ ARIZA', 'ANDERSON MIZAR MENDOZA', 
        'JORGE MEDINA ESPINOSA', 'ESTEBAN CAMILO MEDINA', 
        'SANDRA CAROLINA VALERIANO SARMIENTO', 'JULIAN ANDRES SANCHEZ RESTREPO', 
        'KAREN LORENA BARRERA SERRANO', 'BRYAN ANDRES GUZMAN ROJANO', 
        'JINETH ALEXANDRA GUZMAN HERNANDEZ', 'MAICOL ALEXANDER PITA BLANCO', 
        'MARTHA IBETH MARTIN MARTIN', 'JOHN JAIRO ESPINOSA SANTA', 
        'ELICIA MONGUI DUARTE', 'SONIA CONSTANZA CORREA RODRIGUEZ', 
        'JENNY ALEXANDRA BERNAL BERNAL', 'NORBERTO NIÑO RODRIGUEZ', 
        'WILSON ABEL TORRES FAJARDO', 'WILLIAM IGNACIO VALDERRAMA GONZALEZ', 
        'CAMILO ANDRES LOPEZ PENAGOS', 'RAUL FABIAN ROMERO MICAN', 
        'DEISY YANIRA ROJAS TORRES', 'PAULA KATHERINE CANTOR SALAMANCA',
        'ANGELA MIREYA RIAÑO PASITO'
    ]
}

# Convertir el diccionario a un DataFrame
base = pd.DataFrame(data)

# Mostrar el DataFrame
base.head()

                         RegC                       RegControl
0      Luis Fernando Gonzalez     LUIS FERNANDO GONZALEZ REYES
1      William Munar Gonzalez  WILLIAN HUMBERTO MUNAR GONZALEZ
2     Adriana Patricia Tellez   ADRIANA PATRICIA TELLEZ VARELA
3  Jose Antonio Castro Garcia       JOSE ANTONIO CASTRO GARCIA
4                 Rosa Tellez      ROSA MARIELA TELLEZ NAVARRO

Indicador de regularidad de personal de control

In [241]:
#consolidar iri con los datos de cerrado y etapa_1

iri = pd.concat([cerrado,etapa_1], ignore_index=True)

#Eliminar columnas 

col_eliminar = ['IdIRI', 'Estado', 'F. Inicio DP', 'F. Cierre DP','Operador Programado','Id Operador','Operador','Evidencia']

iri = iri.drop(columns=col_eliminar)

iri['Cantidad'] = 1

iri.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\2805954182.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  iri = pd.concat([cerrado,etapa_1], ignore_index=True)

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,1/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,Con hora de Inicio LG SMART OPERATOR,0,0,0.00,0.00,0,0,0,0,1
1,1/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,Sin hora de Inicio - No Imputado,0,0,0.00,0.00,0,0,0,1,1
2,1/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,Con hora de Inicio LG SMART OPERATOR,1,0,0.00,0.02,200.000.000,1,0,1,1
3,1/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,Con hora de Inicio LG SMART OPERATOR,0,0,20.97,-0.48,200.000.000,1,0,1,1
4,1/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,Con hora de Inicio LG SMART OPERATOR,0,0,21.93,0.47,200.000.000,1,0,1,1

In [242]:
# Convertir la columna 'Fecha Viaje' a tipo datetime
iri['Fecha Viaje'] = pd.to_datetime(iri['Fecha Viaje'], format='%d/%m/%Y', errors='coerce')

# Formatear la columna 'Fecha Viaje' en el formato deseado
iri['Fecha Viaje'] = iri['Fecha Viaje'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame resultante
iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Imputación de datos,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,Con hora de Inicio LG SMART OPERATOR,0,0,0.00,0.00,0,0,0,0,1
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,Sin hora de Inicio - No Imputado,0,0,0.00,0.00,0,0,0,1,1
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,Con hora de Inicio LG SMART OPERATOR,1,0,0.00,0.02,200.000.000,1,0,1,1
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,Con hora de Inicio LG SMART OPERATOR,0,0,20.97,-0.48,200.000.000,1,0,1,1
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,Con hora de Inicio LG SMART OPERATOR,0,0,21.93,0.47,200.000.000,1,0,1,1

In [243]:
#Convertir datos de columna Hora Teórica

# Expresión regular ajustada para extraer la hora
patron_hora = r'(\d{1,2}:\d{2}:\d{2}\s?[ap]\.?m\.?)'

# Aplicar la extracción de hora a la columna 'Hora Teórica'
iri['Hora'] = iri['Hora Teórica'].str.extract(patron_hora)

# Mostrar el DataFrame resultante
iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Primer Viaje,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0,0,0.00,0.00,0,0,0,0,1,NaN
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0,0,0.00,0.00,0,0,0,1,1,NaN
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,1,0,0.00,0.02,200.000.000,1,0,1,1,NaN
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,0,0,20.97,-0.48,200.000.000,1,0,1,1,NaN
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,0,0,21.93,0.47,200.000.000,1,0,1,1,NaN

In [244]:
# Dividir la columna 'Hora Teórica' en 'Fecha' y 'Hora'
iri[['Fecha1', 'Hora']] = iri['Hora Teórica'].str.split(' ', n=1, expand=True)

# Mostrar el DataFrame resultante
iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ultimo Viaje,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0,0.00,0.00,0,0,0,0,1,NaN,NaN
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0,0.00,0.00,0,0,0,1,1,16:02,1/03/2026
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,0,0.00,0.02,200.000.000,1,0,1,1,5:00,1/03/2026
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,0,20.97,-0.48,200.000.000,1,0,1,1,5:44,1/03/2026
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,0,21.93,0.47,200.000.000,1,0,1,1,6:28,1/03/2026

In [245]:
# Dividir la columna  en partes usando ':', y seleccionar la primera parte (horas)
iri['franja'] = iri['Hora'].str.split(':').str[0]

# Convertir la columna 'franja' a tipo entero
iri['franja'] = pd.to_numeric(iri['franja'], errors='coerce').astype('Int64')

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Int Real de Paso Recal,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0.00,0.00,0,0,0,0,1,NaN,NaN,<NA>
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0.00,0.00,0,0,0,1,1,16:02,1/03/2026,16
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,0.00,0.02,200.000.000,1,0,1,1,5:00,1/03/2026,5
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,20.97,-0.48,200.000.000,1,0,1,1,5:44,1/03/2026,5
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,21.93,0.47,200.000.000,1,0,1,1,6:28,1/03/2026,6

In [246]:
#Llevar ruta comercial a iri

def calcular_posicion(Linea):
    
    filtro = (
        (turno_via['Linea'] == Linea)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        ruta = turno_via.loc[filtro, 'Ruta'].iloc[0]
        return ruta  if not pd.isna(ruta) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Ruta_Comercial'] = iri.apply(
    lambda row: calcular_posicion(
        row['Linea SAE']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Dif Hora Real y Teor,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0.00,0,0,0,0,1,NaN,NaN,<NA>,DA218
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0.00,0,0,0,1,1,16:02,1/03/2026,16,16-14 Aeropuerto
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,0.02,200.000.000,1,0,1,1,5:00,1/03/2026,5,DD204
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,-0.48,200.000.000,1,0,1,1,5:44,1/03/2026,5,DD204
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,0.47,200.000.000,1,0,1,1,6:28,1/03/2026,6,DD204

In [247]:
#Llevar tipo día a iri

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Tipo dia'] = iri.apply(
    lambda row: calcular_posicion(
        row['Fecha Viaje']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Intervalo Regulado,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0,0,0,0,1,NaN,NaN,<NA>,DA218,Festivo
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0,0,0,1,1,16:02,1/03/2026,16,16-14 Aeropuerto,Festivo
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,200.000.000,1,0,1,1,5:00,1/03/2026,5,DD204,Festivo
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,200.000.000,1,0,1,1,5:44,1/03/2026,5,DD204,Festivo
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,200.000.000,1,0,1,1,6:28,1/03/2026,6,DD204,Festivo

In [248]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
iri['Tipo_dia'] = iri['Tipo dia'].apply(obtener_letra_inicial)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Viaje Regular,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0,0,0,1,NaN,NaN,<NA>,DA218,Festivo,F
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0,0,1,1,16:02,1/03/2026,16,16-14 Aeropuerto,Festivo,F
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,1,0,1,1,5:00,1/03/2026,5,DD204,Festivo,F
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,1,0,1,1,5:44,1/03/2026,5,DD204,Festivo,F
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,1,0,1,1,6:28,1/03/2026,6,DD204,Festivo,F

In [249]:
#Traer el turno de reg_via

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Enviado en Vacío,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0,0,1,NaN,NaN,<NA>,DA218,Festivo,F,None
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,0,1,1,16:02,1/03/2026,16,16-14 Aeropuerto,Festivo,F,PLA2
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,0,1,1,5:00,1/03/2026,5,DD204,Festivo,F,None
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,0,1,1,5:44,1/03/2026,5,DD204,Festivo,F,None
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,0,1,1,6:28,1/03/2026,6,DD204,Festivo,F,EG23

In [250]:
#Traer el turno de control

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Ruta Calcula IRI,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,0,1,NaN,NaN,<NA>,DA218,Festivo,F,None,None
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,1,1,16:02,1/03/2026,16,16-14 Aeropuerto,Festivo,F,PLA2,ET4T-T2
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,1,1,5:00,1/03/2026,5,DD204,Festivo,F,None,ET3N
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,1,1,5:44,1/03/2026,5,DD204,Festivo,F,None,ET3N
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,1,1,6:28,1/03/2026,6,DD204,Festivo,F,EG23,ET3N

In [251]:
#Traer el turno de supervisor

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turno = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turno if not pd.isna(turno) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Turno_Sup'] = iri.apply(
    lambda row: calcular_turno(
        row['Linea SAE'],
        row['Ruta SAE'],
        row['franja'],
        row['Tipo_dia']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Cantidad,Hora,Fecha1,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,1,NaN,NaN,<NA>,DA218,Festivo,F,None,None,None
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,1,16:02,1/03/2026,16,16-14 Aeropuerto,Festivo,F,PLA2,ET4T-T2,SUP CCZ
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,1,5:00,1/03/2026,5,DD204,Festivo,F,None,ET3N,SUP CCZ
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,1,5:44,1/03/2026,5,DD204,Festivo,F,None,ET3N,SUP CCZ
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,1,6:28,1/03/2026,6,DD204,Festivo,F,EG23,ET3N,SUP CCZ

In [252]:
#Traer el regulador según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['reg_via'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_via']
    ),
    axis=1
)

iri['reg_ccz'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_ccz']
    ),
    axis=1
)

iri['Supervisor'] = iri.apply(
    lambda row: calcular_turno(
        row['Fecha Viaje'],
        row['Turno_Sup']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,franja,Ruta_Comercial,Tipo dia,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,<NA>,DA218,Festivo,F,None,None,None,None,None,None
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,16,16-14 Aeropuerto,Festivo,F,PLA2,ET4T-T2,SUP CCZ,LORENA BENILDA PAJARO AREVALO,None,CAMILO ANDRES LOPEZ PENAGOS
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,5,DD204,Festivo,F,None,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,5,DD204,Festivo,F,None,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,6,DD204,Festivo,F,EG23,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS

In [253]:
#Llevar identificación al regulador

def calcular_posicion(Nombre_completo):
    
    filtro = (
        (personal['Nombre Completo'] == Nombre_completo)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not personal.loc[filtro].empty:
        # Obtener el primer valor
        personas = personal.loc[filtro, 'Identificación'].iloc[0]
        return  personas  if not pd.isna( personas ) else None  
    
    return 0  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
iri['Id_via'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_via']
    ),
    axis=1
)

iri['Id_ccz'] = iri.apply(
    lambda row: calcular_posicion(
        row['reg_ccz']
    ),
    axis=1
)

iri['Id_sup'] = iri.apply(
    lambda row: calcular_posicion(
        row['Supervisor']
    ),
    axis=1
)

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Tipo_dia,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,F,None,None,None,None,None,None,0,0,0
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,F,PLA2,ET4T-T2,SUP CCZ,LORENA BENILDA PAJARO AREVALO,None,CAMILO ANDRES LOPEZ PENAGOS,57290332,0,1023870284
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,F,None,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS,0,52480047,1023870284
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,F,None,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS,0,52480047,1023870284
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,F,EG23,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS,0,52480047,1023870284

In [254]:
# Convertir 'Nodo' a tipo entero
iri['Viaje Regular'] = iri['Viaje Regular'].astype(int)

iri['Viaje Totales'] = iri['Viaje Regular']

iri.head()

,Fecha Viaje,Fuente,Servicio,IdViaje,ViajeLinea,Coche,Id Operador Programado,Linea SAE,Ruta SAE,Vehiculo,...,Turno_via,Turno_ccz,Turno_Sup,reg_via,reg_ccz,Supervisor,Id_via,Id_ccz,Id_sup,Viaje Totales
0,01/03/2026,URBANO,AD0691017,1,1,17,105,10691,12746,504224,...,None,None,None,None,None,None,0,0,0,0
1,01/03/2026,ALIMENTACION,CE0A60012,28,27,2,105,10495,10971,0,...,PLA2,ET4T-T2,SUP CCZ,LORENA BENILDA PAJARO AREVALO,None,CAMILO ANDRES LOPEZ PENAGOS,57290332,0,1023870284,0
2,01/03/2026,URBANO,CE0650001,2,1,1,105,10266,10533,504391,...,None,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS,0,52480047,1023870284,1
3,01/03/2026,URBANO,CE0650001,3,2,1,105,10266,10533,504391,...,None,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS,0,52480047,1023870284,1
4,01/03/2026,URBANO,CE0650001,4,3,1,105,10266,10533,504391,...,EG23,ET3N,SUP CCZ,None,MARTHA IBETH MARTIN MARTIN,CAMILO ANDRES LOPEZ PENAGOS,0,52480047,1023870284,1

In [255]:
#Realizar tres copias para los datos del personal

iri_1 = iri.copy()
iri_2 = iri.copy()
iri_3 = iri.copy()

In [256]:
#Kilometros por regulador de control

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_1 = iri_1.groupby(['Fecha Viaje', 'reg_ccz']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

iri_1.head()

  Fecha Viaje                            reg_ccz  Viaje Regular  Viaje Totales
0  01/03/2026       EDGAR ALEJANDRO RIOS CARDOZO            102            156
1  01/03/2026              ESTEBAN CAMILO MEDINA            179            190
2  01/03/2026        FRANCY LINNE TIMARAN CUESTA            152            221
3  01/03/2026  JINETH ALEXANDRA GUZMAN HERNANDEZ             93            157
4  01/03/2026     JULIAN ANDRES SANCHEZ RESTREPO             85            107

In [257]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_2 = iri_2.groupby(['Fecha Viaje', 'reg_via']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

iri_2.head()

,Fecha Viaje,reg_ccz,Viaje Regular,Viaje Totales
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89

In [258]:
#Kilometros por regulador de via

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
iri_3 = iri_3.groupby(['Fecha Viaje', 'Supervisor']).agg({
    'Viaje Regular': 'sum',
    'Viaje Totales': 'count'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
iri_3.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

iri_3.head()

  Fecha Viaje                         reg_ccz  Viaje Regular  Viaje Totales
0  01/03/2026     CAMILO ANDRES LOPEZ PENAGOS           1767           2206
1  02/03/2026     CAMILO ANDRES LOPEZ PENAGOS            722            978
2  02/03/2026  LISETH GERALDINE GARCIA GARZÓN           2065           2668
3  03/03/2026     CAMILO ANDRES LOPEZ PENAGOS           1878           2541
4  03/03/2026  LISETH GERALDINE GARCIA GARZÓN            680            922

In [259]:
#Consolidar los dos dataframe para validar fonias

regularidad = pd.concat([iri_1,iri_2, iri_3], ignore_index=True)

# Realizar la división y convertir a porcentaje
regularidad['IRI (%)'] = (regularidad['Viaje Regular'] / regularidad['Viaje Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
regularidad['Regularidad (%)'] = regularidad['IRI (%)'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
regularidad.rename(columns={'Fecha Viaje': 'Fecha'}, inplace=True)

regularidad.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,102,156,65.384615,65
1,01/03/2026,ESTEBAN CAMILO MEDINA,179,190,94.210526,94
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,152,221,68.778281,69
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,93,157,59.235669,59
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,85,107,79.439252,79

Kilometros personal de control (SAE _ FMS)

In [260]:
# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en tipo día
tipo_dia['Fecha'] = pd.to_datetime(tipo_dia['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
tipo_dia['Fecha'] = tipo_dia['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
tipo_dia.head()

        Fecha      Día Tipo Día
0  01/01/2016  Viernes  Festivo
1  02/01/2016   Sábado   Sábado
2  03/01/2016  Domingo  Festivo
3  04/01/2016    Lunes    Hábil
4  05/01/2016   Martes    Hábil

In [261]:
#FMS

# Convertir la columna 'Fecha' al formato de fecha y luego formatearla como 'dd/MM/yyyy' en asistencia
desglosados_fms['Fecha'] = pd.to_datetime(desglosados_fms['Fecha'], format='%d/%m/%Y', errors='coerce')

# Formatear la fecha para que siempre tenga dos dígitos en día y mes
desglosados_fms['Fecha'] = desglosados_fms['Fecha'].dt.strftime('%d/%m/%Y')

# Verificar el resultado
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DistNoRealizada,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar
0,01/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,0,11790,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,0,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,0,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,0,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0

In [262]:
#Llevar tipo día a desglosados FMS

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Tipo dia'] = desglosados_fms.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,KmEjecutado,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia
0,01/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,11790,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0,Festivo
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,10904,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,10904,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,10904,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo

In [263]:
# Función para obtener la letra inicial de cada palabra FMS
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
desglosados_fms['Tipo_dia'] = desglosados_fms['Tipo dia'].apply(obtener_letra_inicial)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0,Festivo,F
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F

In [264]:
#Tipo de dato a entero FMS

desglosados_fms['Id Línea '] = desglosados_fms['Id Línea '].astype(int)
desglosados_fms['Ruta '] = desglosados_fms['Ruta '].astype(int)
desglosados_fms['KmEjecutado'] = desglosados_fms['KmEjecutado'].astype(int)
desglosados_fms['KmProgAd'] = desglosados_fms['KmProgAd'].astype(int)
desglosados_fms['KmElimado'] = desglosados_fms['KmElimado'].astype(int)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
0,01/03/2026,ENGATIVA ZN,NaN,(105) GMOVIL ENGATIVA,20260301-AD0691017-1-12746,AD0691017,1,1,1,10691,...,No,NaN,NaN,NaN,"3, 8",NaN,100.0,1.0,Festivo,F
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F

In [265]:
# Filtrar todo lo que no sea vacío ni NaN
desglosados_fms = desglosados_fms[
    desglosados_fms['Hora Ini Teorica '].notna() & 
    (desglosados_fms['Hora Ini Teorica '].astype(str).str.strip() != "")
]

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,DespInicial,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,Si,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,No,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,No,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,No,NaN,NaN,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F

In [266]:
# Extraer la hora y convertirla a entero FMS
desglosados_fms['Hora'] = desglosados_fms['Hora Ini Teorica '].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
desglosados_fms['Hora'] = desglosados_fms['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Puntualidad Preliminar,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,NaN,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,6
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,NaN,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,7
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,NaN,NaN,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F,7

In [267]:
#Traer el turno de control FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_moto_aux['Linea'] == Linea)&
        (turno_moto_aux['Ruta_SAE'] == Ruta_SAE)&
        (turno_moto_aux['Franja'] == Franja)&
        (turno_moto_aux['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_moto_aux.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_moto_aux.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_moto'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,IdValPuntualidad,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_moto
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,None
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,NaN,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,None
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,6,MR
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,NaN,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,7,MR
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,NaN,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F,7,MR

In [268]:
#Traer el turno de control FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_ccz['Linea'] == Linea)&
        (turno_ccz['Ruta_SAE'] == Ruta_SAE)&
        (turno_ccz['Franja'] == Franja)&
        (turno_ccz['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_ccz.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_ccz.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Cumplimiento Preliminar,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_moto,Turno_ccz
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,None,ET3N
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,NaN,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,None,ET3N
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,6,MR,ET3N
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,NaN,"3, 3",CDZ4,100.0,1.0,Festivo,F,7,MR,None
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,NaN,"3, 4",CDZ4,100.0,1.0,Festivo,F,7,MR,None

In [269]:
#Traer el turno de vía FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_via['Linea'] == Linea)&
        (turno_via['Ruta_SAE'] == Ruta_SAE)&
        (turno_via['Franja'] == Franja)&
        (turno_via['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_via.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_via.loc[filtro, 'Turno'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,FraHorCump,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_moto,Turno_ccz,Turno_via
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,None,ET3N,None
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,"3, 2",CDZ4,100.0,1.0,Festivo,F,5,None,ET3N,None
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,"3, 3",CDZ4,100.0,1.0,Festivo,F,6,MR,ET3N,EG23
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,"3, 3",CDZ4,100.0,1.0,Festivo,F,7,MR,None,EG23
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,"3, 4",CDZ4,100.0,1.0,Festivo,F,7,MR,None,EG23

In [270]:
#Traer el turno de supervisor FMS

def calcular_turno(Linea,Ruta_SAE,Franja,Tipo_Dia):
    
    filtro = (
        (turno_sup['Linea'] == Linea)&
        (turno_sup['Ruta_SAE'] == Ruta_SAE)&
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['Turno_sup'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Id Línea '],
        row['Ruta '],
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,IdValCumplimiento,ICK Full Preliminar,ICK Preliminar,Tipo dia,Tipo_dia,Hora,Turno_moto,Turno_ccz,Turno_via,Turno_sup
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,CDZ4,100.0,1.0,Festivo,F,5,None,ET3N,None,SUP CCZ
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,CDZ4,100.0,1.0,Festivo,F,5,None,ET3N,None,SUP CCZ
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,CDZ4,100.0,1.0,Festivo,F,6,MR,ET3N,EG23,SUP CCZ
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,CDZ4,100.0,1.0,Festivo,F,7,MR,None,EG23,SUP CCZ
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,CDZ4,100.0,1.0,Festivo,F,7,MR,None,EG23,SUP CCZ

In [271]:
#Traer el regulador de control según el turno FMS

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_ccz'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_ccz']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['reg_via'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_via']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['supervisor'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

# Aplica la función a las columnas correspondientes
desglosados_fms['motoregulador'] = desglosados_fms.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_moto']
    ),
    axis=1
)

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Tipo_dia,Hora,Turno_moto,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,motoregulador
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,F,5,None,ET3N,None,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,None
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,F,5,None,ET3N,None,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,None
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,F,6,MR,ET3N,EG23,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,F,7,MR,None,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,F,7,MR,None,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ

In [272]:
# Crear una nueva columna con la suma de las columnas kiloemtros planificados y adicionales FMS
desglosados_fms['Kilómetros Totales'] = desglosados_fms['KmProgAd']

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Hora,Turno_moto,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,motoregulador,Kilómetros Totales
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,5,None,ET3N,None,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,None,10904
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,5,None,ET3N,None,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,None,10904
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,6,MR,ET3N,EG23,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ,10904
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,7,MR,None,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ,10904
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,7,MR,None,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ,10904

In [273]:
# Realizar la división y convertir a porcentaje FMS
desglosados_fms['Kilómetros (%)'] = (desglosados_fms['KmEjecutado'] / desglosados_fms['Kilómetros Totales']) * 100

desglosados_fms.head()

,Fecha,Concesión,Concesionario de Operación Planificado,Concesionario de Operación Real,ServViaje,Servicio,Orden Viaje,Id Viaje,Viaje Línea,Id Línea,...,Turno_moto,Turno_ccz,Turno_via,Turno_sup,reg_ccz,reg_via,supervisor,motoregulador,Kilómetros Totales,Kilómetros (%)
1,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-1-10533,CE0650001,1,2,1,10266,...,None,ET3N,None,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,None,10904,100.0
2,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-2-10533,CE0650001,2,3,2,10266,...,None,ET3N,None,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,None,10904,100.0
3,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-3-10533,CE0650001,3,4,3,10266,...,MR,ET3N,EG23,SUP CCZ,MARTHA IBETH MARTIN MARTIN,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ,10904,100.0
4,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-4-10533,CE0650001,4,5,4,10266,...,MR,None,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ,10904,100.0
5,01/03/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,(105) GMOVIL ENGATIVA,20260301-CE0650001-5-10533,CE0650001,5,6,5,10266,...,MR,None,EG23,SUP CCZ,None,None,CAMILO ANDRES LOPEZ PENAGOS,EDWIN ECHEVERRI GOMEZ,10904,100.0

In [274]:
#Copias de los dataframes FMS

desglosados_fms1 = desglosados_fms.copy()
desglosados_fms2 = desglosados_fms.copy()
desglosados_fms3 = desglosados_fms.copy()
desglosados_fms7 = desglosados_fms.copy()

In [275]:
#Kilometros por regulador de control FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms1 = desglosados_fms1.groupby(['Fecha', 'reg_ccz']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

desglosados_fms1.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,7333542,5383161
1,01/03/2026,ESTEBAN CAMILO MEDINA,1644212,1575567
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,9856835,7229628
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,7321891,5019211
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,5420118,4185482

In [276]:
#Kilometros por regulador de via FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms2 = desglosados_fms2.groupby(['Fecha', 'reg_via']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms2.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

desglosados_fms2.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,3080419,2983664
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,5380337,4210995
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,4088852,3090363
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,5827810,4352113
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,3819149,3050194

In [277]:
#Kilometros por supervisor FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms3 = desglosados_fms3.groupby(['Fecha', 'supervisor']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms3.rename(columns={'supervisor': 'reg_ccz'}, inplace=True)

desglosados_fms3.head()

        Fecha                         reg_ccz  Kilómetros Totales  KmEjecutado
0  01/03/2026     CAMILO ANDRES LOPEZ PENAGOS            65816432     53413477
1  02/03/2026     CAMILO ANDRES LOPEZ PENAGOS            36760268     30336298
2  02/03/2026  LISETH GERALDINE GARCIA GARZÓN            76831721     63534239
3  03/03/2026     CAMILO ANDRES LOPEZ PENAGOS            76831721     58953907
4  03/03/2026  LISETH GERALDINE GARCIA GARZÓN            36760268     28203155

In [278]:
#Kilometros por supervisor FMS

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación personalizadas
desglosados_fms7 = desglosados_fms7.groupby(['Fecha', 'motoregulador']).agg({
    'Kilómetros Totales': 'sum',
    'KmEjecutado': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms7.rename(columns={'motoregulador': 'reg_ccz'}, inplace=True)

desglosados_fms7.head()

        Fecha                         reg_ccz  Kilómetros Totales  KmEjecutado
0  01/03/2026           EDWIN ECHEVERRI GOMEZ            37119675     30161711
1  02/03/2026           EDWIN ECHEVERRI GOMEZ            58084773     46651750
2  02/03/2026  JUAN CAMILO ARCINIEGAS QUIROGA            43022726     35694240
3  03/03/2026           EDWIN ECHEVERRI GOMEZ            58084773     40898286
4  03/03/2026  JUAN CAMILO ARCINIEGAS QUIROGA            43022726     33450227

In [279]:
#Consolidar los dos dataframe para validar KM FMS

kilometros_fms = pd.concat([desglosados_fms1,desglosados_fms2, desglosados_fms3, desglosados_fms7], ignore_index=True)

# Realizar la división y convertir a porcentaje
kilometros_fms['Kilómetros (%)'] = (kilometros_fms['KmEjecutado'] / kilometros_fms['Kilómetros Totales']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
kilometros_fms['Kilómetros (%)'] = kilometros_fms['Kilómetros (%)'].round(0).astype(int)

kilometros_fms.head()

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,7333542,5383161,73
1,01/03/2026,ESTEBAN CAMILO MEDINA,1644212,1575567,96
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,9856835,7229628,73
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,7321891,5019211,69
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,5420118,4185482,77

In [280]:
# Consolidar todos los DataFrames en uno solo

kilometros = pd.concat([kilometros_fms], ignore_index=True)

kilometros

,Fecha,reg_ccz,Kilómetros Totales,KmEjecutado,Kilómetros (%)
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,7333542,5383161,73
1,01/03/2026,ESTEBAN CAMILO MEDINA,1644212,1575567,96
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,9856835,7229628,73
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,7321891,5019211,69
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,5420118,4185482,77
...,...,...,...,...,...
1428,17/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,43053112,34049630,79
1429,18/03/2026,EDWIN ECHEVERRI GOMEZ,57879787,39251535,68
1430,18/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,43053112,35009135,81
1431,19/03/2026,EDWIN ECHEVERRI GOMEZ,57879787,44889965,78
1432,19/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,43053112,34258701,80

In [281]:
isv.head()

,Fecha,reg_ccz,accidentes_nivel_1,accidentes_nivel_2,accidentes_nivel_3
0,02/03/2026,CAMILO ANDRES LOPEZ PENAGOS,4,0,0
1,02/03/2026,DIANA CAROLINA MELO PRIETO,2,0,0
2,02/03/2026,EDWIN ECHEVERRI GOMEZ,1,0,0
3,02/03/2026,HENRY OCTAVIO BENAVIDES RAMIREZ,1,0,0
4,02/03/2026,JENNY ALEXANDRA BERNAL BERNAL,1,0,0

ISV-KMS

In [282]:
#Traer los kms por día al isv

def calcular_turno(fecha, nombre):
    
    filtro = (
        (kilometros['Fecha'] == fecha) &
        (kilometros['reg_ccz'] == nombre)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not kilometros.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = kilometros.loc[filtro, 'KmEjecutado'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
isv['KmEjecutado'] = isv.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

isv['KmEjecutado'] = (
    pd.to_numeric(
        isv['KmEjecutado'],
        errors='coerce'
    )
    .fillna(0)
    .astype(int)
)

isv.head(2)

,Fecha,reg_ccz,accidentes_nivel_1,accidentes_nivel_2,accidentes_nivel_3,KmEjecutado
0,02/03/2026,CAMILO ANDRES LOPEZ PENAGOS,4,0,0,30336298
1,02/03/2026,DIANA CAROLINA MELO PRIETO,2,0,0,0

In [283]:
# Calcular ISV

isv['ISV'] = (
    (
        (
            isv['accidentes_nivel_1'] * 1
        ) +
        (
            isv['accidentes_nivel_2'] * 3
        ) +
        (
            isv['accidentes_nivel_3'] * 18
        )
    )
    * 1000000
) / (
    isv['KmEjecutado'] +
    isv['KmEjecutado']
)

# Reemplazar infinitos y nulos
isv['ISV'] = (
    isv['ISV']
    .replace([float('inf'), -float('inf')], 0)
    .fillna(0)
)

# Redondear
isv['ISV'] = isv['ISV'].round(2)

isv[['Fecha', 'reg_ccz', 'ISV']].head()

isv.head()

,Fecha,reg_ccz,accidentes_nivel_1,accidentes_nivel_2,accidentes_nivel_3,KmEjecutado,ISV
0,02/03/2026,CAMILO ANDRES LOPEZ PENAGOS,4,0,0,30336298,0.07
1,02/03/2026,DIANA CAROLINA MELO PRIETO,2,0,0,0,0.00
2,02/03/2026,EDWIN ECHEVERRI GOMEZ,1,0,0,46651750,0.01
3,02/03/2026,HENRY OCTAVIO BENAVIDES RAMIREZ,1,0,0,2970569,0.17
4,02/03/2026,JENNY ALEXANDRA BERNAL BERNAL,1,0,0,3133568,0.16

ICO - KMS

In [284]:
#Traer los kms por día al ICO

def calcular_turno(fecha, nombre):
    
    filtro = (
        (kilometros['Fecha'] == fecha) &
        (kilometros['reg_ccz'] == nombre)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not kilometros.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = kilometros.loc[filtro, 'KmEjecutado'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
ico_proc['KmEjecutado'] = ico_proc.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

ico_proc['KmEjecutado'] = (
    pd.to_numeric(
        ico_proc['KmEjecutado'],
        errors='coerce'
    )
    .fillna(0)
    .astype(int)
)

ico_proc.head(2)

,Fecha,reg_ccz,cantidad_novedades,total_puntos,KmEjecutado
0,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,1,15,4210995
1,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,1,10,3090363

In [285]:
#Cálculo de porcentaje
ico_proc['ICO'] = (
    (
        ico_proc['total_puntos'] * 1000000
    ) /
    ico_proc['KmEjecutado']
).replace(
    [np.inf, -np.inf],
    0
).fillna(0).round(2)

ico_proc.head()

,Fecha,reg_ccz,cantidad_novedades,total_puntos,KmEjecutado,ICO
0,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,1,15,4210995,3.56
1,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,1,10,3090363,3.24
2,01/03/2026,CAMILO ANDRES LOPEZ PENAGOS,7,90,53413477,1.68
3,01/03/2026,EDWIN ECHEVERRI GOMEZ,7,90,30161711,2.98
4,01/03/2026,FRANCY LINNE TIMARAN CUESTA,1,15,7229628,2.07

ICD despachos personal de control

In [286]:
#Copias de los dataframes FMS

desglosados_fms4 = desglosados_fms.copy()
desglosados_fms5 = desglosados_fms.copy()
desglosados_fms6 = desglosados_fms.copy()
desglosados_fms8 = desglosados_fms.copy()

In [287]:
# Crear columnas binarias antes del groupby
desglosados_fms4['despachos_prog'] = np.where(
    desglosados_fms4['Kilómetros Totales'].notna() &
    (desglosados_fms4['Kilómetros Totales'] != 0),
    1,
    0
)

desglosados_fms4['despachos_ejecutados'] = np.where(
    desglosados_fms4['KmEjecutado'] == 0,
    0,
    1
)

# Agrupar por Fecha y reg_ccz
desglosados_fms4 = desglosados_fms4.groupby(
    ['Fecha', 'reg_ccz']
).agg({
    'despachos_prog': 'sum',
    'despachos_ejecutados': 'sum'
}).reset_index()

desglosados_fms4.head()

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,195,145
1,01/03/2026,ESTEBAN CAMILO MEDINA,169,164
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,263,199
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,179,130
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,136,103

In [288]:
# Crear columnas binarias antes del groupby
desglosados_fms5['despachos_prog'] = np.where(
    desglosados_fms5['Kilómetros Totales'].notna() &
    (desglosados_fms5['Kilómetros Totales'] != 0),
    1,
    0
)

desglosados_fms5['despachos_ejecutados'] = np.where(
    desglosados_fms5['KmEjecutado'] == 0,
    0,
    1
)


# Agrupar por Fecha y reg_ccz
desglosados_fms5 = desglosados_fms5.groupby(
    ['Fecha', 'reg_via']
).agg({
    'despachos_prog': 'sum',
    'despachos_ejecutados': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms5.rename(columns={'reg_via': 'reg_ccz'}, inplace=True)

desglosados_fms5.head()

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,345,343
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,156,127
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,104,81
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,142,107
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,109,89

In [289]:
# Crear columnas binarias antes del groupby
desglosados_fms6['despachos_prog'] = np.where(
    desglosados_fms6['Kilómetros Totales'].notna() &
    (desglosados_fms6['Kilómetros Totales'] != 0),
    1,
    0
)

desglosados_fms6['despachos_ejecutados'] = np.where(
    desglosados_fms6['KmEjecutado'] == 0,
    0,
    1
)


# Agrupar por Fecha y reg_ccz
desglosados_fms6 = desglosados_fms6.groupby(
    ['Fecha', 'supervisor']
).agg({
    'despachos_prog': 'sum',
    'despachos_ejecutados': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms6.rename(columns={'supervisor': 'reg_ccz'}, inplace=True)

desglosados_fms6.head()

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados
0,01/03/2026,CAMILO ANDRES LOPEZ PENAGOS,2271,1986
1,02/03/2026,CAMILO ANDRES LOPEZ PENAGOS,1055,897
2,02/03/2026,LISETH GERALDINE GARCIA GARZÓN,2736,2411
3,03/03/2026,CAMILO ANDRES LOPEZ PENAGOS,2736,2295
4,03/03/2026,LISETH GERALDINE GARCIA GARZÓN,1055,836

In [290]:
# Crear columnas binarias antes del groupby
desglosados_fms8['despachos_prog'] = np.where(
    desglosados_fms8['Kilómetros Totales'].notna() &
    (desglosados_fms8['Kilómetros Totales'] != 0),
    1,
    0
)

desglosados_fms8['despachos_ejecutados'] = np.where(
    desglosados_fms8['KmEjecutado'] == 0,
    0,
    1
)


# Agrupar por Fecha y reg_ccz
desglosados_fms8 = desglosados_fms8.groupby(
    ['Fecha', 'motoregulador']
).agg({
    'despachos_prog': 'sum',
    'despachos_ejecutados': 'sum'
}).reset_index()

# Renombrar la columna 'reg_via' a 'reg_ccz'
desglosados_fms8.rename(columns={'motoregulador': 'reg_ccz'}, inplace=True)

desglosados_fms8.head()

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados
0,01/03/2026,EDWIN ECHEVERRI GOMEZ,1241,1089
1,02/03/2026,EDWIN ECHEVERRI GOMEZ,1852,1582
2,02/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,1427,1246
3,03/03/2026,EDWIN ECHEVERRI GOMEZ,1852,1439
4,03/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,1427,1186

In [291]:
#Consolidar los dos dataframe para validar KM FMS

despachos_fms = pd.concat([desglosados_fms4,desglosados_fms5, desglosados_fms6, desglosados_fms8], ignore_index=True)

despachos_fms.head()

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,195,145
1,01/03/2026,ESTEBAN CAMILO MEDINA,169,164
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,263,199
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,179,130
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,136,103

In [292]:
# Realizar la división y convertir a porcentaje
despachos_fms['CumplimientO_ICD (%)'] = (despachos_fms['despachos_ejecutados'] / despachos_fms['despachos_prog']) * 100

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' al entero más cercano
despachos_fms['CumplimientO_ICD (%)'] = despachos_fms['CumplimientO_ICD (%)'].round(0).astype(int)

despachos_fms.head()

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados,CumplimientO_ICD (%)
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,195,145,74
1,01/03/2026,ESTEBAN CAMILO MEDINA,169,164,97
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,263,199,76
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,179,130,73
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,136,103,76

In [293]:
# Consolidar todos los DataFrames en uno solo

despachos_icd = pd.concat([despachos_fms], ignore_index=True)

despachos_icd

,Fecha,reg_ccz,despachos_prog,despachos_ejecutados,CumplimientO_ICD (%)
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,195,145,74
1,01/03/2026,ESTEBAN CAMILO MEDINA,169,164,97
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,263,199,76
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,179,130,73
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,136,103,76
...,...,...,...,...,...
1428,17/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,1428,1220,85
1429,18/03/2026,EDWIN ECHEVERRI GOMEZ,1847,1383,75
1430,18/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,1428,1236,87
1431,19/03/2026,EDWIN ECHEVERRI GOMEZ,1847,1533,83
1432,19/03/2026,JUAN CAMILO ARCINIEGAS QUIROGA,1428,1232,86

Indicadores de fonias de personal de control

In [294]:
#Traer el supervisor según el turno

def calcular_turno(nombre):
    
    filtro = (
        (base['RegC'] == nombre)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base.loc[filtro, 'RegControl'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['reg_ccz'] = fonias.apply(
    lambda row: calcular_turno(
        row['Nombre Usuario']
    ),
    axis=1
)

fonias.head(2)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,NaN,0.5,1.0,04:05:00,04:06:00,04:07:00,00:01:00,00:01:22,NaN,None
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,NaN,NaN,0.0,04:07:00,04:07:00,04:08:00,00:00:00,00:00:03,NaN,None

In [295]:
# Reemplazar valores vacíos y '(en blanco)' con '00:00:00' en las columnas 'TRM' y 'Duración'
fonias['TMR'] = fonias['TMR'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['Duración'] = fonias['Duración'].replace({'': '00:00:00', '(en blanco)': '00:00:00'})
fonias['No Asignado'] = fonias['No Asignado'].replace({'': 0, '(en blanco)': 0})

fonias.head(3)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,ServBus,Cumplimiento,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,NaN,0.5,1.0,04:05:00,04:06:00,04:07:00,00:01:00,00:01:22,NaN,None
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,NaN,NaN,0.0,04:07:00,04:07:00,04:08:00,00:00:00,00:00:03,NaN,None
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,NaN,NaN,0.0,05:04:00,05:04:00,05:04:00,00:00:00,00:00:18,NaN,None

In [296]:
# Asegúrate de que todas las entradas sean cadenas de texto
fonias['TMR'] = fonias['TMR'].astype(str)
fonias['Duración'] = fonias['Duración'].astype(str)

# Convertir las columnas 'TRM' y 'Duración' a formato timedelta
fonias['TMR'] = pd.to_timedelta(fonias['TMR'], errors='coerce')
fonias['Duración'] = pd.to_timedelta(fonias['Duración'], errors='coerce')

# Convertir los tiempos a segundos
fonias['TMR_segundos'] = fonias['TMR'].dt.total_seconds()
fonias['Duración_segundos'] = fonias['Duración'].dt.total_seconds()

# Reemplazar los valores NaN con 0
fonias['TMR_segundos'].fillna(0, inplace=True)
fonias['Duración_segundos'].fillna(0, inplace=True)

# Pasar a enteros
fonias['TMR_segundos'] = fonias['TMR_segundos'].astype(int)
fonias['Duración_segundos'] = fonias['Duración_segundos'].astype(int)

# Mostrar el DataFrame resultante
fonias.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3360421227.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3360421227.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias['Duración_segundos'].fillna(0, inplace=True)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,No Asignado,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,1.0,04:05:00,04:06:00,04:07:00,0 days 00:01:00,0 days 00:01:22,NaN,None,60,82
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0.0,04:07:00,04:07:00,04:08:00,0 days 00:00:00,0 days 00:00:03,NaN,None,0,3
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,...,0.0,05:04:00,05:04:00,05:04:00,0 days 00:00:00,0 days 00:00:18,NaN,None,0,18

In [297]:
#Llevar tipo día a fonias

def calcular_posicion(fecha):
    
    filtro = (
        (tipo_dia['Fecha'] == fecha)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not tipo_dia.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = tipo_dia.loc[filtro, 'Tipo Día'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Tipo dia'] = fonias.apply(
    lambda row: calcular_posicion(
        row['Fecha']
    ),
    axis=1
)

fonias.head(2)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Petición,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,04:05:00,04:06:00,04:07:00,0 days 00:01:00,0 days 00:01:22,NaN,None,60,82,Festivo
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,04:07:00,04:07:00,04:08:00,0 days 00:00:00,0 days 00:00:03,NaN,None,0,3,Festivo

In [298]:
# Función para obtener la letra inicial de cada palabra
def obtener_letra_inicial(texto):
    if pd.isnull(texto):  # Manejar valores None o NaN
        return ''
    palabras = texto.split()
    iniciales = [palabra[0] for palabra in palabras]
    return ''.join(iniciales)

# Aplicar la función a la columna 'Tipo día'
fonias['Tipo_dia'] = fonias['Tipo dia'].apply(obtener_letra_inicial)

fonias.head(2)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Apertura,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,04:06:00,04:07:00,0 days 00:01:00,0 days 00:01:22,NaN,None,60,82,Festivo,F
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,04:07:00,04:08:00,0 days 00:00:00,0 days 00:00:03,NaN,None,0,3,Festivo,F

In [299]:
# Extraer la hora y convertirla a entero

# las entradas sean cadenas de texto
fonias['Hora Petición'] = fonias['Hora Petición'].astype(str)

# Extraer la hora y convertirla a entero
fonias['Hora'] = fonias['Hora Petición'].str.split(':').str[0].astype(int)

# Reemplazar 24 por 0 y 25 por 1
fonias['Hora'] = fonias['Hora'].replace({24: 0, 25: 1,26: 2})

# Verificar el resultado y el tipo de dato
fonias.head(2)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Hora Cierre,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,04:07:00,0 days 00:01:00,0 days 00:01:22,NaN,None,60,82,Festivo,F,4
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,04:08:00,0 days 00:00:00,0 days 00:00:03,NaN,None,0,3,Festivo,F,4

In [300]:
#Traer el turno de supervisor

def calcular_turno(Franja,Tipo_Dia):
    
    filtro = (
        
        (turno_sup['Franja'] == Franja)&
        (turno_sup['Tipo Dia'] == Tipo_Dia)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not turno_sup.loc[filtro].empty:
        # Obtener el primer valor
        turnos = turno_sup.loc[filtro, 'Estacion'].iloc[0]
        return turnos if not pd.isna(turnos) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Turno_sup'] = fonias.apply(
    lambda row: calcular_turno(
        
        row['Hora'],
        row['Tipo_dia']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,TMR,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:01:00,0 days 00:01:22,NaN,None,60,82,Festivo,F,4,SUP CCZ
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:00:00,0 days 00:00:03,NaN,None,0,3,Festivo,F,4,SUP CCZ
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,...,0 days 00:00:00,0 days 00:00:18,NaN,None,0,18,Festivo,F,5,SUP CCZ
36996,01/03/2026,507118,Si,Emergencia,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,SE14,0,...,0 days 00:00:00,0 days 00:00:35,NaN,None,0,35,Festivo,F,5,SUP CCZ
36997,01/03/2026,502095,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,C101,0,...,0 days 00:02:00,0 days 00:00:15,NaN,None,120,15,Festivo,F,5,SUP CCZ

In [301]:
#Traer el supervisor según el turno

def calcular_turno(Fecha,TURNO_Programado):
    
    filtro = (
        (asistencia['Fecha'] == Fecha)&
        (asistencia['TURNO Programado'] == TURNO_Programado)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not asistencia.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = asistencia.loc[filtro, 'NOMBRE'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
fonias['Supervisor'] = fonias.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['Turno_sup']
    ),
    axis=1
)

fonias.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:01:22,NaN,None,60,82,Festivo,F,4,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:00:03,NaN,None,0,3,Festivo,F,4,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,...,0 days 00:00:18,NaN,None,0,18,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36996,01/03/2026,507118,Si,Emergencia,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,SE14,0,...,0 days 00:00:35,NaN,None,0,35,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36997,01/03/2026,502095,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,C101,0,...,0 days 00:00:15,NaN,None,120,15,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS

In [302]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_ser = fonias.copy()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)

fonias_ser['Duración_segundos'].fillna(0, inplace=True)

fonias_ser.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\2462281871.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\2462281871.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:01:22,NaN,None,60,82,Festivo,F,4,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:00:03,NaN,None,0,3,Festivo,F,4,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,...,0 days 00:00:18,NaN,None,0,18,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS

In [303]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_ser = fonias_ser.groupby(['Fecha', 'reg_ccz']).agg({
    'TMR_segundos':  mean_without_zeros,
    'Duración_segundos':  mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_ser['TMR_segundos'].fillna(0, inplace=True)
fonias_ser['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_ser['TMR_segundos'] = fonias_ser['TMR_segundos'].round(0).astype(int)
fonias_ser['Duración_segundos'] = fonias_ser['Duración_segundos'].round(0).astype(int)

fonias_ser.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3888450677.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3888450677.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_ser['Duración_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,01/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,41,0.0
1,02/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,58,0.0
2,03/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,31,0.0
3,04/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,40,0.0
4,05/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,23,0.0

In [304]:
#Copiar el dataframe para sacar por fecha y regulador el promedio de TMR, duración y la suma de No Asignados

fonias_1 = fonias.copy()

fonias_1.head()

,Fecha,Código,Petición Móvil,Urgente,Emergencia,Usuario,Nombre Usuario,Estado,Ruta,Viaje,...,Duración,Unnamed: 18,reg_ccz,TMR_segundos,Duración_segundos,Tipo dia,Tipo_dia,Hora,Turno_sup,Supervisor
36993,01/03/2026,504391,Si,Prioritaria,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:01:22,NaN,None,60,82,Festivo,F,4,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36994,01/03/2026,504391,No,Llamada normal,0,MDCASTRO_TM,MISSY DAYANNA CASTROÂ Â,Llamada terminada por el tÃ©cnico de control,NaN,0,...,0 days 00:00:03,NaN,None,0,3,Festivo,F,4,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36995,01/03/2026,504235,No,Llamada normal,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,12,0,...,0 days 00:00:18,NaN,None,0,18,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36996,01/03/2026,507118,Si,Emergencia,0,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,Llamada terminada por el tÃ©cnico de control,SE14,0,...,0 days 00:00:35,NaN,None,0,35,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS
36997,01/03/2026,502095,Si,Llamada normal,0,MMARTIN_105,MARTHA IBETH MARTIN MARTIN,Llamada terminada por el tÃ©cnico de control,C101,0,...,0 days 00:00:15,NaN,None,120,15,Festivo,F,5,SUP CCZ,CAMILO ANDRES LOPEZ PENAGOS

In [305]:
# Función personalizada para calcular el promedio sin contar los ceros
def mean_without_zeros(series):
    # Filtrar los valores diferentes de cero
    non_zero_values = series[series != 0]
    # Si no hay valores distintos de cero, devolver NaN
    if len(non_zero_values) == 0:
        return np.nan
    # Devolver el promedio de los valores no cero
    return non_zero_values.mean()

# Agrupar por 'Fecha' y 'reg_ccz', y aplicar las funciones de agregación
fonias_1 = fonias_1.groupby(['Fecha', 'Supervisor']).agg({
    'TMR_segundos': mean_without_zeros,
    'Duración_segundos': mean_without_zeros,
    'No Asignado': 'sum'
}).reset_index()

fonias_1['TMR_segundos'].fillna(0, inplace=True)
fonias_1['Duración_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
fonias_1['TMR_segundos'] = fonias_1['TMR_segundos'].round(0).astype(int)
fonias_1['Duración_segundos'] = fonias_1['Duración_segundos'].round(0).astype(int)

# Renombrar la columna 'Supervisor' a 'reg_ccz'
fonias_1.rename(columns={'Supervisor': 'reg_ccz'}, inplace=True)

fonias_1.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3334358817.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['TMR_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3334358817.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fonias_1['Duración_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,01/03/2026,CAMILO ANDRES LOPEZ PENAGOS,68,45,1.0
1,02/03/2026,LISETH GERALDINE GARCIA GARZÓN,71,39,0.0
2,03/03/2026,CAMILO ANDRES LOPEZ PENAGOS,75,39,0.0
3,04/03/2026,LISETH GERALDINE GARCIA GARZÓN,73,43,0.0
4,05/03/2026,LISETH GERALDINE GARCIA GARZÓN,96,42,0.0

In [306]:
#Consolidar los dos dataframe para validar fonias

fonias_fin = pd.concat([fonias_ser, fonias_1], ignore_index=True)

fonias_fin.head()

,Fecha,reg_ccz,TMR_segundos,Duración_segundos,No Asignado
0,01/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,41,0.0
1,02/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,58,0.0
2,03/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,31,0.0
3,04/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,40,0.0
4,05/03/2026,PAULA KATHERINE CANTOR SALAMANCA,60,23,0.0

Información de novedades

In [307]:
# Rellena los valores NaN en la columna
novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

# Convertir 'Nodo' a tipo entero
novedades['CODIGO OPERADOR'] = novedades['CODIGO OPERADOR'].astype(int)

novedades.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\2588241090.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  novedades['CODIGO OPERADOR'].fillna(0, inplace=True)

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
0,1054730,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,500029,19337415,ISRAEL MARTINEZ GONZALEZ,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Por Aprobar,NaN
1,1054731,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501161,79453992,ALEXANDER GARAVITO HERNANDEZ,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
2,1054732,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,501374,91538451,JESUS FLOREZ ALARCON,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
3,1054733,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,502645,79842026,MANUEL PISCO RODRIGUEZ,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS
4,1054734,31/03/2026,31/03/2026,1,Ausentismo,INCAPACIDAD,Patio Dorado,503030,71776641,ALBER MEJIA CARMONA,OPERADOR DE BIARTICULADO,NaN,0.0,NaN,NaN,2026-03-31 00:00:00 Novedad creada de forma au...,Aprobada,JAIRO DAVID CIFUENTES VARGAS

In [308]:
# Filtrar el DataFrame para obtener solo las filas donde 'CODIGO OPERADOR' sea diferente de 0
novedades = novedades[novedades['CODIGO OPERADOR'] == 0]

# Filtrar el DataFrame para eliminar las filas donde 'estado' es igual a 'Eliminada'
novedades = novedades[novedades['ESTADO'] != 'Eliminada']

novedades.head()

,ID NOVEDAD,FECHA INICIAL,FECHA FINAL,NRO DIAS,TIPO NOVEDAD,SUBTIPO DE NOVEDAD,PATIO,CODIGO OPERADOR,IDENTIFICACION,EMPLEADO,CARGO,USUARIO REGISTRA,PUNTAJE FINAL,PUNTAJE NEGOCIADO,CODIGO VEHICULO,HISTORICO COMENTARIOS,ESTADO,USUARIO APRUEBA
17,1055342,31/03/2026,31/03/2026,1,Gestión,NaN,Patio Dorado,0,1024494610,GLORIA ESPERANZA MESA REYES,REGULADOR DE VÍA,DIEGO ARTURO URIBE ROJAS,-30.0,NaN,Z50-4275,2026-03-31 11:24:27 Se presenta novedad con la...,Aprobada,DIEGO ARTURO URIBE ROJAS
20,1055408,31/03/2026,31/03/2026,1,Ausentismo,NO JUSTIFICADO,Patio Dorado,0,79501015,LUIS ENRIQUE MORA SIERRA,AUXILIAR LOGISTICO,JOSE ANTONIO CANGREJO BELTRAN,-100.0,NaN,NaN,2026-03-31 17:15:57 operador no se presenta a ...,Aprobada,MILTON GIOVANNY ARIAS ABRIL
25,1055613,31/03/2026,31/03/2026,1,Retardo,NaN,Patio Dorado,0,1002185518,LUIS ARCESIO NAVARRETE VARGAS,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,-30.0,NaN,NaN,2026-04-01 10:09:45 Se presenta a las 04:04 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL
26,1055614,31/03/2026,31/03/2026,1,Retardo,NaN,Patio Dorado,0,1014228633,LEIDY ESTEFANIA BARRERO CHAVEZ,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,-30.0,NaN,NaN,2026-04-01 10:10:08 Se presenta a las 13:37 ho...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL
27,1055616,31/03/2026,31/03/2026,1,Ausentismo,LICENCIA REMUNERADA,Patio Dorado,0,1022984691,BETSY MILENA DEDIOS HUERFANO,REGULADOR DE VÍA,DIANA CAROLINA MELO PRIETO,0.0,NaN,NaN,2026-04-01 10:11:01 INDICA TENER EL HIJO ENFER...,Aprobada,JONNY JESUS VILLARREAL VILLARREAL

In [309]:
#resumen por fecha y regulador según las novedades

# Crear columnas para cada tipo de novedad
novedades['Ausentismo'] = (novedades['TIPO NOVEDAD'] == 'Ausentismo').astype(int)
novedades['Retardo'] = (novedades['TIPO NOVEDAD'] == 'Retardo').astype(int)
novedades['Novedades'] = ~novedades['TIPO NOVEDAD'].isin(['Ausentismo', 'Retardo'])

# Agrupar por 'FECHA INICIAL' y 'REGULADOR', y contar las ocurrencias de cada tipo de novedad
novedades_fin = novedades.groupby(['FECHA INICIAL', 'EMPLEADO']).agg({
    'Ausentismo': 'sum',
    'Retardo': 'sum',
    'Novedades': 'sum'
}).reset_index()

# Renombrar la columna 'Supervisor' a 'reg_ccz'
novedades_fin.rename(columns={'FECHA INICIAL': 'Fecha'}, inplace=True)
novedades_fin.rename(columns={'EMPLEADO': 'reg_ccz'}, inplace=True)

# Mostrar el DataFrame resultante
novedades_fin.head()

,Fecha,reg_ccz,Ausentismo,Retardo,Novedades
0,01/03/2026,DIANA MARCELA AGUILERA MADRIGAL,0,1,0
1,02/03/2026,HENRY OCTAVIO BENAVIDES RAMIREZ,1,0,0
2,02/03/2026,LUIS ARCESIO NAVARRETE VARGAS,0,1,0
3,02/03/2026,SONIA CONSTANZA CORREA RODRIGUEZ,1,0,0
4,03/03/2026,LEIDY ESTEFANIA BARRERO CHAVEZ,0,1,0

Consolidar la data para validar la información

In [310]:
#copiar data de regularidad

indicadores = regularidad.copy()

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%)
0,01/03/2026,EDGAR ALEJANDRO RIOS CARDOZO,102,156,65.384615,65
1,01/03/2026,ESTEBAN CAMILO MEDINA,179,190,94.210526,94
2,01/03/2026,FRANCY LINNE TIMARAN CUESTA,152,221,68.778281,69
3,01/03/2026,JINETH ALEXANDRA GUZMAN HERNANDEZ,93,157,59.235669,59
4,01/03/2026,JULIAN ANDRES SANCHEZ RESTREPO,85,107,79.439252,79

In [311]:
# Cruce completo entre indicadores y kilometros
indicadores = indicadores.merge(
    kilometros[['Fecha', 'reg_ccz', 'Kilómetros (%)']],
    on=['Fecha', 'reg_ccz'],
    how='outer'
)

# Reemplazar vacíos numéricos por 0
columnas_numericas = [
    'Viaje Regular',
    'Viaje Totales',
    'IRI (%)',
    'Regularidad (%)',
    'Kilómetros (%)'
]

indicadores[columnas_numericas] = indicadores[columnas_numericas].fillna(0)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%)
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365.0,387.0,94.315245,94.0,97
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101.0,127.0,79.527559,80.0,78
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66.0,112.0,58.928571,59.0,76
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79.0,134.0,58.955224,59.0,75
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61.0,89.0,68.539326,69.0,80

In [312]:
# Convertir 'Nodo' a tipo entero
indicadores['Viaje Regular'] = indicadores['Viaje Regular'].astype(int)
indicadores['Viaje Totales'] = indicadores['Viaje Totales'].astype(int)
indicadores['Regularidad (%)'] = indicadores['Regularidad (%)'].astype(int)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%)
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80

In [313]:
isv.head()

,Fecha,reg_ccz,accidentes_nivel_1,accidentes_nivel_2,accidentes_nivel_3,KmEjecutado,ISV
0,02/03/2026,CAMILO ANDRES LOPEZ PENAGOS,4,0,0,30336298,0.07
1,02/03/2026,DIANA CAROLINA MELO PRIETO,2,0,0,0,0.00
2,02/03/2026,EDWIN ECHEVERRI GOMEZ,1,0,0,46651750,0.01
3,02/03/2026,HENRY OCTAVIO BENAVIDES RAMIREZ,1,0,0,2970569,0.17
4,02/03/2026,JENNY ALEXANDRA BERNAL BERNAL,1,0,0,3133568,0.16

In [314]:
#llevar ICo a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (isv['Fecha'] == Fecha)&
        (isv['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not isv.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = isv.loc[filtro, 'ISV'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['ISV (%)'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

indicadores['ISV (%)'] = (
    pd.to_numeric(
        indicadores['ISV (%)'],
        errors='coerce'
    )
    .fillna(0)
    .astype(int)
)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%)
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0

In [315]:
#llevar ICo a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (ico_proc['Fecha'] == Fecha)&
        (ico_proc['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not ico_proc.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = ico_proc.loc[filtro, 'ICO'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['ICO (%)'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

indicadores['ICO (%)'] = (
    pd.to_numeric(
        indicadores['ICO (%)'],
        errors='coerce'
    )
    .fillna(0)
    .astype(int)
)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%)
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0

In [316]:
#llevar KMS a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (despachos_icd['Fecha'] == Fecha)&
        (despachos_icd['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not despachos_icd.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = despachos_icd.loc[filtro, 'CumplimientO_ICD (%)'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['CumplimientO_ICD (%)'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

indicadores.head()

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%)
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82

In [317]:
# Primero convertir la columna a tipo fecha
irp_ccz['Fecha'] = pd.to_datetime(
    irp_ccz['Fecha'],
    errors='coerce'
)

# Luego convertir al formato dd/mm/yyyy
irp_ccz['Fecha'] = irp_ccz['Fecha'].dt.strftime('%d/%m/%Y')

irp_ccz.head()

        Fecha                            reg_ccz  CV_promedio
0  01/03/2026       EDGAR ALEJANDRO RIOS CARDOZO           68
1  01/03/2026              ESTEBAN CAMILO MEDINA           45
2  01/03/2026        FRANCY LINNE TIMARAN CUESTA           68
3  01/03/2026  JINETH ALEXANDRA GUZMAN HERNANDEZ           73
4  01/03/2026     JULIAN ANDRES SANCHEZ RESTREPO           54

In [318]:
#llevar KMS a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (irp_ccz['Fecha'] == Fecha)&
        (irp_ccz['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not irp_ccz.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = irp_ccz.loc[filtro, 'CV_promedio'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['CV_promedio'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['CV_promedio'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
indicadores['CV_promedio'] = indicadores['CV_promedio'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\1610197830.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['CV_promedio'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82,0

In [319]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'TMR_segundos'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['TMR_segundos'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['TMR_segundos'].fillna(0, inplace=True)

# Redondear las columnas 'TMR_segundos' y 'Duración_segundos' a 2 decimales
indicadores['TMR_segundos'] = indicadores['TMR_segundos'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\679954610.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['TMR_segundos'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81,0,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78,0,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82,0,0

In [320]:
#llevar fonias a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (fonias_fin['Fecha'] == Fecha)&
        (fonias_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not fonias_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = fonias_fin.loc[filtro, 'No Asignado'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['No Asignado'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['No Asignado'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['No Asignado'] = indicadores['No Asignado'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3884926540.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['No Asignado'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos,No Asignado
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99,0,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81,0,0,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78,0,0,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75,0,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82,0,0,0

In [321]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Ausentismo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Ausentismo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Ausentismo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Ausentismo'] = indicadores['Ausentismo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\2427483280.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Ausentismo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99,0,0,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81,0,0,0,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78,0,0,0,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75,0,0,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82,0,0,0,0

In [322]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Novedades'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Novedades'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Novedades'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Novedades'] = indicadores['Novedades'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\590017984.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Novedades'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99,0,0,0,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81,0,0,0,0,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78,0,0,0,0,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75,0,0,0,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82,0,0,0,0,0

In [323]:
#llevar novedades a indicadores

def calcular_turno(Fecha,reg):
    
    filtro = (
        (novedades_fin['Fecha'] == Fecha)&
        (novedades_fin['reg_ccz'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not novedades_fin.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = novedades_fin.loc[filtro, 'Retardo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
indicadores['Retardo'] = indicadores.apply(
    lambda row: calcular_turno(
        row['Fecha'],
        row['reg_ccz']
    ),
    axis=1
)

# Rellena los valores NaN 
indicadores['Retardo'].fillna(0, inplace=True)

# Redondear las columnas No Asignado a 2 decimales
indicadores['Retardo'] = indicadores['Retardo'].round(0).astype(int)

indicadores.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_27412\3046602996.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  indicadores['Retardo'].fillna(0, inplace=True)

,Fecha,reg_ccz,Viaje Regular,Viaje Totales,IRI (%),Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,365,387,94.315245,94,97,0,0,99,0,0,0,0,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,101,127,79.527559,80,78,0,3,81,0,0,0,0,0,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,66,112,58.928571,59,76,0,3,78,0,0,0,0,0,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,79,134,58.955224,59,75,0,0,75,0,0,0,0,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,61,89,68.539326,69,80,0,0,82,0,0,0,0,0,0

In [324]:
#Eliminar columnas que no se necesitan para el proceso

col_eliminar = ['Viaje Regular', 'Viaje Totales','IRI (%)']

indicadores= indicadores.drop(columns=col_eliminar)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,94,97,0,0,99,0,0,0,0,0,0
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,80,78,0,3,81,0,0,0,0,0,0
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,59,76,0,3,78,0,0,0,0,0,0
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,59,75,0,0,75,0,0,0,0,0,0
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,69,80,0,0,82,0,0,0,0,0,0

In [325]:
# Agrupar por 'reg_ccz' y contar los días únicos laborados
dias_laborados = indicadores.groupby('reg_ccz')['Fecha'].nunique()

# Crear una nueva columna en el DataFrame de indicadores con los días laborados
indicadores['Días Laborados'] = indicadores['reg_ccz'].map(dias_laborados)

indicadores.head()

,Fecha,reg_ccz,Regularidad (%),Kilómetros (%),ISV (%),ICO (%),CumplimientO_ICD (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,01/03/2026,ADRIANA YANETH RAMIREZ GALVAN,94,97,0,0,99,0,0,0,0,0,0,26
1,01/03/2026,AMANDA LUCIA RODRIGUEZ ARAUJO,80,78,0,3,81,0,0,0,0,0,0,19
2,01/03/2026,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,59,76,0,3,78,0,0,0,0,0,0,25
3,01/03/2026,ANETH MAYERLI CHONTAL VILLARRAGA,59,75,0,0,75,0,0,0,0,0,0,26
4,01/03/2026,CAMILO ALEJANDRO GONGORA SEPULVEDA,69,80,0,0,82,0,0,0,0,0,0,9

In [326]:
# Agrupar por 'reg_ccz' y aplicar las funciones de agregación necesarias
indicadores_f = indicadores.groupby('reg_ccz').agg({
    'Regularidad (%)': 'mean',
    'Kilómetros (%)': 'mean',
    'CumplimientO_ICD (%)': 'mean',
    'ICO (%)': 'mean',
    'ISV (%)': 'mean',
    'CV_promedio': 'mean',
    'TMR_segundos': 'mean',
    'No Asignado': 'sum',
    'Ausentismo': 'sum',
    'Novedades': 'sum',
    'Retardo': 'sum',
    'Días Laborados':'max'
}).reset_index()

# Redondear las columnas a 2 decimales
indicadores_f['Regularidad (%)'] = indicadores_f['Regularidad (%)'].round(0).astype(int)
indicadores_f['CumplimientO_ICD (%)'] = indicadores_f['CumplimientO_ICD (%)'].round(0).astype(int)
indicadores_f['Kilómetros (%)'] = indicadores_f['Kilómetros (%)'].round(0).astype(int)
indicadores_f['TMR_segundos'] = indicadores_f['TMR_segundos'].round(0).astype(int)
indicadores_f['CV_promedio'] = indicadores_f['CV_promedio'].round(0).astype(int)
indicadores_f['ICO (%)'] = indicadores_f['ICO (%)'].round(0).astype(int)

# Mostrar el DataFrame resultante
indicadores_f.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25

In [327]:
#copia de la data de indicadores 

calificacion = indicadores_f.copy()

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25

In [328]:
# Definir la función para convertir la lógica de Excel a Python
def convertir_regularidad(valor):
    if valor >= 84:
        return 100
    elif 80 <= valor < 84:
        return 75
    elif 74 <= valor < 80:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Regularidad (%)'
calificacion['IRI'] = calificacion['Regularidad (%)'].apply(convertir_regularidad)

# Mostrar el DataFrame resultante con la nueva columna
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0

In [329]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_kilometros(valor):
    if valor >= 95:
        return 100
    elif 90 <= valor < 95:
        return 75
    elif 80 <= valor < 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['ICD'] = calificacion['CumplimientO_ICD (%)'].apply(convertir_kilometros)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,ICD
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0,50
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50,50
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0,50
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50,50
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0,50

In [330]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_kilometros(valor):
    if valor >= 95:
        return 100
    elif 90 <= valor < 95:
        return 75
    elif 80 <= valor < 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['KM'] = calificacion['Kilómetros (%)'].apply(convertir_kilometros)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,ICD,KM
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0,50,50
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50,50,50
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0,50,50
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50,50,50
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0,50,50

In [331]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_tmr(valor):
    if valor <= 60:
        return 100
    elif 60 < valor <= 90:
        return 50
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['Fonias'] = calificacion['TMR_segundos'].apply(convertir_tmr)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,ICD,KM,Fonias
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0,50,50,100
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50,50,50,100
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0,50,50,100
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50,50,50,100
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0,50,50,100

In [332]:
# Duplicar la columna 'No Asignado'
calificacion['No Asignado %'] = calificacion['No Asignado']

# Nombres a excluir
excluir_nombres = ['DIEGO ARTURO URIBE ROJAS', 'CAMILO ANDRES LOPEZ PENAGOS', 'LISETH GERALDINE GARCIA GARZÓN']

# Filtrar el DataFrame para excluir estos nombres
calificacion_filtrado = calificacion[~calificacion['reg_ccz'].isin(excluir_nombres)]

# Encontrar el valor máximo en la columna 'No Asignado Modificado' del DataFrame filtrado
max_no_asignado = calificacion_filtrado['No Asignado %'].max()

# Asignar 5 al valor máximo y 0 al resto
calificacion['No Asignado %'] = calificacion['No Asignado %'].apply(lambda x: 5 if x == max_no_asignado else 0)

# Mostrar el DataFrame resultante
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,ICD,KM,Fonias,No Asignado %
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0,50,50,100,5
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50,50,50,100,5
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0,50,50,100,5
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50,50,50,100,5
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0,50,50,100,5

In [333]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_retardo(valor):
    if valor <= 0:
        return 100
    elif 1 >= valor <= 3:
        return 40
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Retardos'] = calificacion['Retardo'].apply(convertir_retardo)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,ICD,KM,Fonias,No Asignado %,% Retardos
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0,50,50,100,5,100
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50,50,50,100,5,100
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0,50,50,100,5,100
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50,50,50,100,5,0
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0,50,50,100,5,100

In [334]:
# Definir la función para convertir la lógica de Excel a Python para 'Kilómetros (%)'
def convertir_novedades(valor):
    if valor <= 0:
        return 100
    elif valor == 1:
        return 75
    elif valor == 2:
        return 50
    elif valor == 3:
        return 25
    else:
        return 0

# Aplicar la función a la columna 'Kilómetros (%)'
calificacion['% Novedades'] = calificacion['Novedades'].apply(convertir_novedades)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,Novedades,Retardo,Días Laborados,IRI,ICD,KM,Fonias,No Asignado %,% Retardos,% Novedades
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,0,0,15,0,50,50,100,5,100,100
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,0,0,26,50,50,50,100,5,100,100
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,0,0,10,0,50,50,100,5,100,100
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,0,3,19,50,50,50,100,5,0,100
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,0,0,25,0,50,50,100,5,100,100

In [335]:
#Sumar las novedades retardos y novedades

calificacion['Novedad'] = ((calificacion['% Novedades'] + calificacion['% Retardos']) / 2).astype(int)

# Calcular el promedio de las columnas mencionadas
calificacion['Total Calificación'] = calificacion[['IRI', 'KM', 'Fonias','Novedad']].mean(axis=1)

# Convertir el resultado a enteros si es necesario
calificacion['Total Calificación'] = calificacion['Total Calificación'].astype(int)

calificacion['Total'] = calificacion['Total Calificación'] + calificacion['No Asignado %']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,...,IRI,ICD,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,...,0,50,50,100,5,100,100,100,62,67
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,...,50,50,50,100,5,100,100,100,75,80
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,...,0,50,50,100,5,100,100,100,62,67
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,...,50,50,50,100,5,0,100,50,62,67
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,...,0,50,50,100,5,100,100,100,62,67

In [336]:
#Crear base auxiliar para llevar el cargo

base_personal = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/base_personal.csv', encoding='latin', delimiter=';')

base_personal.head()

                                Nombre                           Cargo
0     PAULA KATHERINE CANTOR SALAMANCA  REGULADOR EN CENTRO DE CONTROL
1         LUIS FERNANDO GONZALEZ REYES  REGULADOR EN CENTRO DE CONTROL
2         MAICOL ALEXANDER PITA BLANCO  REGULADOR EN CENTRO DE CONTROL
3  SANDRA CAROLINA VALERIANO SARMIENTO  REGULADOR EN CENTRO DE CONTROL
4                 ELICIA MONGUI DUARTE  REGULADOR EN CENTRO DE CONTROL

In [337]:
#Llevar el cargo a la base de calificacion

def calcular_turno(reg):
    
    filtro = (
        (base_personal['Nombre'] == reg)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not base_personal.loc[filtro].empty:
        # Obtener el primer valor
        asistencias = base_personal.loc[filtro, 'Cargo'].iloc[0]
        return asistencias if not pd.isna(asistencias) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
calificacion['Cargo'] = calificacion.apply(
    lambda row: calcular_turno(
        row['reg_ccz']
    ),
    axis=1
)

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,...,ICD,KM,Fonias,No Asignado %,% Retardos,% Novedades,Novedad,Total Calificación,Total,Cargo
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,...,50,50,100,5,100,100,100,62,67,REGULADOR EN CENTRO DE CONTROL
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,...,50,50,100,5,100,100,100,75,80,REGULADOR DE VÍA
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,...,50,50,100,5,100,100,100,62,67,REGULADOR DE VÍA
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,...,50,50,100,5,0,100,50,62,67,REGULADOR DE VÍA
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,...,50,50,100,5,100,100,100,62,67,REGULADOR DE VÍA

In [338]:
#Validación del 100% a que corresponde

# Calcular el 35% de las columnas 'IRI' y 'KM'
calificacion['IRI_35%'] = calificacion['IRI'] * 0.35
calificacion['KM_35%'] = calificacion['KM'] * 0.35
calificacion['fonias_20%'] = calificacion['Fonias'] * 0.20
calificacion['No Asignado_5%'] = calificacion['No Asignado %'] * 0.05
calificacion['Novedad_10%'] = calificacion['Novedad'] * 0.10


# Redondear las columnas a 2 decimales
calificacion['IRI_35%'] = calificacion['IRI_35%'].round(0).astype(int)
calificacion['KM_35%'] = calificacion['KM_35%'].round(0).astype(int)
calificacion['fonias_20%'] = calificacion['fonias_20%'].round(0).astype(int)
calificacion['No Asignado_5%'] =calificacion['No Asignado_5%'].round(2).astype(int)
calificacion['Novedad_10%'] =calificacion['Novedad_10%'].round(0).astype(int)

calificacion['Total_100%'] = calificacion['IRI_35%'] + calificacion['KM_35%'] + calificacion['fonias_20%'] + calificacion['No Asignado_5%'] + calificacion['Novedad_10%']

calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,...,Novedad,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,...,100,62,67,REGULADOR EN CENTRO DE CONTROL,0,18,20,0,10,48
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,...,100,75,80,REGULADOR DE VÍA,18,18,20,0,10,66
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,...,100,62,67,REGULADOR DE VÍA,0,18,20,0,10,48
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,...,50,62,67,REGULADOR DE VÍA,18,18,20,0,5,61
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,...,100,62,67,REGULADOR DE VÍA,0,18,20,0,10,48

In [339]:
# Total de días en el mes

# Calcular el 70% de los días laborados
umbral = 0.70 * total_dias_julio

# Revisar si los días laborados cumplen con la condición
calificacion['Cumple Condición'] = calificacion['Días Laborados'].apply(lambda x: 1 if x >= umbral else 0)

# Mostrar el DataFrame actualizado
calificacion.head()

,reg_ccz,Regularidad (%),Kilómetros (%),CumplimientO_ICD (%),ICO (%),ISV (%),CV_promedio,TMR_segundos,No Asignado,Ausentismo,...,Total Calificación,Total,Cargo,IRI_35%,KM_35%,fonias_20%,No Asignado_5%,Novedad_10%,Total_100%,Cumple Condición
0,ADRIANA PATRICIA TELLEZ VARELA,71,82,85,3,0.0,97,0,0,0,...,62,67,REGULADOR EN CENTRO DE CONTROL,0,18,20,0,10,48,0
1,ADRIANA YANETH RAMIREZ GALVAN,78,84,86,0,0.0,0,0,0,0,...,75,80,REGULADOR DE VÍA,18,18,20,0,10,66,1
2,ALEXANDRA MARTINEZ TAPIA,72,81,82,1,0.0,0,0,0,0,...,62,67,REGULADOR DE VÍA,0,18,20,0,10,48,0
3,AMANDA LUCIA RODRIGUEZ ARAUJO,78,80,82,4,0.0,0,0,0,0,...,62,67,REGULADOR DE VÍA,18,18,20,0,5,61,0
4,AMANDA PATRICIA RODRIGUEZ HERNANDEZ,72,82,83,2,0.0,0,0,0,0,...,62,67,REGULADOR DE VÍA,0,18,20,0,10,48,1

In [340]:
#Exportar archivo
calificacion.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores/calificacion_{mes_i}.csv', index=False)

In [341]:
#Exportar archivo
indicadores.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores//indicadores_{mes_i}.csv', index=False)

In [342]:
#Exportar archivo

kilometros.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores//kilometros_{mes_i}.csv', index=False)

In [343]:
novedades_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores//novedades_fin_{mes_i}.csv', index=False)

In [344]:
#Exportar archivo

fonias_fin.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores//fonias_{mes_i}.csv', index=False)

In [345]:
#Exportar archivo

iri.to_csv(f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Indicadores//regularidad_{mes_i}.csv", index=False)