In [1]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob
from nltk.sentiment import SentimentIntensityAnalyzer
import speech_recognition as sr
from pydub import AudioSegment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
from wordcloud import WordCloud
from collections import Counter
import re

c:\Users\Jonny Villareal\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

In [2]:
#Datos de filtros
fecha_i = '20260301'
fecha_f = '20260331'

mes = 'marzo'

In [3]:
#imprortar paradas

paradas = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Paraderos_Zonales_del_SITP.csv')

paradas.head(3)

,X,Y,objectid,cenefa,zona_sitp,nombre,via,direccion_bandera,localidad,longitud,latitud,consecutivo_zona,tipo_m_s,consola,panel,audio,zonas_nuevas,globalid,shape
0,1.001502e+06,1.010205e+06,1,001A00,00,C.C. Iserra 100,AC 100,AC 100 - KR 54,Barrios Unidos,-74.063971,4.688481,001,M,AC 100 - KR 54 (001A00),AC 100 - KR 54,Avenida Calle 100 Carrera 54,C,{1C0DBC4E-15BC-4BBE-BC16-5628077DBE2E},NaN
1,1.003505e+06,1.009719e+06,2,001A01,01,Br. Rincón del Chicó,AC 100,AC 100 - KR 13,Usaquén,-74.045914,4.684091,001,M,AC 100 - KR 13 (001A01),AC 100 - KR 13,Avenida Calle 100 Carrera 13,B,{60A22A44-AD56-4DF4-A3E6-6830B9FB0792},NaN
2,1.001238e+06,1.018098e+06,3,001A02,02,Gimnasio Iragua,AV. Boyacá,AV. Boyacá - AC 170,Suba,-74.066350,4.759867,001,S,AV. Boyacá - AC 170 (001A02),AV. Boyacá - AC 170,Avenida Boyacá Avenida Calle 170,C,{97155274-E4D5-45A4-891F-2DCA19FF10D9},NaN

In [4]:
# Ruta de la carpeta que contiene los archivos de actividad de bus zonal
ruta_carpeta = 'Z:/01 base_datos/08 varados FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_varados.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    notas = pd.concat(dataframes, ignore_index=True)

    # # Guardar el DataFrame consolidado en un nuevo archivo
    # desg_troncal.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_ago24.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
notas.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Servicio,Id de línea,Nombre Línea,N° Vehículo,Código Conductor,Nombre Conductor,ID Nota,Tipo Nota,Subtipo Nota,Subsubtipo Nota,Observaciones,Creado Por,Modificado Por
0,1/03/2026 3:10,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10292,577,0,0,,802826,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización de Desvío / ID 93132 / 01-03-2026...,WILLIAM MUNAR HUMBERTO GONZALEZ,WILLIAM MUNAR HUMBERTO GONZALEZ
1,1/03/2026 3:10,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10292,577,0,0,,802827,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 90406 / 01-03-2026 / ...,WILLIAM MUNAR HUMBERTO GONZALEZ,WILLIAM MUNAR HUMBERTO GONZALEZ
2,1/03/2026 3:14,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10325,576,0,0,,802828,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 87938 / 01-03-2026 / ...,WILLIAM MUNAR HUMBERTO GONZALEZ,WILLIAM MUNAR HUMBERTO GONZALEZ

In [6]:
#Filtrar por tipo nota igual a 'INTERRUPCION DE SERVICIO ZONAL', 'NOVEDADES SIRCI', 'RUTAS EN SEGUIMIENTO ESPECIAL'
notas = notas[notas["Tipo Nota"].isin([
    "INTERRUPCION DE SERVICIO ZONAL"
])]

notas.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Servicio,Id de línea,Nombre Línea,N° Vehículo,Código Conductor,Nombre Conductor,ID Nota,Tipo Nota,Subtipo Nota,Subsubtipo Nota,Observaciones,Creado Por,Modificado Por
0,1/03/2026 3:10,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10292,577,0,0,,802826,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización de Desvío / ID 93132 / 01-03-2026...,WILLIAM MUNAR HUMBERTO GONZALEZ,WILLIAM MUNAR HUMBERTO GONZALEZ
1,1/03/2026 3:10,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10292,577,0,0,,802827,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 90406 / 01-03-2026 / ...,WILLIAM MUNAR HUMBERTO GONZALEZ,WILLIAM MUNAR HUMBERTO GONZALEZ
2,1/03/2026 3:14,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10325,576,0,0,,802828,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 87938 / 01-03-2026 / ...,WILLIAM MUNAR HUMBERTO GONZALEZ,WILLIAM MUNAR HUMBERTO GONZALEZ

In [7]:
def parse_observacion(texto):
    if pd.isna(texto):
        return {}

    pares = re.findall(r'([^:/]+):\s*([^/]+)', texto)
    return {k.strip(): v.strip() for k, v in pares}

df_obs = notas["Observaciones"].apply(parse_observacion).apply(pd.Series)

df_obs.head(3)

,03,Paradas,Paraderos Omitidos,Reportado por,ID,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,05,...,02,R Reportado por,2026 10,DIRECCION,SENTIDO,AFECTACION,GESTION,2026 11,Siendo las 12,Siendo las 14
0,00,Entre 099D09_Carvajal - Hasta 510B09_Br. Alque...,3,RCC Willian Humberto Munar González,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00,NaN,NaN,NaN,90406,052A08: Hasta: 114A08,Occidente - Oriente,toman av. américas hasta carrera 76k retoman e...,Willian Humberto Munar González,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00,NaN,NaN,NaN,87938,330A08: Hasta: 541A08,Oriente - Occidente,Tomar por la Calle 53 Sur al Occidente Hasta l...,Willian Humberto Munar González,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def parse_observacion(texto):
    if pd.isna(texto):
        return {}

    pares = re.findall(r'([^:/]+):\s*([^/]+)', texto)
    return {k.strip(): v.strip() for k, v in pares}


# Parsear observaciones
df_obs = notas["Observaciones"].apply(parse_observacion).apply(pd.Series)

# Agregar columnas base
df_obs = pd.concat(
    [notas[["Fecha","Id de línea","Nombre Línea","ID Nota"]], df_obs],
    axis=1
)

df_obs.head(3)

,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,Desde,...,02,R Reportado por,2026 10,DIRECCION,SENTIDO,AFECTACION,GESTION,2026 11,Siendo las 12,Siendo las 14
0,1/03/2026 3:10,10292,577,802826,00,Entre 099D09_Carvajal - Hasta 510B09_Br. Alque...,3,RCC Willian Humberto Munar González,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/03/2026 3:10,10292,577,802827,00,NaN,NaN,NaN,90406,052A08: Hasta: 114A08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/03/2026 3:14,10325,576,802828,00,NaN,NaN,NaN,87938,330A08: Hasta: 541A08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_obs = df_obs.sort_values(by="ID", key=lambda x: x.isna())

df_obs.head(3)

,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,Desde,...,02,R Reportado por,2026 10,DIRECCION,SENTIDO,AFECTACION,GESTION,2026 11,Siendo las 12,Siendo las 14
2493,15/03/2026 1:29,10196,E25,850699,00,NaN,NaN,NaN,95735,050A00: Hasta: 227A00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3706,22/03/2026 1:30,10342,KB309,874377,00,NaN,NaN,NaN,82281,441A01: Hasta: 064A01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3705,22/03/2026 1:29,10342,KB309,874376,00,NaN,NaN,NaN,107762,355B00: Hasta: 913A00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_obs.insert(
    0,
    "tipo_evento",
    np.where(df_obs["ID"].notna() & (df_obs["ID"] != ""), "Desvios", "Novedades de ruta")
)

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,02,R Reportado por,2026 10,DIRECCION,SENTIDO,AFECTACION,GESTION,2026 11,Siendo las 12,Siendo las 14
2493,Desvios,15/03/2026 1:29,10196,E25,850699,00,NaN,NaN,NaN,95735,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3706,Desvios,22/03/2026 1:30,10342,KB309,874377,00,NaN,NaN,NaN,82281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3705,Desvios,22/03/2026 1:29,10342,KB309,874376,00,NaN,NaN,NaN,107762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_obs.columns = df_obs.columns.str.strip()

In [12]:
#Limpiar texto
mask = df_obs["tipo_evento"] == "Desvios"

extraidos = (
    df_obs.loc[mask, "Desde"]
    .astype(str)
    .str.findall(r"\d+[A-Z]\d+")
)

df_obs.loc[mask, "Parada_ini"] = extraidos.str[0]
df_obs.loc[mask, "Parada_fin"] = extraidos.str[1]

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,2026 10,DIRECCION,SENTIDO,AFECTACION,GESTION,2026 11,Siendo las 12,Siendo las 14,Parada_ini,Parada_fin
2493,Desvios,15/03/2026 1:29,10196,E25,850699,00,NaN,NaN,NaN,95735,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,050A00,227A00
3706,Desvios,22/03/2026 1:30,10342,KB309,874377,00,NaN,NaN,NaN,82281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441A01,064A01
3705,Desvios,22/03/2026 1:29,10342,KB309,874376,00,NaN,NaN,NaN,107762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,355B00,913A00

In [ ]:
print(df_obs["Paradas"].str.contains("Entre", case=False, na=False).sum())

965

In [14]:
# Limpieza base
df_obs["Paradas"] = (
    df_obs["Paradas"]
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace("\r", " ", regex=False)
    .str.strip()
)

# Extracción robusta
extraido = df_obs["Paradas"].str.extract(
    r'Entre\s*(.*?)\s*-\s*Hasta\s*(.*)',
    flags=re.IGNORECASE
)

# Aplicar solo si es Novedades de ruta
mask = df_obs["tipo_evento"].str.contains("Novedades", case=False, na=False)

df_obs.loc[mask, "parada_ini_afectada"] = extraido[0]
df_obs.loc[mask, "parada_fin_afectada"] = extraido[1]

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,SENTIDO,AFECTACION,GESTION,2026 11,Siendo las 12,Siendo las 14,Parada_ini,Parada_fin,parada_ini_afectada,parada_fin_afectada
2493,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,NaN,NaN,NaN,NaN,NaN,NaN,050A00,227A00,NaN,NaN
3706,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,NaN,NaN,NaN,NaN,NaN,NaN,441A01,064A01,NaN,NaN
3705,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,NaN,NaN,NaN,NaN,NaN,NaN,355B00,913A00,NaN,NaN

In [15]:
# Regex para extraer código de parada
patron = r'(\d{3}[A-Za-z]\d{2})'

df_obs["parada_ini_afec"] = df_obs["parada_ini_afectada"].str.extract(patron)
df_obs["parada_fin_afec"] = df_obs["parada_fin_afectada"].str.extract(patron)

df_obs["parada_ini_afec"] = df_obs["parada_ini_afec"].str.upper()
df_obs["parada_fin_afec"] = df_obs["parada_fin_afec"].str.upper()

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,GESTION,2026 11,Siendo las 12,Siendo las 14,Parada_ini,Parada_fin,parada_ini_afectada,parada_fin_afectada,parada_ini_afec,parada_fin_afec
2493,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,NaN,NaN,NaN,NaN,050A00,227A00,NaN,NaN,NaN,NaN
3706,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,NaN,NaN,NaN,NaN,441A01,064A01,NaN,NaN,NaN,NaN
3705,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,NaN,NaN,NaN,NaN,355B00,913A00,NaN,NaN,NaN,NaN

In [16]:
#cruzar datos de paradas con paradas de la bitácora

maestro_paradas = paradas[[
    "cenefa",
    "nombre",
    "via",
    "direccion_bandera",
    "localidad",
    "longitud",
    "latitud"
]]

maestro_paradas.head()

,cenefa,nombre,via,direccion_bandera,localidad,longitud,latitud
0,001A00,C.C. Iserra 100,AC 100,AC 100 - KR 54,Barrios Unidos,-74.063971,4.688481
1,001A01,Br. Rincón del Chicó,AC 100,AC 100 - KR 13,Usaquén,-74.045914,4.684091
2,001A02,Gimnasio Iragua,AV. Boyacá,AV. Boyacá - AC 170,Suba,-74.066350,4.759867
3,001A03,Br. Julio Flórez,AC 100,AC 100 - KR 66A,Suba,-74.071439,4.689504
4,001A04,Avenida Calle 80,AK 68,AK 68 - CL 79D,Barrios Unidos,-74.080392,4.682626

In [17]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_ini"),
    left_on="Parada_ini",
    right_on="cenefa_ini",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,parada_fin_afectada,parada_ini_afec,parada_fin_afec,cenefa_ini,nombre_ini,via_ini,direccion_bandera_ini,localidad_ini,longitud_ini,latitud_ini
0,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,NaN,NaN,NaN,050A00,Br. Colombia,Av. Chile,AC 72 - KR 22,Barrios Unidos,-74.066179,4.662240
1,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,NaN,NaN,NaN,441A01,Br. Tibabita,KR 8C,KR 8C - CL 185B,Usaquén,-74.029942,4.763045
2,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,NaN,NaN,NaN,355B00,Br. Concepción Norte,KR 17,KR 17 - CL 67,Barrios Unidos,-74.065826,4.656064

In [18]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_fin"),
    left_on="Parada_fin",
    right_on="cenefa_fin",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,localidad_ini,longitud_ini,latitud_ini,cenefa_fin,nombre_fin,via_fin,direccion_bandera_fin,localidad_fin,longitud_fin,latitud_fin
0,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,Barrios Unidos,-74.066179,4.662240,227A00,Clínica de Traumatología y Ortopedia,AK 11,AK 11 - CL 70A,Chapinero,-74.059659,4.656000
1,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,Usaquén,-74.029942,4.763045,064A01,Gimnasio Las Palmas,AK 7,AK 7 - CL 186,Usaquén,-74.027455,4.763086
2,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,Barrios Unidos,-74.065826,4.656064,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_ini_afec"),
    left_on="parada_ini_afec",
    right_on="cenefa_ini_afec",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,localidad_fin,longitud_fin,latitud_fin,cenefa_ini_afec,nombre_ini_afec,via_ini_afec,direccion_bandera_ini_afec,localidad_ini_afec,longitud_ini_afec,latitud_ini_afec
0,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,Chapinero,-74.059659,4.656000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,Usaquén,-74.027455,4.763086,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_fin_afec"),
    left_on="parada_fin_afec",
    right_on="cenefa_fin_afec",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,localidad_ini_afec,longitud_ini_afec,latitud_ini_afec,cenefa_fin_afec,nombre_fin_afec,via_fin_afec,direccion_bandera_fin_afec,localidad_fin_afec,longitud_fin_afec,latitud_fin_afec
0,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
columnas_cero = [
    "longitud_fin_afec",
    "latitud_fin_afec",
    "longitud_ini_afec",
    "latitud_ini_afec",
    "latitud_ini",
    "longitud_ini",
    "latitud_fin",
    "longitud_fin"
]

df_obs[columnas_cero] = df_obs[columnas_cero].fillna(0)

df_obs.head(3)

,tipo_evento,Fecha,Id de línea,Nombre Línea,ID Nota,03,Paradas,Paraderos Omitidos,Reportado por,ID,...,localidad_ini_afec,longitud_ini_afec,latitud_ini_afec,cenefa_fin_afec,nombre_fin_afec,via_fin_afec,direccion_bandera_fin_afec,localidad_fin_afec,longitud_fin_afec,latitud_fin_afec
0,Desvios,15/03/2026 1:29,10196,E25,850699,00,nan,NaN,NaN,95735,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,Desvios,22/03/2026 1:30,10342,KB309,874377,00,nan,NaN,NaN,82281,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,Desvios,22/03/2026 1:29,10342,KB309,874376,00,nan,NaN,NaN,107762,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [22]:
print(df_obs['latitud_ini_afec'].unique())

[0.         4.60178015 4.60749454 4.6460606  4.71689461 4.64953457
 4.65823957 4.60884778 4.62261171 4.65157026 4.555117   4.66113505
 4.6042917  4.57597306 4.65746279 4.56096701 4.5594871  4.58221416
 4.672921   4.65064725 4.66998312 4.59345452 4.66944024 4.65111749
 4.67052663 4.56443772 4.67333148 4.61608037 4.5693859  4.64366426
 4.760222   4.760348   4.58789498 4.675746   4.63051206 4.687194
 4.66353923 4.69686489 4.478735   4.63060007 4.61736456 4.595634
 4.59498552 4.66725267 4.67441202 4.55099149 4.703389   4.56393612
 4.67372494 4.67535218 4.66263352 4.68400257 4.69033645 4.57547435
 4.58534386 4.68322252 4.6262458  4.67936135 4.67594882 4.68320848
 4.66736444 4.68186234 4.675564   4.68374383 4.69962016 4.71264116
 4.70522754 4.70590762 4.6742381  4.65635708 4.59400231 4.59186761
 4.600383   4.57160399 4.68338161 4.680646   4.57148757 4.68209102
 4.5735905  4.5899546  4.54379563 4.54953528 4.62231624 4.61881354
 4.61605125 4.61585259 4.71019252 4.55876892 4.68050166 4.680281
 4.615172   4.64985726 4.62713431 4.50914245 4.50952598 4.65470096
 4.66756366 4.60018285 4.67405138 4.67286365 4.70140661 4.70227777
 4.711096   4.70162435 4.70512731 4.60047177 4.59202219 4.61851313
 4.62661874 4.70541054 4.70092251 4.70256424 4.611259   4.58731229
 4.64205986 4.63989613 4.68535524 4.54643032 4.61788987 4.54020365
 4.70349797 4.680267   4.61614404 4.6846908  4.48738107 4.69666392
 4.719444   4.7225739  4.719729   4.61892128 4.59282182 4.72237611
 4.68500331 4.56922752 4.61680881 4.61208098 4.57670201 4.6278488
 4.70957942 4.760477   4.54615637 4.57542449 4.56044216 4.55711341
 4.60583534 4.6240144  4.68086208 4.706083   4.63833519 4.66131189
 4.68837612 4.59874901 4.67715554 4.67921746 4.55433315 4.63835839
 4.70820689 4.59360951 4.54540911 4.54394013 4.595885   4.68847303
 4.55101576 4.661125   4.709606   4.70989684 4.71140535 4.70084675
 4.71023735 4.62921004 4.61558685 4.71372596 4.70780071 4.579827
 4.66894323 4.67100241 4.67378008 4.70257773 4.60175767 4.709103
 4.558524   4.7423935  4.763744   4.70571913 4.59493386 4.54789472
 4.61605879 4.70935871 4.66110525 4.52020287 4.65656219 4.594138
 4.55247941 4.61710822 4.72151844 4.56878702 4.61060389 4.67118831
 4.63356466 4.66932137 4.64123442 4.568728   4.66238546 4.73956408
 4.67183606 4.67933673 4.64157641 4.51414483 4.49265501 4.64100344
 4.68124537 4.71591335 4.67989262 4.68023009 4.49601068 4.48886966
 4.70938061 4.7208614  4.63316    4.61129064 4.59007996 4.63131639
 4.63098223 4.57691214 4.55518421 4.55851005 4.69745598 4.69757184
 4.69726234 4.67153666 4.68984103 4.69904164 4.69114775 4.684987
 4.65670045 4.65616265 4.62126547 4.65606417 4.76087755 4.55428848
 4.65431866 4.66224012 4.6450422  4.66062316 4.65332272 4.64034171
 4.68139389 4.64143812 4.65762116 4.63506388 4.60064073 4.60376152
 4.63863187 4.61351981 4.63835996 4.61049771 4.75868744 4.58954535
 4.63153866 4.68328369 4.58596082 4.589934   4.57191329 4.590447
 4.61467448 4.66312355 4.63792974 4.57709434 4.70188461 4.57358808
 4.61889258 4.61911275 4.70214319 4.49984836 4.70082488 4.70050592
 4.75462296 4.69467715 4.61129852 4.6896824  4.5842983  4.58542097
 4.58574787 4.67808594 4.64399113 4.61776162 4.585144   4.62207754
 4.71523259 4.61565586 4.675833   4.68903747 4.69803937 4.6751557
 4.54926646 4.70405496 4.70760029 4.56853305 4.58110201 4.6733904
 4.684029   4.686293   4.71757117 4.71669145 4.71458849 4.6163847
 4.55533669 4.57869991 4.71302088 4.712751   4.71434839 4.55906945
 4.71453737 4.5804361  4.70494339 4.59446836 4.54366397 4.73886919
 4.54812475 4.548742   4.72322    4.69580134 4.70572334 4.72067119
 4.69813218 4.66071004 4.62016966 4.62629911 4.62270524 4.61639512
 4.65561735 4.62182918 4.66607527 4.64185775 4.63866527 4.63832141
 4.70374811 4.63500814 4.61817622 4.62405238 4.67189879 4.54501342
 4.57544697 4.57392629 4.67607479 4.674014   4.674297   4.69288791
 4.69308861 4.70001079 4.69967592 4.62988127 4.66878047 4.58923551
 4.57825134 4.59080637 4.59725927 4.54654708 4.54814559 4.54518515
 4.60683294 4.59759272 4.58501728 4.52346862 4.67371628 4.69544913
 4.59979519 4.58452508 4.51693088]

In [23]:
df_obs.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Rutas_puntos_críticos/factores_rutas_{mes}.csv', sep=';', index=False)