In [4934]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import unicodedata
import re

Calendario fin de semana - festivos

In [4935]:
calendario = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/fin_semana_festivos.xlsx')

calendario.head()

        Date  DayName     Tipo
0 2026-01-04  Domingo  Domingo
1 2026-01-11  Domingo  Domingo
2 2026-01-18  Domingo  Domingo
3 2026-01-25  Domingo  Domingo
4 2026-02-01  Domingo  Domingo

Rotación semanal

In [4936]:
rotacion = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/rotación_semanal.xlsx')

rotacion.head()

,PATIO,SEMANA 1,SEMANA 2,SEMANA 3,SEMANA 4,SEMANA 5,SEMANA 6,SEMANA 7,SEMANA 8,SEMANA 9,SEMANA 10,SEMANA 11,SEMANA 12,SEMANA 13,SEMANA 14,SEMANA 15
0,TINTAL I,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N
1,TINTAL I,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1
2,TINTAL I,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1
3,TINTAL I,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1
4,TINTAL I,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1,ET1M-T1,ET2T-T1,ET2M-T1,ET1N,ET1T-T1

Semanas

In [4937]:
semanas = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/semanas_lab.xlsx')

semanas.head()

     SEMANA FECHA_INICIO  FECHA_FIN
0  SEMANA 1   2026-06-29 2026-07-05
1  SEMANA 2   2026-07-06 2026-07-12
2  SEMANA 3   2026-07-13 2026-07-19
3  SEMANA 4   2026-07-20 2026-07-26
4  SEMANA 5   2026-07-27 2026-08-02

personal

In [4938]:
personal = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/planta_centro_control.xlsx')

personal.head()

   IDENTIFICACION                             NAME             CARGO
0      1000325280     CHARYD JAYELY DURAN GONZALEZ  REGULADOR DE VIA
1      1000692075  MARIA FERNANDA HERNANDEZ TRIANA  REGULADOR DE VIA
2      1000721004          MARYORY BESABE CASTILLO  REGULADOR DE VIA
3      1001171370         ALEXANDRA MARTINEZ TAPIA  REGULADOR DE VIA
4      1001204614   LEIDY TATIANA SANCHEZ VELANDIA  REGULADOR DE VIA

Vacaciones

In [4939]:
vac = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/vacaciones_2026.xlsx')

vac.head()

,Preriodo,Fecha inicio,Fecha fin,Cargo,C.C,Nombres,Apellidos,Name
0,P1,2026-01-05,2026-01-22,Regulador CCO,52735918,ROSA MARIELA,TELLEZ NAVARRO,ROSA MARIELA TELLEZ NAVARRO
1,P1,2026-01-05,2026-01-22,Regulador Vía,79399645,LUIS ALBERTO,MOLANO BALLESTEROS,LUIS ALBERTO MOLANO BALLESTEROS
2,P1,2026-01-05,2026-01-22,Regulador Vía,80764583,EDGAR ALEJANDRO,RIOS CARDOZO,EDGAR ALEJANDRO RIOS CARDOZO
3,P1,2026-01-05,2026-01-22,Regulador Vía,1090538188,JOSE YOVANNY,OSTOS MEDINA,JOSE YOVANNY OSTOS MEDINA
4,P1,2026-01-05,2026-01-22,Regulador CCO,49695293,ADRIANA PATRICIA,TELLEZ VARELA,ADRIANA PATRICIA TELLEZ VARELA

In [4940]:
#Llevar tipo día a iri

def calcular_posicion(id):
    
    filtro = (
        (personal['IDENTIFICACION'] == id)
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not personal.loc[filtro].empty:
        # Obtener el primer valor
        Tipo_día = personal.loc[filtro, 'CARGO'].iloc[0]
        return Tipo_día  if not pd.isna(Tipo_día ) else None  
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
vac['CARGO'] = vac.apply(
    lambda row: calcular_posicion(
        row['C.C']
    ),
    axis=1
)

vac.head()

,Preriodo,Fecha inicio,Fecha fin,Cargo,C.C,Nombres,Apellidos,Name,CARGO
0,P1,2026-01-05,2026-01-22,Regulador CCO,52735918,ROSA MARIELA,TELLEZ NAVARRO,ROSA MARIELA TELLEZ NAVARRO,REGULADOR EN CENTRO DE CONTROL
1,P1,2026-01-05,2026-01-22,Regulador Vía,79399645,LUIS ALBERTO,MOLANO BALLESTEROS,LUIS ALBERTO MOLANO BALLESTEROS,REGULADOR DE VIA
2,P1,2026-01-05,2026-01-22,Regulador Vía,80764583,EDGAR ALEJANDRO,RIOS CARDOZO,EDGAR ALEJANDRO RIOS CARDOZO,REGULADOR DE VIA
3,P1,2026-01-05,2026-01-22,Regulador Vía,1090538188,JOSE YOVANNY,OSTOS MEDINA,JOSE YOVANNY OSTOS MEDINA,REGULADOR DE VIA
4,P1,2026-01-05,2026-01-22,Regulador CCO,49695293,ADRIANA PATRICIA,TELLEZ VARELA,ADRIANA PATRICIA TELLEZ VARELA,REGULADOR EN CENTRO DE CONTROL

Personal a programar en control

In [4941]:
personal_prog = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/personal_programar_control.xlsx')

personal_prog.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,DOMINGO,PATIO,BASE
0,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,D,TINTAL II,ET3M-T2
1,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,ENLACE N,TINTAL II,ET5M-T2
2,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,D,TINTAL II,ENLACE N
3,1024489560,YERLI IRENE HERNANDEZ ARIZA,YERLI IRENE,HERNÁNDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,3,2,1,0,T,D,TINTAL II,ET5T-T2
4,53152835,FRANCY LINNE TIMARAN CUESTA,FRANCY LINNE,TIMARAN CUESTA,REGULADOR EN CENTRO DE CONTROL,4,7,3,0,D,M,TINTAL II,ET3T-T2

In [4942]:
fechas = []

for _, row in semanas.iterrows():
    rango = pd.date_range(start=row['FECHA_INICIO'], end=row['FECHA_FIN'])
    fechas.extend(rango)

# Eliminar duplicados
fechas = pd.Series(fechas).drop_duplicates().sort_values()

In [4943]:
fechas_str = fechas.dt.strftime('%d/%m/%Y')

In [4944]:
for f in fechas_str:
    personal_prog[f] = None

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_33400\3349601713.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  personal_prog[f] = None

In [4945]:
cols = list(personal_prog.columns)
pos = cols.index('BASE') + 1

cols_final = cols[:pos] + list(fechas_str) + cols[pos:-len(fechas_str)]
personal_prog = personal_prog[cols_final]

personal_prog.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,None,None,None,None,None,None,None,None,None,None
1,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,None,None,None,None,None,None,None,None,None,None
2,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,None,None,None,None,None,None,None,None,None,None
3,1024489560,YERLI IRENE HERNANDEZ ARIZA,YERLI IRENE,HERNÁNDEZ ARIZA,REGULADOR EN CENTRO DE CONTROL,3,2,1,0,T,...,None,None,None,None,None,None,None,None,None,None
4,53152835,FRANCY LINNE TIMARAN CUESTA,FRANCY LINNE,TIMARAN CUESTA,REGULADOR EN CENTRO DE CONTROL,4,7,3,0,D,...,None,None,None,None,None,None,None,None,None,None

In [4946]:
calendario['Fecha_str'] = calendario['Date'].dt.strftime('%d/%m/%Y')
columnas_fechas = personal_prog.columns[personal_prog.columns.str.match(r'\d{2}/\d{2}/\d{4}')]

In [4947]:
# Diccionarios vacíos con todas las columnas
fila_dayname = {col: '' for col in personal_prog.columns}
fila_tipo = {col: '' for col in personal_prog.columns}

# Llenar solo las columnas de fechas
for col in columnas_fechas:
    match = calendario[calendario['Fecha_str'] == col]
    
    if not match.empty:
        fila_dayname[col] = match['DayName'].values[0]
        fila_tipo[col] = match['Tipo'].values[0]

In [4948]:
df_headers = pd.DataFrame([fila_dayname, fila_tipo])

In [4949]:
personal_prog_final = pd.concat([df_headers, personal_prog], ignore_index=True)

personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,None,None,None,None,None,None,None,None,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,None,None,None,None,None,None,None,None,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,None,None,None,None,None,None,None,None,None,None

In [4950]:
columnas_fechas = personal_prog_final.columns[
    personal_prog_final.columns.str.match(r'\d{2}/\d{2}/\d{4}')
]

In [4951]:
fechas_dt = pd.to_datetime(columnas_fechas, format='%d/%m/%Y')

In [4952]:
for i, row in personal_prog_final.iterrows():
    
    id_persona = row['Id']
    
    # Filtrar vacaciones por identificación
    vac_persona = vac[vac['C.C'] == id_persona]
    
    if vac_persona.empty:
        continue
    
    for _, v in vac_persona.iterrows():
        
        mask = (fechas_dt >= v['Fecha inicio ']) & (fechas_dt <= v['Fecha fin'])
        
        cols_vac = columnas_fechas[mask]
        
        personal_prog_final.loc[i, cols_vac] = 'VAC'
        
        
personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,None,None,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,None,None,None,None,None,None,None,None,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,None,None,None,None,None,None,VAC,VAC,VAC,VAC

In [4953]:
fila_dayname = personal_prog_final.iloc[0]

In [4954]:
for i in range(2, len(personal_prog_final)):  # saltar filas de encabezado
    
    for j, col in enumerate(columnas_fechas[:-1]):
        
        col_siguiente = columnas_fechas[j + 1]
        
        # Validar que sea sábado con VAC
        if (
            str(personal_prog_final.loc[i, col]) == 'VAC' and
            str(fila_dayname[col]).strip().lower() == 'sabado'
        ):
            
            # Todas las columnas después deben estar vacías
            cols_restantes = columnas_fechas[j + 1:]
            valores_restantes = personal_prog_final.loc[i, cols_restantes]
            
            if valores_restantes.isna().all():
                personal_prog_final.loc[i, col_siguiente] = 'D'
            
personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,None,None,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,None,None,None,None,None,None,None,None,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,None,None,None,None,None,None,VAC,VAC,VAC,VAC

In [4955]:
rot_long = rotacion.melt(
    id_vars=['PATIO'],
    var_name='SEMANA',
    value_name='TURNO'
)

rot_long.head()

      PATIO    SEMANA    TURNO
0  TINTAL I  SEMANA 1  ET1T-T1
1  TINTAL I  SEMANA 1     ET1N
2  TINTAL I  SEMANA 1  ET2M-T1
3  TINTAL I  SEMANA 1  ET2T-T1
4  TINTAL I  SEMANA 1  ET1M-T1

In [4956]:
rot_semana = rot_long.merge(
    semanas,
    on='SEMANA',
    how='left'
)

rot_semana.head()

      PATIO    SEMANA    TURNO FECHA_INICIO  FECHA_FIN
0  TINTAL I  SEMANA 1  ET1T-T1   2026-06-29 2026-07-05
1  TINTAL I  SEMANA 1     ET1N   2026-06-29 2026-07-05
2  TINTAL I  SEMANA 1  ET2M-T1   2026-06-29 2026-07-05
3  TINTAL I  SEMANA 1  ET2T-T1   2026-06-29 2026-07-05
4  TINTAL I  SEMANA 1  ET1M-T1   2026-06-29 2026-07-05

In [4957]:
lista = []

for _, row in rot_semana.iterrows():
    
    fechas = pd.date_range(row['FECHA_INICIO'], row['FECHA_FIN'])
    
    for f in fechas:
        lista.append({
            'PATIO': row['PATIO'],
            'Fecha': f,
            'TURNO': row['TURNO']
        })

rot_diario = pd.DataFrame(lista)

rot_diario.head()

      PATIO      Fecha    TURNO
0  TINTAL I 2026-06-29  ET1T-T1
1  TINTAL I 2026-06-30  ET1T-T1
2  TINTAL I 2026-07-01  ET1T-T1
3  TINTAL I 2026-07-02  ET1T-T1
4  TINTAL I 2026-07-03  ET1T-T1

In [4958]:
rot_diario['Fecha_str'] = rot_diario['Fecha'].dt.strftime('%d/%m/%Y')

rot_diario

         PATIO      Fecha       TURNO   Fecha_str
0     TINTAL I 2026-06-29     ET1T-T1  29/06/2026
1     TINTAL I 2026-06-30     ET1T-T1  30/06/2026
2     TINTAL I 2026-07-01     ET1T-T1  01/07/2026
3     TINTAL I 2026-07-02     ET1T-T1  02/07/2026
4     TINTAL I 2026-07-03     ET1T-T1  03/07/2026
...        ...        ...         ...         ...
3985     APOYO 2026-10-07  AUX CCZ II  07/10/2026
3986     APOYO 2026-10-08  AUX CCZ II  08/10/2026
3987     APOYO 2026-10-09  AUX CCZ II  09/10/2026
3988     APOYO 2026-10-10  AUX CCZ II  10/10/2026
3989     APOYO 2026-10-11  AUX CCZ II  11/10/2026

[3990 rows x 4 columns]

Asignar la rotación de los turnos

In [4959]:
cols_semanas = [col for col in rotacion.columns if 'SEMANA' in col]

rot_dict = {}

for patio, df in rotacion.groupby('PATIO'):
    rot_dict[patio] = df[cols_semanas].values.tolist()

In [4960]:
def obtener_fila_rotacion(patio, base):
    
    filas = rot_dict.get(patio, [])
    
    for fila in filas:
        if base in fila:
            return fila
    
    return None

In [4961]:
fila_tipo = personal_prog_final.iloc[1]

for i in range(2, len(personal_prog_final)):
    
    patio = personal_prog_final.loc[i, 'PATIO']
    base = personal_prog_final.loc[i, 'BASE']
    
    if pd.isna(base):
        continue
    
    fila_rot = obtener_fila_rotacion(patio, base)
    
    if fila_rot is None:
        continue
    
    idx_inicio = fila_rot.index(base)
    semana_idx = idx_inicio
    
    primera_asignacion = True
    semana_iso_actual = None
    
    for col in columnas_fechas:
        
        fecha = pd.to_datetime(col, dayfirst=True)
        tipo = str(fila_tipo[col]).lower()
        
        semana_iso = fecha.isocalendar().week
        
        # 🔥 cambio de semana REAL (aunque sea festivo)
        if not primera_asignacion and semana_iso != semana_iso_actual:
            semana_idx = (semana_idx + 1) % len(fila_rot)
        
        semana_iso_actual = semana_iso
        
        # ❌ saltar días no válidos
        if tipo in ['sabado','domingo','festivo']:
            continue
        
        # ❌ no sobreescribir VAC
        if personal_prog_final.loc[i, col] == 'VAC':
            continue
        
        turno = fila_rot[semana_idx]
        
        personal_prog_final.loc[i, col] = turno
        
        primera_asignacion = False

personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,None,None,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,None,None,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

Asignar turnos cuando estan en vacaciones (saliendo después de la misma)

In [4962]:
fila_tipo = personal_prog_final.iloc[1]

for i in range(2, len(personal_prog_final)):
    
    patio = personal_prog_final.loc[i, 'PATIO']
    base = personal_prog_final.loc[i, 'BASE']
    
    if pd.isna(base):
        continue
    
    fila_rot = obtener_fila_rotacion(patio, base)
    
    if fila_rot is None:
        continue
    
    idx_inicio = fila_rot.index(base)
    semana_idx = idx_inicio
    
    primera_asignacion = True
    semana_iso_actual = None
    
    for col in columnas_fechas:
        
        fecha = pd.to_datetime(col, dayfirst=True)
        tipo = str(fila_tipo[col]).lower()
        
        semana_iso = fecha.isocalendar().week
        
        # 🔥 CAMBIO DE SEMANA SIEMPRE (independiente de VAC o tipo)
        if not primera_asignacion and semana_iso != semana_iso_actual:
            semana_idx = (semana_idx + 1) % len(fila_rot)
        
        semana_iso_actual = semana_iso
        
        turno = fila_rot[semana_idx]  # 🔥 SIEMPRE calcular turno
        
        # ❌ NO sobreescribir VAC
        if personal_prog_final.loc[i, col] == 'VAC':
            primera_asignacion = False
            continue
        
        # ❌ no escribir en sábados, domingos, festivos
        if tipo in ['sabado','domingo','festivo']:
            primera_asignacion = False
            continue
        
        # ✅ asignar turno
        personal_prog_final.loc[i, col] = turno
        
        primera_asignacion = False
        
personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,None,None,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,None,None,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

Rotación asignando turnos faltantes

In [4963]:
fila_tipo = personal_prog_final.iloc[1]

turnos_objetivo = [
    'ET1T-T1','ET1N','ET2M-T1','ET2T-T1','ET1M-T1',
    'ET3T-T2','ENLACE N','ET5M-T2','ET5T-T2','ET3M-T2',
    'ET6T-Y','ET6N','ET7M-Y','ET7T-Y','ET6M-Y',
    'ET8T-V','ET3N','ET9M-V','ET9T-V','ET8M-V',
    'ET4I-T2','ET4M-T2','ET4T-T2'
]

# 🔥 FUNCIÓN CORRECTA
def obtener_tipo_turno(turno):
    turno = str(turno).upper().strip()
    
    if '-' in turno:
        base = turno.split('-')[0]  # ejemplo: ET2M
    else:
        base = turno
    
    if base.endswith('M'):
        return 'M'
    elif base.endswith('T'):
        return 'T'
    elif base.endswith('N'):
        return 'N'
    
    return None


for col in columnas_fechas:
    
    tipo_dia = str(fila_tipo[col]).lower()
    
    # ✅ SOLO HÁBIL
    if tipo_dia != 'habil':
        continue

    # valores actuales
    col_vals = personal_prog_final.loc[2:, col].copy()

    # 🔥 candidatos EXACTOS (solo M o T puros)
    candidatos_M = list(col_vals[col_vals == 'M'].index)
    candidatos_T = list(col_vals[col_vals == 'T'].index)

    # turnos actuales
    turnos_actuales = set(
        col_vals.dropna().astype(str).str.strip()
    )

    faltantes = [t for t in turnos_objetivo if t not in turnos_actuales]

    if not faltantes:
        continue

    # 🔥 separar correctamente por tipo REAL
    faltantes_M = [t for t in faltantes if obtener_tipo_turno(t) == 'M']
    faltantes_T = [t for t in faltantes if obtener_tipo_turno(t) == 'T']

    # =========================
    # ✅ ASIGNAR M (solo a M)
    # =========================
    for turno in faltantes_M:
        if not candidatos_M:
            break
        
        i_sel = candidatos_M.pop(0)
        personal_prog_final.loc[i_sel, col] = turno

    # =========================
    # ✅ ASIGNAR T (solo a T)
    # =========================
    for turno in faltantes_T:
        if not candidatos_T:
            break
        
        i_sel = candidatos_T.pop(0)
        personal_prog_final.loc[i_sel, col] = turno

personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,None,None,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,None,None,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

Visualización de turnos faltantes

In [4964]:
fila_tipo = personal_prog_final.iloc[1]

# Diccionario: fecha -> lista de faltantes
pendientes_por_fecha = {}

max_filas = 0

for col in columnas_fechas:
    
    tipo_dia = str(fila_tipo[col]).lower()
    
    if tipo_dia != 'habil':
        pendientes_por_fecha[col] = []
        continue
    
    turnos_actuales = set(
        personal_prog_final.loc[2:, col]
        .dropna()
        .astype(str)
        .str.strip()
    )
    
    faltantes = [t for t in turnos_objetivo if t not in turnos_actuales]
    
    pendientes_por_fecha[col] = faltantes
    
    if len(faltantes) > max_filas:
        max_filas = len(faltantes)



filas_pendientes = []

for n in range(max_filas):
    
    fila = {}
    
    for col in columnas_fechas:
        
        lista = pendientes_por_fecha[col]
        
        if n < len(lista):
            fila[col] = lista[n]
        else:
            fila[col] = ''
    
    filas_pendientes.append(fila)



df_pendientes = pd.DataFrame(filas_pendientes)

# Agregar columnas descriptivas
ids = ['PENDIENTES'] + [f'PENDIENTES {i}' for i in range(1, len(df_pendientes))]

df_pendientes.insert(0, 'Id', ids)
df_pendientes.insert(1, 'Name', '')
df_pendientes.insert(2, 'NOMBRES', '')
df_pendientes.insert(3, 'APELLIDOS', '')
df_pendientes.insert(4, 'CARGO', '')
df_pendientes.insert(5, 'PATIO', '')
df_pendientes.insert(6, 'BASE', '')



personal_prog_final = pd.concat(
    [personal_prog_final, df_pendientes],
    ignore_index=True
)

personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,None,None,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,None,None,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

Asignar descansos y turnos N de acuerdo al tipo día

In [4965]:
fila_tipo = personal_prog_final.iloc[1]

for i in range(2, len(personal_prog_final)):
    
    semana_actual = None
    tiene_nocturno = False
    cols_semana = []
    
    for col in columnas_fechas:
        
        fecha = pd.to_datetime(col, dayfirst=True)
        tipo = str(fila_tipo[col]).lower()
        valor = personal_prog_final.loc[i, col]
        
        semana_iso = fecha.isocalendar().week
        
        # 🔁 cambio de semana
        if semana_actual is not None and semana_iso != semana_actual:
            
            # 🔥 aplicar D si hubo nocturno
            if tiene_nocturno:
                for c in cols_semana:
                    tipo_c = str(fila_tipo[c]).lower()
                    
                    if tipo_c in ['sabado','domingo']:
                        if pd.isna(personal_prog_final.loc[i, c]):
                            personal_prog_final.loc[i, c] = 'D'
            
            # reset
            tiene_nocturno = False
            cols_semana = []
        
        semana_actual = semana_iso
        cols_semana.append(col)
        
        # detectar si hay turno N en la semana
        if isinstance(valor, str) and 'N' in valor:
            tiene_nocturno = True
    
    # 🔥 última semana
    if tiene_nocturno:
        for c in cols_semana:
            tipo_c = str(fila_tipo[c]).lower()
            
            if tipo_c in ['sabado','domingo']:
                if pd.isna(personal_prog_final.loc[i, c]):
                    personal_prog_final.loc[i, c] = 'D'
        
personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,None,None,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,None,None,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

In [4966]:
fila_tipo = personal_prog_final.iloc[1]

for i in range(2, len(personal_prog_final)):
    
    for j, col in enumerate(columnas_fechas):
        
        tipo = str(fila_tipo[col]).lower()
        valor = personal_prog_final.loc[i, col]
        
        # ✅ detectar inicio de semana hábil con N
        if tipo == 'habil' and isinstance(valor, str) and 'N' in valor:
            
            turno_n = valor
            
            # 🔙 ir hacia atrás
            k = j - 1
            
            while k >= 0:
                
                col_prev = columnas_fechas[k]
                tipo_prev = str(fila_tipo[col_prev]).lower()
                val_prev = personal_prog_final.loc[i, col_prev]
                
                # solo sabado, domingo o festivo
                if tipo_prev in ['sabado', 'domingo', 'festivo']:
                    
                    # no sobreescribir
                    if pd.notna(val_prev):
                        break
                    
                    personal_prog_final.loc[i, col_prev] = turno_n
                    k -= 1
                
                else:
                    break
                
                    
personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,None,None
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,None,None,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,None,None
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,None,None,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

Completar fin de semana

In [4967]:
def completar_por_viernes(personal_prog_final):

    df = personal_prog_final

    columnas_fechas = df.columns[5:]
    fila_tipos = 1
    tipos_dia = df.iloc[fila_tipos][columnas_fechas]

    for idx in df.index[2:]:

        for i, col in enumerate(columnas_fechas):

            # Solo cuando es viernes (Hábil)
            if tipos_dia[col] == 'Habil':

                valor_viernes = df.loc[idx, col]

                if pd.isna(valor_viernes) or valor_viernes == '':
                    continue

                # Buscar en el MISMO dataframe la fila cuyo BASE coincida
                match = df[df['BASE'] == valor_viernes]

                if match.empty:
                    continue

                # Tomar patrón de esa BASE encontrada
                sab_val = match['SABADO'].iloc[0]
                dom_val = match['DOMINGO'].iloc[0]

                # Buscar sábado y domingo de esa semana (hacia adelante)
                sab_col = None
                dom_col = None

                for j in range(i+1, len(columnas_fechas)):
                    col_sig = columnas_fechas[j]
                    tipo_sig = tipos_dia[col_sig]

                    if tipo_sig == 'Sabado':
                        sab_col = col_sig

                    elif tipo_sig == 'Domingo':
                        dom_col = col_sig
                        break

                # Completar SOLO si está vacío
                if sab_col:
                    if pd.isna(df.loc[idx, sab_col]) or df.loc[idx, sab_col] == '':
                        if pd.notna(sab_val) and sab_val != '':
                            df.loc[idx, sab_col] = sab_val

                if dom_col:
                    if pd.isna(df.loc[idx, dom_col]) or df.loc[idx, dom_col] == '':
                        if pd.notna(dom_val) and dom_val != '':
                            df.loc[idx, dom_col] = dom_val

    return df


# Aplicar directamente
personal_prog_final = completar_por_viernes(personal_prog_final)

personal_prog_final.head()

,Id,Name,NOMBRES,APELLIDOS,CARGO,DESCANSOS,FIN_LABORADOS,HABITUALES_JUN,LABORA_1FDS,SABADO,...,02/10/2026,03/10/2026,04/10/2026,05/10/2026,06/10/2026,07/10/2026,08/10/2026,09/10/2026,10/10/2026,11/10/2026
0,,,,,,,,,,,...,Viernes,Sabado,Domingo,Lunes,Martes,Miercoles,Jueves,Viernes,Sabado,Domingo
1,,,,,,,,,,,...,Habil,Sabado,Domingo,Habil,Habil,Habil,Habil,Habil,Sabado,Domingo
2,39678186,SONIA CONSTANZA CORREA RODRIGUEZ,SONIA CONSTANZA,CORREA RODRIGUEZ,REGULADOR EN CENTRO DE CONTROL,5,6,3,0,M,...,VAC,VAC,VAC,VAC,VAC,VAC,ET3T-T2,ET3T-T2,D,M
3,1000860322,PAULA KATHERINE CANTOR SALAMANCA,PAULA KATHERINE,CANTOR SALAMANCA,REGULADOR EN CENTRO DE CONTROL,5,6,2,0,ENLACE N,...,ET3M-T2,M,D,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,ET5T-T2,T,D
4,1072642532,LAURA MARCELA VARGAS GUTIERREZ,LAURA MARCELA,VARGAS GUTIERREZ,REGULADOR EN CENTRO DE CONTROL,3,8,4,0,D,...,ET5T-T2,T,D,ET5M-T2,ET5M-T2,ET5M-T2,VAC,VAC,VAC,VAC

In [4968]:
personal_prog_final.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/programacion.csv', index=False, sep=';')

In [4969]:
personal_prog_final.to_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/programacion.xlsx')

In [4970]:
rot_diario.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/diario_rotacion.csv', index=False, sep=';')

Formato de celdas

In [4971]:
ruta_archivo = "C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Programación/programacion.xlsx"

personal_prog_final.to_excel(ruta_archivo, index=False)

In [4972]:
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# Cargar archivo
wb = load_workbook(ruta_archivo)
ws = wb.active

# 🎨 Colores
color_vac = PatternFill(start_color="ADD8E6", end_color="ADD8E6", fill_type="solid")   # Azul
color_d = PatternFill(start_color="C0C0C0", end_color="C0C0C0", fill_type="solid")     # Gris
color_habil = PatternFill(start_color="90EE90", end_color="90EE90", fill_type="solid") # Verde
color_no_habil = PatternFill(start_color="FFF59D", end_color="FFF59D", fill_type="solid") # Amarillo

for row in ws.iter_rows(min_row=2):  # saltar encabezado
    
    for cell in row:
        
        if not isinstance(cell.value, str):
            continue
        
        valor = cell.value.strip()
        
        # 🔵 VAC
        if valor == "VAC":
            cell.fill = color_vac
        
        # ⚪ D
        elif valor == "D":
            cell.fill = color_d
        
        # 🟢 HABIL
        elif valor.lower() == "habil":
            cell.fill = color_habil
        
        # 🟡 NO HÁBIL
        elif valor.lower() in ["festivo", "sabado", "domingo"]:
            cell.fill = color_no_habil

# Guardar cambios
wb.save(ruta_archivo)