In [28]:
import re
import pandas as pd
import numpy as np
import os
import glob
from pathlib import Path

In [29]:
dia= "20260406"

In [30]:
# Ruta de la carpeta de matriz de distancia

carpeta_origen = 'Z:/01 base_datos/41 Informe Diario CCZ/FMS 2025/SMART OPERATOR/viajes smart operator/viajes smart operator' 

dataframes = [] # Lista para almacenar cada archivo

fecha_inicio = f'{dia}' 
fecha_fin = f'{dia}'  

for archivo in os.listdir(carpeta_origen):
    if archivo.endswith('.csv'):  # Filtra solo los archivos con extensión .csv
        ruta_archivo = os.path.join(carpeta_origen, archivo)
        df = pd.read_csv(ruta_archivo, encoding='latin',skiprows=1,on_bad_lines='skip')
        
        # Obtén la fecha a partir del nombre del archivo
        fecha_archivo = pd.to_datetime(archivo.split('_')[0], format='%Y%m%d', errors='coerce')
        
        # Filtra por fechas
        if fecha_archivo >= pd.to_datetime(fecha_inicio, format='%Y%m%d') and fecha_archivo <= pd.to_datetime(fecha_fin, format='%Y%m%d'):
            df['Fecha'] = fecha_archivo  # Agrega la columna de fecha
            dataframes.append(df)

inicio_viajes = pd.concat(dataframes)

inicio_viajes.head()

,LÃÂ­nea,Ruta,Servicio,Viaje en lÃÂ­nea,Viaje,H.Ini.Teor,H.Fin.Teor,H.Ini.Real,H.Fin.Real,Desv.H.F.Prev,Desv.HI,Dur.Teo,Dur.Real,Desv.Dur,Frec.HI.Teo,Frec.HI.Real,Desv.Frec,Fecha,Línea,Viaje en línea
0,1-1,Cocheras/Vacio,CO11B0001,0,1,03:14,04:04,NaN,03:38,NaN,00:26,00:50,NaN,NaN,00:00,NaN,NaN,2026-04-06,NaN,NaN
1,1-1,1-1_V1,CO11B0001,1,2,04:04,04:30,04:04,04:25,00:00,00:05,00:26,00:21,00:05,00:00,00:00,NaN,2026-04-06,NaN,NaN
2,1-1,1-1_V1,CO11B0001,2,3,04:35,05:03,04:33,05:00,00:02,00:03,00:28,00:27,00:01,00:31,00:00,00:10,2026-04-06,NaN,NaN
3,1-1,1-1_V1,CO11B0001,3,4,05:11,05:42,05:08,05:35,00:03,00:07,00:31,00:26,00:05,00:36,00:00,00:07,2026-04-06,NaN,NaN
4,1-1,1-1_V1,CO11B0001,4,5,05:47,06:22,05:47,06:15,00:00,00:07,00:35,00:28,00:07,00:36,00:00,00:07,2026-04-06,NaN,NaN

In [31]:
#Filtrar lo diferente a cero en viaje linea
inicio_viajes = inicio_viajes[inicio_viajes["Viaje en línea"] != 0]

inicio_viajes.head()

,LÃÂ­nea,Ruta,Servicio,Viaje en lÃÂ­nea,Viaje,H.Ini.Teor,H.Fin.Teor,H.Ini.Real,H.Fin.Real,Desv.H.F.Prev,Desv.HI,Dur.Teo,Dur.Real,Desv.Dur,Frec.HI.Teo,Frec.HI.Real,Desv.Frec,Fecha,Línea,Viaje en línea
0,1-1,Cocheras/Vacio,CO11B0001,0,1,03:14,04:04,NaN,03:38,NaN,00:26,00:50,NaN,NaN,00:00,NaN,NaN,2026-04-06,NaN,NaN
1,1-1,1-1_V1,CO11B0001,1,2,04:04,04:30,04:04,04:25,00:00,00:05,00:26,00:21,00:05,00:00,00:00,NaN,2026-04-06,NaN,NaN
2,1-1,1-1_V1,CO11B0001,2,3,04:35,05:03,04:33,05:00,00:02,00:03,00:28,00:27,00:01,00:31,00:00,00:10,2026-04-06,NaN,NaN
3,1-1,1-1_V1,CO11B0001,3,4,05:11,05:42,05:08,05:35,00:03,00:07,00:31,00:26,00:05,00:36,00:00,00:07,2026-04-06,NaN,NaN
4,1-1,1-1_V1,CO11B0001,4,5,05:47,06:22,05:47,06:15,00:00,00:07,00:35,00:28,00:07,00:36,00:00,00:07,2026-04-06,NaN,NaN

In [32]:
inicio_viajes = inicio_viajes.sort_values(
    by=["Línea", "Ruta","H.Ini.Teor", "Viaje en línea"]
)

inicio_viajes.head()

,LÃÂ­nea,Ruta,Servicio,Viaje en lÃÂ­nea,Viaje,H.Ini.Teor,H.Fin.Teor,H.Ini.Real,H.Fin.Real,Desv.H.F.Prev,Desv.HI,Dur.Teo,Dur.Real,Desv.Dur,Frec.HI.Teo,Frec.HI.Real,Desv.Frec,Fecha,Línea,Viaje en línea
1,NaN,12,CE12B0001,NaN,2,04:00,05:59,03:59,05:53,00:01,00:06,01:59,01:54,00:05,00:00,00:07,NaN,2026-04-06,12,1.0
8,NaN,12,CE12B0002,NaN,2,04:11,06:09,04:13,06:02,-00:02,00:08,01:58,01:48,00:10,00:00,00:29,-00:18,2026-04-06,12,1.0
16,NaN,12,CE12B0003,NaN,2,04:22,06:22,04:26,06:15,-00:04,00:07,02:00,01:49,00:11,00:00,00:59,-00:48,2026-04-06,12,1.0
22,NaN,12,CE12B0004,NaN,2,04:33,06:43,04:36,06:59,-00:03,-00:16,02:10,02:23,-00:13,00:00,NaN,NaN,2026-04-06,12,1.0
29,NaN,12,CE12B0005,NaN,2,04:44,06:54,04:44,06:59,00:00,-00:05,02:10,02:15,-00:05,00:00,00:00,00:11,2026-04-06,12,1.0

In [33]:
#Franjas teóricas vs real
inicio_viajes["Franja_Teor"] = inicio_viajes["H.Ini.Teor"].astype(str).str[:2]
inicio_viajes["Franja_Real"] = inicio_viajes["H.Ini.Real"].astype(str).str[:2]

inicio_viajes.head()

,LÃÂ­nea,Ruta,Servicio,Viaje en lÃÂ­nea,Viaje,H.Ini.Teor,H.Fin.Teor,H.Ini.Real,H.Fin.Real,Desv.H.F.Prev,...,Dur.Real,Desv.Dur,Frec.HI.Teo,Frec.HI.Real,Desv.Frec,Fecha,Línea,Viaje en línea,Franja_Teor,Franja_Real
1,NaN,12,CE12B0001,NaN,2,04:00,05:59,03:59,05:53,00:01,...,01:54,00:05,00:00,00:07,NaN,2026-04-06,12,1.0,04,03
8,NaN,12,CE12B0002,NaN,2,04:11,06:09,04:13,06:02,-00:02,...,01:48,00:10,00:00,00:29,-00:18,2026-04-06,12,1.0,04,04
16,NaN,12,CE12B0003,NaN,2,04:22,06:22,04:26,06:15,-00:04,...,01:49,00:11,00:00,00:59,-00:48,2026-04-06,12,1.0,04,04
22,NaN,12,CE12B0004,NaN,2,04:33,06:43,04:36,06:59,-00:03,...,02:23,-00:13,00:00,NaN,NaN,2026-04-06,12,1.0,04,04
29,NaN,12,CE12B0005,NaN,2,04:44,06:54,04:44,06:59,00:00,...,02:15,-00:05,00:00,00:00,00:11,2026-04-06,12,1.0,04,04

In [34]:
inicio_viajes.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Regularidad_FMS/{dia}_regularidad_fms.csv', index=False)