In [1]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#Datos de filtros
fecha_ip = '20260501'
fecha_fp = '20260531'

mes = 'may'

In [3]:
# Ruta de la carpeta que contiene los archivos
ruta_carpeta = 'Z:/01 base_datos/18 pasajeros_asociados'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_ip}'
fecha_fin = f'{fecha_fp}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_pax_asociados.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    resultado2 = pd.concat(dataframes, ignore_index=True)
else:
    print("No se encontraron archivos para consolidar.")
    
resultado2.head()

,FechaId,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,IdViajeGrupo,HoraInicio,StrParadero,Paradero,TipoValidacion,TipoOperacion
0,20260501,2026-05-01,507078,CE0D80003,10354.0,10674,10674,16-5,2.0,507416.0,2026-05-01T03:32:57Z,2026-05-01507078CE0D80003-2,03:30,(52843) 243A05_TM|243A05_Br. MarandÃº,52843.0,Transbordo,PADRON ZONAL
1,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:00:58Z,2026-05-01507095CE0D80001-2,03:30,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,PADRON ZONAL
2,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:01:03Z,2026-05-01507095CE0D80001-2,03:30,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,PADRON ZONAL
3,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:02:02Z,2026-05-01507095CE0D80001-2,03:30,(51163) 044A04_TM|044A04_Villas de AlcalÃ¡,51163.0,Transbordo,PADRON ZONAL
4,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:07:49Z,2026-05-01507095CE0D80001-2,03:30,(52813) 232A05_TM|232A05_Br. MarandÃº,52813.0,Transbordo,PADRON ZONAL

In [4]:
# Dividir la columna "FechaReal" en dos columnas "Fecha" y "Hora"
resultado2[['Fecha_real', 'Hora']] = resultado2['FechaReal'].str.split('T', expand=True)

# Eliminar el carácter "Z" al final de la columna "Hora"
resultado2['Hora'] = resultado2['Hora'].str.rstrip('Z')

# Dividir la columna 'hora' en partes usando ':', y seleccionar la primera parte (horas)
resultado2['franja'] = resultado2['Hora'].str.split(':').str[0]

resultado2.head()

,FechaId,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,IdViajeGrupo,HoraInicio,StrParadero,Paradero,TipoValidacion,TipoOperacion,Fecha_real,Hora,franja
0,20260501,2026-05-01,507078,CE0D80003,10354.0,10674,10674,16-5,2.0,507416.0,2026-05-01T03:32:57Z,2026-05-01507078CE0D80003-2,03:30,(52843) 243A05_TM|243A05_Br. MarandÃº,52843.0,Transbordo,PADRON ZONAL,2026-05-01,03:32:57,03
1,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:00:58Z,2026-05-01507095CE0D80001-2,03:30,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,PADRON ZONAL,2026-05-01,04:00:58,04
2,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:01:03Z,2026-05-01507095CE0D80001-2,03:30,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,PADRON ZONAL,2026-05-01,04:01:03,04
3,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:02:02Z,2026-05-01507095CE0D80001-2,03:30,(51163) 044A04_TM|044A04_Villas de AlcalÃ¡,51163.0,Transbordo,PADRON ZONAL,2026-05-01,04:02:02,04
4,20260501,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:07:49Z,2026-05-01507095CE0D80001-2,03:30,(52813) 232A05_TM|232A05_Br. MarandÃº,52813.0,Transbordo,PADRON ZONAL,2026-05-01,04:07:49,04

In [5]:
# Eliminar las columnas
columnas_a_eliminar = ['FechaId','IdViajeGrupo','HoraInicio','TipoOperacion']
resultado2 = resultado2.drop(columns=columnas_a_eliminar)

resultado2.head()

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,StrParadero,Paradero,TipoValidacion,Fecha_real,Hora,franja
0,2026-05-01,507078,CE0D80003,10354.0,10674,10674,16-5,2.0,507416.0,2026-05-01T03:32:57Z,(52843) 243A05_TM|243A05_Br. MarandÃº,52843.0,Transbordo,2026-05-01,03:32:57,03
1,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:00:58Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,2026-05-01,04:00:58,04
2,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:01:03Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,2026-05-01,04:01:03,04
3,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:02:02Z,(51163) 044A04_TM|044A04_Villas de AlcalÃ¡,51163.0,Transbordo,2026-05-01,04:02:02,04
4,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:07:49Z,(52813) 232A05_TM|232A05_Br. MarandÃº,52813.0,Transbordo,2026-05-01,04:07:49,04

In [6]:
# Convertir la columna 'Fecha' a tipo datetime
resultado2['Fecha_real'] = pd.to_datetime(resultado2['Fecha_real'], format='%Y-%m-%d')

# Extraer el nombre del mes en español
resultado2['Mes'] = resultado2['Fecha_real'].dt.strftime('%B').str.capitalize()

# Extraer el año y almacenarlo como un entero en una nueva columna 'Año'
resultado2['Año'] = resultado2['Fecha_real'].dt.year

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
resultado2['Fecha_real'] = resultado2['Fecha_real'].dt.strftime('%d/%m/%Y')

# Mostrar el DataFrame actualizado
resultado2.head()

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,StrParadero,Paradero,TipoValidacion,Fecha_real,Hora,franja,Mes,Año
0,2026-05-01,507078,CE0D80003,10354.0,10674,10674,16-5,2.0,507416.0,2026-05-01T03:32:57Z,(52843) 243A05_TM|243A05_Br. MarandÃº,52843.0,Transbordo,01/05/2026,03:32:57,03,May,2026
1,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:00:58Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,01/05/2026,04:00:58,04,May,2026
2,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:01:03Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,01/05/2026,04:01:03,04,May,2026
3,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:02:02Z,(51163) 044A04_TM|044A04_Villas de AlcalÃ¡,51163.0,Transbordo,01/05/2026,04:02:02,04,May,2026
4,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:07:49Z,(52813) 232A05_TM|232A05_Br. MarandÃº,52813.0,Transbordo,01/05/2026,04:07:49,04,May,2026

In [7]:
# Limpiar la columna 'Hora' eliminando caracteres no deseados
resultado2['Hora'] = resultado2['Hora'].replace('[^\d:]', '', regex=True)

# Reemplazar el caso del punto con un valor predeterminado (por ejemplo, '0:00:00')
resultado2['Hora'] = resultado2['Hora'].replace('.', '0:00:00')

# Convertir la columna 'Hora Petición' a timedelta y luego a segundos
resultado2['HoraIniSegundos'] = pd.to_timedelta(resultado2['Hora']).dt.total_seconds()

# Asignar un valor constante a la nueva columna 'cantidad'
resultado2['cantidad'] = 1 

resultado2.head()

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_23292\1548606869.py:2: SyntaxWarning: invalid escape sequence '\d'
  resultado2['Hora'] = resultado2['Hora'].replace('[^\d:]', '', regex=True)

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,StrParadero,Paradero,TipoValidacion,Fecha_real,Hora,franja,Mes,Año,HoraIniSegundos,cantidad
0,2026-05-01,507078,CE0D80003,10354.0,10674,10674,16-5,2.0,507416.0,2026-05-01T03:32:57Z,(52843) 243A05_TM|243A05_Br. MarandÃº,52843.0,Transbordo,01/05/2026,03:32:57,03,May,2026,12777.0,1
1,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:00:58Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,01/05/2026,04:00:58,04,May,2026,14458.0,1
2,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:01:03Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,01/05/2026,04:01:03,04,May,2026,14463.0,1
3,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:02:02Z,(51163) 044A04_TM|044A04_Villas de AlcalÃ¡,51163.0,Transbordo,01/05/2026,04:02:02,04,May,2026,14522.0,1
4,2026-05-01,507095,CE0D80001,10354.0,10674,10674,16-5,2.0,503819.0,2026-05-01T04:07:49Z,(52813) 232A05_TM|232A05_Br. MarandÃº,52813.0,Transbordo,01/05/2026,04:07:49,04,May,2026,14869.0,1

In [8]:
cols = ['LineAso','RutaAso','RutaOrg','IdViaje','Conductor','HoraIniSegundos']

resultado2[cols] = (
    resultado2[cols]
    .fillna(0)
    .astype(int)
)
resultado2.head()

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,StrParadero,Paradero,TipoValidacion,Fecha_real,Hora,franja,Mes,Año,HoraIniSegundos,cantidad
0,2026-05-01,507078,CE0D80003,10354,10674,10674,16-5,2,507416,2026-05-01T03:32:57Z,(52843) 243A05_TM|243A05_Br. MarandÃº,52843.0,Transbordo,01/05/2026,03:32:57,03,May,2026,12777,1
1,2026-05-01,507095,CE0D80001,10354,10674,10674,16-5,2,503819,2026-05-01T04:00:58Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,01/05/2026,04:00:58,04,May,2026,14458,1
2,2026-05-01,507095,CE0D80001,10354,10674,10674,16-5,2,503819,2026-05-01T04:01:03Z,(58327) 449A04_TM|449A04_Gran Granada,58327.0,Transbordo,01/05/2026,04:01:03,04,May,2026,14463,1
3,2026-05-01,507095,CE0D80001,10354,10674,10674,16-5,2,503819,2026-05-01T04:02:02Z,(51163) 044A04_TM|044A04_Villas de AlcalÃ¡,51163.0,Transbordo,01/05/2026,04:02:02,04,May,2026,14522,1
4,2026-05-01,507095,CE0D80001,10354,10674,10674,16-5,2,503819,2026-05-01T04:07:49Z,(52813) 232A05_TM|232A05_Br. MarandÃº,52813.0,Transbordo,01/05/2026,04:07:49,04,May,2026,14869,1

In [9]:
resultado_resumido = (
    resultado2
    .groupby([
        'Fecha','NumeroBus','ServicioBus','LineAso',
        'RutaAso','RutaOrg','LineaOrg','IdViaje','Conductor'
    ], as_index=False)
    ['cantidad']
    .sum()
)

In [10]:
resultado_resumido = resultado_resumido.rename(
    columns={'cantidad': 'validaciones'}
)

resultado_resumido.head()

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,validaciones
0,2026-05-01,502002,CE1730002,10551,12856,12856,KL307,2,505851,53
1,2026-05-01,502002,CE1730002,10551,12856,12856,KL307,3,505851,116
2,2026-05-01,502002,CE1730009,10551,12856,12856,KL307,7,509959,9
3,2026-05-01,502002,CE173G010,10551,12856,12856,KL307,1,509332,113
4,2026-05-01,502003,CE1730001,10551,12856,12856,KL307,2,509093,71

In [11]:
resultado_resumido.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/IRP/Validaciones_resumen/{mes}_validaciones.csv', index=False, sep=';')