In [28]:
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from textblob import TextBlob
from nltk.sentiment import SentimentIntensityAnalyzer
import speech_recognition as sr
from pydub import AudioSegment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import nltk
from wordcloud import WordCloud
from collections import Counter
import re

In [29]:
#Datos de filtros
fecha_i = '20260401'
fecha_f = '20260430'

mes = 'abril'

In [30]:
#imprortar paradas

paradas = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Paraderos_Zonales_del_SITP.csv')

paradas.head(3)

,X,Y,objectid,cenefa,zona_sitp,nombre,via,direccion_bandera,localidad,longitud,latitud,consecutivo_zona,tipo_m_s,consola,panel,audio,zonas_nuevas,globalid,shape
0,1.001502e+06,1.010205e+06,1,001A00,00,C.C. Iserra 100,AC 100,AC 100 - KR 54,Barrios Unidos,-74.063971,4.688481,001,M,AC 100 - KR 54 (001A00),AC 100 - KR 54,Avenida Calle 100 Carrera 54,C,{1C0DBC4E-15BC-4BBE-BC16-5628077DBE2E},NaN
1,1.003505e+06,1.009719e+06,2,001A01,01,Br. Rincón del Chicó,AC 100,AC 100 - KR 13,Usaquén,-74.045914,4.684091,001,M,AC 100 - KR 13 (001A01),AC 100 - KR 13,Avenida Calle 100 Carrera 13,B,{60A22A44-AD56-4DF4-A3E6-6830B9FB0792},NaN
2,1.001238e+06,1.018098e+06,3,001A02,02,Gimnasio Iragua,AV. Boyacá,AV. Boyacá - AC 170,Suba,-74.066350,4.759867,001,S,AV. Boyacá - AC 170 (001A02),AV. Boyacá - AC 170,Avenida Boyacá Avenida Calle 170,C,{97155274-E4D5-45A4-891F-2DCA19FF10D9},NaN

In [31]:
# Ruta de la carpeta que contiene los archivos de actividad de bus zonal
ruta_carpeta = 'Z:/01 base_datos/08 varados FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_varados.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            # Leer el archivo CSV omitiendo la primera fila vacía
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    notas = pd.concat(dataframes, ignore_index=True)

    # # Guardar el DataFrame consolidado en un nuevo archivo
    # desg_troncal.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2024/Indicadores/Indicadores_python/desgl_troncal_ago24.csv', index=False)
else:
    print("No se encontraron archivos para consolidar.")
    
notas.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Servicio,Id de línea,Nombre Línea,N° Vehículo,Código Conductor,Nombre Conductor,ID Nota,Tipo Nota,Subtipo Nota,Subsubtipo Nota,Observaciones,Creado Por,Modificado Por
0,1/04/2026 0:11,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10194,539,0,0,,902057,NOVEDADES SIRCI,EQUIPAMIENTO A BORDO VEHÍCULOS,FALLA GPS (SIN LOCALIZACIÓN DATOS),SIRCI / falla de geo localización / ticket: #...,Raul Fabian Romero Mican,Raul Fabian Romero Mican
1,1/04/2026 0:48,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10196,E25,0,0,,902121,ENTREGA DE TURNO,EMPALME,TODOS LOS TURNOS,EMPALME\nSUPERVISIÓN G-MOVIL\n31-03-2026\nTurn...,Diego Armando Triana Soriano,Diego Armando Triana Soriano
2,1/04/2026 1:28,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10331,12,0,0,,902183,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 100186/ 01-04-2026/ 0...,Raul Fabian Romero Mican,Raul Fabian Romero Mican

In [32]:
#Filtrar ruta SE14 - línea 10350 y convertir a entero
notas = notas[notas["Id de línea"] == 10350.0]

notas["Id de línea"] = notas["Id de línea"].astype(int)

notas.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Servicio,Id de línea,Nombre Línea,N° Vehículo,Código Conductor,Nombre Conductor,ID Nota,Tipo Nota,Subtipo Nota,Subsubtipo Nota,Observaciones,Creado Por,Modificado Por
28,1/04/2026 1:50,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10350,SE14,0,0,,902223,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 101157/ 01-04-2026/ 0...,Raul Fabian Romero Mican,Raul Fabian Romero Mican
29,1/04/2026 1:51,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10350,SE14,0,0,,902224,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 102707/ 01-04-2026/ 0...,Raul Fabian Romero Mican,Raul Fabian Romero Mican
45,1/04/2026 7:23,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10350,SE14,0,0,,902595,INTERRUPCION DE SERVICIO ZONAL,CONGESTION VEHICULAR,General,Congestion Vehicular / 01-04-2026 / 07:20 / R...,ADRIANA TELLEZ PATRICIA VARELA,ADRIANA TELLEZ PATRICIA VARELA

In [33]:
#Filtrar por tipo nota igual a 'INTERRUPCION DE SERVICIO ZONAL', 'NOVEDADES SIRCI', 'RUTAS EN SEGUIMIENTO ESPECIAL'
notas = notas[notas["Tipo Nota"].isin([
    "INTERRUPCION DE SERVICIO ZONAL"
])]

notas.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Servicio,Id de línea,Nombre Línea,N° Vehículo,Código Conductor,Nombre Conductor,ID Nota,Tipo Nota,Subtipo Nota,Subsubtipo Nota,Observaciones,Creado Por,Modificado Por
28,1/04/2026 1:50,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10350,SE14,0,0,,902223,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 101157/ 01-04-2026/ 0...,Raul Fabian Romero Mican,Raul Fabian Romero Mican
29,1/04/2026 1:51,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10350,SE14,0,0,,902224,INTERRUPCION DE SERVICIO ZONAL,DESVIO BUS ZONAL,GENERAL,Autorización desvío/ ID: 102707/ 01-04-2026/ 0...,Raul Fabian Romero Mican,Raul Fabian Romero Mican
45,1/04/2026 7:23,ENGATIVA ZN,GMOVIL ENGATIVA,URBANO,10350,SE14,0,0,,902595,INTERRUPCION DE SERVICIO ZONAL,CONGESTION VEHICULAR,General,Congestion Vehicular / 01-04-2026 / 07:20 / R...,ADRIANA TELLEZ PATRICIA VARELA,ADRIANA TELLEZ PATRICIA VARELA

In [34]:
print(notas.columns)

Index(['Fecha', 'Concesión', 'Concesionario de Operación', 'Tipo de Servicio',
       'Id de línea', 'Nombre Línea', 'N° Vehículo', 'Código Conductor',
       'Nombre Conductor', 'ID Nota', 'Tipo Nota', 'Subtipo Nota',
       'Subsubtipo Nota', 'Observaciones', 'Creado Por', 'Modificado Por'],
      dtype='object')

In [35]:
def parse_observacion(texto):
    if pd.isna(texto):
        return {}

    pares = re.findall(r'([^:/]+):\s*([^/]+)', texto)
    return {k.strip(): v.strip() for k, v in pares}

df_obs = notas["Observaciones"].apply(parse_observacion).apply(pd.Series)

df_obs.head(3)

,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,07,Descripcion,Reportado por,...,16,19,Paradas Desde,08,17,sentido,18,Descripción,14,23
28,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,102707,00,129A12: Hasta: 004A12,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,Raúl Fabián Romero,Alejandro Monroy,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,Se presenta congestión por alto flujo vehicu...,RCC ADRIANA PATRICIA TELLEZ VARELA a TS DUVAN ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
def parse_observacion(texto):
    if pd.isna(texto):
        return {}

    pares = re.findall(r'([^:/]+):\s*([^/]+)', texto)
    return {k.strip(): v.strip() for k, v in pares}


# Parsear observaciones
df_obs = notas["Observaciones"].apply(parse_observacion).apply(pd.Series)

# Agregar columnas base
df_obs = pd.concat(
    [notas[["Fecha", "ID Nota"]], df_obs],
    axis=1
)

df_obs.head(3)

,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,07,...,16,19,Paradas Desde,08,17,sentido,18,Descripción,14,23
28,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1/04/2026 1:51,902224,102707,00,129A12: Hasta: 004A12,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,Raúl Fabián Romero,Alejandro Monroy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,1/04/2026 7:23,902595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df_obs = df_obs.sort_values(by="ID", key=lambda x: x.isna())

df_obs.head(3)

,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,07,...,16,19,Paradas Desde,08,17,sentido,18,Descripción,14,23
28,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,NaN,...,NaN,NaN,579A11: Hasta: 131B12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,NaN,...,NaN,NaN,129A12: Hasta: 004A12,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df_obs.insert(
    0,
    "tipo_evento",
    np.where(df_obs["ID"].notna() & (df_obs["ID"] != ""), "Desvios", "Novedades de ruta")
)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,16,19,Paradas Desde,08,17,sentido,18,Descripción,14,23
28,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,579A11: Hasta: 131B12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,129A12: Hasta: 004A12,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
#dividir las columnas a fecha e isntante
df_obs[["Fecha_registro", "Instante"]] = df_obs["Fecha"].str.split(" ", expand=True)

# Normalizar Instante a HH:MM:SS
df_obs["Instante"] = (
    df_obs["Instante"]
    .astype(str)
    .str.strip()
    .apply(lambda x: x if x.count(":") == 2 else x + ":00")
)

# Convertir a segundos
df_obs["Instante_seg"] = (
    pd.to_timedelta(df_obs["Instante"], errors="coerce")
    .dt.total_seconds()
    .astype("Int64")
)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,08,17,sentido,18,Descripción,14,23,Fecha_registro,Instante,Instante_seg
28,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/04/2026,1:50:00,6600
754,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8/04/2026,3:01:00,10860
598,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7/04/2026,2:59:00,10740

In [40]:
#Limpiar texto
mask = df_obs["tipo_evento"] == "Desvios"

extraidos = (
    df_obs.loc[mask, "Desde"]
    .astype(str)
    .str.findall(r"\d+[A-Z]\d+")
)

df_obs.loc[mask, "Parada_ini"] = extraidos.str[0]
df_obs.loc[mask, "Parada_fin"] = extraidos.str[1]

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,sentido,18,Descripción,14,23,Fecha_registro,Instante,Instante_seg,Parada_ini,Parada_fin
28,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,NaN,NaN,1/04/2026,1:50:00,6600,579A11,131B12
754,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8/04/2026,3:01:00,10860,NaN,NaN
598,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7/04/2026,2:59:00,10740,NaN,NaN

In [41]:
df_obs["Paradas"].str.contains("Entre", case=False, na=False).sum()

5

In [42]:
print(df_obs['tipo_evento'].unique())

['Desvios' 'Novedades de ruta']

In [43]:
# Limpieza base
df_obs["Paradas"] = (
    df_obs["Paradas"]
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace("\r", " ", regex=False)
    .str.strip()
)

# Extracción robusta
extraido = df_obs["Paradas"].str.extract(
    r'Entre\s*(.*?)\s*-\s*Hasta\s*(.*)',
    flags=re.IGNORECASE
)

# Aplicar solo si es Novedades de ruta
mask = df_obs["tipo_evento"].str.contains("Novedades", case=False, na=False)

df_obs.loc[mask, "parada_ini_afectada"] = extraido[0]
df_obs.loc[mask, "parada_fin_afectada"] = extraido[1]

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,Descripción,14,23,Fecha_registro,Instante,Instante_seg,Parada_ini,Parada_fin,parada_ini_afectada,parada_fin_afectada
28,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,1/04/2026,1:50:00,6600,579A11,131B12,NaN,NaN
754,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,8/04/2026,3:01:00,10860,NaN,NaN,NaN,NaN
598,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,7/04/2026,2:59:00,10740,NaN,NaN,NaN,NaN

In [44]:
# Regex para extraer código de parada
patron = r'(\d{3}[A-Za-z]\d{2})'

df_obs["parada_ini_afec"] = df_obs["parada_ini_afectada"].str.extract(patron)
df_obs["parada_fin_afec"] = df_obs["parada_fin_afectada"].str.extract(patron)

df_obs["parada_ini_afec"] = df_obs["parada_ini_afec"].str.upper()
df_obs["parada_fin_afec"] = df_obs["parada_fin_afec"].str.upper()

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,23,Fecha_registro,Instante,Instante_seg,Parada_ini,Parada_fin,parada_ini_afectada,parada_fin_afectada,parada_ini_afec,parada_fin_afec
28,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,1/04/2026,1:50:00,6600,579A11,131B12,NaN,NaN,NaN,NaN
754,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,8/04/2026,3:01:00,10860,NaN,NaN,NaN,NaN,NaN,NaN
598,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,7/04/2026,2:59:00,10740,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
#cruzar datos de paradas con paradas de la bitácora

maestro_paradas = paradas[[
    "cenefa",
    "nombre",
    "via",
    "direccion_bandera",
    "localidad",
    "longitud",
    "latitud"
]]

maestro_paradas.head()

,cenefa,nombre,via,direccion_bandera,localidad,longitud,latitud
0,001A00,C.C. Iserra 100,AC 100,AC 100 - KR 54,Barrios Unidos,-74.063971,4.688481
1,001A01,Br. Rincón del Chicó,AC 100,AC 100 - KR 13,Usaquén,-74.045914,4.684091
2,001A02,Gimnasio Iragua,AV. Boyacá,AV. Boyacá - AC 170,Suba,-74.066350,4.759867
3,001A03,Br. Julio Flórez,AC 100,AC 100 - KR 66A,Suba,-74.071439,4.689504
4,001A04,Avenida Calle 80,AK 68,AK 68 - CL 79D,Barrios Unidos,-74.080392,4.682626

In [46]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_ini"),
    left_on="Parada_ini",
    right_on="cenefa_ini",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,parada_fin_afectada,parada_ini_afec,parada_fin_afec,cenefa_ini,nombre_ini,via_ini,direccion_bandera_ini,localidad_ini,longitud_ini,latitud_ini
0,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,579A11,Br. Tunjuelito,AV. Caracas,AV. Caracas - KR 10,Tunjuelito,-74.122966,4.55851
1,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_fin"),
    left_on="Parada_fin",
    right_on="cenefa_fin",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,localidad_ini,longitud_ini,latitud_ini,cenefa_fin,nombre_fin,via_fin,direccion_bandera_fin,localidad_fin,longitud_fin,latitud_fin
0,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,Tunjuelito,-74.122966,4.55851,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_ini_afec"),
    left_on="parada_ini_afec",
    right_on="cenefa_ini_afec",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,localidad_fin,longitud_fin,latitud_fin,cenefa_ini_afec,nombre_ini_afec,via_ini_afec,direccion_bandera_ini_afec,localidad_ini_afec,longitud_ini_afec,latitud_ini_afec
0,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df_obs = df_obs.merge(
    maestro_paradas.add_suffix("_fin_afec"),
    left_on="parada_fin_afec",
    right_on="cenefa_fin_afec",
    how="left"
)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,localidad_ini_afec,longitud_ini_afec,latitud_ini_afec,cenefa_fin_afec,nombre_fin_afec,via_fin_afec,direccion_bandera_fin_afec,localidad_fin_afec,longitud_fin_afec,latitud_fin_afec
0,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
columnas_cero = [
    "longitud_fin_afec",
    "latitud_fin_afec",
    "longitud_ini_afec",
    "latitud_ini_afec",
    "latitud_ini",
    "longitud_ini",
    "latitud_fin",
    "longitud_fin"
]

df_obs[columnas_cero] = df_obs[columnas_cero].fillna(0)

df_obs.head(3)

,tipo_evento,Fecha,ID Nota,ID,03,Desde,Sentido,Descripción de desvío,Reportado por Regulador de CCZ,Reportado a TS,...,localidad_ini_afec,longitud_ini_afec,latitud_ini_afec,cenefa_fin_afec,nombre_fin_afec,via_fin_afec,direccion_bandera_fin_afec,localidad_fin_afec,longitud_fin_afec,latitud_fin_afec
0,Desvios,1/04/2026 1:50,902223,101157,00,579A11: Hasta: 131B12,Sur-Norte,Seguir la cra 8a al Occidente y tomar calle 53...,Raúl Fabián Romero,Alejandro Monroy,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0
1,Desvios,8/04/2026 3:01,916841,101157,00,NaN,Sur-Norte,Seguir la carrera 8a al Occidente y tomar call...,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,Desvios,7/04/2026 2:59,913691,102707,00,NaN,Sur-Norte,Desde la Diagonal 50 Sur tomar Carrera 5r a Ca...,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [51]:
print(df_obs['latitud_ini_afec'].unique())

[0.         4.64366426 4.542164   4.54604037]

In [52]:
df_obs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 70 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   tipo_evento                     38 non-null     object
 1   Fecha                           38 non-null     object
 2   ID Nota                         38 non-null     int64
 3   ID                              15 non-null     object
 4   03                              15 non-null     object
 5   Desde                           12 non-null     object
 6   Sentido                         15 non-null     object
 7   Descripción de desvío           15 non-null     object
 8   Reportado por Regulador de CCZ  8 non-null      object
 9   Reportado a TS                  8 non-null      object
 10  07                              3 non-null      object
 11  Descripcion                     12 non-null     object
 12  Reportado por                   30 non-null     object
 13  Observaciones                   10 non-null     object
 14  13                              1 non-null      object
 15  Paradas                         38 non-null     object
 16  Paraderos Omitidos              10 non-null     object
 17  15                              1 non-null      object
 18  Motivo                          5 non-null      object
 19  Sentido Sur  - Norte;  Paradas  5 non-null      object
 20  09                              3 non-null      object
 21  20                              1 non-null      object
 22  00                              1 non-null      object
 23  16                              2 non-null      object
 24  19                              1 non-null      object
 25  Paradas  Desde                  3 non-null      object
 26  08                              2 non-null      object
 27  17                              5 non-null      object
 28  sentido                         1 non-null      object
 29  18                              1 non-null      object
 30  Descripción                     1 non-null      object
 31  14                              1 non-null      object
 32  23                              1 non-null      object
 33  Fecha_registro                  38 non-null     object
 34  Instante                        38 non-null     object
 35  Instante_seg                    38 non-null     Int64
 36  Parada_ini                      12 non-null     object
 37  Parada_fin                      12 non-null     object
 38  parada_ini_afectada             5 non-null      object
 39  parada_fin_afectada             5 non-null      object
 40  parada_ini_afec                 5 non-null      object
 41  parada_fin_afec                 5 non-null      object
 42  cenefa_ini                      12 non-null     object
 43  nombre_ini                      12 non-null     object
 44  via_ini                         12 non-null     object
 45  direccion_bandera_ini           12 non-null     object
 46  localidad_ini                   12 non-null     object
 47  longitud_ini                    38 non-null     float64
 48  latitud_ini                     38 non-null     float64
 49  cenefa_fin                      6 non-null      object
 50  nombre_fin                      6 non-null      object
 51  via_fin                         6 non-null      object
 52  direccion_bandera_fin           6 non-null      object
 53  localidad_fin                   6 non-null      object
 54  longitud_fin                    38 non-null     float64
 55  latitud_fin                     38 non-null     float64
 56  cenefa_ini_afec                 5 non-null      object
 57  nombre_ini_afec                 5 non-null      object
 58  via_ini_afec                    5 non-null      object
 59  direccion_bandera_ini_afec      5 non-null      object
 60  localidad_ini_afec              5 non-null      object
 61  longitud_ini_afec               38 non-null     float64
 62  latitud_ini_afec                38 non-null     float64
 63  cenefa_fin_afec                 5 non-null      object
 64  nombre_fin_afec                 5 non-null      object
 65  via_fin_afec                    5 non-null      object
 66  direccion_bandera_fin_afec      5 non-null      object
 67  localidad_fin_afec              5 non-null      object
 68  longitud_fin_afec               38 non-null     float64
 69  latitud_fin_afec                38 non-null     float64
dtypes: Int64(1), float64(8), int64(1), object(60)
memory usage: 20.9+ KB

In [53]:
print(df_obs.columns)

Index(['tipo_evento', 'Fecha', 'ID Nota', 'ID', '03', 'Desde', 'Sentido',
       'Descripción de desvío', 'Reportado por Regulador de CCZ',
       'Reportado a TS', '07', 'Descripcion', 'Reportado por', 'Observaciones',
       '13', 'Paradas', 'Paraderos Omitidos', '15', 'Motivo',
       'Sentido Sur  - Norte;  Paradas', '09', '20', '00', '16', '19',
       'Paradas  Desde', '08', '17', 'sentido', '18', 'Descripción', '14',
       '23', 'Fecha_registro', 'Instante', 'Instante_seg', 'Parada_ini',
       'Parada_fin', 'parada_ini_afectada', 'parada_fin_afectada',
       'parada_ini_afec', 'parada_fin_afec', 'cenefa_ini', 'nombre_ini',
       'via_ini', 'direccion_bandera_ini', 'localidad_ini', 'longitud_ini',
       'latitud_ini', 'cenefa_fin', 'nombre_fin', 'via_fin',
       'direccion_bandera_fin', 'localidad_fin', 'longitud_fin', 'latitud_fin',
       'cenefa_ini_afec', 'nombre_ini_afec', 'via_ini_afec',
       'direccion_bandera_ini_afec', 'localidad_ini_afec', 'longitud_ini_afec',
       'latitud_ini_afec', 'cenefa_fin_afec', 'nombre_fin_afec',
       'via_fin_afec', 'direccion_bandera_fin_afec', 'localidad_fin_afec',
       'longitud_fin_afec', 'latitud_fin_afec'],
      dtype='object')

In [54]:
df_obs.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Ruta_SE14/factores_SE14_{mes}.csv', sep=';', index=False)