In [36]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import locale
import seaborn as sns
import matplotlib.pyplot as plt
import unicodedata
import re

Base de quejas

In [37]:
#Importar archivo

quejas = pd.read_excel('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/PQRS_TMSA/quejas_TMSA.xlsx')

quejas.head()

,MECANISMO DE RECEPCION DE LA QUEJA,RADICADO,FECHA ASIGNACIÓN,FECHA DE VENCIMIENTO,DESCRIPCION,TIPO DE RADICADO,RUTA,FECHA DE RESPUESTA,DIAS RESPUESTA,Mes,Fecha,Hora,Bus,Paradero,Dirección,Sentido
0,Correo electronico Aux. Operaciones Tintal 2,3617737,2026-01-13,2026-01-19,Se genera respuesta por correo,Queja,E25,2026-01-13,0,enero,NaT,NaN,NaN,NaN,NaN,NaN
1,CRM,3616075,2026-01-09,2026-01-15,El servicio de SITP de la ruta 740 que sale de...,Reclamo,740,2026-01-13,4,enero,NaT,04:48:00,504374.0,NaN,Kenny - Techo,NaN
2,CRM,3629209,2026-01-09,2026-01-15,Usuario se comunica para informar que la ruta ...,Reclamo,614,2026-01-13,4,enero,NaT,NaN,NaN,NaN,Br. Granjas De Techo,NaN
3,CRM,3609297,2026-01-09,2026-01-15,"Sr. Jose Igancio, se comunica para informar qu...",Reclamo,402,2026-01-13,4,enero,NaT,19:21:00,NaN,497A00,Vía Choachí,NaN
4,Correo electronico Coordinador CCZ,GM-R-2026-06455,2026-01-26,2026-02-01,No tiene archivos adjuntos,Requerimiento,NaN,2026-01-27,1,enero,NaT,NaN,NaN,493A04,NaN,NaN

In [38]:
valores_excluir = [
    'Correo electronico  Aux. Operaciones Tintal 2',
    'Correo electronico Coordinador CCZ',
    'Whats app Diana Ortegon Verbena '
]

quejas = quejas[
    ~quejas['MECANISMO DE RECEPCION DE LA QUEJA'].isin(valores_excluir)
]

quejas.head()

,MECANISMO DE RECEPCION DE LA QUEJA,RADICADO,FECHA ASIGNACIÓN,FECHA DE VENCIMIENTO,DESCRIPCION,TIPO DE RADICADO,RUTA,FECHA DE RESPUESTA,DIAS RESPUESTA,Mes,Fecha,Hora,Bus,Paradero,Dirección,Sentido
1,CRM,3616075,2026-01-09,2026-01-15,El servicio de SITP de la ruta 740 que sale de...,Reclamo,740,2026-01-13,4,enero,NaT,04:48:00,504374.0,NaN,Kenny - Techo,NaN
2,CRM,3629209,2026-01-09,2026-01-15,Usuario se comunica para informar que la ruta ...,Reclamo,614,2026-01-13,4,enero,NaT,NaN,NaN,NaN,Br. Granjas De Techo,NaN
3,CRM,3609297,2026-01-09,2026-01-15,"Sr. Jose Igancio, se comunica para informar qu...",Reclamo,402,2026-01-13,4,enero,NaT,19:21:00,NaN,497A00,Vía Choachí,NaN
6,Bogotá te escucha,383752026,2026-01-26,2026-02-01,"LAS RUTAS DE BUSES 12, K303, P500. TARDAN DEMA...",Petición,12,2026-01-27,1,enero,NaT,NaN,NaN,NaN,NaN,NaN
7,CRM,3656709,2026-01-26,2026-02-01,Usuario se comunica para informar que la ruta ...,Reclamo,DD204,2026-01-27,1,enero,NaT,06:50:00,NaN,493A04,NaN,NaN

In [39]:
print(quejas['MECANISMO DE RECEPCION DE LA QUEJA'].unique())

['CRM' 'Bogotá te escucha']

In [40]:
quejas.to_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/PQRS_TMSA/seguimiento_quejas.csv', index=False, sep=';')