In [1]:
import pandas as pd
import numpy as np
import subprocess
import os
from datetime import datetime, timedelta, time, date
import datetime
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Datos de filtros
fecha_i = '20260420'
fecha_f = '20260426'
mes = 'April'

semana = 'semana_20_26_abr26' # Quejas
semana_bus = 'bus_lleno_20_26_abr26' # Bus lleno

data = 'w20_26_abr26'

Paradas

In [3]:
#importar paradas

paradas = pd.read_csv('C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Paraderos_Zonales_del_SITP.csv')

paradas["cenefa"] = paradas["cenefa"].astype(str).str.strip().str.upper()

paradas.head(3)

,X,Y,objectid,cenefa,zona_sitp,nombre,via,direccion_bandera,localidad,longitud,latitud,consecutivo_zona,tipo_m_s,consola,panel,audio,zonas_nuevas,globalid,shape
0,1.001502e+06,1.010205e+06,1,001A00,00,C.C. Iserra 100,AC 100,AC 100 - KR 54,Barrios Unidos,-74.063971,4.688481,001,M,AC 100 - KR 54 (001A00),AC 100 - KR 54,Avenida Calle 100 Carrera 54,C,{1C0DBC4E-15BC-4BBE-BC16-5628077DBE2E},NaN
1,1.003505e+06,1.009719e+06,2,001A01,01,Br. Rincón del Chicó,AC 100,AC 100 - KR 13,Usaquén,-74.045914,4.684091,001,M,AC 100 - KR 13 (001A01),AC 100 - KR 13,Avenida Calle 100 Carrera 13,B,{60A22A44-AD56-4DF4-A3E6-6830B9FB0792},NaN
2,1.001238e+06,1.018098e+06,3,001A02,02,Gimnasio Iragua,AV. Boyacá,AV. Boyacá - AC 170,Suba,-74.066350,4.759867,001,S,AV. Boyacá - AC 170 (001A02),AV. Boyacá - AC 170,Avenida Boyacá Avenida Calle 170,C,{97155274-E4D5-45A4-891F-2DCA19FF10D9},NaN

Revisar datos de actividad de bus

In [4]:
# Ruta de la carpeta que contiene los archivos
ruta_carpeta = 'Z:/01 base_datos/03 actividad_bus_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_actividad_bus.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    df_final = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
df_final.head(3)

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Nombre de Conductor,Evento,Hora Teórica,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias
0,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,MARIA EUGENIA SILVA CORTES,Inicio Viaje(3),5:48:30,5:48:30,NaN,NaN,NaN,NaN,NaN,NaN
1,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,MARIA EUGENIA SILVA CORTES,NaN,5:49:06,5:49:06,6:16:13,6:16:29,NaN,NaN,0:00:00,NaN
2,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,MARIA EUGENIA SILVA CORTES,NaN,5:50:23,5:50:23,6:17:53,6:18:31,0:01:24,NaN,0:00:16,NaN

In [5]:
# Extraer la parte antes del guion bajo en la columna 'Descripcion'
df_final['paradero'] = df_final['Nombre Nodo'].str.split('_').str[0]

df_final['paradero'] = df_final['paradero'].astype(str).str.strip().str.upper()

df_final.head(3)

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Evento,Hora Teórica,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,paradero
0,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,Inicio Viaje(3),5:48:30,5:48:30,NaN,NaN,NaN,NaN,NaN,NaN,247A05
1,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,5:49:06,5:49:06,6:16:13,6:16:29,NaN,NaN,0:00:00,NaN,222A05
2,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,5:50:23,5:50:23,6:17:53,6:18:31,0:01:24,NaN,0:00:16,NaN,068A05

In [6]:
df_final['HoraLleg'] = df_final['Hora Llegada']

df_final.head()

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Hora Teórica,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,paradero,HoraLleg
0,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:48:30,5:48:30,NaN,NaN,NaN,NaN,NaN,NaN,247A05,NaN
1,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:49:06,5:49:06,6:16:13,6:16:29,NaN,NaN,0:00:00,NaN,222A05,6:16:13
2,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:50:23,5:50:23,6:17:53,6:18:31,0:01:24,NaN,0:00:16,NaN,068A05,6:17:53
3,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:51:33,5:51:33,6:19:14,6:19:21,0:00:43,NaN,0:00:00,NaN,110A05,6:19:14
4,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:52:47,5:52:47,6:19:47,6:20:20,0:00:26,NaN,0:00:07,NaN,070A05,6:19:47

In [7]:
# Reemplazar los NaN en la columna 'HoraLleg' por '0:00:00' y dejarle una columna de marcador
# Crear marcador: 1 si es NaN (se va a modificar), 0 si no
df_final['HoraLleg_modificado'] = df_final['HoraLleg'].isna().astype(int)

# Reemplazar los NaN
df_final['HoraLleg'].fillna('0:00:00', inplace=True)

df_final.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\995336642.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['HoraLleg'].fillna('0:00:00', inplace=True)

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Hora Referencia,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,paradero,HoraLleg,HoraLleg_modificado
0,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:48:30,NaN,NaN,NaN,NaN,NaN,NaN,247A05,0:00:00,1
1,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:49:06,6:16:13,6:16:29,NaN,NaN,0:00:00,NaN,222A05,6:16:13,0
2,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,5:50:23,6:17:53,6:18:31,0:01:24,NaN,0:00:16,NaN,068A05,6:17:53,0

In [8]:
# Función para corregir tiempos con "24:00:00"
def fix_time(time_str):
    try:
        time_str = str(time_str).strip()
        h, m, s = map(int, time_str.split(':'))

        # Convertir TODO a segundos
        total_segundos = h * 3600 + m * 60 + s

        # Reducir al rango de 24h
        total_segundos = total_segundos % (24 * 3600)

        # Volver a formato hh:mm:ss
        h_new = total_segundos // 3600
        m_new = (total_segundos % 3600) // 60
        s_new = total_segundos % 60

        return f"{h_new:02}:{m_new:02}:{s_new:02}"

    except:
        return None

df_final['HoraLleg'] = df_final['HoraLleg'].astype(str)

df_final['HoraLleg'] = df_final['HoraLleg'].apply(fix_time)

df_final['HoraLleg'] = pd.to_datetime(
    df_final['HoraLleg'],
    format='%H:%M:%S',
    errors='coerce'
)

df_final['Horas_Minutos_Segundos'] = (
    df_final['HoraLleg'].dt.hour * 3600 +
    df_final['HoraLleg'].dt.minute * 60 +
    df_final['HoraLleg'].dt.second
)

df_final.head(3)

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,paradero,HoraLleg,HoraLleg_modificado,Horas_Minutos_Segundos
0,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,247A05,1900-01-01 00:00:00,1,0
1,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,6:16:13,6:16:29,NaN,NaN,0:00:00,NaN,222A05,1900-01-01 06:16:13,0,22573
2,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,6:17:53,6:18:31,0:01:24,NaN,0:00:16,NaN,068A05,1900-01-01 06:17:53,0,22673

Matriz de distancia

In [9]:
carpeta_origen = 'Z:/01 base_datos/06 matriz_distancia_FMS'  

dataframes = [] 

fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'  

for archivo in os.listdir(carpeta_origen):
    if archivo.endswith('.csv'):
        ruta_archivo = os.path.join(carpeta_origen, archivo)
        df = pd.read_csv(ruta_archivo, encoding='latin')
        
        # Obtén la fecha a partir del nombre del archivo
        fecha_archivo = pd.to_datetime(archivo.split('_')[0], format='%Y%m%d', errors='coerce')
        
        # Filtra por fechas
        if fecha_archivo >= pd.to_datetime(fecha_inicio, format='%Y%m%d') and fecha_archivo <= pd.to_datetime(fecha_fin, format='%Y%m%d'):
            df['Fecha'] = fecha_archivo  # Agrega la columna de fecha
            dataframes.append(df)

matriz_distancia = pd.concat(dataframes)

matriz_distancia.head(3)

,ï»¿Tipo de Servicio,Id LÃ­nea,LÃ­nea,Configuraciones,ConfiguraciÃ³n Activa,Id SublÃ­nea,Id Ruta,Nombre Ruta,Sentido,Id Nodo,Etiqueta Nodo,Nombre Nodo,PosiciÃ³n,Coordenada X,Coordenada Y,Atributos,Fecha
0,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52845.0,247A05_TM,247A05_Br. La Esperanza II,0.0,595348.0,521193.0,"SinÃ³ptico, Horario GOAL, Punto de control (TM...",2026-04-20
1,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52806.0,222A05_TM,222A05_Hospital de EngativÃ¡ EmaÃºs,138.0,595258.0,521149.0,NaN,2026-04-20
2,URBANO,10184,740,1,2,338.0,10415.0,740_V1,Circular,52365.0,068A05_TM,068A05_Liceo SalomÃ³n Sabio,425.0,595014.0,520997.0,NaN,2026-04-20

In [10]:
# completar vacios
df_final['Id Ruta'].fillna('0', inplace=True)

df_final['Id Ruta'] = df_final['Id Ruta'].astype(int)

# df_final['IDViaje'].fillna('0', inplace=True)

df_final['Id Viaje'] = df_final['Id Viaje'].astype(int)

df_final['Número FMS Bus'].fillna('0', inplace=True)

df_final['Número FMS Bus'] = df_final['Número FMS Bus'].astype(int)

df_final.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2677187658.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['Id Ruta'].fillna('0', inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2677187658.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['Número FMS Bus'].fillna('0', inplace=True)

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Hora Llegada,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,paradero,HoraLleg,HoraLleg_modificado,Horas_Minutos_Segundos
0,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,247A05,1900-01-01 00:00:00,1,0
1,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,6:16:13,6:16:29,NaN,NaN,0:00:00,NaN,222A05,1900-01-01 06:16:13,0,22573
2,20/04/2026,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,6:17:53,6:18:31,0:01:24,NaN,0:00:16,NaN,068A05,1900-01-01 06:17:53,0,22673

In [11]:
# Crear una copia del DataFrame original
df_final_copy = df_final.copy()

# Filtrar el DataFrame por la columna 'Ruta_SAE', manteniendo solo los valores iguales a 0
df_filter = df_final_copy[df_final_copy['Id Ruta'] == 0]

# Mostrar el DataFrame filtrado
df_filter.head()

Empty DataFrame
Columns: [Fecha, Concesión, Concesionario de Operación, Id Línea, Línea, Id Ruta, Ruta, Tabla, Viaje Linea, Orden Viaje, Id Viaje, Tipo de Nodo, Id Nodo, Nombre Nodo, Servicio Bus, Código Bus, Número FMS Bus, Conductor, Nombre de Conductor, Evento, Hora Teórica, Hora Referencia, Hora Llegada, Hora Salida, Tiempo entre paradas, Alarma Exceso de Tiempo en Parada, Tiempo Apertura de Puertas, Lista de acciones regulatorias, paradero, HoraLleg, HoraLleg_modificado, Horas_Minutos_Segundos]
Index: []

[0 rows x 32 columns]

Información de quejas

In [12]:
#Abrir Actividad de bus

archivo = f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Omision_parada/{semana}.csv"

# Cargar el archivo 

quejas = pd.read_csv(archivo, encoding="latin", sep=';')

quejas.head()

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,12/04/2026,10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,26/04/2026,22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,26/04/2026,21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,26/04/2026,21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,26/04/2026,20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0

In [13]:
quejas['hora1'] = quejas['hora']

quejas.head(3)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,12/04/2026,10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,26/04/2026,22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,26/04/2026,21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17

In [14]:
# Función para corregir tiempos con "24:00:00"
def fix_time(time_str):
    try:
        time_str = str(time_str).strip()
        h, m, s = map(int, time_str.split(':'))

        # Convertir TODO a segundos
        total_segundos = h * 3600 + m * 60 + s

        # Reducir al rango de 24h
        total_segundos = total_segundos % (24 * 3600)

        # Volver a formato hh:mm:ss
        h_new = total_segundos // 3600
        m_new = (total_segundos % 3600) // 60
        s_new = total_segundos % 60

        return f"{h_new:02}:{m_new:02}:{s_new:02}"

    except:
        return None

quejas['hora'] = quejas['hora'].astype(str)

quejas['hora'] = quejas['hora'].apply(fix_time)

quejas['hora'] = pd.to_datetime(
    quejas['hora'],
    format='%H:%M:%S',
    errors='coerce'
)

quejas['Horas_Minutos_Segundos'] = (
    quejas['hora'].dt.hour * 3600 +
    quejas['hora'].dt.minute * 60 +
    quejas['hora'].dt.second
)

quejas.head(3)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,12/04/2026,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,26/04/2026,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,26/04/2026,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117

In [15]:
# Convertir la columna 'Fecha' a tipo datetime
quejas['fecha'] = pd.to_datetime(quejas['fecha'], format='%d/%m/%Y')

# Extraer el nombre del mes en español
quejas['Mes'] = quejas['fecha'].dt.strftime('%B').str.capitalize()

# Extraer el año y almacenarlo como un entero en una nueva columna 'Año'
quejas['Año'] = quejas['fecha'].dt.year

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
quejas['fecha'] = quejas['fecha'].dt.strftime('%d/%m/%Y')

quejas.head()

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,12/04/2026,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,26/04/2026,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,26/04/2026,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,26/04/2026,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,26/04/2026,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026

In [16]:
# Aplicar el filtro por mes de agosto y año 2024
quejas = quejas[(quejas['Mes'] == f'{mes}') & (quejas['Año'] == 2026)]

quejas.head(3)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,12/04/2026,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,26/04/2026,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,26/04/2026,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026

In [17]:
#Verificar y ajustar los tipos de datos

print(quejas[['Horas_Minutos_Segundos', 'fecha', 'identificador del bus']].dtypes)
print(df_final[['Horas_Minutos_Segundos', 'Fecha', 'Número FMS Bus']].dtypes)

Horas_Minutos_Segundos     int32
fecha                     object
identificador del bus      int64
dtype: object
Horas_Minutos_Segundos     int32
Fecha                     object
Número FMS Bus             int32
dtype: object

Probar para resultados más exactos, cuando se para obtener el conductor

In [18]:
# Convertir las columnas de fecha en ambos DataFrames a datetime
quejas['fecha'] = pd.to_datetime(quejas['fecha'], dayfirst=True)  # Ajusta el formato según sea necesario
df_final['Fecha'] = pd.to_datetime(df_final['Fecha'], dayfirst=True)

def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_ref = int(horaReferencia)

    # Filtrar por fecha y bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    resultados = df_final.loc[filtro].copy()
    
    if not resultados.empty:
        # Calcular diferencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_ref)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Conductor'] if not pd.isna(resultado['Conductor']) else None

    return None

# Aplicar la función a acada fila en quejas
quejas['Conductor'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['Conductor'].fillna(0, inplace=True)
quejas['Conductor'] = quejas['Conductor'].astype(int)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\3317042362.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Conductor'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año,Conductor
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026,508015
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026,510262
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026,510419
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026,510088

In [19]:
#Llevar km de viaje desglosado a fallas sistema
def calcular_accion1(fecha, bus, parada):
    
    filtro = (
        (df_final['Fecha'] == fecha)&
        (df_final['Número FMS Bus'] == bus)&
        (df_final['paradero'] == parada)       
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not df_final.loc[filtro].empty:
        # Obtener el primer valor
        srv = df_final.loc[filtro, 'Tiempo Apertura de Puertas'].iloc[0]
        return srv if not pd.isna(srv) else None 
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
quejas['Tiempo Apertura de Puertas'] = quejas.apply(
    lambda row: calcular_accion1(
        row['fecha'],
        row['identificador del bus'],
        row['paradero']
    ),
    axis=1
)

# Mostrar el DataFrame resultante
quejas.head()

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año,Conductor,Tiempo Apertura de Puertas
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026,0,None
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026,508015,0:00:00
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026,510262,0:00:00
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026,510419,0:00:09
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026,510088,0:00:00

In [20]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Servicio Bus'] if not pd.isna(resultado['Servicio Bus']) else None

    return None

# Aplicar la función a acada fila en quejas
quejas['Servicio Bus'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['Servicio Bus'].fillna(0, inplace=True)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\54161422.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Servicio Bus'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026,0,None,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026,508015,0:00:00,CE1730006
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026,510262,0:00:00,CE17D0001
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026,510419,0:00:09,CE1350006
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026,510088,0:00:00,CE1700008

In [21]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        # Seleccionar el registro con la menor diferencia (más cercano en tiempo)
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Id Línea'] if not pd.isna(resultado['Id Línea']) else None

    return None

# Aplicar la función a acada fila en quejas
quejas['Id Línea'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['Id Línea'].fillna(0, inplace=True)
quejas['Id Línea'] = quejas['Id Línea'].astype(int)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\30546510.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Id Línea'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus,Id Línea
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026,0,None,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026,508015,0:00:00,CE1730006,10551
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026,510262,0:00:00,CE17D0001,10282
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026,510419,0:00:09,CE1350006,10305
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026,510088,0:00:00,CE1700008,10292

In [22]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Id Ruta'] if not pd.isna(resultado['Id Ruta']) else None

    return None

# Aplicar la función a acada fila en quejas
quejas['Id Ruta'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['Id Ruta'].fillna(0, inplace=True)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\853367704.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Id Ruta'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus,Id Línea,Id Ruta
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026,0,None,0,0,0.0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026,508015,0:00:00,CE1730006,10551,12856.0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026,510262,0:00:00,CE17D0001,10282,12852.0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026,510419,0:00:09,CE1350006,10305,12740.0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026,510088,0:00:00,CE1700008,10292,12790.0

In [23]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Ruta'] if not pd.isna(resultado['Ruta']) else None

    return None

# Aplicar la función a acada fila en quejas
quejas['Ruta'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['Ruta'].fillna(0, inplace=True)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2867149212.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Ruta'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,hora1,Horas_Minutos_Segundos,Mes,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus,Id Línea,Id Ruta,Ruta
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,10:28:09,37689,April,2026,0,None,0,0,0.0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,22:43:43,81823,April,2026,508015,0:00:00,CE1730006,10551,12856.0,KL307_V3
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,21:25:17,77117,April,2026,510262,0:00:00,CE17D0001,10282,12852.0,DH209_V3
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,21:02:21,75741,April,2026,510419,0:00:09,CE1350006,10305,12740.0,DD212_Festivo_V1
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,20:33:36,74016,April,2026,510088,0:00:00,CE1700008,10292,12790.0,577_Vuelta_V2

Información de bus lleno

In [24]:
#Abrir información de bus lleno

archivo = f"C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Omision_parada/{semana_bus}.csv"

# Cargar el archivo 

bus_lleno = pd.read_csv(archivo, encoding="latin", delimiter=";")

bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja
0,20/04/2026,15:10:48,10331,504542,13,CE12B0013,510485,Recibido,Evasion,15
1,20/04/2026,13:48:15,10331,502169,4,CE12B0004,507967,Recibido,Evasion,13
2,20/04/2026,12:48:15,10331,504059,2,CE12B0002,509289,Recibido,Evasion,12
3,20/04/2026,12:27:56,10331,504002,1,CE12B0001,510112,Recibido,Evasion,12
4,20/04/2026,11:57:46,10331,504009,10,CE12B0010,509695,Recibido,Evasion,11

In [25]:
bus_lleno = bus_lleno[bus_lleno['Mensajes'] == 'Bus Lleno']

bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6
15,20/04/2026,6:01:54,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,6
16,20/04/2026,5:59:46,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,5

In [26]:
# Renombrar la columna ï»¿Fecha a Fecha
bus_lleno.rename(columns={'ï»¿Fecha': 'Fecha'}, inplace=True)

bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6
15,20/04/2026,6:01:54,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,6
16,20/04/2026,5:59:46,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,5

In [27]:
# Crear nuevas columnas para la fecha y la hora
bus_lleno['Fecha_N'] = bus_lleno['Fecha']
bus_lleno['Hora'] = bus_lleno['Instante']

# Mostrar el DataFrame con las nuevas columnas
bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,8:05:40
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,6:37:47
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,6:30:02
15,20/04/2026,6:01:54,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,6,20/04/2026,6:01:54
16,20/04/2026,5:59:46,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,5,20/04/2026,5:59:46

In [28]:
bus_lleno['Mensaje'] = 1

bus_lleno['Hora1'] = bus_lleno['Hora']

bus_lleno.head(3)

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,8:05:40,1,8:05:40
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,6:37:47,1,6:37:47
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,6:30:02,1,6:30:02

In [29]:
# Función para corregir tiempos con "24:00:00"
def fix_time(time_str):
    try:
        time_str = str(time_str).strip()
        h, m, s = map(int, time_str.split(':'))

        # Convertir TODO a segundos
        total_segundos = h * 3600 + m * 60 + s

        # Reducir al rango de 24h
        total_segundos = total_segundos % (24 * 3600)

        # Volver a formato hh:mm:ss
        h_new = total_segundos // 3600
        m_new = (total_segundos % 3600) // 60
        s_new = total_segundos % 60

        return f"{h_new:02}:{m_new:02}:{s_new:02}"

    except:
        return None

# Convertir las columnas de tiempo a cadenas
bus_lleno['Hora'] = bus_lleno['Hora'].astype(str)

# Aplicar la función para corregir los tiempos en 'HoraLlegada'
bus_lleno['Hora'] = bus_lleno['Hora'].apply(fix_time)

# Convertir las columnas de tiempo a datetime (sin fecha, solo tiempo)
bus_lleno['Hora'] = pd.to_datetime(
    bus_lleno['Hora'],
    format='%H:%M:%S',
    errors='coerce'
)

bus_lleno['Horas_Minutos_Segundos'] = (
    bus_lleno['Hora'].dt.hour * 3600 +
    bus_lleno['Hora'].dt.minute * 60 +
    bus_lleno['Hora'].dt.second
)

bus_lleno.head(3)

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1,Horas_Minutos_Segundos
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,1900-01-01 08:05:40,1,8:05:40,29140
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:37:47,1,6:37:47,23867
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:30:02,1,6:30:02,23402

In [30]:
# Convertir la columna 'Fecha' a tipo datetime
bus_lleno['Fecha'] = pd.to_datetime(bus_lleno['Fecha'], format='%d/%m/%Y')

# Extraer el nombre del mes en español
bus_lleno['Mes'] = bus_lleno['Fecha'].dt.strftime('%B').str.capitalize()

# Extraer el año y almacenarlo como un entero en una nueva columna 'Año'
bus_lleno['Año'] = bus_lleno['Fecha'].dt.year

# Formatear la columna 'Fecha' en el formato dd/mm/yyyy
bus_lleno['Fecha'] = bus_lleno['Fecha'].dt.strftime('%d/%m/%Y')

bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1,Horas_Minutos_Segundos,Mes,Año
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,1900-01-01 08:05:40,1,8:05:40,29140,April,2026
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:37:47,1,6:37:47,23867,April,2026
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:30:02,1,6:30:02,23402,April,2026
15,20/04/2026,6:01:54,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:01:54,1,6:01:54,21714,April,2026
16,20/04/2026,5:59:46,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,5,20/04/2026,1900-01-01 05:59:46,1,5:59:46,21586,April,2026

In [31]:
# Aplicar el filtro por mes de agosto y año 2024
bus_lleno = bus_lleno[(bus_lleno['Mes'] == f'{mes}') & (bus_lleno['Año'] == 2026)]

bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1,Horas_Minutos_Segundos,Mes,Año
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,1900-01-01 08:05:40,1,8:05:40,29140,April,2026
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:37:47,1,6:37:47,23867,April,2026
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:30:02,1,6:30:02,23402,April,2026
15,20/04/2026,6:01:54,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:01:54,1,6:01:54,21714,April,2026
16,20/04/2026,5:59:46,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,5,20/04/2026,1900-01-01 05:59:46,1,5:59:46,21586,April,2026

In [32]:
#rutas

archivo = "C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Indicadores/Base_indicadores/rutas.xlsx"

# Cargar el archivo 

rutas = pd.read_excel(archivo)

rutas.head()

   Id Línea  Nombre Línea   Ruta      Nombre Ruta  Sublínea
0      10014       M86-K86  10176       M86 - K86        115
1      10011       L81-D81  10022    L81_Ref_CL72         20
2      10011       L81-D81  10025      D81_Normal         21
3      10011       L81-D81  10026    L81_Normal           21
4      10010       H83-M83  10023            H83          22

In [33]:
# Llevar PIR de paradas a data

def calcular_posicion(linea):
    
    filtro = (
        (rutas['Id Línea '] == linea)  
    )
    
    # Verificar si hay algún resultado después de aplicar el filtro
    if not rutas.loc[filtro].empty:
        # Obtener el primer valor
        tipo = rutas.loc[filtro, 'Nombre Línea '].iloc[0]
        return tipo if not pd.isna(tipo) else None 
    
    return None  # Devolver None si no hay resultados

# Aplica la función a las columnas correspondientes
bus_lleno['Ruta_com'] = bus_lleno.apply(
    lambda row: calcular_posicion(
        row['Linea SAE']
    ),
    axis=1
)

bus_lleno.head()

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1,Horas_Minutos_Segundos,Mes,Año,Ruta_com
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,1900-01-01 08:05:40,1,8:05:40,29140,April,2026,12
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:37:47,1,6:37:47,23867,April,2026,12
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:30:02,1,6:30:02,23402,April,2026,12
15,20/04/2026,6:01:54,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:01:54,1,6:01:54,21714,April,2026,12
16,20/04/2026,5:59:46,10331,504059,9,CE12B0009,509858,Recibido,Bus Lleno,5,20/04/2026,1900-01-01 05:59:46,1,5:59:46,21586,April,2026,12

In [34]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia,ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['paradero'] if not pd.isna(resultado['paradero']) else None

    return None

# Aplicar la función a acada fila en quejas
bus_lleno['paradero'] = bus_lleno.apply(
    lambda row: calcular_conductor(
        row['Fecha'],
        row['Id Vehiculo'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
bus_lleno['paradero'].fillna(0, inplace=True)

# Mostrar el DataFrame actualizado
bus_lleno.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\4038819817.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bus_lleno['paradero'].fillna(0, inplace=True)

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1,Horas_Minutos_Segundos,Mes,Año,Ruta_com,paradero
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,1900-01-01 08:05:40,1,8:05:40,29140,April,2026,12,374A05
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:37:47,1,6:37:47,23867,April,2026,12,433A06
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:30:02,1,6:30:02,23402,April,2026,12,433A06

In [35]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
        
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Id Ruta'] if not pd.isna(resultado['Id Ruta']) else None

    return None

# Aplicar la función a acada fila en quejas
bus_lleno['Id Ruta'] = bus_lleno.apply(
    lambda row: calcular_conductor(
        row['Fecha'],
        row['Id Vehiculo'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
bus_lleno['Id Ruta'].fillna(0, inplace=True)
bus_lleno['Id Ruta'] = bus_lleno['Id Ruta'].astype(int)

# Mostrar el DataFrame actualizado
bus_lleno.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\1361437899.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bus_lleno['Id Ruta'].fillna(0, inplace=True)

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,Fecha_N,Hora,Mensaje,Hora1,Horas_Minutos_Segundos,Mes,Año,Ruta_com,paradero,Id Ruta
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,20/04/2026,1900-01-01 08:05:40,1,8:05:40,29140,April,2026,12,374A05,10632
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:37:47,1,6:37:47,23867,April,2026,12,433A06,10632
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,20/04/2026,1900-01-01 06:30:02,1,6:30:02,23402,April,2026,12,433A06,10632

In [36]:
# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
        
    )
    
    # Aplicar el filtro
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Id Viaje'] if not pd.isna(resultado['Id Viaje']) else None

    return None
# Aplicar la función a acada fila en quejas
bus_lleno['Id Viaje'] = bus_lleno.apply(
    lambda row: calcular_conductor(
        row['Fecha'],
        row['Id Vehiculo'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
bus_lleno['Id Viaje'].fillna(0, inplace=True)
bus_lleno['Id Viaje'] = bus_lleno['Id Viaje'].astype(int)

# Mostrar el DataFrame actualizado
bus_lleno.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\3549707057.py:40: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bus_lleno['Id Viaje'].fillna(0, inplace=True)

,Fecha,Instante,Linea SAE,Id Vehiculo,Tabla,Servicio,IdConductor,Estado,Mensajes,Franja,...,Hora,Mensaje,Hora1,Horas_Minutos_Segundos,Mes,Año,Ruta_com,paradero,Id Ruta,Id Viaje
8,20/04/2026,8:05:40,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,8,...,1900-01-01 08:05:40,1,8:05:40,29140,April,2026,12,374A05,10632,3
11,20/04/2026,6:37:47,10331,502018,2,CE12B0002,509109,Recibido,Bus Lleno,6,...,1900-01-01 06:37:47,1,6:37:47,23867,April,2026,12,433A06,10632,3
12,20/04/2026,6:30:02,10331,502026,1,CE12B0001,509959,Recibido,Bus Lleno,6,...,1900-01-01 06:30:02,1,6:30:02,23402,April,2026,12,433A06,10632,3

In [37]:
bus_lleno['Fecha_N'] = pd.to_datetime(bus_lleno['Fecha_N'], dayfirst=True)

# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    horaReferenciaSegundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (bus_lleno['Fecha_N'] == fecha) &
        (bus_lleno['Id Vehiculo'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = bus_lleno.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - horaReferenciaSegundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Mensaje'] if not pd.isna(resultado['Mensaje']) else None

    return None
        
# Aplicar la función a acada fila en quejas 
quejas['Mensaje_buslleno'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['Mensaje_buslleno'].fillna(0, inplace=True)
quejas['Mensaje_buslleno'] = quejas['Mensaje_buslleno'].astype(int)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\215671419.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Mensaje_buslleno'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Horas_Minutos_Segundos,Mes,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus,Id Línea,Id Ruta,Ruta,Mensaje_buslleno
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,37689,April,2026,0,None,0,0,0.0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,81823,April,2026,508015,0:00:00,CE1730006,10551,12856.0,KL307_V3,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,77117,April,2026,510262,0:00:00,CE17D0001,10282,12852.0,DH209_V3,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,75741,April,2026,510419,0:00:09,CE1350006,10305,12740.0,DD212_Festivo_V1,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,74016,April,2026,510088,0:00:00,CE1700008,10292,12790.0,577_Vuelta_V2,0

In [38]:
bus_lleno['Fecha_N'] = pd.to_datetime(bus_lleno['Fecha_N'], dayfirst=True)

# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    horaReferenciaSegundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (bus_lleno['Fecha_N'] == fecha) &
        (bus_lleno['Id Vehiculo'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = bus_lleno.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - horaReferenciaSegundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Hora1'] if not pd.isna(resultado['Hora1']) else None

    return None

# Aplicar la función a acada fila en quejas 
quejas['hora_buslleno'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['hora_buslleno'].fillna(0, inplace=True)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2394860484.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['hora_buslleno'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Mes,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus,Id Línea,Id Ruta,Ruta,Mensaje_buslleno,hora_buslleno
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,April,2026,0,None,0,0,0.0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,April,2026,508015,0:00:00,CE1730006,10551,12856.0,KL307_V3,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,April,2026,510262,0:00:00,CE17D0001,10282,12852.0,DH209_V3,0,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,April,2026,510419,0:00:09,CE1350006,10305,12740.0,DD212_Festivo_V1,0,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,April,2026,510088,0:00:00,CE1700008,10292,12790.0,577_Vuelta_V2,0,0

In [39]:
bus_lleno['Fecha_N'] = pd.to_datetime(bus_lleno['Fecha_N'], dayfirst=True)

# Luego, puedes proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    horaReferenciaSegundos = int(horaReferencia)

    # Filtrar por fecha y número de bus
    filtro = (
        (bus_lleno['Fecha_N'] == fecha) &
        (bus_lleno['Id Vehiculo'] == numeroBus)
    )
    
    # Aplicar el filtro
    resultados = bus_lleno.loc[filtro]
    
    if not resultados.empty:
        # Ordenar los resultados por la diferencia absoluta con la hora de referencia
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - horaReferenciaSegundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['paradero'] if not pd.isna(resultado['paradero']) else None

    return None

# Aplicar la función a acada fila en quejas
quejas['paradero_buslleno'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Rellenar valores NaN y convertir a entero
quejas['paradero_buslleno'].fillna(0, inplace=True)

# Mostrar el DataFrame actualizado
quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2705520197.py:42: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['paradero_buslleno'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Año,Conductor,Tiempo Apertura de Puertas,Servicio Bus,Id Línea,Id Ruta,Ruta,Mensaje_buslleno,hora_buslleno,paradero_buslleno
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,2026,0,None,0,0,0.0,0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,2026,508015,0:00:00,CE1730006,10551,12856.0,KL307_V3,0,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,2026,510262,0:00:00,CE17D0001,10282,12852.0,DH209_V3,0,0,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,2026,510419,0:00:09,CE1350006,10305,12740.0,DD212_Festivo_V1,0,0,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,2026,510088,0:00:00,CE1700008,10292,12790.0,577_Vuelta_V2,0,0,0

In [40]:
# Crear la columna 'Franja' extrayendo la hora
quejas['Franja'] = quejas['hora1'].str[:2]

quejas['Cantidad'] = 1

quejas.head()

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Tiempo Apertura de Puertas,Servicio Bus,Id Línea,Id Ruta,Ruta,Mensaje_buslleno,hora_buslleno,paradero_buslleno,Franja,Cantidad
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,None,0,0,0.0,0,0,0,0,1,1
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,0:00:00,CE1730006,10551,12856.0,KL307_V3,0,0,0,2,1
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,0:00:00,CE17D0001,10282,12852.0,DH209_V3,0,0,0,2,1
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,0:00:09,CE1350006,10305,12740.0,DD212_Festivo_V1,0,0,0,2,1
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,0:00:00,CE1700008,10292,12790.0,577_Vuelta_V2,0,0,0,2,1

In [41]:
# Ruta de la carpeta que contiene los archivos
ruta_carpeta = 'Z:/01 base_datos/18 pasajeros_asociados'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_pax_asociados.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    pasajeros = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
pasajeros.head()

,FechaId,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,IdViajeGrupo,HoraInicio,StrParadero,Paradero,TipoValidacion,TipoOperacion
0,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,2026-04-20T03:56:58Z,2026-04-20504340CE12D0002-2,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL
1,20260420,2026-04-20,504180,CE12D0003,10264.0,12328,12328,614,2.0,510417.0,2026-04-20T03:57:02Z,2026-04-20504180CE12D0003-2,03:30,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,BUSETON ZONAL
2,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,2026-04-20T03:57:02Z,2026-04-20504340CE12D0002-2,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL
3,20260420,2026-04-20,504306,CE12D0009,10264.0,12328,12328,614,2.0,510177.0,2026-04-20T03:57:04Z,2026-04-20504306CE12D0009-2,03:30,(54101) 473A12_TM|473A12_Br. Gran Yomasa II Se...,54101.0,Transbordo,BUSETON ZONAL
4,20260420,2026-04-20,504180,CE12D0003,10264.0,12328,12328,614,2.0,510417.0,2026-04-20T03:57:06Z,2026-04-20504180CE12D0003-2,03:30,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,BUSETON ZONAL

In [42]:
# Convertir la columna 'Instante' a un objeto datetime
pasajeros['FechaReal'] = pd.to_datetime(pasajeros['FechaReal'])

# Crear nuevas columnas para la fecha y la hora
pasajeros['Fecha_N'] = pasajeros['FechaReal'].dt.strftime('%d/%m/%Y').str.lstrip('0').replace('/0', '/')
pasajeros['Hora'] = pasajeros['FechaReal'].dt.strftime('%H:%M:%S')

# Mostrar el DataFrame con las nuevas columnas
pasajeros.head(3)

,FechaId,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,FechaReal,IdViajeGrupo,HoraInicio,StrParadero,Paradero,TipoValidacion,TipoOperacion,Fecha_N,Hora
0,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,2026-04-20 03:56:58+00:00,2026-04-20504340CE12D0002-2,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL,20/04/2026,03:56:58
1,20260420,2026-04-20,504180,CE12D0003,10264.0,12328,12328,614,2.0,510417.0,2026-04-20 03:57:02+00:00,2026-04-20504180CE12D0003-2,03:30,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,BUSETON ZONAL,20/04/2026,03:57:02
2,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,2026-04-20 03:57:02+00:00,2026-04-20504340CE12D0002-2,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL,20/04/2026,03:57:02

In [43]:
pasajeros['Hora1']  = pasajeros['Hora'] 

pasajeros['validacion'] = 1

pasajeros.head(3)

,FechaId,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,...,IdViajeGrupo,HoraInicio,StrParadero,Paradero,TipoValidacion,TipoOperacion,Fecha_N,Hora,Hora1,validacion
0,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,...,2026-04-20504340CE12D0002-2,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL,20/04/2026,03:56:58,03:56:58,1
1,20260420,2026-04-20,504180,CE12D0003,10264.0,12328,12328,614,2.0,510417.0,...,2026-04-20504180CE12D0003-2,03:30,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,BUSETON ZONAL,20/04/2026,03:57:02,03:57:02,1
2,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,...,2026-04-20504340CE12D0002-2,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL,20/04/2026,03:57:02,03:57:02,1

In [44]:
# Función para corregir tiempos con "24:00:00"
def fix_time(time_str):
    try:
        time_str = str(time_str).strip()
        h, m, s = map(int, time_str.split(':'))

        # Convertir TODO a segundos
        total_segundos = h * 3600 + m * 60 + s

        # Reducir al rango de 24h
        total_segundos = total_segundos % (24 * 3600)

        # Volver a formato hh:mm:ss
        h_new = total_segundos // 3600
        m_new = (total_segundos % 3600) // 60
        s_new = total_segundos % 60

        return f"{h_new:02}:{m_new:02}:{s_new:02}"

    except:
        return None


# Convertir las columnas de tiempo a cadenas
pasajeros['Hora'] = pasajeros['Hora'].astype(str)

# Aplicar la función para corregir los tiempos en 'HoraLlegada'
pasajeros['Hora'] = pasajeros['Hora'].apply(fix_time)

# Convertir las columnas de tiempo a datetime (sin fecha, solo tiempo)
pasajeros['Hora'] = pd.to_datetime(
    pasajeros['Hora'],
    format='%H:%M:%S',
    errors='coerce'
)

pasajeros['Horas_Minutos_Segundos'] = (
    pasajeros['Hora'].dt.hour * 3600 +
    pasajeros['Hora'].dt.minute * 60 +
    pasajeros['Hora'].dt.second
)

pasajeros.head(3)

,FechaId,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,...,HoraInicio,StrParadero,Paradero,TipoValidacion,TipoOperacion,Fecha_N,Hora,Hora1,validacion,Horas_Minutos_Segundos
0,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,...,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL,20/04/2026,1900-01-01 03:56:58,03:56:58,1,14218
1,20260420,2026-04-20,504180,CE12D0003,10264.0,12328,12328,614,2.0,510417.0,...,03:30,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,BUSETON ZONAL,20/04/2026,1900-01-01 03:57:02,03:57:02,1,14222
2,20260420,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,...,03:30,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,BUSETON ZONAL,20/04/2026,1900-01-01 03:57:02,03:57:02,1,14222

In [45]:
# Eliminar columnas específicas
columnas_a_eliminar = ['FechaId', 'IdViajeGrupo', 'HoraInicio', 'TipoOperacion','FechaReal']
pasajeros = pasajeros.drop(columns=columnas_a_eliminar)

pasajeros.head(3)

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,StrParadero,Paradero,TipoValidacion,Fecha_N,Hora,Hora1,validacion,Horas_Minutos_Segundos
0,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,20/04/2026,1900-01-01 03:56:58,03:56:58,1,14218
1,2026-04-20,504180,CE12D0003,10264.0,12328,12328,614,2.0,510417.0,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,20/04/2026,1900-01-01 03:57:02,03:57:02,1,14222
2,2026-04-20,504340,CE12D0002,10264.0,12328,12328,614,2.0,510452.0,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,20/04/2026,1900-01-01 03:57:02,03:57:02,1,14222

In [46]:
# Filtrar el DataFrame para mantener solo las filas donde 'ServicioBus' no es NaN
pasajeros = pasajeros[pasajeros['ServicioBus'].notna()]

In [47]:
# Crear la columna 'Franja' extrayendo la hora
pasajeros['Franja'] = pasajeros['Hora1'].str[:2]

pasajeros['LineAso'].fillna(0, inplace=True)
pasajeros['LineAso'] = pasajeros['LineAso'].astype(int)

pasajeros['RutaOrg'].fillna(0, inplace=True)
pasajeros['RutaOrg'] = pasajeros['RutaOrg'].astype(int)

pasajeros['IdViaje'] = pasajeros['IdViaje'].astype(int)

pasajeros.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\757509059.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pasajeros['LineAso'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\757509059.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pasajeros['RutaOrg'].fillna(0, inplace=True)

,Fecha,NumeroBus,ServicioBus,LineAso,RutaAso,RutaOrg,LineaOrg,IdViaje,Conductor,StrParadero,Paradero,TipoValidacion,Fecha_N,Hora,Hora1,validacion,Horas_Minutos_Segundos,Franja
0,2026-04-20,504340,CE12D0002,10264,12328,12328,614,2,510452.0,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,20/04/2026,1900-01-01 03:56:58,03:56:58,1,14218,03
1,2026-04-20,504180,CE12D0003,10264,12328,12328,614,2,510417.0,(53746) 251A12_TM|251A12_Br. Diana Turbay,53746.0,Transbordo,20/04/2026,1900-01-01 03:57:02,03:57:02,1,14222,03
2,2026-04-20,504340,CE12D0002,10264,12328,12328,614,2,510452.0,(53402) 071A12_TM|071A12_Br. Puerto Rico,53402.0,Transbordo,20/04/2026,1900-01-01 03:57:02,03:57:02,1,14222,03

In [48]:
#Dejar por servicio, tabla, viaje, el punto max y mín 

# Encontrar el mínimo y máximo por grupo y marcar con 1, el resto con 0
df_final['seleccion'] = df_final.groupby(['Servicio Bus', 'Id Línea', 'Id Ruta', 'Tabla', 'Id Viaje'])['Horas_Minutos_Segundos'].transform(
    lambda x: (x == x.min()) | (x == x.max())
)

# Reemplazar NaN por 0
df_final['seleccion'] = df_final['seleccion'].fillna(0).astype(int)

# Filtrar las filas donde 'seleccion' es igual a 1
df_final1 = df_final[df_final['seleccion'] == 1]

df_final1['Id Viaje'] = df_final1['Id Viaje'].astype(int)

df_final1['Número FMS Bus'] = df_final1['Número FMS Bus'].astype(int)

# Mostrar el resultado
df_final1.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\622283554.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1['Id Viaje'] = df_final1['Id Viaje'].astype(int)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\622283554.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1['Número FMS Bus'] = df_final1['Número FMS Bus'].astype(int)

,Fecha,Concesión,Concesionario de Operación,Id Línea,Línea,Id Ruta,Ruta,Tabla,Viaje Linea,Orden Viaje,...,Hora Salida,Tiempo entre paradas,Alarma Exceso de Tiempo en Parada,Tiempo Apertura de Puertas,Lista de acciones regulatorias,paradero,HoraLleg,HoraLleg_modificado,Horas_Minutos_Segundos,seleccion
0,2026-04-20,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,NaN,NaN,NaN,NaN,247A05,1900-01-01,1,0,1
14,2026-04-20,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,NaN,NaN,NaN,NaN,478A05,1900-01-01,1,0,1
15,2026-04-20,ENGATIVA ZN,(105) GMOVIL ENGATIVA,10310,C101,12777,C101_Ida_V2,24,1,1,...,NaN,NaN,NaN,NaN,NaN,172A05,1900-01-01,1,0,1

In [49]:
# proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
    # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Id Viaje'] if not pd.isna(resultado['Id Viaje']) else None

    return None    

# Aplica la función a las columnas correspondientes
quejas['Id Viaje'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

quejas['Id Viaje'].fillna(0, inplace=True)
quejas['Id Viaje'] = quejas['Id Viaje'].astype(int)

quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\1934984650.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Id Viaje'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Servicio Bus,Id Línea,Id Ruta,Ruta,Mensaje_buslleno,hora_buslleno,paradero_buslleno,Franja,Cantidad,Id Viaje
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,0,0.0,0,0,0,0,1,1,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,CE1730006,10551,12856.0,KL307_V3,0,0,0,2,1,6
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,CE17D0001,10282,12852.0,DH209_V3,0,0,0,2,1,7
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,CE1350006,10305,12740.0,DD212_Festivo_V1,0,0,0,2,1,9
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,CE1700008,10292,12790.0,577_Vuelta_V2,0,0,0,2,1,7

In [50]:
# Paso 2: Obtener los valores mínimos y máximos de tiempo en df_final
min_max_times = df_final.groupby(['Fecha','Servicio Bus', 'Número FMS Bus','Id Línea', 'Id Ruta', 'Tabla', 'Id Viaje'])['Horas_Minutos_Segundos'].agg(['min', 'max']).reset_index()

min_max_times.head()

,Fecha,Servicio Bus,Número FMS Bus,Id Línea,Id Ruta,Tabla,Id Viaje,min,max
0,2026-04-20,AD0310024,502134,10310,12777,24,1,0,31217
1,2026-04-20,BC29D0002,0,10350,12738,1,7,0,0
2,2026-04-20,BC29D0002,0,10350,12739,1,6,0,0
3,2026-04-20,BC29D0002,507049,10350,12738,1,3,0,30152
4,2026-04-20,BC29D0002,507049,10350,12738,1,5,0,50538

In [51]:
#Verificar y ajustar los tipos de datos

print(pasajeros[['Fecha_N', 'NumeroBus', 'LineAso','RutaOrg','IdViaje','Horas_Minutos_Segundos']].dtypes)
print(quejas[['fecha', 'identificador del bus', 'Id Línea', 'Id Ruta','Id Viaje','Horas_Minutos_Segundos']].dtypes)

Fecha_N                   object
NumeroBus                  int64
LineAso                    int32
RutaOrg                    int32
IdViaje                    int32
Horas_Minutos_Segundos     int32
dtype: object
fecha                     datetime64[ns]
identificador del bus              int64
Id Línea                           int32
Id Ruta                          float64
Id Viaje                           int32
Horas_Minutos_Segundos             int32
dtype: object

In [52]:
pasajeros['Fecha_N'] = pd.to_datetime(pasajeros['Fecha_N'], dayfirst=True)

# Definir la función para contar validaciones hacia atrás desde la hora de la queja
def contar_validaciones(fecha, identificadorBus, linea, ruta, id_viaje, hora_referencia):
    # Aplicar el filtro para seleccionar las filas relevantes hasta la hora de la queja
    filtro = (
        (pasajeros['Fecha_N'] == fecha) &
        (pasajeros['NumeroBus'] == identificadorBus) &
        (pasajeros['LineAso'] == linea) &
        (pasajeros['RutaOrg'] == ruta) &
        (pasajeros['IdViaje'] == id_viaje) &
        (pasajeros['Horas_Minutos_Segundos'] <= hora_referencia)
    )
    
    # Filtrar los datos
    resultados_filtrados = pasajeros.loc[filtro]

    # Sumar las cantidades de validaciones que cumplen con el filtro
    validaciones = resultados_filtrados['validacion'].sum()
    
    return validaciones

# Aplica la función a las filas correspondientes en el dataframe de quejas
quejas['Cantidad Validaciones'] = quejas.apply(
    lambda row: contar_validaciones(
        row['fecha'],
        row['identificador del bus'],
        row['Id Línea'],
        row['Id Ruta'],
        row['Id Viaje'],
        row['Horas_Minutos_Segundos'] 
    ),
    axis=1
)

# Verificar los resultados
quejas.head()

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Id Línea,Id Ruta,Ruta,Mensaje_buslleno,hora_buslleno,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,0.0,0,0,0,0,1,1,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,10551,12856.0,KL307_V3,0,0,0,2,1,6,11
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,10282,12852.0,DH209_V3,0,0,0,2,1,7,12
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,10305,12740.0,DD212_Festivo_V1,0,0,0,2,1,9,2
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,10292,12790.0,577_Vuelta_V2,0,0,0,2,1,7,8

Acciones de regulacion

In [53]:
# Ruta de la carpeta que contiene los archivos
ruta_carpeta = 'Z:/01 base_datos/09 acciones_regulacion_FMS'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_accionesregulacion.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    acciones = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
acciones.head(3)

,Fecha,Instante,Id Línea,Línea,Tabla,Código Bus,Número FMS Bus,Id Acción,Descripción de Acción,Id Usuario,Nombre de Usuario,Parámetros,Id Motivo,Motivo,Reversada por
0,20/04/2026,0:54:45,10273,142,11.0,NaN,NaN,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Chang...,0,Motivo no definido.,NaN
1,20/04/2026,0:59:35,10292,577,13.0,NaN,NaN,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Chang...,0,Motivo no definido.,NaN
2,20/04/2026,1:00:37,10292,577,17.0,NaN,0.0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Alloc...,0,Motivo no definido.,NaN

In [54]:
#copiar data

ar = acciones.copy()

ar['Número FMS Bus'].fillna(0, inplace=True)
ar['Número FMS Bus'] = ar['Número FMS Bus'].astype(int)

ar.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\181476058.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ar['Número FMS Bus'].fillna(0, inplace=True)

,Fecha,Instante,Id Línea,Línea,Tabla,Código Bus,Número FMS Bus,Id Acción,Descripción de Acción,Id Usuario,Nombre de Usuario,Parámetros,Id Motivo,Motivo,Reversada por
0,20/04/2026,0:54:45,10273,142,11.0,NaN,0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Chang...,0,Motivo no definido.,NaN
1,20/04/2026,0:59:35,10292,577,13.0,NaN,0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Chang...,0,Motivo no definido.,NaN
2,20/04/2026,1:00:37,10292,577,17.0,NaN,0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Alloc...,0,Motivo no definido.,NaN

In [55]:
#Pasar instante a segundos

# Función para corregir tiempos con "24:00:00"
def fix_time(time_str):
    try:
        time_str = str(time_str).strip()
        h, m, s = map(int, time_str.split(':'))

        # Convertir TODO a segundos
        total_segundos = h * 3600 + m * 60 + s

        # Reducir al rango de 24h
        total_segundos = total_segundos % (24 * 3600)

        # Volver a formato hh:mm:ss
        h_new = total_segundos // 3600
        m_new = (total_segundos % 3600) // 60
        s_new = total_segundos % 60

        return f"{h_new:02}:{m_new:02}:{s_new:02}"

    except:
        return None

# Convertir las columnas de tiempo a cadenas
ar['Instante'] = ar['Instante'].astype(str)

# Aplicar la función para corregir los tiempos
ar['Instante'] = ar['Instante'].apply(fix_time)

# Convertir las columnas de tiempo a datetime (sin fecha, solo tiempo), manejando valores nulos
ar['Instante'] = pd.to_datetime(
    ar['Instante'],
    format='%H:%M:%S',
    errors='coerce'
)

ar['instante_segundos'] = (
    ar['Instante'].dt.hour * 3600 +
    ar['Instante'].dt.minute * 60 +
    ar['Instante'].dt.second
)

ar.head(3)

,Fecha,Instante,Id Línea,Línea,Tabla,Código Bus,Número FMS Bus,Id Acción,Descripción de Acción,Id Usuario,Nombre de Usuario,Parámetros,Id Motivo,Motivo,Reversada por,instante_segundos
0,20/04/2026,1900-01-01 00:54:45,10273,142,11.0,NaN,0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Chang...,0,Motivo no definido.,NaN,3285
1,20/04/2026,1900-01-01 00:59:35,10292,577,13.0,NaN,0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Chang...,0,Motivo no definido.,NaN,3575
2,20/04/2026,1900-01-01 01:00:37,10292,577,17.0,NaN,0,20,Cambiar Conductor,WMUNAR_105,WILLIAM MUNAR HUMBERTO GONZALEZ,com.lgcns.fms.oprt.schedule.driver.model.Alloc...,0,Motivo no definido.,NaN,3637

In [56]:
# Ordenar el DataFrame por 'CodigoBus' y luego por 'HoraLlegada_segundos', ambos en orden descendente
ar = ar.sort_values(by=['Número FMS Bus', 'instante_segundos'], ascending=[False, False])

ar.head(3)

,Fecha,Instante,Id Línea,Línea,Tabla,Código Bus,Número FMS Bus,Id Acción,Descripción de Acción,Id Usuario,Nombre de Usuario,Parámetros,Id Motivo,Motivo,Reversada por,instante_segundos
2982,21/04/2026,1900-01-01 14:31:46,10350,SE14,24.0,Z80-7419,807419,5,Eliminar Vehiculo,ETOCORA_108,EDNA VIVIANA TOCORA LOZANO,"<= Elimination Vehicle =>\nIdLinea=10350,\nSer...",14,No se presenta conductor a realizar servicio,UTAMAYO_TM,52306
5204,22/04/2026,1900-01-01 20:22:54,10350,SE14,28.0,Z80-7412,807412,36,Retomar Viajes,KMORALES_108,KARINA MORALES MORALES BOTERO,"<= Change Vehicle =>\nIdLinea=10350,\nServBusR...",26,Retoma de viaje,NaN,73374
6043,23/04/2026,1900-01-01 08:50:43,10350,SE14,30.0,Z80-7343,807343,27,Vacio/Limitacion,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,<= Create Empty/Limitaion =>\nSecuenciaVacíoLi...,5,Congestion vehicular,NaN,31843

In [57]:
# Convertir la columna 'Fecha' a datetime64[ns]
ar['Fecha'] = pd.to_datetime(ar['Fecha'], errors='coerce')

ar.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\340994780.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ar['Fecha'] = pd.to_datetime(ar['Fecha'], errors='coerce')

,Fecha,Instante,Id Línea,Línea,Tabla,Código Bus,Número FMS Bus,Id Acción,Descripción de Acción,Id Usuario,Nombre de Usuario,Parámetros,Id Motivo,Motivo,Reversada por,instante_segundos
2982,2026-04-21,1900-01-01 14:31:46,10350,SE14,24.0,Z80-7419,807419,5,Eliminar Vehiculo,ETOCORA_108,EDNA VIVIANA TOCORA LOZANO,"<= Elimination Vehicle =>\nIdLinea=10350,\nSer...",14,No se presenta conductor a realizar servicio,UTAMAYO_TM,52306
5204,2026-04-22,1900-01-01 20:22:54,10350,SE14,28.0,Z80-7412,807412,36,Retomar Viajes,KMORALES_108,KARINA MORALES MORALES BOTERO,"<= Change Vehicle =>\nIdLinea=10350,\nServBusR...",26,Retoma de viaje,NaN,73374
6043,2026-04-23,1900-01-01 08:50:43,10350,SE14,30.0,Z80-7343,807343,27,Vacio/Limitacion,WVALDERRAMA_105,WILLIAM VALDERRAMA IGNACIO GONZALEZ,<= Create Empty/Limitaion =>\nSecuenciaVacíoLi...,5,Congestion vehicular,NaN,31843

Fonias

In [58]:
# Ruta de la carpeta que contiene los archivos
ruta_carpeta = 'Z:/01 base_datos/41 Informe Diario CCZ/FMS 2025/Zonal/Fonias'

# Fechas de inicio y fin para el filtro
fecha_inicio = f'{fecha_i}'
fecha_fin = f'{fecha_f}'

# Lista para almacenar los DataFrames
dataframes = []

# Recorrer todos los archivos en la carpeta
for nombre_archivo in os.listdir(ruta_carpeta):
    if nombre_archivo.endswith('_fonias.csv'):
        # Extraer la fecha del nombre del archivo
        fecha_archivo = nombre_archivo[:8]  
        
        # Convertir la fecha a un formato adecuado para comparación
        fecha_archivo_dt = pd.to_datetime(fecha_archivo, format='%Y%m%d', errors='coerce')

        # Verificar si la fecha está dentro del rango deseado
        if fecha_inicio <= fecha_archivo <= fecha_fin:
            ruta_archivo = os.path.join(ruta_carpeta, nombre_archivo)
            df = pd.read_csv(ruta_archivo, encoding='latin', low_memory=False)
            dataframes.append(df)

# Verificar si se encontraron DataFrames
if dataframes:
    # Consolidar todos los DataFrames en uno solo
    fonias = pd.concat(dataframes, ignore_index=True)

else:
    print("No se encontraron archivos para consolidar.")
    
fonias.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Estado,Concesin,Concesionario de Operacin,Id Lnea,Etiqueta Lnea,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin
0,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,NaN,NaN,Z50-4455,...,Solicitud cerrada por nueva de igual o mayor j...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,12774.0,740_V2,Z50-4465,...,Llamada terminada por el técnico de control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,12774.0,740_V2,Z50-4465,...,Llamada terminada por el técnico de control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:

#copiar data

fn = fonias.copy()

fn.head(2)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Estado,Concesin,Concesionario de Operacin,Id Lnea,Etiqueta Lnea,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin
0,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,NaN,NaN,Z50-4455,...,Solicitud cerrada por nueva de igual o mayor j...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,12774.0,740_V2,Z50-4465,...,Llamada terminada por el técnico de control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
# Convertir las columnas de tiempo a formato de fecha y hora
fn['Tiempo Petición Real'] = pd.to_datetime(fn['Tiempo Petición Real'], dayfirst=True, errors='coerce')
fn['Tiempo Apertura'] = pd.to_datetime(fn['Tiempo Apertura'], dayfirst=True, errors='coerce')
fn['Tiempo Cierre'] = pd.to_datetime(fn['Tiempo Cierre'], dayfirst=True, errors='coerce')

# Calcular los segundos totales
fn['HPeticion_segundos'] = fn['Tiempo Petición Real'].dt.hour * 3600 + fn['Tiempo Petición Real'].dt.minute * 60 + fn['Tiempo Petición Real'].dt.second
fn['HApertura_segundos'] = fn['Tiempo Apertura'].dt.hour * 3600 + fn['Tiempo Apertura'].dt.minute * 60 + fn['Tiempo Apertura'].dt.second
fn['HCierre_segundos'] = fn['Tiempo Cierre'].dt.hour * 3600 + fn['Tiempo Cierre'].dt.minute * 60 + fn['Tiempo Cierre'].dt.second

# Calcular la diferencia en segundos entre HApertura_segundos y HPeticion_segundos
fn['Diferencia_segundos'] = fn['HApertura_segundos'] - fn['HPeticion_segundos']

# Calcular la diferencia en segundos entre HCierre_segundos y HApertura_segundos
fn['Diferencia_CA'] = fn['HCierre_segundos'] - fn['HApertura_segundos']

# Eliminar el prefijo "V" de la columna "Codigo"
fn['Código Bus'] = fn['Código Bus'].str.replace('V', 'Z')

# Modificar los valores de la columna 'Código'
fn['Código Bus'] = fn['Código Bus'].str[:3] + '-' + fn['Código Bus'].str[3:]

fn.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA
0,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,NaN,NaN,Z50--4455,...,NaN,NaN,NaN,NaN,NaN,11820.0,11820.0,11820.0,0.0,0.0
1,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,12774.0,740_V2,Z50--4465,...,NaN,NaN,NaN,NaN,NaN,12060.0,12060.0,12060.0,0.0,0.0
2,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184.0,740,740,12774.0,740_V2,Z50--4465,...,NaN,NaN,NaN,NaN,NaN,12060.0,12060.0,12120.0,0.0,60.0

In [61]:
fn['HPeticion_segundos'].fillna(0, inplace=True)
fn['HPeticion_segundos'] = fn['HPeticion_segundos'].astype(int)

fn['HApertura_segundos'].fillna(0, inplace=True)
fn['HApertura_segundos'] = fn['HApertura_segundos'].astype(int)

fn['HCierre_segundos'].fillna(0, inplace=True)
fn['HCierre_segundos'] = fn['HCierre_segundos'].astype(int)

fn['Diferencia_segundos'].fillna(0, inplace=True)
fn['Diferencia_segundos'] = fn['Diferencia_segundos'].astype(int)

fn['Diferencia_CA'].fillna(0, inplace=True)
fn['Diferencia_CA'] = fn['Diferencia_CA'].astype(int)

fn['Id Línea'].fillna(0, inplace=True)
fn['Id Línea'] = fn['Id Línea'].astype(int)

fn.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\110647199.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['HPeticion_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\110647199.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['HApertura_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\110647199.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['HCierre_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\110647199.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['Diferencia_segundos'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\110647199.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['Diferencia_CA'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\110647199.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['Id Línea'].fillna(0, inplace=True)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA
0,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,NaN,NaN,Z50--4455,...,NaN,NaN,NaN,NaN,NaN,11820,11820,11820,0,0
1,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,12774.0,740_V2,Z50--4465,...,NaN,NaN,NaN,NaN,NaN,12060,12060,12060,0,0
2,20/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10184,740,740,12774.0,740_V2,Z50--4465,...,NaN,NaN,NaN,NaN,NaN,12060,12060,12120,0,60

In [62]:
# Ordenar el DataFrame por 'CodigoBus' y luego por 'HoraLlegada_segundos', ambos en orden descendente
fn = fn.sort_values(by=['Código Bus', 'HPeticion_segundos'], ascending=[False, False])

fn.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA
5063,23/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,Z52--4010,...,NaN,NaN,NaN,NaN,NaN,77940,77940,78000,0,60
3563,22/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10304,806,806,12780.0,806_Vuelta_V3,Z52--4010,...,NaN,NaN,NaN,NaN,NaN,74460,74520,74580,60,60
6421,24/04/2026,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,12786.0,539_Vuelta_V2,Z52--4010,...,NaN,NaN,NaN,NaN,NaN,65580,65580,65640,0,60

In [63]:
# Convertir la columna 'Fecha' a datetime64[ns]
fn['Fecha'] = pd.to_datetime(fn['Fecha'], errors='coerce')

fn.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\3393677655.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  fn['Fecha'] = pd.to_datetime(fn['Fecha'], errors='coerce')

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA
5063,2026-04-23,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,Z52--4010,...,NaN,NaN,NaN,NaN,NaN,77940,77940,78000,0,60
3563,2026-04-22,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10304,806,806,12780.0,806_Vuelta_V3,Z52--4010,...,NaN,NaN,NaN,NaN,NaN,74460,74520,74580,60,60
6421,2026-04-24,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,12786.0,539_Vuelta_V2,Z52--4010,...,NaN,NaN,NaN,NaN,NaN,65580,65580,65640,0,60

In [64]:
# Eliminar cualquier letra en la columna 'Codigo' y conservar solo los números
fn['Código Bus'] = fn['Código Bus'].astype(str).str.replace(r'\D', '', regex=True)

fn.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Lnea,Cdigo Bus,Peticin Vehculo,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA
5063,2026-04-23,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,524010,...,NaN,NaN,NaN,NaN,NaN,77940,77940,78000,0,60
3563,2026-04-22,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10304,806,806,12780.0,806_Vuelta_V3,524010,...,NaN,NaN,NaN,NaN,NaN,74460,74520,74580,60,60
6421,2026-04-24,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,12786.0,539_Vuelta_V2,524010,...,NaN,NaN,NaN,NaN,NaN,65580,65580,65640,0,60

In [66]:
# Eliminar la letra 'Z' y el guion '-' y convertir a entero

fn['Movil_'] = fn['Código Bus'].astype(str)

# Limpiar valores
fn['Movil_'] = (
    fn['Movil_']
    .str.replace('Z', '', regex=False)
    .str.replace('-', '', regex=False)
    .str.strip()
)

# Reemplazar vacíos por 0
fn['Movil_'] = fn['Movil_'].replace('', '0')

# Convertir a entero
fn['Movil_'] = fn['Movil_'].astype(int)

fn ['fonia_b'] = 1

fn.head(3)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Peticin Vehculo,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA,Movil_,fonia_b
5063,2026-04-23,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,524010,...,NaN,NaN,NaN,77940,77940,78000,0,60,524010,1
3563,2026-04-22,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10304,806,806,12780.0,806_Vuelta_V3,524010,...,NaN,NaN,NaN,74460,74520,74580,60,60,524010,1
6421,2026-04-24,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,12786.0,539_Vuelta_V2,524010,...,NaN,NaN,NaN,65580,65580,65640,0,60,524010,1

In [67]:
# proceder con la función anterior
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (df_final['Fecha'] == fecha) &
        (df_final['Número FMS Bus'] == numeroBus)
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = df_final.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['Horas_Minutos_Segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['paradero'] if not pd.isna(resultado['paradero']) else None

    return None

# Aplica la función a las columnas correspondientes
fn['paradero_fonia'] = fn.apply(
    lambda row: calcular_conductor(
        row['Fecha'],
        row['Movil_'],
        row['HPeticion_segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

fn['paradero_fonia'].fillna(0, inplace=True)

fn.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\3811917446.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fn['paradero_fonia'].fillna(0, inplace=True)

,Fecha,Concesión,Concesionario de Operación,Tipo de Llamada,Id Línea,Etiqueta Línea,Línea,Id Ruta,Ruta,Código Bus,...,Tiempo Peticin Real,Duracin,HPeticion_segundos,HApertura_segundos,HCierre_segundos,Diferencia_segundos,Diferencia_CA,Movil_,fonia_b,paradero_fonia
5063,2026-04-23,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10690,DL219,DL219,12721.0,DL219_V2,524010,...,NaN,NaN,77940,77940,78000,0,60,524010,1,097A13
3563,2026-04-22,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10304,806,806,12780.0,806_Vuelta_V3,524010,...,NaN,NaN,74460,74520,74580,60,60,524010,1,353B10
6421,2026-04-24,ENGATIVA ZN,GMOVIL ENGATIVA,Vehículo,10194,539,539,12786.0,539_Vuelta_V2,524010,...,NaN,NaN,65580,65580,65640,0,60,524010,1,037A12

In [68]:
#identificar acciones de regulación
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (fn['Fecha'] == fecha) &
        (fn['Movil_'] == numeroBus) &
        (fn['HPeticion_segundos'] <= hora_referencia_segundos) &  # Solo hacia atrás
        (fn['HPeticion_segundos'] >= (hora_referencia_segundos - 1800))  # 30 minutos hacia atrás
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = fn.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['HPeticion_segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['fonia_b'] if not pd.isna(resultado['fonia_b']) else None

    return None

# Aplica la función a las columnas correspondientes   
quejas['fonia_b'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Llenar los valores nulos con 0
quejas['fonia_b'].fillna(0, inplace=True)
quejas['fonia_b'] = quejas['fonia_b'].astype(int)

quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\3363606891.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['fonia_b'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Id Ruta,Ruta,Mensaje_buslleno,hora_buslleno,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0.0,0,0,0,0,1,1,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,12856.0,KL307_V3,0,0,0,2,1,6,11,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,12852.0,DH209_V3,0,0,0,2,1,7,12,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,12740.0,DD212_Festivo_V1,0,0,0,2,1,9,2,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,12790.0,577_Vuelta_V2,0,0,0,2,1,7,8,0

In [69]:
#identificar acciones de regulación
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (fn['Fecha'] == fecha) &
        (fn['Movil_'] == numeroBus) &
        (fn['HPeticion_segundos'] <= hora_referencia_segundos) &  # Solo hacia atrás
        (fn['HPeticion_segundos'] >= (hora_referencia_segundos - 1800))  # 30 minutos hacia atrás
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = fn.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['HPeticion_segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['paradero_fonia'] if not pd.isna(resultado['paradero_fonia']) else None

    return None

# Aplica la función a las columnas correspondientes  
quejas['paradero_fonia'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Llenar los valores nulos con 0
quejas['paradero_fonia'].fillna(0, inplace=True)

quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2673239381.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['paradero_fonia'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Ruta,Mensaje_buslleno,hora_buslleno,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,0,0,0,1,1,0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,KL307_V3,0,0,0,2,1,6,11,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,DH209_V3,0,0,0,2,1,7,12,0,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,DD212_Festivo_V1,0,0,0,2,1,9,2,0,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,577_Vuelta_V2,0,0,0,2,1,7,8,0,0

In [70]:
#identificar acciones de regulación
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (fn['Fecha'] == fecha) &
        (fn['Movil_'] == numeroBus) &
        (fn['HPeticion_segundos'] <= hora_referencia_segundos) &  # Solo hacia atrás
        (fn['HPeticion_segundos'] >= (hora_referencia_segundos - 1800))  # 30 minutos hacia atrás
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = fn.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['HPeticion_segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Tiempo Petición Real'] if not pd.isna(resultado['Tiempo Petición Real']) else None

    return None

# Aplica la función a las columnas correspondientes  
quejas['hora_fonia'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Llenar los valores nulos con 0
quejas['hora_fonia'].fillna(0, inplace=True)

quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2829242719.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['hora_fonia'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2829242719.py:41: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  quejas['hora_fonia'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Mensaje_buslleno,hora_buslleno,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia,hora_fonia
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,0,0,1,1,0,0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,0,0,0,2,1,6,11,0,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,0,0,0,2,1,7,12,0,0,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,0,0,0,2,1,9,2,0,0,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,0,0,0,2,1,7,8,0,0,0

In [71]:
#identificar acciones de regulación
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (ar['Fecha'] == fecha) &
        (ar['Número FMS Bus'] == numeroBus) &
        (ar['instante_segundos'] <= hora_referencia_segundos) &  # Solo hacia atrás
        (ar['instante_segundos'] >= (hora_referencia_segundos - 1800))  # 30 minutos hacia atrás
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = ar.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['instante_segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Instante'] if not pd.isna(resultado['Instante']) else None

    return None

# Aplica la función a las columnas correspondientes 
quejas['Instante_Accion'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Llenar los valores nulos con 0
quejas['Instante_Accion'].fillna(0, inplace=True)

quejas.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\1632301267.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['Instante_Accion'].fillna(0, inplace=True)
C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\1632301267.py:41: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  quejas['Instante_Accion'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,hora_buslleno,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia,hora_fonia,Instante_Accion
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,0,1,1,0,0,0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,0,0,2,1,6,11,0,0,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,0,0,2,1,7,12,0,0,0,0

In [72]:
#identificar acciones de regulación
def calcular_conductor(fecha, numeroBus, horaReferencia, ventana=600):
    hora_referencia_segundos = int(horaReferencia)

    filtro = (
        (ar['Fecha'] == fecha) &
        (ar['Número FMS Bus'] == numeroBus) &
        (ar['instante_segundos'] <= hora_referencia_segundos) &  # Solo hacia atrás
        (ar['instante_segundos'] >= (hora_referencia_segundos - 1800))  # 30 minutos hacia atrás
    )
    
    # Aplicar el filtro y seleccionar el conductor más cercano
    resultados = ar.loc[filtro]
    
    if not resultados.empty:
        # Calcular la diferencia de tiempo
        resultados['diferencia'] = abs(resultados['instante_segundos'] - hora_referencia_segundos)
        
        # 🔥 FILTRO CLAVE: solo dentro de la ventana
        resultados = resultados[resultados['diferencia'] <= ventana]
        
        if not resultados.empty:
            # Tomar el más cercano dentro de la ventana
            resultado = resultados.sort_values(by='diferencia').iloc[0]
            return resultado['Descripción de Acción'] if not pd.isna(resultado['Descripción de Acción']) else None

    return None

# Aplica la función a las columnas correspondientes  
quejas['DescripcionAccion'] = quejas.apply(
    lambda row: calcular_conductor(
        row['fecha'],
        row['identificador del bus'],
        row['Horas_Minutos_Segundos'],
        ventana=600  # 👈 10 minutos
    ),
    axis=1
)

# Llenar los valores nulos con 0
quejas['DescripcionAccion'].fillna(0, inplace=True)

quejas.head(3)

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\1752083683.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['DescripcionAccion'].fillna(0, inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia,hora_fonia,Instante_Accion,DescripcionAccion
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,1,1,0,0,0,0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,0,2,1,6,11,0,0,0,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,0,2,1,7,12,0,0,0,0,0

In [73]:
# completar vacios
quejas['ubicacion reporte'].fillna('0', inplace=True)

quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2030273537.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['ubicacion reporte'].fillna('0', inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,paradero_buslleno,Franja,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia,hora_fonia,Instante_Accion,DescripcionAccion
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,0,1,1,0,0,0,0,0,0,0
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,0,2,1,6,11,0,0,0,0,0
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,0,2,1,7,12,0,0,0,0,0
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,0,2,1,9,2,0,0,0,0,0
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,0,2,1,7,8,0,0,0,0,0

In [74]:
import folium

# Crear latitud - Longuitud

# Separar latitud y longitud en columnas diferentes
quejas[['latitud', 'longitud']] = quejas['ubicacion reporte'].str.split(',', expand=True)
quejas['latitud'] = quejas['latitud'].astype(float)
quejas['longitud'] = quejas['longitud'].astype(float)

quejas.head()

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia,hora_fonia,Instante_Accion,DescripcionAccion,latitud,longitud
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,1,0,0,0,0,0,0,0,4.684581,-74.111280
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,1,6,11,0,0,0,0,0,4.630592,-74.092859
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,1,7,12,0,0,0,0,0,4.683076,-74.115619
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,1,9,2,0,0,0,0,0,4.705798,-74.108197
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,1,7,8,0,0,0,0,0,4.691103,-74.132468

In [75]:
# completar vacios
quejas['longitud'].fillna('0', inplace=True)

quejas['longitud'] = quejas['longitud'].astype(float)

quejas.head()

C:\Users\Jonny Villareal\AppData\Local\Temp\ipykernel_40080\2404757678.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  quejas['longitud'].fillna('0', inplace=True)

,imagen,identificador del bus,fecha,hora,operador,ruta,paradero,SubTipo,ubicacion reporte,foto_png,...,Cantidad,Id Viaje,Cantidad Validaciones,fonia_b,paradero_fonia,hora_fonia,Instante_Accion,DescripcionAccion,latitud,longitud
0,https://png.pngtree.com/png-vector/20190719/ou...,504407,2026-04-12,1900-01-01 10:28:09,GMOVIL ENGATIVA,D209,312A05,Bus no paró,"4.6845813509624845,-74.1112804715524",0,...,1,0,0,0,0,0,0,0,4.684581,-74.111280
1,https://png.pngtree.com/png-vector/20190719/ou...,502159,2026-04-26,1900-01-01 22:43:43,GMOVIL ENGATIVA,K307,036A06,Bus no paró,"4.630591712623785,-74.09285872702819",0,...,1,6,11,0,0,0,0,0,4.630592,-74.092859
2,https://png.pngtree.com/png-vector/20190719/ou...,504277,2026-04-26,1900-01-01 21:25:17,GMOVIL ENGATIVA,H209,168B05,Bus no paró,"4.6830762306608005,-74.11561886406463",0,...,1,7,12,0,0,0,0,0,4.683076,-74.115619
3,https://png.pngtree.com/png-vector/20190719/ou...,504441,2026-04-26,1900-01-01 21:02:21,GMOVIL ENGATIVA,D212,430A04,Bus no paró,"4.705798441461917,-74.10819724325002",0,...,1,9,2,0,0,0,0,0,4.705798,-74.108197
4,https://png.pngtree.com/png-vector/20190719/ou...,504375,2026-04-26,1900-01-01 20:33:36,GMOVIL ENGATIVA,577,380A05,Bus no paró,"4.6911027579782205,-74.13246814116377",0,...,1,7,8,0,0,0,0,0,4.691103,-74.132468

In [76]:
quejas.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Omision_parada/{data}_queja_procesada.csv', index=False, sep=';')

In [77]:
fn.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Omision_parada/{data}_fonia_procesada.csv', index=False, sep=';')

In [78]:
bus_lleno.to_csv(f'C:/Users/Jonny Villareal/OneDrive - Gmovil SAS/Escritorio/Jonny/Control 2026/Omision_parada/bus_lleno_procesado.csv', index=False, sep=';')